-- ./excel/skill/school.xlsx
return {

    [3001] = {
        icon = 3001,
        init_level = 1,
        school = 1,
        school_branch = 1,
        skill_id = 3001,
        skill_name = "落刃",
        skill_pos = 1,
        type = 1,
        unlock_grade = 1,
    },

    [3002] = {
        icon = 3002,
        init_level = 1,
        school = 1,
        school_branch = 1,
        skill_id = 3002,
        skill_name = "疾风闪",
        skill_pos = 3,
        type = 1,
        unlock_grade = 1,
    },

    [3004] = {
        icon = 3004,
        init_level = 0,
        school = 1,
        school_branch = 1,
        skill_id = 3004,
        skill_name = "狂影焚钺",
        skill_pos = 5,
        type = 1,
        unlock_grade = 10,
    },

    [3005] = {
        icon = 3005,
        init_level = 0,
        school = 1,
        school_branch = 1,
        skill_id = 3005,
        skill_name = "瞬狱天冲",
        skill_pos = 6,
        type = 3,
        unlock_grade = 13,
    },

    [3006] = {
        icon = 3006,
        init_level = 0,
        school = 1,
        school_branch = 1,
        skill_id = 3006,
        skill_name = "血噬",
        skill_pos = 2,
        type = 2,
        unlock_grade = 6,
    },

    [3007] = {
        icon = 3007,
        init_level = 0,
        school = 1,
        school_branch = 1,
        skill_id = 3007,
        skill_name = "暗刃",
        skill_pos = 4,
        type = 2,
        unlock_grade = 8,
    },

    [3101] = {
        icon = 3101,
        init_level = 1,
        school = 1,
        school_branch = 2,
        skill_id = 3101,
        skill_name = "开山",
        skill_pos = 1,
        type = 1,
        unlock_grade = 1,
    },

    [3102] = {
        icon = 3102,
        init_level = 1,
        school = 1,
        school_branch = 2,
        skill_id = 3102,
        skill_name = "震天裂",
        skill_pos = 3,
        type = 1,
        unlock_grade = 1,
    },

    [3103] = {
        icon = 3103,
        init_level = 0,
        school = 1,
        school_branch = 2,
        skill_id = 3103,
        skill_name = "崩风掩骨",
        skill_pos = 5,
        type = 1,
        unlock_grade = 10,
    },

    [3105] = {
        icon = 3105,
        init_level = 0,
        school = 1,
        school_branch = 2,
        skill_id = 3105,
        skill_name = "怒卷流邪",
        skill_pos = 6,
        type = 3,
        unlock_grade = 13,
    },

    [3106] = {
        icon = 3106,
        init_level = 0,
        school = 1,
        school_branch = 2,
        skill_id = 3106,
        skill_name = "魔陨",
        skill_pos = 2,
        type = 2,
        unlock_grade = 6,
    },

    [3107] = {
        icon = 3107,
        init_level = 0,
        school = 1,
        school_branch = 2,
        skill_id = 3107,
        skill_name = "不魇",
        skill_pos = 4,
        type = 2,
        unlock_grade = 8,
    },

    [3201] = {
        icon = 3201,
        init_level = 1,
        school = 2,
        school_branch = 1,
        skill_id = 3201,
        skill_name = "疾射",
        skill_pos = 1,
        type = 1,
        unlock_grade = 1,
    },

    [3202] = {
        icon = 3202,
        init_level = 1,
        school = 2,
        school_branch = 1,
        skill_id = 3202,
        skill_name = "回鹰袭",
        skill_pos = 3,
        type = 1,
        unlock_grade = 1,
    },

    [3204] = {
        icon = 3204,
        init_level = 0,
        school = 2,
        school_branch = 1,
        skill_id = 3204,
        skill_name = "破空之矢",
        skill_pos = 5,
        type = 1,
        unlock_grade = 10,
    },

    [3205] = {
        icon = 3205,
        init_level = 0,
        school = 2,
        school_branch = 1,
        skill_id = 3205,
        skill_name = "疾鹰重影",
        skill_pos = 6,
        type = 3,
        unlock_grade = 13,
    },

    [3206] = {
        icon = 3206,
        init_level = 0,
        school = 2,
        school_branch = 1,
        skill_id = 3206,
        skill_name = "穷追",
        skill_pos = 2,
        type = 2,
        unlock_grade = 6,
    },

    [3207] = {
        icon = 3207,
        init_level = 0,
        school = 2,
        school_branch = 1,
        skill_id = 3207,
        skill_name = "无尽",
        skill_pos = 4,
        type = 2,
        unlock_grade = 8,
    },

    [3301] = {
        icon = 3301,
        init_level = 1,
        school = 2,
        school_branch = 2,
        skill_id = 3301,
        skill_name = "斩魄",
        skill_pos = 1,
        type = 1,
        unlock_grade = 1,
    },

    [3302] = {
        icon = 3302,
        init_level = 1,
        school = 2,
        school_branch = 2,
        skill_id = 3302,
        skill_name = "封灵阵",
        skill_pos = 3,
        type = 1,
        unlock_grade = 1,
    },

    [3303] = {
        icon = 3303,
        init_level = 0,
        school = 2,
        school_branch = 2,
        skill_id = 3303,
        skill_name = "断龙真斩",
        skill_pos = 5,
        type = 1,
        unlock_grade = 10,
    },

    [3305] = {
        icon = 3305,
        init_level = 0,
        school = 2,
        school_branch = 2,
        skill_id = 3305,
        skill_name = "龙缚炎爆",
        skill_pos = 6,
        type = 3,
        unlock_grade = 13,
    },

    [3306] = {
        icon = 3306,
        init_level = 0,
        school = 2,
        school_branch = 2,
        skill_id = 3306,
        skill_name = "逆饮",
        skill_pos = 2,
        type = 2,
        unlock_grade = 6,
    },

    [3307] = {
        icon = 3307,
        init_level = 0,
        school = 2,
        school_branch = 2,
        skill_id = 3307,
        skill_name = "厄转",
        skill_pos = 4,
        type = 2,
        unlock_grade = 8,
    },

    [3401] = {
        icon = 3401,
        init_level = 1,
        school = 3,
        school_branch = 1,
        skill_id = 3401,
        skill_name = "二旋拳",
        skill_pos = 1,
        type = 1,
        unlock_grade = 1,
    },

    [3402] = {
        icon = 3402,
        init_level = 1,
        school = 3,
        school_branch = 1,
        skill_id = 3402,
        skill_name = "雷霆贯穿",
        skill_pos = 3,
        type = 1,
        unlock_grade = 1,
    },

    [3403] = {
        icon = 3403,
        init_level = 0,
        school = 3,
        school_branch = 1,
        skill_id = 3403,
        skill_name = "君临之境",
        skill_pos = 5,
        type = 1,
        unlock_grade = 10,
    },

    [3405] = {
        icon = 3405,
        init_level = 0,
        school = 3,
        school_branch = 1,
        skill_id = 3405,
        skill_name = "无限破坏",
        skill_pos = 6,
        type = 3,
        unlock_grade = 13,
    },

    [3406] = {
        icon = 3406,
        init_level = 0,
        school = 3,
        school_branch = 1,
        skill_id = 3406,
        skill_name = "神谴",
        skill_pos = 2,
        type = 2,
        unlock_grade = 6,
    },

    [3407] = {
        icon = 3407,
        init_level = 0,
        school = 3,
        school_branch = 1,
        skill_id = 3407,
        skill_name = "修罗暴月",
        skill_pos = 4,
        type = 2,
        unlock_grade = 8,
    },

    [3501] = {
        icon = 3501,
        init_level = 1,
        school = 3,
        school_branch = 2,
        skill_id = 3501,
        skill_name = "荆棘卷",
        skill_pos = 1,
        type = 1,
        unlock_grade = 1,
    },

    [3502] = {
        icon = 3502,
        init_level = 1,
        school = 3,
        school_branch = 2,
        skill_id = 3502,
        skill_name = "贤之卷",
        skill_pos = 3,
        type = 1,
        unlock_grade = 1,
    },

    [3503] = {
        icon = 3503,
        init_level = 0,
        school = 3,
        school_branch = 2,
        skill_id = 3503,
        skill_name = "神庭黄昏",
        skill_pos = 5,
        type = 1,
        unlock_grade = 10,
    },

    [3505] = {
        icon = 3505,
        init_level = 0,
        school = 3,
        school_branch = 2,
        skill_id = 3505,
        skill_name = "星门咏唱",
        skill_pos = 6,
        type = 3,
        unlock_grade = 13,
    },

    [3506] = {
        icon = 3506,
        init_level = 0,
        school = 3,
        school_branch = 2,
        skill_id = 3506,
        skill_name = "溺境微光",
        skill_pos = 2,
        type = 2,
        unlock_grade = 6,
    },

    [3507] = {
        icon = 3507,
        init_level = 0,
        school = 3,
        school_branch = 2,
        skill_id = 3507,
        skill_name = "堕落之翼",
        skill_pos = 4,
        type = 2,
        unlock_grade = 8,
    },

}
