-- ./excel/skill/npc.xlsx
return {

    [1] = {
        ai_cd = 0,
        ai_target = "",
        args = "{abnormal_ratio=1500,min_ratio=750,max_ratio=3000}",
        args_desc = "ratio:几率,critical_ratio:暴击率,cnt:最多叠加次数",
        attackBuff = {},
        damage_ratio = "{12000,}",
        desc = "世界BOSS用技能",
        skill_id = 5001,
        skill_level = 1,
        victimBuff = {{["buffid"] = 1049, ["bout"] = 2}},
        war_desc = "攻击全体，有几率附加黑暗链",
    },

    [2] = {
        ai_cd = 0,
        ai_target = "",
        args = "{abnormal_ratio=1500,min_ratio=750,max_ratio=3000}",
        args_desc = "",
        attackBuff = {},
        damage_ratio = "{12000,}",
        desc = "世界BOSS用技能",
        skill_id = 5002,
        skill_level = 1,
        victimBuff = {{["buffid"] = 1017, ["bout"] = 1}},
        war_desc = "攻击全体，有几率造成眩晕",
    },

    [3] = {
        ai_cd = 0,
        ai_target = "",
        args = "{abnormal_ratio=1500,min_ratio=750,max_ratio=3000}",
        args_desc = "",
        attackBuff = {},
        damage_ratio = "{12000,}",
        desc = "世界BOSS用技能",
        skill_id = 5003,
        skill_level = 1,
        victimBuff = {{["buffid"] = 1004, ["bout"] = 2}},
        war_desc = "攻击全体，有几率造成失血",
    },

    [4] = {
        ai_cd = 0,
        ai_target = "",
        args = "",
        args_desc = "",
        attackBuff = {},
        damage_ratio = "{4200,4200,4200}",
        desc = "",
        skill_id = 5004,
        skill_level = 1,
        victimBuff = {},
        war_desc = "",
    },

    [5] = {
        ai_cd = 0,
        ai_target = "",
        args = "{abnormal_ratio=3000,min_ratio=1500,max_ratio=6000,damage=10}",
        args_desc = "",
        attackBuff = {},
        damage_ratio = "{3400,}",
        desc = "",
        skill_id = 5005,
        skill_level = 1,
        victimBuff = {},
        war_desc = "",
    },

    [6] = {
        ai_cd = 0,
        ai_target = "",
        args = "{damage_ratio=13000}",
        args_desc = "",
        attackBuff = {},
        damage_ratio = "{4800,4800}",
        desc = "",
        skill_id = 5006,
        skill_level = 1,
        victimBuff = {{["buffid"] = 1051, ["bout"] = 2}, {["buffid"] = 1050, ["bout"] = 2}},
        war_desc = "",
    },

    [7] = {
        ai_cd = 0,
        ai_target = "",
        args = "{abnormal_ratio=1500,min_ratio=750,max_ratio=3000,damage=100}",
        args_desc = "",
        attackBuff = {},
        damage_ratio = "{3600,3600,3600}",
        desc = "",
        skill_id = 5007,
        skill_level = 1,
        victimBuff = {},
        war_desc = "",
    },

    [8] = {
        ai_cd = 0,
        ai_target = "",
        args = "{ratio=3000,attack_ratio=3000,attack_damage=3000,cnt=2}",
        args_desc = "ratio:buff命中,attack_ratio:溅射伤害触发概率,cnt:溅射数量,attack_damage:伤害比",
        attackBuff = {},
        damage_ratio = "{9000,}",
        desc = "野外BOSS技能",
        skill_id = 5008,
        skill_level = 1,
        victimBuff = {{["buffid"] = 1065, ["bout"] = 1}},
        war_desc = "单体攻击一次，30%攻击溅射，30%概率陷入乏力",
    },

    [9] = {
        ai_cd = 0,
        ai_target = "",
        args = "{sleep=1,ratio=1000,min_ratio=1000,max_ratio=5000}",
        args_desc = "ratio：睡眠触发概率,sleep:同伴睡眠个数",
        attackBuff = {{["buffid"] = 1064, ["bout"] = 3}},
        damage_ratio = "{3600,3600,3600}",
        desc = "野外BOSS技能",
        skill_id = 5009,
        skill_level = 1,
        victimBuff = {{["buffid"] = 1019, ["bout"] = 2}},
        war_desc = "攻击全体3次，10%造成睡眠,小怪进入睡眠陷阱",
    },

    [10] = {
        ai_cd = 0,
        ai_target = "",
        args = "{buff_ratio=3000,}",
        args_desc = "buff_ratio:buff命中",
        attackBuff = {},
        damage_ratio = "{10000,}",
        desc = "野外BOSS技能",
        skill_id = 5010,
        skill_level = 1,
        victimBuff = {},
        war_desc = "对一个目标造成1次100%攻击的伤害，30%概率为一个喽啰施加协同BUFF",
    },

    [11] = {
        ai_cd = 0,
        ai_target = "",
        args = "{ratio=3000}",
        args_desc = "ratio:概率",
        attackBuff = {},
        damage_ratio = "{9000,9000}",
        desc = "野外BOSS技能",
        skill_id = 5011,
        skill_level = 1,
        victimBuff = {},
        war_desc = "对一个单位造成1次90%的攻击伤害；每个存活喽啰有30%概率同时使用普通攻击攻击该目标；然后对全体敌对单位造成90%伤害",
    },

    [12] = {
        ai_cd = 0,
        ai_target = "",
        args = "{ratio=2500,attack_ratio_min=1250,attack_ratio_max=6250,}",
        args_desc = "ratio:概率",
        attackBuff = {},
        damage_ratio = "{9000,}",
        desc = "野外BOSS技能",
        skill_id = 5012,
        skill_level = 1,
        victimBuff = {{["buffid"] = 1067, ["bout"] = 5}},
        war_desc = "对一个目标造成1次90%伤害，并有25%+效果命中概率标记目标",
    },

    [13] = {
        ai_cd = 0,
        ai_target = "",
        args = "{ratio=3000,attack_ratio_min=1000,attack_ratio_max=5000,}",
        args_desc = "ratio:概率",
        attackBuff = {},
        damage_ratio = "{3600,3600,3600}",
        desc = "野外BOSS技能",
        skill_id = 5013,
        skill_level = 1,
        victimBuff = {{["buffid"] = 1067, ["bout"] = 5}},
        war_desc = "对全体单位造成3次40%的攻击伤害，技能冷却3回合并于第一回合施放",
    },

    [14] = {
        ai_cd = 0,
        ai_target = "",
        args = "",
        args_desc = "",
        attackBuff = {},
        damage_ratio = "{9000,}",
        desc = "野外BOSS技能",
        skill_id = 5014,
        skill_level = 1,
        victimBuff = {},
        war_desc = "对全体伤害，与被5011组合使用的技能",
    },

    [15] = {
        ai_cd = 0,
        ai_target = "",
        args = "",
        args_desc = "",
        attackBuff = {},
        damage_ratio = "{}",
        desc = "召唤怪用技能，发呆不做任何事情",
        skill_id = 5015,
        skill_level = 1,
        victimBuff = {},
        war_desc = "召唤怪用技能，发呆不做任何事情",
    },

    [16] = {
        ai_cd = 0,
        ai_target = "",
        args = "{damageratio=3000}",
        args_desc = "ratio:概率",
        attackBuff = {},
        damage_ratio = "{4000,4000}",
        desc = "对全体敌我单位造成两次40%攻击力的伤害，每个被此技能杀死的单位会对敌方全体单位造成一次30%攻击的伤害",
        skill_id = 5016,
        skill_level = 1,
        victimBuff = {},
        war_desc = "对全体敌我单位造成两次40%攻击力的伤害，每个被此技能杀死的单位会对敌方全体单位造成一次30%攻击的伤害",
    },

    [17] = {
        ai_cd = 0,
        ai_target = "",
        args = "{attack_ratio=2000,buff=1071}",
        args_desc = "",
        attackBuff = {},
        damage_ratio = "{10800}",
        desc = "对全体敌方单位造成一次108%攻击力的伤害，释放结束后，所有存活小怪获得boss的20%攻击力，持续2次行动（不包括刚召唤的）",
        skill_id = 5017,
        skill_level = 1,
        victimBuff = {},
        war_desc = "对全体敌方单位造成一次108%攻击力的伤害，释放结束后，所有存活小怪获得boss的20%攻击力，持续2次行动（不包括刚召唤的）",
    },

    [18] = {
        ai_cd = 0,
        ai_target = "",
        args = "{buff=1072,damage_ratio=5000}",
        args_desc = "",
        attackBuff = {},
        damage_ratio = "{4500,4500}",
        desc = "对全体敌方单位造成两次45%攻击力的伤害，并将最多2个我方小怪（不包括刚召唤的）改造为炸弹，炸弹无法攻击，存活的炸弹在2次行动后自爆，对全体敌方单位造成50%BOSS攻击力的伤害",
        skill_id = 5018,
        skill_level = 1,
        victimBuff = {},
        war_desc = "对全体敌方单位造成两次45%攻击力的伤害，并将最多2个我方小怪（不包括刚召唤的）改造为炸弹，炸弹无法攻击，存活的炸弹在2次行动后自爆，对全体敌方单位造成50%BOSS攻击力的伤害",
    },

}
