-- ./excel/skill/se.xlsx
return {

    [1] = {
        args = "{damage_ratio=2300}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "套装：血衣，造成伤害的15%将转化为自身气血",
        effect_type = 0,
        name = "",
        skill_id = 210,
        skill_level = 1,
        victimBuff = {},
    },

    [2] = {
        args = "{hp_ratio=3000,damage_ratio=3800}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "流莺",
        effect_type = 0,
        name = "",
        skill_id = 211,
        skill_level = 1,
        victimBuff = {},
    },

    [3] = {
        args = "{hp_ratio=7000,damage_ratio=3000}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "博戏鬼",
        effect_type = 0,
        name = "",
        skill_id = 212,
        skill_level = 1,
        victimBuff = {},
    },

    [4] = {
        args = "{ratio=10000}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "归无处",
        effect_type = 0,
        name = "",
        skill_id = 213,
        skill_level = 1,
        victimBuff = {},
    },

    [5] = {
        args = "{ratio=1800}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "黑帝",
        effect_type = 0,
        name = "",
        skill_id = 214,
        skill_level = 1,
        victimBuff = {},
    },

    [6] = {
        args = "{damage_ratio=4000}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "洛迦",
        effect_type = 0,
        name = "",
        skill_id = 215,
        skill_level = 1,
        victimBuff = {},
    },

    [7] = {
        args = "{defense_ratio=5000,ratio=6000}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "红雨将军",
        effect_type = 0,
        name = "",
        skill_id = 216,
        skill_level = 1,
        victimBuff = {},
    },

    [8] = {
        args = "{damage_ratio=3500}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "套装：异常增伤 自己拥有异常状态",
        effect_type = 0,
        name = "",
        skill_id = 217,
        skill_level = 1,
        victimBuff = {},
    },

    [9] = {
        args = "{damage_ratio=2500,rebound_ratio=1500}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "套装： 舍身 技能基础伤害提升20%(A类系数)，伤害计算结束后自身损失总伤害25%的气血（能致死）",
        effect_type = 0,
        name = "",
        skill_id = 218,
        skill_level = 1,
        victimBuff = {},
    },

    [10] = {
        args = "{ratio=4500,damage_ratio=6000}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "套装： 针女 每次暴击时，30%概率附加自己攻击15%的真实伤害",
        effect_type = 0,
        name = "",
        skill_id = 219,
        skill_level = 1,
        victimBuff = {},
    },

    [11] = {
        args = "{ratio=2500,damage_ratio=10000}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "茨童",
        effect_type = 0,
        name = "",
        skill_id = 230,
        skill_level = 1,
        victimBuff = {},
    },

    [12] = {
        args = "{damage_ratio=2000}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "颜无月",
        effect_type = 0,
        name = "",
        skill_id = 231,
        skill_level = 1,
        victimBuff = {},
    },

    [13] = {
        args = "{ratio=1800}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "巫左道",
        effect_type = 0,
        name = "",
        skill_id = 232,
        skill_level = 1,
        victimBuff = {},
    },

    [14] = {
        args = "{hp_ratio=500}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "漓渚",
        effect_type = 0,
        name = "",
        skill_id = 233,
        skill_level = 1,
        victimBuff = {{["buffid"] = 1035, ["bout"] = 2}},
    },

    [15] = {
        args = "{revive_ratio=3000,revive_cnt=2}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "套装：抗致死 受到致死伤害时有20%机率剩余1点气血不死，每回合最多触发2次",
        effect_type = 0,
        name = "",
        skill_id = 234,
        skill_level = 1,
        victimBuff = {},
    },

    [16] = {
        args = "{ratio=4500,hp_ratio=50}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "套装： 受伤回血 每回合结束时，30%概率恢复本回合受到的总伤害的50%气血",
        effect_type = 0,
        name = "",
        skill_id = 235,
        skill_level = 1,
        victimBuff = {},
    },

    [17] = {
        args = "{ratio=800,min_ratio=400,max_ratio=2000}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "偃月无夜",
        effect_type = 0,
        name = "",
        skill_id = 240,
        skill_level = 1,
        victimBuff = {{["buffid"] = 1017, ["bout"] = 1}},
    },

    [18] = {
        args = "{ratio=1000,min_ratio=500,max_ratio=2500}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "湫",
        effect_type = 0,
        name = "",
        skill_id = 241,
        skill_level = 1,
        victimBuff = {{["buffid"] = 1019, ["bout"] = 1}},
    },

    [19] = {
        args = "{ratio=2000,min_ratio=1000,max_ratio=5000}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "铃音",
        effect_type = 0,
        name = "",
        skill_id = 242,
        skill_level = 1,
        victimBuff = {{["buffid"] = 1024, ["bout"] = 2}},
    },

    [20] = {
        args = "{ratio=800}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "陶磊磊",
        effect_type = 0,
        name = "",
        skill_id = 243,
        skill_level = 1,
        victimBuff = {{["buffid"] = 1017, ["bout"] = 1}},
    },

    [21] = {
        args = "{ratio=5000}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "巳日时君",
        effect_type = 0,
        name = "",
        skill_id = 244,
        skill_level = 1,
        victimBuff = {{["buffid"] = 1041, ["bout"] = 1}},
    },

    [22] = {
        args = "{ratio=3000,sp=20}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "套装：增压 受到怒气技能伤害时，30%机率使对方损失1格怒气",
        effect_type = 0,
        name = "",
        skill_id = 245,
        skill_level = 1,
        victimBuff = {},
    },

    [23] = {
        args = "",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "椿",
        effect_type = 0,
        name = "",
        skill_id = 250,
        skill_level = 1,
        victimBuff = {},
    },

    [24] = {
        args = "{ratio=5000}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "锵明",
        effect_type = 0,
        name = "",
        skill_id = 251,
        skill_level = 1,
        victimBuff = {},
    },

    [25] = {
        args = "{ratio=2400,hp_ratio=500}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "流臾之须",
        effect_type = 0,
        name = "",
        skill_id = 252,
        skill_level = 1,
        victimBuff = {},
    },

    [26] = {
        args = "{ratio=3000}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "诡象之匣",
        effect_type = 0,
        name = "",
        skill_id = 253,
        skill_level = 1,
        victimBuff = {{["buffid"] = 1042, ["bout"] = 1}},
    },

    [27] = {
        args = "{ratio=2500}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "一阕秋",
        effect_type = 0,
        name = "",
        skill_id = 254,
        skill_level = 1,
        victimBuff = {},
    },

    [28] = {
        args = "{ratio=4000}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "斑曜",
        effect_type = 0,
        name = "",
        skill_id = 255,
        skill_level = 1,
        victimBuff = {{["buffid"] = 1034, ["bout"] = 1}},
    },

    [29] = {
        args = "",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "拥有该被动，自动使用怒气技能且不消耗怒气",
        effect_type = 0,
        name = "",
        skill_id = 1001,
        skill_level = 1,
        victimBuff = {},
    },

    [30] = {
        args = "{ratio=1000,damage_ratio=3000}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "10%格挡率,反弹伤害",
        effect_type = 0,
        name = "格挡",
        skill_id = 1002,
        skill_level = 1,
        victimBuff = {},
    },

    [31] = {
        args = "{damage_ratio=1000}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "BOSS进行任何行动时，对拥有标记的单位造成本次行动造成伤害（只算主目标所受伤害）*10%*标记数的真实伤害（同时计算标记增伤）",
        effect_type = 0,
        name = "",
        skill_id = 1003,
        skill_level = 1,
        victimBuff = {},
    },

    [32] = {
        args = "",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "伙伴副本专用(256)",
        effect_type = 0,
        name = "",
        skill_id = 1004,
        skill_level = 1,
        victimBuff = {},
    },

    [33] = {
        args = "",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "世界BOSS专用被动，召唤,当召唤物死亡后，会被封印1043BUFF(257)",
        effect_type = 0,
        name = "",
        skill_id = 1005,
        skill_level = 1,
        victimBuff = {},
    },

    [34] = {
        args = "",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "普攻时20%概率清除(258)",
        effect_type = 0,
        name = "",
        skill_id = 1006,
        skill_level = 1,
        victimBuff = {},
    },

    [35] = {
        args = "",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "免疫异常大组，控制类BUFF(259)",
        effect_type = 0,
        name = "",
        skill_id = 1007,
        skill_level = 1,
        victimBuff = {},
    },

    [36] = {
        args = "{bout_damage=5}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "回合伤害上升(260)",
        effect_type = 0,
        name = "",
        skill_id = 1008,
        skill_level = 1,
        victimBuff = {},
    },

    [37] = {
        args = "",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "敌方开场获得80%怒气(300)",
        effect_type = 0,
        name = "",
        skill_id = 1009,
        skill_level = 1,
        victimBuff = {},
    },

    [38] = {
        args = "{bout_damage=5}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "回合伤害上升5%",
        effect_type = 0,
        name = "",
        skill_id = 1010,
        skill_level = 1,
        victimBuff = {},
    },

    [39] = {
        args = "{bout_damage=5}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "回合伤害上升(260)",
        effect_type = 0,
        name = "",
        skill_id = 1011,
        skill_level = 1,
        victimBuff = {},
    },

    [40] = {
        args = "",
        attackBuff = {},
        attr_ratio_list = "{attack=500}",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "",
        effect_type = 1,
        name = "",
        skill_id = 1040,
        skill_level = 1,
        victimBuff = {},
    },

    [41] = {
        args = "",
        attackBuff = {},
        attr_ratio_list = "{defense=1000}",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "",
        effect_type = 1,
        name = "",
        skill_id = 1140,
        skill_level = 1,
        victimBuff = {},
    },

    [42] = {
        args = "",
        attackBuff = {},
        attr_ratio_list = "{attack=500}",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "",
        effect_type = 1,
        name = "",
        skill_id = 1240,
        skill_level = 1,
        victimBuff = {},
    },

    [43] = {
        args = "",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "{abnormal_attr_ratio=500}",
        desc = "",
        effect_type = 1,
        name = "",
        skill_id = 1340,
        skill_level = 1,
        victimBuff = {},
    },

    [44] = {
        args = "",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "{critical_damage=500}",
        desc = "",
        effect_type = 1,
        name = "",
        skill_id = 1440,
        skill_level = 1,
        victimBuff = {},
    },

    [45] = {
        args = "",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "{cure_critical_ratio=500}",
        desc = "",
        effect_type = 1,
        name = "",
        skill_id = 1540,
        skill_level = 1,
        victimBuff = {},
    },

    [46] = {
        args = "{ratio=3000}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "",
        effect_type = 0,
        name = "",
        skill_id = 1050,
        skill_level = 1,
        victimBuff = {},
    },

    [47] = {
        args = "{ratio=1000}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "",
        effect_type = 0,
        name = "",
        skill_id = 1150,
        skill_level = 1,
        victimBuff = {},
    },

    [48] = {
        args = "{hp_ratio=1000}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "",
        effect_type = 0,
        name = "",
        skill_id = 1250,
        skill_level = 1,
        victimBuff = {},
    },

    [49] = {
        args = "{ratio=1000}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "",
        effect_type = 0,
        name = "",
        skill_id = 1350,
        skill_level = 1,
        victimBuff = {},
    },

    [50] = {
        args = "{critical_damage=1000}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "",
        effect_type = 0,
        name = "",
        skill_id = 1450,
        skill_level = 1,
        victimBuff = {},
    },

    [51] = {
        args = "{ratio=1000}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "",
        effect_type = 0,
        name = "",
        skill_id = 1550,
        skill_level = 1,
        victimBuff = {},
    },

    [52] = {
        args = "{ratio=4000}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "",
        effect_type = 0,
        name = "",
        skill_id = 1060,
        skill_level = 1,
        victimBuff = {},
    },

    [53] = {
        args = "{ratio=2000}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "",
        effect_type = 0,
        name = "",
        skill_id = 1160,
        skill_level = 1,
        victimBuff = {},
    },

    [54] = {
        args = "{hp_ratio=2000}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "",
        effect_type = 0,
        name = "",
        skill_id = 1260,
        skill_level = 1,
        victimBuff = {},
    },

    [55] = {
        args = "{ratio=1500}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "",
        effect_type = 0,
        name = "",
        skill_id = 1360,
        skill_level = 1,
        victimBuff = {},
    },

    [56] = {
        args = "{critical_damage=100}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "",
        effect_type = 0,
        name = "",
        skill_id = 1460,
        skill_level = 1,
        victimBuff = {},
    },

    [57] = {
        args = "{ratio=2000}",
        attackBuff = {},
        attr_ratio_list = "",
        attr_temp_addvalue = "",
        attr_temp_ratio = "",
        attr_value_list = "",
        desc = "",
        effect_type = 0,
        name = "",
        skill_id = 1560,
        skill_level = 1,
        victimBuff = {},
    },

}
