-- ./excel/task/shimen/taskdialog.xlsx
return {

    [1] = {
        content = "白婆婆需要一些蘑菇，你能帮忙采集一些吗？",
        dialog_id = 60001,
        finish_event = "STARTPICK",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [2] = {
        content = "谢谢你帮我采蘑菇",
        dialog_id = 60001,
        finish_event = "STARTPICK",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [3] = {
        content = "就是这种大蘑菇，太感谢你了！",
        dialog_id = 60001,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 5,
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [4] = {
        content = "蝴蝶，美丽的蝴蝶，我想要，喵~",
        dialog_id = 60002,
        finish_event = "_FP",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [5] = {
        content = "谢谢你帮我收割鲜花",
        dialog_id = 60002,
        finish_event = "_FP",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [6] = {
        content = "情报科关于冥界的相关记录比较缺失，你去考察一番！",
        dialog_id = 60003,
        finish_event = "_PATROL",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [7] = {
        content = "任务完成的不错！",
        dialog_id = 60003,
        finish_event = "_PATROL",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [8] = {
        content = "喵萌茶会要开始了，今年特邀嘉宾是执阳，你去枫竹林把邀请函给他吧。",
        dialog_id = 60004,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [9] = {
        content = "茶会，茶会，很多好吃食物的茶会，我要去！",
        dialog_id = 60004,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [10] = {
        content = "侦察调查是每个新兵的必备技能，你去找外勤科丑无完成侦察训练。",
        dialog_id = 60005,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [11] = {
        content = "目前为止，今年新兵的训练成绩都很不错，你也要加油！",
        dialog_id = 60005,
        finish_event = "",
        last_action = {{["content"] = "开始特训", ["event"] = "F10011"}, {["content"] = "再准备一下", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [12] = {
        content = "我的酱香豆豉小鱼干，到底是谁偷走的！",
        dialog_id = 60006,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [13] = {
        content = "鱼干的嚼劲加上豆豉的香气，简直是人间极品啊！",
        dialog_id = 60006,
        finish_event = "",
        last_action = {{["content"] = "交出鱼干", ["event"] = "F10021"}, {["content"] = "认错人了", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [14] = {
        content = "我的鸡！一大早起来就不见了我的鸡！快帮我找找",
        dialog_id = 60007,
        finish_event = "TARGET40004",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [15] = {
        content = "终于找到你了，快跟我回去吧！",
        dialog_id = 60007,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "40004,0",
        status = 1,
        subid = 2,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [16] = {
        content = "咯咯咯…",
        dialog_id = 60007,
        finish_event = "STARTTRACE,COMMIT,_DESC2",
        last_action = {},
        next = "0",
        pre_id_list = "40004,0",
        status = 1,
        subid = 3,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [17] = {
        content = "我的宝贝回来了，太谢谢你了，这个鸡蛋送给你！",
        dialog_id = 60007,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 5,
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [18] = {
        content = "莹月老早就说想看雪莲，你能去幽溟镇找一株给她吗？",
        dialog_id = 60011,
        finish_event = "STARTPICK",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [19] = {
        content = "雪莲",
        dialog_id = 60011,
        finish_event = "STARTPICK",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [20] = {
        content = "咦，哪来的莲花，是要送给我吗，谢谢你！我拿去给绿狸看看。",
        dialog_id = 60011,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 5,
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [21] = {
        content = "飞龙哥想栽培一些观赏竹，但这种竹子只有枫树竹林才有！",
        dialog_id = 60012,
        finish_event = "STARTPICK",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [22] = {
        content = "竹竿",
        dialog_id = 60012,
        finish_event = "STARTPICK",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [23] = {
        content = "踏破帝都无觅处，得来全不费功夫，这竹笋我收下了！",
        dialog_id = 60012,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 5,
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [24] = {
        content = "仇大富需要一些蘑菇，你能帮忙采集一些吗？",
        dialog_id = 60013,
        finish_event = "STARTPICK",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [25] = {
        content = "谢谢你帮我采蘑菇",
        dialog_id = 60013,
        finish_event = "STARTPICK",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [26] = {
        content = "就是这种蘑菇！这下我有又可以做香辣烤肉了。",
        dialog_id = 60013,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 5,
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [27] = {
        content = "咸鱼飞最近来问我有无明矾，要这东西来做什么呢？",
        dialog_id = 60014,
        finish_event = "STARTPICK",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [28] = {
        content = "谢谢你帮我采蘑菇",
        dialog_id = 60014,
        finish_event = "STARTPICK",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [29] = {
        content = "这些可以把水源净化一下了",
        dialog_id = 60014,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 5,
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [30] = {
        content = "丽丝希望能看一眼雪莲的样子，愿主能完成她的心愿。",
        dialog_id = 60015,
        finish_event = "STARTPICK",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [31] = {
        content = "雪莲",
        dialog_id = 60015,
        finish_event = "STARTPICK",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [32] = {
        content = "莲花！一定是主听到了我的祈祷。",
        dialog_id = 60015,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 5,
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [33] = {
        content = "早上甘医生过来询问是否有褐铁矿出售，这种矿物在断魂崖才有。",
        dialog_id = 60016,
        finish_event = "STARTPICK",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [34] = {
        content = "雪莲",
        dialog_id = 60016,
        finish_event = "STARTPICK",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [35] = {
        content = "褐铁矿！这些足够做一整锅止血药了。",
        dialog_id = 60016,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 5,
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [36] = {
        content = "今年风沙频繁，链想在矿洞的水源附近栽培竹子阻挡风沙。",
        dialog_id = 60017,
        finish_event = "STARTPICK",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [37] = {
        content = "竹竿",
        dialog_id = 60017,
        finish_event = "STARTPICK",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [38] = {
        content = "太好了，我马上就去种上！",
        dialog_id = 60017,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 5,
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [39] = {
        content = "曼殊沙华，彼岸之花，幽冥之火，我兄弟一定很喜欢！",
        dialog_id = 60018,
        finish_event = "STARTPICK",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [40] = {
        content = "竹竿",
        dialog_id = 60018,
        finish_event = "STARTPICK",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [41] = {
        content = "无缘无故送人家花干嘛，讨厌厌~",
        dialog_id = 60018,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 5,
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [42] = {
        content = "邓酒爷那小子一直很想要彼岸花，我这个做大哥的得给他弄一朵！",
        dialog_id = 60019,
        finish_event = "STARTPICK",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [43] = {
        content = "竹竿",
        dialog_id = 60019,
        finish_event = "STARTPICK",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [44] = {
        content = "冥…冥界才有的东西，你怎么会有，不可思议！",
        dialog_id = 60019,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 5,
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [45] = {
        content = "听说从帝都往北直到下雪的地方，生长着一种紫色花朵。",
        dialog_id = 60021,
        finish_event = "_FP",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [46] = {
        content = "谢谢你帮我收割鲜花",
        dialog_id = 60021,
        finish_event = "_FP",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [47] = {
        content = "矿石之城已经采集不到复活草了，或许断魂崖还能发现。",
        dialog_id = 60022,
        finish_event = "_FP",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [48] = {
        content = "谢谢你帮我收割鲜花",
        dialog_id = 60022,
        finish_event = "_FP",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [49] = {
        content = "蝴蝶，莹月想要蝴蝶，快去帮我抓一只蝴蝶！",
        dialog_id = 60023,
        finish_event = "_FP",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [50] = {
        content = "谢谢你帮我收割鲜花",
        dialog_id = 60023,
        finish_event = "_FP",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [51] = {
        content = "教会培养了一种珍稀的蝴蝶品种，如果能弄到一只样本的话，啵哟~",
        dialog_id = 60024,
        finish_event = "_FP",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [52] = {
        content = "谢谢你帮我收割鲜花",
        dialog_id = 60024,
        finish_event = "_FP",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [53] = {
        content = "外勤科报告，月见岛发现有妖族踪迹，统帅部指派你前去巡查。",
        dialog_id = 60031,
        finish_event = "_PATROL",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [54] = {
        content = "任务完成的不错！",
        dialog_id = 60031,
        finish_event = "_PATROL",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [55] = {
        content = "八门村居民报告，最近经常受到流民袭扰，就由你来处理这件事吧。",
        dialog_id = 60032,
        finish_event = "_PATROL",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [56] = {
        content = "任务完成的不错！",
        dialog_id = 60032,
        finish_event = "_PATROL",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [57] = {
        content = "外勤科一直无法渗透进枫竹林，或许你可以去试试。",
        dialog_id = 60033,
        finish_event = "_PATROL",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [58] = {
        content = "任务完成的不错！",
        dialog_id = 60033,
        finish_event = "_PATROL",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [59] = {
        content = "武道会参赛失踪人员至今没有线索，统帅部指派你再次去断魂崖调查。",
        dialog_id = 60034,
        finish_event = "_PATROL",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [60] = {
        content = "任务完成的不错！",
        dialog_id = 60034,
        finish_event = "_PATROL",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [61] = {
        content = "派往矿石之城的调查人员屡屡被遣回，统帅部想派一些新面孔过去。",
        dialog_id = 60035,
        finish_event = "_PATROL",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [62] = {
        content = "任务完成的不错！",
        dialog_id = 60035,
        finish_event = "_PATROL",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [63] = {
        content = "幽溟镇秩序尚未恢复正常，统帅部指派你前去弹压。",
        dialog_id = 60036,
        finish_event = "_PATROL",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [64] = {
        content = "任务完成的不错！",
        dialog_id = 60036,
        finish_event = "_PATROL",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [65] = {
        content = "中级调查组发现了一些线索，需要矿石之城的锋配合调查，你把这份统帅部的传票送给他吧。",
        dialog_id = 60041,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [66] = {
        content = "整天调查调查，有完没完！",
        dialog_id = 60041,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [67] = {
        content = "八门村猫蜀黍定制的衣服已经做好了，你帮人家送过去嘛，嘤嘤嘤~",
        dialog_id = 60042,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [68] = {
        content = "我的衣服终于到了，迫不及待想穿上！",
        dialog_id = 60042,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [69] = {
        content = "外勤科在断魂崖发现了重要线索，你立即把情报送给乔焱！",
        dialog_id = 60043,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [70] = {
        content = "做的不错！这条情报对我们来说非常重要。",
        dialog_id = 60043,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [71] = {
        content = "教会已经收到断魂崖村民的祈祷，你把这份福音传递给他们吧。",
        dialog_id = 60044,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [72] = {
        content = "神父会派出骑士团来保护我们吗？",
        dialog_id = 60044,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [73] = {
        content = "已经很久没有看到莹月姐姐了，她什么时候才能再来看我？",
        dialog_id = 60045,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [74] = {
        content = "枫竹林的小执阳？或许我再也回不去了。",
        dialog_id = 60045,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [75] = {
        content = "昨天捡到一位衣着奇怪的小姐姐掉的东西，你帮我送回去吧，嘻嘻嘻~",
        dialog_id = 60046,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [76] = {
        content = "会说话的公告牌？人类的世界真是太危险了！",
        dialog_id = 60046,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [77] = {
        content = "忘川之下，幽溟之子，也不知现在如何了？",
        dialog_id = 60047,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [78] = {
        content = "奉主夜鹤，我曾与他见过吗？",
        dialog_id = 60047,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [79] = {
        content = "耐心是每个新兵必备的素质，你去找八门村熊猫爷爷完成耐性训练。",
        dialog_id = 60051,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [80] = {
        content = "心境平和，动心忍性，增益其所不能。",
        dialog_id = 60051,
        finish_event = "",
        last_action = {{["content"] = "开始特训", ["event"] = "F10012"}, {["content"] = "再准备一下", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [81] = {
        content = "近身格斗是每个新兵的必备技能，你去找竞技场的荆鸣完成格斗训练。",
        dialog_id = 60052,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [82] = {
        content = "这不是上次武道会的冠军吗？好好加油！",
        dialog_id = 60052,
        finish_event = "",
        last_action = {{["content"] = "开始特训", ["event"] = "F10013"}, {["content"] = "再准备一下", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [83] = {
        content = "战地救护是每个新兵必备技能，你去找医生甘完成救护训练！",
        dialog_id = 60053,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [84] = {
        content = "战场受伤在所难免，每个新兵都需要学会救护。",
        dialog_id = 60053,
        finish_event = "",
        last_action = {{["content"] = "开始特训", ["event"] = "F10014"}, {["content"] = "再准备一下", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [85] = {
        content = "荒野求生是每个新兵必备技能，你去找喵小萌完成烹饪训练！",
        dialog_id = 60054,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [86] = {
        content = "在野外可吃不到小萌的包子哦",
        dialog_id = 60054,
        finish_event = "",
        last_action = {{["content"] = "开始特训", ["event"] = "F10018"}, {["content"] = "再准备一下", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [87] = {
        content = "昨天市政监狱发生越狱，统帅部安排你去幽溟镇追回逃犯。",
        dialog_id = 60061,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [88] = {
        content = "我的越狱经历完全可以拍成电影！",
        dialog_id = 60061,
        finish_event = "",
        last_action = {{["content"] = "跟我回去", ["event"] = "F10022"}, {["content"] = "认错人了", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [89] = {
        content = "谁偷了我的包子！快去帮我抓回来~~",
        dialog_id = 60062,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [90] = {
        content = "小笼包，叉烧包，奶黄芝麻豆沙包",
        dialog_id = 60062,
        finish_event = "",
        last_action = {{["content"] = "交出包子", ["event"] = "F10023"}, {["content"] = "认错人了", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [91] = {
        content = "今早发现熊霸又走丢了，你能帮我找找吗？",
        dialog_id = 60063,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [92] = {
        content = "吼，吼，吼~~",
        dialog_id = 60063,
        finish_event = "",
        last_action = {{["content"] = "跟我回去", ["event"] = "F10024"}, {["content"] = "认错人了", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [93] = {
        content = "今早又发现村庄外面有妖族活动，统帅部打算放弃我们吗？",
        dialog_id = 60064,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [94] = {
        content = "嘎~嘎嘎嘎嘎~人类，必须离开！",
        dialog_id = 60064,
        finish_event = "",
        last_action = {{["content"] = "莫要伤人", ["event"] = "F10025"}, {["content"] = "路过", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [95] = {
        content = "今天忙起来，发现喵喵不见了，你能帮我找找吗？",
        dialog_id = 60071,
        finish_event = "TARGET40009",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [96] = {
        content = "终于找到你了，快跟我回去吧！",
        dialog_id = 60071,
        finish_event = "STARTTRACE,COMMIT,_DESC2",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [97] = {
        content = "我的小宝贝，想死我了！感谢你。",
        dialog_id = 60071,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 5,
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [98] = {
        content = "我找遍了整个枫竹林都没有发现花花，到底跑去那里了？",
        dialog_id = 60072,
        finish_event = "TARGET40010",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [99] = {
        content = "终于找到你了，快跟我回去吧！",
        dialog_id = 60072,
        finish_event = "STARTTRACE,COMMIT,_DESC2",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 1,
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [100] = {
        content = "跑到哪里去了，外面的世界很危险！",
        dialog_id = 60072,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 5,
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

}
