-- ./excel/house/furniture.xlsx
return {

    [1] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 1,
        gold = 5000,
        item_cnt = 20,
        level = 1,
        up_level_time = 5,
    },

    [2] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 1,
        gold = 10000,
        item_cnt = 30,
        level = 2,
        up_level_time = 15,
    },

    [3] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 1,
        gold = 20000,
        item_cnt = 40,
        level = 3,
        up_level_time = 60,
    },

    [4] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 1,
        gold = 50000,
        item_cnt = 60,
        level = 4,
        up_level_time = 120,
    },

    [5] = {
        desc = "增加温馨度",
        effect = "{warm=10}",
        effect_desc = "升级描述",
        furniture_type = 1,
        gold = 100000,
        item_cnt = 90,
        level = 5,
        up_level_time = 180,
    },

    [6] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 1,
        gold = 200000,
        item_cnt = 130,
        level = 6,
        up_level_time = 360,
    },

    [7] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 1,
        gold = 400000,
        item_cnt = 180,
        level = 7,
        up_level_time = 540,
    },

    [8] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 1,
        gold = 800000,
        item_cnt = 250,
        level = 8,
        up_level_time = 720,
    },

    [9] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 1,
        gold = 1400000,
        item_cnt = 330,
        level = 9,
        up_level_time = 1440,
    },

    [10] = {
        desc = "增加温馨度",
        effect = "{warm=10}",
        effect_desc = "升级描述",
        furniture_type = 1,
        gold = 2000000,
        item_cnt = 400,
        level = 10,
        up_level_time = 2880,
    },

    [11] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 2,
        gold = 5000,
        item_cnt = 20,
        level = 1,
        up_level_time = 5,
    },

    [12] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 2,
        gold = 10000,
        item_cnt = 30,
        level = 2,
        up_level_time = 15,
    },

    [13] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 2,
        gold = 20000,
        item_cnt = 40,
        level = 3,
        up_level_time = 60,
    },

    [14] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 2,
        gold = 50000,
        item_cnt = 60,
        level = 4,
        up_level_time = 120,
    },

    [15] = {
        desc = "增加温馨度",
        effect = "{warm=10}",
        effect_desc = "升级描述",
        furniture_type = 2,
        gold = 100000,
        item_cnt = 90,
        level = 5,
        up_level_time = 180,
    },

    [16] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 2,
        gold = 200000,
        item_cnt = 130,
        level = 6,
        up_level_time = 360,
    },

    [17] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 2,
        gold = 400000,
        item_cnt = 180,
        level = 7,
        up_level_time = 540,
    },

    [18] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 2,
        gold = 800000,
        item_cnt = 250,
        level = 8,
        up_level_time = 720,
    },

    [19] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 2,
        gold = 1400000,
        item_cnt = 330,
        level = 9,
        up_level_time = 1440,
    },

    [20] = {
        desc = "增加温馨度",
        effect = "{warm=10}",
        effect_desc = "升级描述",
        furniture_type = 2,
        gold = 2000000,
        item_cnt = 400,
        level = 10,
        up_level_time = 2880,
    },

    [21] = {
        desc = "增加温馨度",
        effect = "{cook_rate=2}",
        effect_desc = "升级描述",
        furniture_type = 3,
        gold = 5000,
        item_cnt = 20,
        level = 1,
        up_level_time = 5,
    },

    [22] = {
        desc = "增加温馨度",
        effect = "{cook_rate=4}",
        effect_desc = "升级描述",
        furniture_type = 3,
        gold = 10000,
        item_cnt = 30,
        level = 2,
        up_level_time = 15,
    },

    [23] = {
        desc = "增加温馨度",
        effect = "{cook_rate=6}",
        effect_desc = "升级描述",
        furniture_type = 3,
        gold = 20000,
        item_cnt = 40,
        level = 3,
        up_level_time = 60,
    },

    [24] = {
        desc = "增加温馨度",
        effect = "{cook_rate=8}",
        effect_desc = "升级描述",
        furniture_type = 3,
        gold = 50000,
        item_cnt = 60,
        level = 4,
        up_level_time = 120,
    },

    [25] = {
        desc = "增加温馨度",
        effect = "{cook_rate=10,warm=10}",
        effect_desc = "升级描述",
        furniture_type = 3,
        gold = 100000,
        item_cnt = 90,
        level = 5,
        up_level_time = 180,
    },

    [26] = {
        desc = "增加温馨度",
        effect = "{cook_rate=12}",
        effect_desc = "升级描述",
        furniture_type = 3,
        gold = 200000,
        item_cnt = 130,
        level = 6,
        up_level_time = 360,
    },

    [27] = {
        desc = "增加温馨度",
        effect = "{cook_rate=14}",
        effect_desc = "升级描述",
        furniture_type = 3,
        gold = 400000,
        item_cnt = 180,
        level = 7,
        up_level_time = 540,
    },

    [28] = {
        desc = "增加温馨度",
        effect = "{cook_rate=16}",
        effect_desc = "升级描述",
        furniture_type = 3,
        gold = 800000,
        item_cnt = 250,
        level = 8,
        up_level_time = 720,
    },

    [29] = {
        desc = "增加温馨度",
        effect = "{cook_rate=18}",
        effect_desc = "升级描述",
        furniture_type = 3,
        gold = 1400000,
        item_cnt = 330,
        level = 9,
        up_level_time = 1440,
    },

    [30] = {
        desc = "增加温馨度",
        effect = "{cook_rate=20,warm=10}",
        effect_desc = "升级描述",
        furniture_type = 3,
        gold = 2000000,
        item_cnt = 400,
        level = 10,
        up_level_time = 2880,
    },

    [31] = {
        desc = "增加温馨度",
        effect = "{chuanshuo_rate=2}",
        effect_desc = "升级描述",
        furniture_type = 4,
        gold = 5000,
        item_cnt = 20,
        level = 1,
        up_level_time = 5,
    },

    [32] = {
        desc = "增加温馨度",
        effect = "{chuanshuo_rate=4}",
        effect_desc = "升级描述",
        furniture_type = 4,
        gold = 10000,
        item_cnt = 30,
        level = 2,
        up_level_time = 15,
    },

    [33] = {
        desc = "增加温馨度",
        effect = "{chuanshuo_rate=6}",
        effect_desc = "升级描述",
        furniture_type = 4,
        gold = 20000,
        item_cnt = 40,
        level = 3,
        up_level_time = 60,
    },

    [34] = {
        desc = "增加温馨度",
        effect = "{chuanshuo_rate=8}",
        effect_desc = "升级描述",
        furniture_type = 4,
        gold = 50000,
        item_cnt = 60,
        level = 4,
        up_level_time = 120,
    },

    [35] = {
        desc = "增加温馨度",
        effect = "{chuanshuo_rate=10,warm=10}",
        effect_desc = "升级描述",
        furniture_type = 4,
        gold = 100000,
        item_cnt = 90,
        level = 5,
        up_level_time = 180,
    },

    [36] = {
        desc = "增加温馨度",
        effect = "{chuanshuo_rate=12}",
        effect_desc = "升级描述",
        furniture_type = 4,
        gold = 200000,
        item_cnt = 130,
        level = 6,
        up_level_time = 360,
    },

    [37] = {
        desc = "增加温馨度",
        effect = "{chuanshuo_rate=14}",
        effect_desc = "升级描述",
        furniture_type = 4,
        gold = 400000,
        item_cnt = 180,
        level = 7,
        up_level_time = 540,
    },

    [38] = {
        desc = "增加温馨度",
        effect = "{chuanshuo_rate=16}",
        effect_desc = "升级描述",
        furniture_type = 4,
        gold = 800000,
        item_cnt = 250,
        level = 8,
        up_level_time = 720,
    },

    [39] = {
        desc = "增加温馨度",
        effect = "{chuanshuo_rate=18}",
        effect_desc = "升级描述",
        furniture_type = 4,
        gold = 1400000,
        item_cnt = 330,
        level = 9,
        up_level_time = 1440,
    },

    [40] = {
        desc = "增加温馨度",
        effect = "{chuanshuo_rate=20,warm=10}",
        effect_desc = "升级描述",
        furniture_type = 4,
        gold = 2000000,
        item_cnt = 400,
        level = 10,
        up_level_time = 2880,
    },

    [41] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 5,
        gold = 5000,
        item_cnt = 20,
        level = 1,
        up_level_time = 5,
    },

    [42] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 5,
        gold = 10000,
        item_cnt = 30,
        level = 2,
        up_level_time = 15,
    },

    [43] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 5,
        gold = 20000,
        item_cnt = 40,
        level = 3,
        up_level_time = 60,
    },

    [44] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 5,
        gold = 50000,
        item_cnt = 60,
        level = 4,
        up_level_time = 120,
    },

    [45] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 5,
        gold = 100000,
        item_cnt = 90,
        level = 5,
        up_level_time = 180,
    },

    [46] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 5,
        gold = 200000,
        item_cnt = 130,
        level = 6,
        up_level_time = 360,
    },

    [47] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 5,
        gold = 400000,
        item_cnt = 180,
        level = 7,
        up_level_time = 540,
    },

    [48] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 5,
        gold = 800000,
        item_cnt = 250,
        level = 8,
        up_level_time = 720,
    },

    [49] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 5,
        gold = 1400000,
        item_cnt = 330,
        level = 9,
        up_level_time = 1440,
    },

    [50] = {
        desc = "增加温馨度",
        effect = "",
        effect_desc = "升级描述",
        furniture_type = 5,
        gold = 2000000,
        item_cnt = 400,
        level = 10,
        up_level_time = 2880,
    },

}
