-- ./excel/house/housepartner.xlsx
return {

    [1] = {
        key = "D_PSD.93",
        motionName = "show_4",
        name = "右手",
        part = 4,
        partner_type = 1001,
        sort_id = 16,
        sound = {"sound_house_ch_005", "sound_house_ch_006"},
        speak_id = {5, 6},
    },

    [2] = {
        key = "D_PSD.92",
        motionName = "show_4",
        name = "右手",
        part = 4,
        partner_type = 1001,
        sort_id = 15,
        sound = {"sound_house_ch_005", "sound_house_ch_006"},
        speak_id = {5, 6},
    },

    [3] = {
        key = "D_PSD.91",
        motionName = "show_4",
        name = "右手",
        part = 4,
        partner_type = 1001,
        sort_id = 14,
        sound = {"sound_house_ch_005", "sound_house_ch_006"},
        speak_id = {5, 6},
    },

    [4] = {
        key = "D_PSD.90",
        motionName = "show_4",
        name = "左手",
        part = 4,
        partner_type = 1001,
        sort_id = 13,
        sound = {"sound_house_ch_005", "sound_house_ch_006"},
        speak_id = {5, 6},
    },

    [5] = {
        key = "D_PSD.31",
        motionName = "show_4",
        name = "右手",
        part = 4,
        partner_type = 1001,
        sort_id = 12,
        sound = {"sound_house_ch_005", "sound_house_ch_006"},
        speak_id = {5, 6},
    },

    [6] = {
        key = "D_PSD.30",
        motionName = "show_4",
        name = "右手",
        part = 4,
        partner_type = 1001,
        sort_id = 11,
        sound = {"sound_house_ch_005", "sound_house_ch_006"},
        speak_id = {5, 6},
    },

    [7] = {
        key = "D_PSD.29",
        motionName = "show_4",
        name = "右手",
        part = 4,
        partner_type = 1001,
        sort_id = 10,
        sound = {"sound_house_ch_005", "sound_house_ch_006"},
        speak_id = {5, 6},
    },

    [8] = {
        key = "D_PSD.27",
        motionName = "show_4",
        name = "左手",
        part = 4,
        partner_type = 1001,
        sort_id = 9,
        sound = {"sound_house_ch_005", "sound_house_ch_006"},
        speak_id = {5, 6},
    },

    [9] = {
        key = "D_PSD.28",
        motionName = "show_4",
        name = "左手",
        part = 4,
        partner_type = 1001,
        sort_id = 8,
        sound = {"sound_house_ch_005", "sound_house_ch_006"},
        speak_id = {5, 6},
    },

    [10] = {
        key = "D_PSD.07",
        motionName = "show_5",
        name = "左腿",
        part = 5,
        partner_type = 1001,
        sort_id = 7,
        sound = {"sound_house_ch_009", "sound_house_ch_010"},
        speak_id = {9, 10},
    },

    [11] = {
        key = "D_PSD.08",
        motionName = "show_5",
        name = "右腿",
        part = 5,
        partner_type = 1001,
        sort_id = 6,
        sound = {"sound_house_ch_009", "sound_house_ch_010"},
        speak_id = {9, 10},
    },

    [12] = {
        key = "D_PSD.19",
        motionName = "show_2",
        name = "胸",
        part = 2,
        partner_type = 1001,
        sort_id = 5,
        sound = {"sound_house_ch_003", "sound_house_ch_004"},
        speak_id = {3, 4},
    },

    [13] = {
        key = "D_PSD.10",
        motionName = "show_3",
        name = "胖次",
        part = 3,
        partner_type = 1001,
        sort_id = 1,
        sound = {"sound_house_ch_007", "sound_house_ch_008"},
        speak_id = {7, 8},
    },

    [14] = {
        key = "D_PSD.34",
        motionName = "show_1",
        name = "脸",
        part = 1,
        partner_type = 1001,
        sort_id = 4,
        sound = {"sound_house_ch_001", "sound_house_ch_002"},
        speak_id = {1, 2},
    },

    [15] = {
        key = "D_PSD.65",
        motionName = "show_1",
        name = "左包子",
        part = 1,
        partner_type = 1001,
        sort_id = 2,
        sound = {"sound_house_ch_001", "sound_house_ch_002"},
        speak_id = {1, 2},
    },

    [16] = {
        key = "D_PSD.66",
        motionName = "show_1",
        name = "右包子",
        part = 1,
        partner_type = 1001,
        sort_id = 3,
        sound = {"sound_house_ch_001", "sound_house_ch_002"},
        speak_id = {1, 2},
    },

    [17] = {
        key = "lian",
        motionName = "touch_head",
        name = "脸",
        part = 1,
        partner_type = 1002,
        sort_id = 3,
        sound = {"sound_house_yl_001", "sound_house_yl_002"},
        speak_id = {11, 12},
    },

    [18] = {
        key = "youtui",
        motionName = "touch_leg",
        name = "右腿",
        part = 5,
        partner_type = 1002,
        sort_id = 4,
        sound = {"sound_house_yl_009", "sound_house_yl_010"},
        speak_id = {19, 20},
    },

    [19] = {
        key = "zuotui",
        motionName = "touch_leg",
        name = "左腿",
        part = 5,
        partner_type = 1002,
        sort_id = 5,
        sound = {"sound_house_yl_009", "sound_house_yl_010"},
        speak_id = {19, 20},
    },

    [20] = {
        key = "armr1",
        motionName = "touch_arm",
        name = "右手",
        part = 2,
        partner_type = 1002,
        sort_id = 7,
        sound = {"sound_house_yl_005", "sound_house_yl_006"},
        speak_id = {15, 16},
    },

    [21] = {
        key = "armr2",
        motionName = "touch_arm",
        name = "右手",
        part = 2,
        partner_type = 1002,
        sort_id = 8,
        sound = {"sound_house_yl_005", "sound_house_yl_006"},
        speak_id = {15, 16},
    },

    [22] = {
        key = "handr",
        motionName = "touch_arm",
        name = "右手",
        part = 2,
        partner_type = 1002,
        sort_id = 9,
        sound = {"sound_house_yl_005", "sound_house_yl_006"},
        speak_id = {15, 16},
    },

    [23] = {
        key = "arml1",
        motionName = "touch_arm",
        name = "左手",
        part = 2,
        partner_type = 1002,
        sort_id = 10,
        sound = {"sound_house_yl_005", "sound_house_yl_006"},
        speak_id = {15, 16},
    },

    [24] = {
        key = "arml2",
        motionName = "touch_arm",
        name = "左手",
        part = 2,
        partner_type = 1002,
        sort_id = 11,
        sound = {"sound_house_yl_005", "sound_house_yl_006"},
        speak_id = {15, 16},
    },

    [25] = {
        key = "handl",
        motionName = "touch_arm",
        name = "左手",
        part = 2,
        partner_type = 1002,
        sort_id = 6,
        sound = {"sound_house_yl_005", "sound_house_yl_006"},
        speak_id = {15, 16},
    },

    [26] = {
        key = "xiong",
        motionName = "touch_breast",
        name = "胸",
        part = 3,
        partner_type = 1002,
        sort_id = 2,
        sound = {"sound_house_yl_003", "sound_house_yl_004"},
        speak_id = {13, 14},
    },

    [27] = {
        key = "qunzi",
        motionName = "touch_b",
        name = "胖次",
        part = 4,
        partner_type = 1002,
        sort_id = 1,
        sound = {"sound_house_yl_007", "sound_house_yl_008"},
        speak_id = {17, 18},
    },

    [28] = {
        key = "lian",
        motionName = "touch_head",
        name = "脸",
        part = 1,
        partner_type = 1003,
        sort_id = 3,
        sound = {"sound_house_mxm_001_1", "sound_house_mxm_001_2", "sound_house_mxm_001_3", "sound_house_mxm_002_2", "sound_house_mxm_002_3", "sound_house_mxm_002_1"},
        speak_id = {21, 22, 23, 24, 25, 26},
    },

    [29] = {
        key = "youtui",
        motionName = "touch_leg",
        name = "右腿",
        part = 5,
        partner_type = 1003,
        sort_id = 4,
        sound = {"sound_house_mxm_009_2", "sound_house_mxm_009_1", "sound_house_mxm_010_2", "sound_house_mxm_010_1"},
        speak_id = {39, 40, 41, 42},
    },

    [30] = {
        key = "zuotui",
        motionName = "touch_leg",
        name = "左腿",
        part = 5,
        partner_type = 1003,
        sort_id = 5,
        sound = {"sound_house_mxm_009_2", "sound_house_mxm_009_1", "sound_house_mxm_010_2", "sound_house_mxm_010_1"},
        speak_id = {39, 40, 41, 42},
    },

    [31] = {
        key = "armr1",
        motionName = "touch_arm",
        name = "右手",
        part = 2,
        partner_type = 1003,
        sort_id = 7,
        sound = {"sound_house_mxm_005_2", "sound_house_mxm_005_1", "sound_house_mxm_006_2", "sound_house_mxm_006_1"},
        speak_id = {31, 32, 33, 34},
    },

    [32] = {
        key = "armr2",
        motionName = "touch_arm",
        name = "右手",
        part = 2,
        partner_type = 1003,
        sort_id = 8,
        sound = {"sound_house_mxm_005_2", "sound_house_mxm_005_1", "sound_house_mxm_006_2", "sound_house_mxm_006_1"},
        speak_id = {31, 32, 33, 34},
    },

    [33] = {
        key = "handr",
        motionName = "touch_arm",
        name = "右手",
        part = 2,
        partner_type = 1003,
        sort_id = 9,
        sound = {"sound_house_mxm_005_2", "sound_house_mxm_005_1", "sound_house_mxm_006_2", "sound_house_mxm_006_1"},
        speak_id = {31, 32, 33, 34},
    },

    [34] = {
        key = "arml1",
        motionName = "touch_arm",
        name = "左手",
        part = 2,
        partner_type = 1003,
        sort_id = 10,
        sound = {"sound_house_mxm_005_2", "sound_house_mxm_005_1", "sound_house_mxm_006_2", "sound_house_mxm_006_1"},
        speak_id = {31, 32, 33, 34},
    },

    [35] = {
        key = "arml2",
        motionName = "touch_arm",
        name = "左手",
        part = 2,
        partner_type = 1003,
        sort_id = 11,
        sound = {"sound_house_mxm_005_2", "sound_house_mxm_005_1", "sound_house_mxm_006_2", "sound_house_mxm_006_1"},
        speak_id = {31, 32, 33, 34},
    },

    [36] = {
        key = "handl",
        motionName = "touch_arm",
        name = "左手",
        part = 2,
        partner_type = 1003,
        sort_id = 6,
        sound = {"sound_house_mxm_005_2", "sound_house_mxm_005_1", "sound_house_mxm_006_2", "sound_house_mxm_006_1"},
        speak_id = {31, 32, 33, 34},
    },

    [37] = {
        key = "xiong",
        motionName = "touch_breast",
        name = "胸",
        part = 3,
        partner_type = 1003,
        sort_id = 2,
        sound = {"sound_house_mxm_003_2", "sound_house_mxm_003_1", "sound_house_mxm_004_2", "sound_house_mxm_004_1"},
        speak_id = {27, 28, 29, 30},
    },

    [38] = {
        key = "qunzi",
        motionName = "touch_b",
        name = "胖次",
        part = 4,
        partner_type = 1003,
        sort_id = 1,
        sound = {"sound_house_mxm_007_2", "sound_house_mxm_007_1", "sound_house_mxm_008_2", "sound_house_mxm_008_1"},
        speak_id = {35, 36, 37, 38},
    },

    [39] = {
        key = "lian",
        motionName = "touch_head",
        name = "脸",
        part = 1,
        partner_type = 1004,
        sort_id = 3,
        sound = {},
        speak_id = {},
    },

    [40] = {
        key = "youtui",
        motionName = "touch_leg",
        name = "右腿",
        part = 5,
        partner_type = 1004,
        sort_id = 4,
        sound = {},
        speak_id = {},
    },

    [41] = {
        key = "zuotui",
        motionName = "touch_leg",
        name = "左腿",
        part = 5,
        partner_type = 1004,
        sort_id = 5,
        sound = {},
        speak_id = {},
    },

    [42] = {
        key = "armr1",
        motionName = "touch_arm",
        name = "右手",
        part = 2,
        partner_type = 1004,
        sort_id = 7,
        sound = {},
        speak_id = {},
    },

    [43] = {
        key = "armr2",
        motionName = "touch_arm",
        name = "右手",
        part = 2,
        partner_type = 1004,
        sort_id = 8,
        sound = {},
        speak_id = {},
    },

    [44] = {
        key = "handr",
        motionName = "touch_arm",
        name = "右手",
        part = 2,
        partner_type = 1004,
        sort_id = 9,
        sound = {},
        speak_id = {},
    },

    [45] = {
        key = "arml1",
        motionName = "touch_arm",
        name = "左手",
        part = 2,
        partner_type = 1004,
        sort_id = 10,
        sound = {},
        speak_id = {},
    },

    [46] = {
        key = "arml2",
        motionName = "touch_arm",
        name = "左手",
        part = 2,
        partner_type = 1004,
        sort_id = 11,
        sound = {},
        speak_id = {},
    },

    [47] = {
        key = "handl",
        motionName = "touch_arm",
        name = "左手",
        part = 2,
        partner_type = 1004,
        sort_id = 6,
        sound = {},
        speak_id = {},
    },

    [48] = {
        key = "xiong",
        motionName = "touch_breast",
        name = "胸",
        part = 3,
        partner_type = 1004,
        sort_id = 2,
        sound = {},
        speak_id = {},
    },

    [49] = {
        key = "qunzi",
        motionName = "touch_b",
        name = "胖次",
        part = 4,
        partner_type = 1004,
        sort_id = 1,
        sound = {},
        speak_id = {},
    },

}
