.TH "gdsl_macros.h" 3 "Wed Jun 12 2013" "Version 1.7" "gdsl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gdsl_macros.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBGDSL_MAX\fP(X, Y)   (X>Y?X:Y)"
.br
.RI "\fIGive the greatest number of two numbers\&. \fP"
.ti -1c
.RI "#define \fBGDSL_MIN\fP(X, Y)   (X>Y?Y:X)"
.br
.RI "\fIGive the lowest number of two numbers\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for gdsl from the source code\&.
