-- ./excel/task/practice/taskdialog.xlsx
return {

    [1] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1000,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [2] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1000,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [3] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1000,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [4] = {
        content = "你对音律还是毫无长进！",
        dialog_id = 1000,
        finish_event = "",
        last_action = {{["content"] = "再给次机会！", ["event"] = "F15000"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [5] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1001,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [6] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1001,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [7] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1001,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [8] = {
        content = "听说你要挑战我？",
        dialog_id = 1001,
        finish_event = "",
        last_action = {{["content"] = "请多多指教！", ["event"] = "F15001"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [9] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1002,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [10] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1002,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [11] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1002,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [12] = {
        content = "输的人要请客哟，人家要大吃一顿！",
        dialog_id = 1002,
        finish_event = "",
        last_action = {{["content"] = "我一定会赢！", ["event"] = "F15002"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [13] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1003,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [14] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1003,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [15] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1003,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [16] = {
        content = "正好研发出新型药剂，那就拿你试试效果好了！",
        dialog_id = 1003,
        finish_event = "",
        last_action = {{["content"] = "必须反抗！", ["event"] = "F15003"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [17] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1004,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [18] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1004,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [19] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1004,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [20] = {
        content = "请……请多多指教！",
        dialog_id = 1004,
        finish_event = "",
        last_action = {{["content"] = "请指教！", ["event"] = "F15004"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [21] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1005,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [22] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1005,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [23] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1005,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [24] = {
        content = "废话少说，举起你的武器！",
        dialog_id = 1005,
        finish_event = "",
        last_action = {{["content"] = "放马过来！", ["event"] = "F15005"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [25] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1006,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [26] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1006,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [27] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1006,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [28] = {
        content = "我出5成力，输了的话你知道后果！",
        dialog_id = 1006,
        finish_event = "",
        last_action = {{["content"] = "手下留情！", ["event"] = "F15006"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [29] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1007,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [30] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1007,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [31] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1007,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [32] = {
        content = "来来来，输了就告诉我你的初恋是谁~",
        dialog_id = 1007,
        finish_event = "",
        last_action = {{["content"] = "我一定会赢！", ["event"] = "F15007"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [33] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1008,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [34] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1008,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [35] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1008,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [36] = {
        content = "咕噜噜咕噜~！",
        dialog_id = 1008,
        finish_event = "",
        last_action = {{["content"] = "呃开始吧！", ["event"] = "F15008"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [37] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1009,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [38] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1009,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [39] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1009,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [40] = {
        content = "哼，弱者就应该靠边站！",
        dialog_id = 1009,
        finish_event = "",
        last_action = {{["content"] = "放马过来！", ["event"] = "F15009"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [41] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1010,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [42] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1010,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [43] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1010,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [44] = {
        content = "我们来赌赌赢的人是谁？",
        dialog_id = 1010,
        finish_event = "",
        last_action = {{["content"] = "我一定会赢！", ["event"] = "F15010"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [45] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1011,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [46] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1011,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [47] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1011,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [48] = {
        content = "嘻嘻，留下来陪我玩吧！",
        dialog_id = 1011,
        finish_event = "",
        last_action = {{["content"] = "容我拒绝！", ["event"] = "F15011"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [49] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1012,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [50] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1012,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [51] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1012,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [52] = {
        content = "你若输了，我将会把你带到归处去。",
        dialog_id = 1012,
        finish_event = "",
        last_action = {{["content"] = "我一定会赢！", ["event"] = "F15012"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [53] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1013,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [54] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1013,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [55] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1013,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [56] = {
        content = "你真的不认识我？",
        dialog_id = 1013,
        finish_event = "",
        last_action = {{["content"] = "现在认识算吗", ["event"] = "F15013"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [57] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1014,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [58] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1014,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [59] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1014,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [60] = {
        content = "好困好困，打完我要睡觉啦。",
        dialog_id = 1014,
        finish_event = "",
        last_action = {{["content"] = "请多指教！", ["event"] = "F15014"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [61] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1015,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [62] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1015,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [63] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1015,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [64] = {
        content = "蛇宝宝们说你打不赢的，嘶嘶。",
        dialog_id = 1015,
        finish_event = "",
        last_action = {{["content"] = "我一定会赢！", ["event"] = "F15015"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [65] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1016,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [66] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1016,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [67] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1016,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [68] = {
        content = "哎呀呀~无聊就陪你玩玩。",
        dialog_id = 1016,
        finish_event = "",
        last_action = {{["content"] = "请多指教！", ["event"] = "F15016"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [69] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1017,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [70] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1017,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [71] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1017,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [72] = {
        content = "吾辈绝对不会手软！",
        dialog_id = 1017,
        finish_event = "",
        last_action = {{["content"] = "请多指教！", ["event"] = "F15017"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [73] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1018,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [74] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1018,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [75] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1018,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [76] = {
        content = "输了要请我吃大餐，说定啦！",
        dialog_id = 1018,
        finish_event = "",
        last_action = {{["content"] = "我一定会赢！", ["event"] = "F15018"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [77] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1019,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [78] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1019,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [79] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1019,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [80] = {
        content = "你怕火吗？",
        dialog_id = 1019,
        finish_event = "",
        last_action = {{["content"] = "放马过来！", ["event"] = "F15019"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [81] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1020,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [82] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1020,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [83] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1020,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [84] = {
        content = "闭嘴！少废话！",
        dialog_id = 1020,
        finish_event = "",
        last_action = {{["content"] = "请多指教！", ["event"] = "F15020"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [85] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1021,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [86] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1021,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [87] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1021,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [88] = {
        content = "听说你要挑战我？",
        dialog_id = 1021,
        finish_event = "",
        last_action = {{["content"] = "我一定会赢！", ["event"] = "F15021"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [89] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1022,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [90] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1022,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [91] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1022,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [92] = {
        content = "输了就给我擦地板3个月！",
        dialog_id = 1022,
        finish_event = "",
        last_action = {{["content"] = "我一定会赢！", ["event"] = "F15022"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [93] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1023,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [94] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1023,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [95] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1023,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [96] = {
        content = "看你弱不禁风的样子，说好了就过几招！",
        dialog_id = 1023,
        finish_event = "",
        last_action = {{["content"] = "我一定会赢！", ["event"] = "F15023"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [97] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1024,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [98] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1024,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [99] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1024,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [100] = {
        content = "速战速决！",
        dialog_id = 1024,
        finish_event = "",
        last_action = {{["content"] = "我一定会赢！", ["event"] = "F15024"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [101] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1025,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [102] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1025,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [103] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1025,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [104] = {
        content = "你猜你能赢吗？",
        dialog_id = 1025,
        finish_event = "",
        last_action = {{["content"] = "我一定会赢！", ["event"] = "F15025"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [105] = {
        content = "学武永无止境，只有不断修行才能超越自我！作为武者，向我证明你并非浪得虚名！",
        dialog_id = 1026,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [106] = {
        content = "请荆鸣前辈指教！",
        dialog_id = 1026,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [107] = {
        content = "我已经为你找好指导员，去吧，别让我失望！",
        dialog_id = 1026,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [108] = {
        content = "你修行这么久总该有所长进了吧？",
        dialog_id = 1026,
        finish_event = "",
        last_action = {{["content"] = "我一定会赢！", ["event"] = "F15026"}, {["content"] = "便捷组队", ["event"] = "CREATETEAM"}, {["content"] = "我再想想", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

}
