-- ./excel/huodong/npcfight/dialog.xlsx
return {

    [502300] = {
        content = "为什么要这样对我，绝对不放过你们！啊啊啊啊！\n #R(已挑战:%s次)#n",
        dialog_id = 502300,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F502300"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [502301] = {
        content = "为什么要这样对我，绝对不放过你们！啊啊啊啊！\n #R(已挑战:%s次)#n",
        dialog_id = 502301,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [502302] = {
        content = "好痛好痛！啊啊啊！谁能救救我！",
        dialog_id = 502302,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503100] = {
        content = "你们是谁为什么要伤害我们！\n #R(已挑战:%s次)#n",
        dialog_id = 503100,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F503100"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503101] = {
        content = "你们是谁为什么要伤害我们！\n #R(已挑战:%s次)#n",
        dialog_id = 503101,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503102] = {
        content = "我是谁我在哪里……（黑人问号.JPG）",
        dialog_id = 503102,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503200] = {
        content = "我们的怨恨，要你百倍地奉还！\n #R(已挑战:%s次)#n",
        dialog_id = 503200,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F503200"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503201] = {
        content = "我们的怨恨，要你百倍地奉还！\n #R(已挑战:%s次)#n",
        dialog_id = 503201,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503202] = {
        content = "我是谁我在哪里……（黑人问号.JPG）",
        dialog_id = 503202,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503700] = {
        content = "做人如果没有梦想，那跟一条咸鱼有什么不同！\n #R(已挑战:%s次)#n",
        dialog_id = 503700,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F503700"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503701] = {
        content = "做人如果没有梦想，那跟一条咸鱼有什么不同！\n #R(已挑战:%s次)#n",
        dialog_id = 503701,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503702] = {
        content = "新鲜的鱼最好吃了！",
        dialog_id = 503702,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503800] = {
        content = "你们的梦想由我来守护！\n #R(已挑战:%s次)#n",
        dialog_id = 503800,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F503800"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503801] = {
        content = "你们的梦想由我来守护！\n #R(已挑战:%s次)#n",
        dialog_id = 503801,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503802] = {
        content = "最讨厌欺负弱小的人，敢不敢跟我比试比试！",
        dialog_id = 503802,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503600] = {
        content = "做菜不仅要讲究时令火候技法，还要走心，我从来\n不敷衍大家。\n #R(已挑战:%s次)#n",
        dialog_id = 503600,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F503600"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503601] = {
        content = "做菜不仅要讲究时令火候技法，还要走心，我从来\n不敷衍大家。\n #R(已挑战:%s次)#n",
        dialog_id = 503601,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503602] = {
        content = "我又研究出了新菜式你要不要试一试？",
        dialog_id = 503602,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [501700] = {
        content = "主会保佑所有站在他身边的人。\n #R(已挑战:%s次)#n",
        dialog_id = 501700,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F501700"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [501701] = {
        content = "主会保佑所有站在他身边的人。\n #R(已挑战:%s次)#n",
        dialog_id = 501701,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [501702] = {
        content = "虔诚祷告,神一定会听到你的愿望,福佑你我的朋友。",
        dialog_id = 501702,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [500300] = {
        content = "武道之魂不是让你们践踏的！\n #R(已挑战:%s次)#n",
        dialog_id = 500300,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F500300"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [500301] = {
        content = "武道之魂不是让你们践踏的！\n #R(已挑战:%s次)#n",
        dialog_id = 500301,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [500302] = {
        content = "小小年纪别轻举妄动，懂吗？",
        dialog_id = 500302,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [500400] = {
        content = "倾听吧，罪恶的声音，这一切都是神的旨意。\n #R(已挑战:%s次)#n",
        dialog_id = 500400,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F500400"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [500401] = {
        content = "倾听吧，罪恶的声音，这一切都是神的旨意。\n #R(已挑战:%s次)#n",
        dialog_id = 500401,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [500402] = {
        content = "感谢你的到来，愿主保佑你。",
        dialog_id = 500402,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [500500] = {
        content = "你的罪孽没有消减是你不够诚心。\n #R(已挑战:%s次)#n",
        dialog_id = 500500,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F500500"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [500501] = {
        content = "你的罪孽没有消减是你不够诚心。\n #R(已挑战:%s次)#n",
        dialog_id = 500501,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [500502] = {
        content = "你也来祷告吗？",
        dialog_id = 500502,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [501000] = {
        content = "你也不问问这里是谁的地盘！\n #R(已挑战:%s次)#n",
        dialog_id = 501000,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F501000"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [501001] = {
        content = "你也不问问这里是谁的地盘！\n #R(已挑战:%s次)#n",
        dialog_id = 501001,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [501002] = {
        content = "谁又在商业街乱丢垃圾！",
        dialog_id = 501002,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [501100] = {
        content = "让开，这个地儿我占了！\n #R(已挑战:%s次)#n",
        dialog_id = 501100,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F501100"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [501101] = {
        content = "让开，这个地儿我占了！\n #R(已挑战:%s次)#n",
        dialog_id = 501101,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [501102] = {
        content = "有本事比一比咱两谁才是千杯不醉！",
        dialog_id = 501102,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [501200] = {
        content = "你们太弱了，还要锻炼锻炼再锻炼，加强锻炼！\n #R(已挑战:%s次)#n",
        dialog_id = 501200,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F501200"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [501201] = {
        content = "你们太弱了，还要锻炼锻炼再锻炼，加强锻炼！\n #R(已挑战:%s次)#n",
        dialog_id = 501201,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [501202] = {
        content = "没有人靠运气就能永远第一，别心存侥幸！",
        dialog_id = 501202,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [501400] = {
        content = "吼！吼！吼！\n #R(已挑战:%s次)#n",
        dialog_id = 501400,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F501400"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [501401] = {
        content = "吼！吼！吼！\n #R(已挑战:%s次)#n",
        dialog_id = 501401,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [501402] = {
        content = "吼！吼！吼！",
        dialog_id = 501402,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [501500] = {
        content = "嘘！我研究药理的时候不许吵闹！\n #R(已挑战:%s次)#n",
        dialog_id = 501500,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F501500"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [501501] = {
        content = "嘘！我研究药理的时候不许吵闹！\n #R(已挑战:%s次)#n",
        dialog_id = 501501,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [501502] = {
        content = "有人的地方就需要医生，我是不会离开的。",
        dialog_id = 501502,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [501600] = {
        content = "既然敢挑战我，那就做好被打败的心理准备吧！\n #R(已挑战:%s次)#n",
        dialog_id = 501600,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F501600"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [501601] = {
        content = "既然敢挑战我，那就做好被打败的心理准备吧！\n #R(已挑战:%s次)#n",
        dialog_id = 501601,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [501602] = {
        content = "尊重武道，刻苦修炼，是我们习武者永远的誓言！",
        dialog_id = 501602,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [501800] = {
        content = "嘻嘻，你尽管试试好了啵哟！\n #R(已挑战:%s次)#n",
        dialog_id = 501800,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F501800"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [501801] = {
        content = "嘻嘻，你尽管试试好了啵哟！\n #R(已挑战:%s次)#n",
        dialog_id = 501801,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [501802] = {
        content = "啵哟！啵哟！啵哟！",
        dialog_id = 501802,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [502000] = {
        content = "做好准备了吗，尽管放马过来！\n #R(已挑战:%s次)#n",
        dialog_id = 502000,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F502000"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [502001] = {
        content = "做好准备了吗，尽管放马过来！\n #R(已挑战:%s次)#n",
        dialog_id = 502001,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [502002] = {
        content = "任务还没有完成，我绝对不会放弃！",
        dialog_id = 502002,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [502100] = {
        content = "你想获得力量，变得更强吗？来吧，我有让你进化\n 的方法！\n #R(已挑战:%s次)#n",
        dialog_id = 502100,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F502100"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [502101] = {
        content = "你想获得力量，变得更强吗？来吧，我有让你进化\n 的方法！\n #R(已挑战:%s次)#n",
        dialog_id = 502101,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [502102] = {
        content = "不会吧，又失败了？我再改改！",
        dialog_id = 502102,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [502600] = {
        content = "啧啧，你的肌肉一点都不美丽。\n #R(已挑战:%s次)#n",
        dialog_id = 502600,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F502600"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [502601] = {
        content = "啧啧，你的肌肉一点都不美丽。\n #R(已挑战:%s次)#n",
        dialog_id = 502601,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [502602] = {
        content = "守护梦想与忠诚，我们是世界的偶像~",
        dialog_id = 502602,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [502700] = {
        content = "你要温柔一点，人家怕疼呢！\n #R(已挑战:%s次)#n",
        dialog_id = 502700,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F502700"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [502701] = {
        content = "你要温柔一点，人家怕疼呢！\n #R(已挑战:%s次)#n",
        dialog_id = 502701,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [502702] = {
        content = "宣扬正义和爱，我们是大家的比翼鸟！",
        dialog_id = 502702,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503300] = {
        content = "让猫叔看看你的修行成果！\n #R(已挑战:%s次)#n",
        dialog_id = 503300,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F503300"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503301] = {
        content = "让猫叔看看你的修行成果！\n #R(已挑战:%s次)#n",
        dialog_id = 503301,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503302] = {
        content = "修炼的时候一定要给我穿上猫咪装！",
        dialog_id = 503302,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503400] = {
        content = "看你不好好吃饭，连我都打不过。\n #R(已挑战:%s次)#n",
        dialog_id = 503400,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F503400"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503401] = {
        content = "看你不好好吃饭，连我都打不过。\n #R(已挑战:%s次)#n",
        dialog_id = 503401,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503402] = {
        content = "喵小萌特制大肉包子，真真真是超级好吃的喵！",
        dialog_id = 503402,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503500] = {
        content = "让婆婆看看你的修行成果。\n #R(已挑战:%s次)#n",
        dialog_id = 503500,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F503500"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503501] = {
        content = "让婆婆看看你的修行成果。\n #R(已挑战:%s次)#n",
        dialog_id = 503501,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503502] = {
        content = "都已经鉴定多少次啦，说了不能练功夫就是不能，婆婆也没有办法呀！",
        dialog_id = 503502,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [502400] = {
        content = "嗝！你这臭小子，赶紧把我的酒壶还回来嗝！\n #R(已挑战:%s次)#n",
        dialog_id = 502400,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F502400"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [502401] = {
        content = "嗝！你这臭小子，赶紧把我的酒壶还回来嗝！\n #R(已挑战:%s次)#n",
        dialog_id = 502401,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [502402] = {
        content = "喝喝小酒钓会儿鱼，小日子过得滋润滋润的。",
        dialog_id = 502402,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503900] = {
        content = "世界上只有一种人永远都不会泄露秘密。\n #R(已挑战:%s次)#n",
        dialog_id = 503900,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F503900"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503901] = {
        content = "世界上只有一种人永远都不会泄露秘密。\n #R(已挑战:%s次)#n",
        dialog_id = 503901,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [503902] = {
        content = "金钱、权利全部……全部都属于我！",
        dialog_id = 503902,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [504800] = {
        content = "说叔不帅的放学别走！\n #R(已挑战:%s次)#n",
        dialog_id = 504800,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F504800"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [504801] = {
        content = "说叔不帅的放学别走！\n #R(已挑战:%s次)#n",
        dialog_id = 504801,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [504802] = {
        content = "啧啧，你们都还太年轻呐，呼~",
        dialog_id = 504802,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [505900] = {
        content = "主会保佑所有站在他身边的人。\n #R(已挑战:%s次)#n",
        dialog_id = 505900,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F505900"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [505901] = {
        content = "主会保佑所有站在他身边的人。\n #R(已挑战:%s次)#n",
        dialog_id = 505901,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [505902] = {
        content = "虔诚祷告,神一定会听到你的愿望,福佑你我的朋友。",
        dialog_id = 505902,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [505600] = {
        content = "倾听吧，罪恶的声音，这一切都是神的旨意。\n #R(已挑战:%s次)#n",
        dialog_id = 505600,
        last_action = {{["content"] = "我要挑战你！", ["event"] = "F505600"}, {["content"] = "再考虑一下！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [505601] = {
        content = "倾听吧，罪恶的声音，这一切都是神的旨意。\n #R(已挑战:%s次)#n",
        dialog_id = 505601,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [505602] = {
        content = "感谢你的到来，愿主保佑你。",
        dialog_id = 505602,
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 2,
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

}
