-- ./excel/task/plot/taskdialog.xlsx
return {

    [1] = {
        content = 666.0,
        dialog_id = 6000,
        dialogue_hide_action = "",
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = 0.0,
        social_action_list = "",
        spine_ani_list = "",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = "",
    },

    [2] = {
        content = 333.0,
        dialog_id = 6000,
        dialogue_hide_action = "",
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = 0.0,
        social_action_list = "",
        spine_ani_list = "",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = "",
    },

    [3] = {
        content = 444.0,
        dialog_id = 6000,
        dialogue_hide_action = "",
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = 0.0,
        social_action_list = "",
        spine_ani_list = "",
        status = 1,
        sub_talker_list = "",
        subid = 3,
        type = 2,
        ui_mode = 2,
        voice = "",
    },

    [4] = {
        content = 555.0,
        dialog_id = 6000,
        dialogue_hide_action = "",
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = 0.0,
        social_action_list = "",
        spine_ani_list = "",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = "",
    },

}
