-- ./excel/arena/arena.xlsx
return {

    [1] = {
        award_per_game = 100,
        basescore = 0,
        bg = "bg_bingdoumudibeijing_jingjichang",
        duanwei_icon = "text_duanwei_bingdoumudi",
        icon = "pic_bingdoumudi_jingjichang",
        id = 1,
        name = "冰斗墓地",
        para = 60,
        rank_name = "1段",
        text_icon = "text_bingdoumudi",
        week_rewardlist = {1001},
        weeky_award = {{["num"] = 120, ["id"] = 1003}},
        weeky_limit = 2400,
    },

    [2] = {
        award_per_game = 120,
        basescore = 1200,
        bg = "bg_shenhaiyijibeijing_jingjichang",
        duanwei_icon = "text_duanwei_shenhaiyiji",
        icon = "pic_shenghaiyiji_jingjichang",
        id = 2,
        name = "深海遗迹",
        para = 60,
        rank_name = "2段",
        text_icon = "text_shenhaiyiji",
        week_rewardlist = {1002},
        weeky_award = {{["num"] = 250, ["id"] = 1003}},
        weeky_limit = 2800,
    },

    [3] = {
        award_per_game = 140,
        basescore = 1400,
        bg = "bg_taohuamengjingbeijing_jingjichang",
        duanwei_icon = "text_duanwei_taohuamengjing",
        icon = "pic_taohuamengjing_jingjichang",
        id = 3,
        name = "桃花梦境",
        para = 60,
        rank_name = "3段",
        text_icon = "text_taohuamengjing",
        week_rewardlist = {1003},
        weeky_award = {{["num"] = 360, ["id"] = 1003}},
        weeky_limit = 3200,
    },

    [4] = {
        award_per_game = 160,
        basescore = 1600,
        bg = "bg_bingdoumudibeijing_jingjichang",
        duanwei_icon = "text_duanwei_zhujianmiwu",
        icon = "pic_bingdoumudi_jingjichang",
        id = 4,
        name = "竹涧迷雾",
        para = 60,
        rank_name = "4段",
        text_icon = "text_zhujianmiwu",
        week_rewardlist = {1004},
        weeky_award = {{["num"] = 500, ["id"] = 1003}},
        weeky_limit = 3600,
    },

    [5] = {
        award_per_game = 180,
        basescore = 1800,
        bg = "bg_kongquezhishen_jingjichang",
        duanwei_icon = "text_duanwei_kongquezhishen",
        icon = "pic_shenghaiyiji_jingjichang",
        id = 5,
        name = "孔雀之森",
        para = 45,
        rank_name = "5段",
        text_icon = "text_kongquezhishen",
        week_rewardlist = {1005},
        weeky_award = {{["num"] = 600, ["id"] = 1003}},
        weeky_limit = 4000,
    },

    [6] = {
        award_per_game = 200,
        basescore = 2000,
        bg = "bg_taohuamengjingbeijing_jingjichang",
        duanwei_icon = "text_duanwei_xiaoyexingchen",
        icon = "pic_taohuamengjing_jingjichang",
        id = 6,
        name = "晓夜星辰",
        para = 45,
        rank_name = "6段",
        text_icon = "text_xiaoyexingchen",
        week_rewardlist = {1006, 1009},
        weeky_award = {{["num"] = 700, ["id"] = 1003}, {["num"] = 100, ["id"] = 1009}},
        weeky_limit = 4400,
    },

    [7] = {
        award_per_game = 220,
        basescore = 2200,
        bg = "bg_bingdoumudibeijing_jingjichang",
        duanwei_icon = "text_duanwei_fengyelanshan",
        icon = "pic_bingdoumudi_jingjichang",
        id = 7,
        name = "枫叶阑珊",
        para = 36,
        rank_name = "7段",
        text_icon = "text_fengyelanshan",
        week_rewardlist = {1007, 1010},
        weeky_award = {{["num"] = 800, ["id"] = 1003}, {["num"] = 200, ["id"] = 1009}},
        weeky_limit = 4800,
    },

    [8] = {
        award_per_game = 240,
        basescore = 2400,
        bg = "bg_shenhaiyijibeijing_jingjichang",
        duanwei_icon = "text_duanwei_liaoyuanshaqiu",
        icon = "pic_shenghaiyiji_jingjichang",
        id = 8,
        name = "燎原沙丘",
        para = 36,
        rank_name = "8段",
        text_icon = "text_liaoyuanshaqiu",
        week_rewardlist = {1008, 1011},
        weeky_award = {{["num"] = 900, ["id"] = 1003}, {["num"] = 400, ["id"] = 1009}},
        weeky_limit = 5200,
    },

}
