-- ./excel/schedule/schedule.xlsx
return {

    [3001] = {
        active = 3,
        addlimit = 1,
        def_create = 0,
        gotoway = 2,
        grade = {["max"] = 120, ["min"] = 120},
        huodong = "buygoldcoin",
        id = 3001,
        maxactive = 6,
        maxfinish = 2,
        name = "购买金币",
        open_view = 1009,
        open_week = {},
        server_day = 0,
        type = 3,
    },

    [3002] = {
        active = 3,
        addlimit = 1,
        def_create = 0,
        gotoway = 2,
        grade = {["max"] = 120, ["min"] = 120},
        huodong = "upcard",
        id = 3002,
        maxactive = 3,
        maxfinish = 1,
        name = "王者招募",
        open_view = 1001,
        open_week = {},
        server_day = 0,
        type = 3,
    },

    [1016] = {
        active = 1,
        addlimit = 1,
        def_create = 0,
        gotoway = 2,
        grade = {["max"] = 100, ["min"] = 2},
        huodong = "chapterfb",
        id = 1016,
        maxactive = 10,
        maxfinish = 10,
        name = "挑战战役关卡",
        open_view = 1035,
        open_week = {},
        server_day = 0,
        type = 1,
    },

    [3009] = {
        active = 1,
        addlimit = 1,
        def_create = 0,
        gotoway = 2,
        grade = {["max"] = 100, ["min"] = 20},
        huodong = "partner_love",
        id = 3009,
        maxactive = 5,
        maxfinish = 5,
        name = "宅邸互动",
        open_view = 1004,
        open_week = {},
        server_day = 0,
        type = 1,
    },

    [3005] = {
        active = 5,
        addlimit = 1,
        def_create = 0,
        gotoway = 2,
        grade = {["max"] = 100, ["min"] = 9},
        huodong = "buy_giftbag",
        id = 3005,
        maxactive = 5,
        maxfinish = 1,
        name = "购买商品",
        open_view = 501,
        open_week = {},
        server_day = 0,
        type = 3,
    },

    [1003] = {
        active = 2,
        addlimit = 1,
        def_create = 1,
        gotoway = 2,
        grade = {["max"] = 100, ["min"] = 30},
        huodong = "equipfuben",
        id = 1003,
        maxactive = 6,
        maxfinish = 3,
        name = "装备副本",
        open_view = 1061,
        open_week = {},
        server_day = 0,
        type = 1,
    },

    [1011] = {
        active = 2,
        addlimit = 1,
        def_create = 1,
        gotoway = 2,
        grade = {["max"] = 100, ["min"] = 14},
        huodong = "orgfuben",
        id = 1011,
        maxactive = 4,
        maxfinish = 2,
        name = "公会赏金",
        open_view = 603,
        open_week = {},
        server_day = 0,
        type = 1,
    },

    [1015] = {
        active = 2,
        addlimit = 1,
        def_create = 0,
        gotoway = 2,
        grade = {["max"] = 100, ["min"] = 53},
        huodong = "equalarena",
        id = 1015,
        maxactive = 10,
        maxfinish = 5,
        name = "公平比武",
        open_view = 1015,
        open_week = {6, 7},
        server_day = 0,
        type = 2,
    },

    [1021] = {
        active = 3,
        addlimit = 1,
        def_create = 0,
        gotoway = 2,
        grade = {["max"] = 100, ["min"] = 28},
        huodong = "teampvp",
        id = 1021,
        maxactive = 15,
        maxfinish = 5,
        name = "协同比武",
        open_view = 1038,
        open_week = {6, 7},
        server_day = 0,
        type = 2,
    },

    [2003] = {
        active = 3,
        addlimit = 1,
        def_create = 0,
        gotoway = 2,
        grade = {["max"] = 100, ["min"] = 28},
        huodong = "arenagame",
        id = 2003,
        maxactive = 15,
        maxfinish = 5,
        name = "段位比武",
        open_view = 1002,
        open_week = {1, 2, 3, 4, 5},
        server_day = 0,
        type = 2,
    },

    [1017] = {
        active = 1,
        addlimit = 1,
        def_create = 1,
        gotoway = 2,
        grade = {["max"] = 100, ["min"] = 15},
        huodong = "shimen",
        id = 1017,
        maxactive = 20,
        maxfinish = 20,
        name = "杂务巡查",
        open_view = 1039,
        open_week = {},
        server_day = 0,
        type = 3,
    },

    [1006] = {
        active = 5,
        addlimit = 1,
        def_create = 1,
        gotoway = 0,
        grade = {["max"] = 100, ["min"] = 35},
        huodong = "minglei",
        id = 1006,
        maxactive = 10,
        maxfinish = 2,
        name = "喵萌茶会",
        open_view = 0,
        open_week = {},
        server_day = 0,
        type = 1,
    },

    [1018] = {
        active = 2,
        addlimit = 1,
        def_create = 1,
        gotoway = 2,
        grade = {["max"] = 100, ["min"] = 43},
        huodong = "convoy",
        id = 1018,
        maxactive = 6,
        maxfinish = 3,
        name = "帝都宅急便",
        open_view = 1037,
        open_week = {},
        server_day = 0,
        type = 1,
    },

    [1007] = {
        active = 1,
        addlimit = 1,
        def_create = 1,
        gotoway = 2,
        grade = {["max"] = 100, ["min"] = 38},
        huodong = "trapmine",
        id = 1007,
        maxactive = 20,
        maxfinish = 20,
        name = "探 索",
        open_view = 1011,
        open_week = {},
        server_day = 0,
        type = 1,
    },

    [2001] = {
        active = 3,
        addlimit = 1,
        def_create = 0,
        gotoway = 2,
        grade = {["max"] = 100, ["min"] = 36},
        huodong = "question",
        id = 2001,
        maxactive = 3,
        maxfinish = 1,
        name = "学渣的逆袭",
        open_view = 1008,
        open_week = {1, 3, 5, 7},
        server_day = 0,
        type = 2,
    },

    [1019] = {
        active = 3,
        addlimit = 1,
        def_create = 0,
        gotoway = 2,
        grade = {["max"] = 100, ["min"] = 36},
        huodong = "question2",
        id = 1019,
        maxactive = 3,
        maxfinish = 1,
        name = "学霸去哪儿",
        open_view = 1021,
        open_week = {2, 4, 6},
        server_day = 0,
        type = 2,
    },

    [2002] = {
        active = 3,
        addlimit = 1,
        def_create = 0,
        gotoway = 2,
        grade = {["max"] = 100, ["min"] = 33},
        huodong = "worldboss",
        id = 2002,
        maxactive = 3,
        maxfinish = 1,
        name = "封印之地",
        open_view = 1006,
        open_week = {1, 2, 4, 5},
        server_day = 0,
        type = 2,
    },

    [1020] = {
        active = 3,
        addlimit = 1,
        def_create = 0,
        gotoway = 2,
        grade = {["max"] = 100, ["min"] = 33},
        huodong = "msattack",
        id = 1020,
        maxactive = 3,
        maxfinish = 1,
        name = "怪物攻城",
        open_view = 1036,
        open_week = {3, 6},
        server_day = 0,
        type = 2,
    },

    [1005] = {
        active = 2,
        addlimit = 1,
        def_create = 1,
        gotoway = 2,
        grade = {["max"] = 100, ["min"] = 42},
        huodong = "pefuben",
        id = 1005,
        maxactive = 6,
        maxfinish = 3,
        name = "御灵副本",
        open_view = 1040,
        open_week = {},
        server_day = 0,
        type = 1,
    },

    [1004] = {
        active = 1,
        addlimit = 1,
        def_create = 1,
        gotoway = 2,
        grade = {["max"] = 100, ["min"] = 45},
        huodong = "pata",
        id = 1004,
        maxactive = 5,
        maxfinish = 5,
        name = "地牢5层",
        open_view = 1003,
        open_week = {},
        server_day = 0,
        type = 1,
    },

    [1001] = {
        active = 1,
        addlimit = 1,
        def_create = 1,
        gotoway = 2,
        grade = {["max"] = 100, ["min"] = 25},
        huodong = "lilian",
        id = 1001,
        maxactive = 30,
        maxfinish = 30,
        name = "每日修行",
        open_view = 1053,
        open_week = {},
        server_day = 1,
        type = 1,
    },

    [1012] = {
        active = 5,
        addlimit = 1,
        def_create = 1,
        gotoway = 2,
        grade = {["max"] = 100, ["min"] = 50},
        huodong = "yjfuben",
        id = 1012,
        maxactive = 5,
        maxfinish = 1,
        name = "梦魇狩猎",
        open_view = 1060,
        open_week = {},
        server_day = 0,
        type = 1,
    },

    [1013] = {
        active = 5,
        addlimit = 1,
        def_create = 1,
        gotoway = 2,
        grade = {["max"] = 120, ["min"] = 120},
        huodong = "fieldboss",
        id = 1013,
        maxactive = 5,
        maxfinish = 1,
        name = "人形讨伐",
        open_view = 1045,
        open_week = {},
        server_day = 0,
        type = 1,
    },

    [3003] = {
        active = 10,
        addlimit = 1,
        def_create = 0,
        gotoway = 2,
        grade = {["max"] = 120, ["min"] = 120},
        huodong = "breed_partner",
        id = 3003,
        maxactive = 10,
        maxfinish = 1,
        name = "培育伙伴",
        open_view = 201,
        open_week = {},
        server_day = 0,
        type = 3,
    },

    [3004] = {
        active = 10,
        addlimit = 1,
        def_create = 0,
        gotoway = 2,
        grade = {["max"] = 120, ["min"] = 120},
        huodong = "promoted_partner",
        id = 3004,
        maxactive = 10,
        maxfinish = 1,
        name = "强化符文",
        open_view = 203,
        open_week = {},
        server_day = 0,
        type = 3,
    },

    [1002] = {
        active = 5,
        addlimit = 1,
        def_create = 1,
        gotoway = 2,
        grade = {["max"] = 100, ["min"] = 46},
        huodong = "endlesspve",
        id = 1002,
        maxactive = 5,
        maxfinish = 1,
        name = "月见幻境",
        open_view = 1007,
        open_week = {},
        server_day = 0,
        type = 1,
    },

    [1009] = {
        active = 0,
        addlimit = 0,
        def_create = 1,
        gotoway = 2,
        grade = {["max"] = 120, ["min"] = 120},
        huodong = "treasure",
        id = 1009,
        maxactive = 0,
        maxfinish = 0,
        name = "星象图",
        open_view = 1010,
        open_week = {},
        server_day = 0,
        type = 1,
    },

    [3008] = {
        active = 2,
        addlimit = 1,
        def_create = 0,
        gotoway = 2,
        grade = {["max"] = 100, ["min"] = 14},
        huodong = "org_build",
        id = 3008,
        maxactive = 2,
        maxfinish = 1,
        name = "公会建设",
        open_view = 601,
        open_week = {},
        server_day = 0,
        type = 1,
    },

    [1014] = {
        active = 0,
        addlimit = 0,
        def_create = 1,
        gotoway = 2,
        grade = {["max"] = 120, ["min"] = 120},
        huodong = "travel",
        id = 1014,
        maxactive = 0,
        maxfinish = 0,
        name = "游历",
        open_view = 1013,
        open_week = {},
        server_day = 0,
        type = 1,
    },

    [2004] = {
        active = 0,
        addlimit = 0,
        def_create = 1,
        gotoway = 2,
        grade = {["max"] = 120, ["min"] = 120},
        huodong = "terrawars",
        id = 2004,
        maxactive = 0,
        maxfinish = 0,
        name = "据点攻防战",
        open_view = 1022,
        open_week = {},
        server_day = 0,
        type = 2,
    },

    [2005] = {
        active = 5,
        addlimit = 1,
        def_create = 0,
        gotoway = 2,
        grade = {["max"] = 100, ["min"] = 20},
        huodong = "orgwar",
        id = 2005,
        maxactive = 5,
        maxfinish = 1,
        name = "公会战",
        open_view = 604,
        open_week = {7},
        server_day = 0,
        type = 2,
    },

    [1022] = {
        active = 1,
        addlimit = 1,
        def_create = 1,
        gotoway = 2,
        grade = {["max"] = 100, ["min"] = 40},
        huodong = "hunt",
        id = 1022,
        maxactive = 5,
        maxfinish = 5,
        name = "猎灵",
        open_view = 1055,
        open_week = {},
        server_day = 0,
        type = 1,
    },

    [1023] = {
        active = 0,
        addlimit = 0,
        def_create = 1,
        gotoway = 2,
        grade = {["max"] = 120, ["min"] = 120},
        huodong = "OrgWish",
        id = 1023,
        maxactive = 0,
        maxfinish = 0,
        name = "公会许愿",
        open_view = 1044,
        open_week = {},
        server_day = 0,
        type = 1,
    },

    [1024] = {
        active = 1,
        addlimit = 1,
        def_create = 1,
        gotoway = 2,
        grade = {["max"] = 100, ["min"] = 28},
        huodong = "clubarena",
        id = 1024,
        maxactive = 5,
        maxfinish = 5,
        name = "武馆挑战",
        open_view = 1056,
        open_week = {},
        server_day = 0,
        type = 1,
    },

}
