.TH "gdsl_sort.h" 3 "Wed Jun 12 2013" "Version 1.7" "gdsl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gdsl_sort.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgdsl_sort\fP (\fBgdsl_element_t\fP *T, \fBulong\fP N, const \fBgdsl_compare_func_t\fP COMP_F)"
.br
.RI "\fISort an array in place\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for gdsl from the source code\&.
