-- ./excel/handbook/condition.xlsx
return {

    [400001] = {
        condition = "战胜仇大富=1",
        degreetype = 2,
        desc = "战胜仇大富一次",
        detail = "本字段策划暂时没用",
        id = 400001,
        name = "战胜仇大富1次",
        sub_type = 3,
        type = 3,
    },

    [400002] = {
        condition = "战胜仇大富=5",
        degreetype = 2,
        desc = "战胜仇大富五次",
        detail = "本字段策划暂时没用",
        id = 400002,
        name = "战胜仇大富5次",
        sub_type = 2,
        type = 3,
    },

    [400003] = {
        condition = "战胜咸鱼飞=1",
        degreetype = 2,
        desc = "战胜咸鱼飞一次",
        detail = "本字段策划暂时没用",
        id = 400003,
        name = "战胜咸鱼飞1次",
        sub_type = 3,
        type = 3,
    },

    [400004] = {
        condition = "战胜咸鱼飞=5",
        degreetype = 2,
        desc = "战胜咸鱼飞五次",
        detail = "本字段策划暂时没用",
        id = 400004,
        name = "战胜咸鱼飞5次",
        sub_type = 2,
        type = 3,
    },

    [400005] = {
        condition = "战胜李铁蛋=1",
        degreetype = 2,
        desc = "战胜李铁蛋一次",
        detail = "本字段策划暂时没用",
        id = 400005,
        name = "战胜李铁蛋1次",
        sub_type = 3,
        type = 3,
    },

    [400006] = {
        condition = "战胜李铁蛋=5",
        degreetype = 2,
        desc = "战胜李铁蛋五次",
        detail = "本字段策划暂时没用",
        id = 400006,
        name = "战胜李铁蛋5次",
        sub_type = 2,
        type = 3,
    },

    [400007] = {
        condition = "战胜乔焱=1",
        degreetype = 2,
        desc = "战胜乔焱一次",
        detail = "本字段策划暂时没用",
        id = 400007,
        name = "战胜乔焱1次",
        sub_type = 3,
        type = 3,
    },

    [400008] = {
        condition = "战胜乔焱=5",
        degreetype = 2,
        desc = "战胜乔焱五次",
        detail = "本字段策划暂时没用",
        id = 400008,
        name = "战胜乔焱5次",
        sub_type = 2,
        type = 3,
    },

    [400009] = {
        condition = "战胜丽丝=1",
        degreetype = 2,
        desc = "战胜丽丝一次",
        detail = "本字段策划暂时没用",
        id = 400009,
        name = "战胜丽丝1次",
        sub_type = 3,
        type = 3,
    },

    [400010] = {
        condition = "战胜丽丝=5",
        degreetype = 2,
        desc = "战胜丽丝五次",
        detail = "本字段策划暂时没用",
        id = 400010,
        name = "战胜丽丝5次",
        sub_type = 2,
        type = 3,
    },

    [400011] = {
        condition = "战胜遥=1",
        degreetype = 2,
        desc = "战胜遥一次",
        detail = "本字段策划暂时没用",
        id = 400011,
        name = "战胜遥1次",
        sub_type = 3,
        type = 3,
    },

    [400012] = {
        condition = "战胜遥=5",
        degreetype = 2,
        desc = "战胜遥五次",
        detail = "本字段策划暂时没用",
        id = 400012,
        name = "战胜遥5次",
        sub_type = 2,
        type = 3,
    },

    [400013] = {
        condition = "战胜飞龙哥=1",
        degreetype = 2,
        desc = "战胜飞龙哥一次",
        detail = "本字段策划暂时没用",
        id = 400013,
        name = "战胜飞龙哥1次",
        sub_type = 3,
        type = 3,
    },

    [400014] = {
        condition = "战胜飞龙哥=5",
        degreetype = 2,
        desc = "战胜飞龙哥五次",
        detail = "本字段策划暂时没用",
        id = 400014,
        name = "战胜飞龙哥5次",
        sub_type = 2,
        type = 3,
    },

    [400015] = {
        condition = "战胜邓酒爷=1",
        degreetype = 2,
        desc = "战胜邓酒爷一次",
        detail = "本字段策划暂时没用",
        id = 400015,
        name = "战胜邓酒爷1次",
        sub_type = 3,
        type = 3,
    },

    [400016] = {
        condition = "战胜邓酒爷=5",
        degreetype = 2,
        desc = "战胜邓酒爷五次",
        detail = "本字段策划暂时没用",
        id = 400016,
        name = "战胜邓酒爷5次",
        sub_type = 2,
        type = 3,
    },

    [400017] = {
        condition = "战胜荆鸣=1",
        degreetype = 2,
        desc = "战胜荆鸣一次",
        detail = "本字段策划暂时没用",
        id = 400017,
        name = "战胜荆鸣1次",
        sub_type = 3,
        type = 3,
    },

    [400018] = {
        condition = "战胜荆鸣=5",
        degreetype = 2,
        desc = "战胜荆鸣五次",
        detail = "本字段策划暂时没用",
        id = 400018,
        name = "战胜荆鸣5次",
        sub_type = 2,
        type = 3,
    },

    [400019] = {
        condition = "战胜熊霸=1",
        degreetype = 2,
        desc = "战胜熊霸一次",
        detail = "本字段策划暂时没用",
        id = 400019,
        name = "战胜熊霸1次",
        sub_type = 3,
        type = 3,
    },

    [400020] = {
        condition = "战胜熊霸=5",
        degreetype = 2,
        desc = "战胜熊霸五次",
        detail = "本字段策划暂时没用",
        id = 400020,
        name = "战胜熊霸5次",
        sub_type = 2,
        type = 3,
    },

    [400021] = {
        condition = "战胜甘=1",
        degreetype = 2,
        desc = "战胜甘一次",
        detail = "本字段策划暂时没用",
        id = 400021,
        name = "战胜甘1次",
        sub_type = 3,
        type = 3,
    },

    [400022] = {
        condition = "战胜甘=5",
        degreetype = 2,
        desc = "战胜甘五次",
        detail = "本字段策划暂时没用",
        id = 400022,
        name = "战胜甘5次",
        sub_type = 2,
        type = 3,
    },

    [400023] = {
        condition = "战胜峰馆长=1",
        degreetype = 2,
        desc = "战胜峰馆长一次",
        detail = "本字段策划暂时没用",
        id = 400023,
        name = "战胜峰馆长1次",
        sub_type = 3,
        type = 3,
    },

    [400024] = {
        condition = "战胜峰馆长=5",
        degreetype = 2,
        desc = "战胜峰馆长五次",
        detail = "本字段策划暂时没用",
        id = 400024,
        name = "战胜峰馆长5次",
        sub_type = 2,
        type = 3,
    },

    [400025] = {
        condition = "战胜桀修=1",
        degreetype = 2,
        desc = "战胜桀修一次",
        detail = "本字段策划暂时没用",
        id = 400025,
        name = "战胜桀修1次",
        sub_type = 3,
        type = 3,
    },

    [400026] = {
        condition = "战胜桀修=5",
        degreetype = 2,
        desc = "战胜桀修五次",
        detail = "本字段策划暂时没用",
        id = 400026,
        name = "战胜桀修5次",
        sub_type = 2,
        type = 3,
    },

    [400027] = {
        condition = "战胜丑无=1",
        degreetype = 2,
        desc = "战胜丑无一次",
        detail = "本字段策划暂时没用",
        id = 400027,
        name = "战胜丑无1次",
        sub_type = 3,
        type = 3,
    },

    [400028] = {
        condition = "战胜丑无=5",
        degreetype = 2,
        desc = "战胜丑无五次",
        detail = "本字段策划暂时没用",
        id = 400028,
        name = "战胜丑无5次",
        sub_type = 2,
        type = 3,
    },

    [400029] = {
        condition = "战胜鬼幽子=1",
        degreetype = 2,
        desc = "战胜鬼幽子一次",
        detail = "本字段策划暂时没用",
        id = 400029,
        name = "战胜鬼幽子1次",
        sub_type = 3,
        type = 3,
    },

    [400030] = {
        condition = "战胜鬼幽子=5",
        degreetype = 2,
        desc = "战胜鬼幽子五次",
        detail = "本字段策划暂时没用",
        id = 400030,
        name = "战胜鬼幽子5次",
        sub_type = 2,
        type = 3,
    },

    [400031] = {
        condition = "战胜熊猫爷爷=1",
        degreetype = 2,
        desc = "战胜熊猫爷爷一次",
        detail = "本字段策划暂时没用",
        id = 400031,
        name = "战胜熊猫爷爷1次",
        sub_type = 3,
        type = 3,
    },

    [400032] = {
        condition = "战胜熊猫爷爷=5",
        degreetype = 2,
        desc = "战胜熊猫爷爷五次",
        detail = "本字段策划暂时没用",
        id = 400032,
        name = "战胜熊猫爷爷5次",
        sub_type = 2,
        type = 3,
    },

    [400033] = {
        condition = "战胜绯翼=1",
        degreetype = 2,
        desc = "战胜绯翼一次",
        detail = "本字段策划暂时没用",
        id = 400033,
        name = "战胜绯翼1次",
        sub_type = 3,
        type = 3,
    },

    [400034] = {
        condition = "战胜绯翼=5",
        degreetype = 2,
        desc = "战胜绯翼五次",
        detail = "本字段策划暂时没用",
        id = 400034,
        name = "战胜绯翼5次",
        sub_type = 2,
        type = 3,
    },

    [400035] = {
        condition = "战胜青翼=1",
        degreetype = 2,
        desc = "战胜青翼一次",
        detail = "本字段策划暂时没用",
        id = 400035,
        name = "战胜青翼1次",
        sub_type = 3,
        type = 3,
    },

    [400036] = {
        condition = "战胜青翼=5",
        degreetype = 2,
        desc = "战胜青翼五次",
        detail = "本字段策划暂时没用",
        id = 400036,
        name = "战胜青翼5次",
        sub_type = 2,
        type = 3,
    },

    [400037] = {
        condition = "战胜猫蜀黍=1",
        degreetype = 2,
        desc = "战胜猫蜀黍一次",
        detail = "本字段策划暂时没用",
        id = 400037,
        name = "战胜猫蜀黍1次",
        sub_type = 3,
        type = 3,
    },

    [400038] = {
        condition = "战胜猫蜀黍=5",
        degreetype = 2,
        desc = "战胜猫蜀黍五次",
        detail = "本字段策划暂时没用",
        id = 400038,
        name = "战胜猫蜀黍5次",
        sub_type = 2,
        type = 3,
    },

    [400039] = {
        condition = "战胜喵小萌=1",
        degreetype = 2,
        desc = "战胜喵小萌一次",
        detail = "本字段策划暂时没用",
        id = 400039,
        name = "战胜喵小萌1次",
        sub_type = 3,
        type = 3,
    },

    [400040] = {
        condition = "战胜喵小萌=5",
        degreetype = 2,
        desc = "战胜喵小萌五次",
        detail = "本字段策划暂时没用",
        id = 400040,
        name = "战胜喵小萌5次",
        sub_type = 2,
        type = 3,
    },

    [400041] = {
        condition = "战胜白婆婆=1",
        degreetype = 2,
        desc = "战胜白婆婆一次",
        detail = "本字段策划暂时没用",
        id = 400041,
        name = "战胜白婆婆1次",
        sub_type = 3,
        type = 3,
    },

    [400042] = {
        condition = "战胜白婆婆=5",
        degreetype = 2,
        desc = "战胜白婆婆五次",
        detail = "本字段策划暂时没用",
        id = 400042,
        name = "战胜白婆婆5次",
        sub_type = 2,
        type = 3,
    },

    [400043] = {
        condition = "战胜克瑞斯汀=1",
        degreetype = 2,
        desc = "战胜克瑞斯汀一次",
        detail = "本字段策划暂时没用",
        id = 400043,
        name = "战胜克瑞斯汀1次",
        sub_type = 3,
        type = 3,
    },

    [400044] = {
        condition = "战胜克瑞斯汀=5",
        degreetype = 2,
        desc = "战胜克瑞斯汀五次",
        detail = "本字段策划暂时没用",
        id = 400044,
        name = "战胜克瑞斯汀5次",
        sub_type = 2,
        type = 3,
    },

    [400045] = {
        condition = "战胜链=1",
        degreetype = 2,
        desc = "战胜链一次",
        detail = "本字段策划暂时没用",
        id = 400045,
        name = "战胜链1次",
        sub_type = 3,
        type = 3,
    },

    [400046] = {
        condition = "战胜链=5",
        degreetype = 2,
        desc = "战胜链五次",
        detail = "本字段策划暂时没用",
        id = 400046,
        name = "战胜链5次",
        sub_type = 2,
        type = 3,
    },

    [400047] = {
        condition = "战胜扳尾=1",
        degreetype = 2,
        desc = "战胜扳尾一次",
        detail = "本字段策划暂时没用",
        id = 400047,
        name = "战胜扳尾1次",
        sub_type = 3,
        type = 3,
    },

    [400048] = {
        condition = "战胜扳尾=5",
        degreetype = 2,
        desc = "战胜扳尾五次",
        detail = "本字段策划暂时没用",
        id = 400048,
        name = "战胜扳尾5次",
        sub_type = 2,
        type = 3,
    },

    [113011] = {
        condition = "获得祁连=1",
        degreetype = 2,
        desc = "开启条件：与祁连成为伙伴",
        detail = "本字段策划暂时没用",
        id = 113011,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [113012] = {
        condition = "觉醒祁连=1",
        degreetype = 2,
        desc = "开启条件：祁连觉醒",
        detail = "本字段策划暂时没用",
        id = 113012,
        name = "觉醒",
        sub_type = 2,
        type = 1,
    },

    [113013] = {
        condition = "获得朵屠=1",
        degreetype = 2,
        desc = "开启条件：与祁连、朵屠成为伙伴",
        detail = "本字段策划暂时没用",
        id = 113013,
        name = "获得",
        sub_type = 2,
        type = 1,
    },

    [113014] = {
        condition = "获得祁连碎片=30",
        degreetype = 2,
        desc = "开启条件：累计获得30片祁连碎片",
        detail = "本字段策划暂时没用",
        id = 113014,
        name = "获得",
        sub_type = 2,
        type = 1,
    },

    [113021] = {
        condition = "获得重华=1",
        degreetype = 2,
        desc = "开启条件：与重华成为伙伴",
        detail = "本字段策划暂时没用",
        id = 113021,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [113022] = {
        condition = "重华提升技能次数=2",
        degreetype = 2,
        desc = "开启条件：技能升级2次",
        detail = "本字段策划暂时没用",
        id = 113022,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [113023] = {
        condition = "获得檀=1",
        degreetype = 2,
        desc = "开启条件：与重华、檀成为伙伴",
        detail = "本字段策划暂时没用",
        id = 113023,
        name = "获得",
        sub_type = 2,
        type = 1,
    },

    [113024] = {
        condition = "重华星级达到4星=1",
        degreetype = 2,
        desc = "开启条件：重华星级达到四星",
        detail = "本字段策划暂时没用",
        id = 113024,
        name = "升级-升星",
        sub_type = 2,
        type = 1,
    },

    [113031] = {
        condition = "获得朵屠=1",
        degreetype = 2,
        desc = "开启条件：与朵屠成为伙伴",
        detail = "本字段策划暂时没用",
        id = 113031,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [113032] = {
        condition = "觉醒朵屠=1",
        degreetype = 2,
        desc = "开启条件：朵屠觉醒",
        detail = "本字段策划暂时没用",
        id = 113032,
        name = "觉醒",
        sub_type = 2,
        type = 1,
    },

    [113033] = {
        condition = "竞技场朵屠战胜重华=2",
        degreetype = 2,
        desc = "开启条件：比武场中，协助朵屠战胜携带重华的玩家累计2场",
        detail = "本字段策划暂时没用",
        id = 113033,
        name = "两种竞技场",
        sub_type = 2,
        type = 1,
    },

    [113034] = {
        condition = "朵屠星级达到4星=1",
        degreetype = 2,
        desc = "开启条件：朵屠星级达到四星",
        detail = "本字段策划暂时没用",
        id = 113034,
        name = "升级-升星",
        sub_type = 2,
        type = 1,
    },

    [113051] = {
        condition = "获得亦候=1",
        degreetype = 2,
        desc = "开启条件：与亦候成为伙伴",
        detail = "本字段策划暂时没用",
        id = 113051,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [113052] = {
        condition = "觉醒亦候=1",
        degreetype = 2,
        desc = "开启条件：亦候觉醒",
        detail = "本字段策划暂时没用",
        id = 113052,
        name = "觉醒",
        sub_type = 2,
        type = 1,
    },

    [113053] = {
        condition = "亦候提升技能次数=6",
        degreetype = 2,
        desc = "开启条件：技能升级6次",
        detail = "本字段策划暂时没用",
        id = 113053,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [113054] = {
        condition = "许愿亦候碎片次数=10",
        degreetype = 2,
        desc = "开启条件：许愿亦候碎片10次",
        detail = "本字段策划暂时没用",
        id = 113054,
        name = "许愿池-许愿",
        sub_type = 2,
        type = 1,
    },

    [113061] = {
        condition = "获得袁雀=1",
        degreetype = 2,
        desc = "开启条件：与袁雀成为伙伴",
        detail = "本字段策划暂时没用",
        id = 113061,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [113062] = {
        condition = "觉醒袁雀=1",
        degreetype = 2,
        desc = "开启条件：袁雀觉醒",
        detail = "本字段策划暂时没用",
        id = 113062,
        name = "觉醒",
        sub_type = 2,
        type = 1,
    },

    [113063] = {
        condition = "袁雀提升技能次数=6",
        degreetype = 2,
        desc = "开启条件：技能升级6次",
        detail = "本字段策划暂时没用",
        id = 113063,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [113064] = {
        condition = "许愿袁雀碎片次数=10",
        degreetype = 2,
        desc = "开启条件：许愿袁雀碎片10次",
        detail = "本字段策划暂时没用",
        id = 113064,
        name = "许愿池-许愿",
        sub_type = 2,
        type = 1,
    },

    [113081] = {
        condition = "获得黑烈=1",
        degreetype = 2,
        desc = "开启条件：与黑烈成为伙伴",
        detail = "本字段策划暂时没用",
        id = 113081,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [113082] = {
        condition = "觉醒黑烈=1",
        degreetype = 2,
        desc = "开启条件：黑烈觉醒",
        detail = "本字段策划暂时没用",
        id = 113082,
        name = "觉醒",
        sub_type = 2,
        type = 1,
    },

    [113083] = {
        condition = "黑烈等级升至30级=1",
        degreetype = 1,
        desc = "开启条件：黑烈等级升至30级",
        detail = "本字段策划暂时没用",
        id = 113083,
        name = "升级-伙伴等级",
        sub_type = 2,
        type = 1,
    },

    [113084] = {
        condition = "地牢黑烈获胜=15",
        degreetype = 2,
        desc = "开启条件：与黑烈组队勇闯地牢，累计获得15胜",
        detail = "本字段策划暂时没用",
        id = 113084,
        name = "地牢",
        sub_type = 2,
        type = 1,
    },

    [113111] = {
        condition = "获得花常酒=1",
        degreetype = 2,
        desc = "开启条件：与花常酒成为伙伴",
        detail = "本字段策划暂时没用",
        id = 113111,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [113112] = {
        condition = "觉醒花常酒=1",
        degreetype = 2,
        desc = "开启条件：花常酒觉醒",
        detail = "本字段策划暂时没用",
        id = 113112,
        name = "觉醒",
        sub_type = 2,
        type = 1,
    },

    [113113] = {
        condition = "花常酒提升技能次数=3",
        degreetype = 2,
        desc = "开启条件：技能升级3次",
        detail = "本字段策划暂时没用",
        id = 113113,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [113114] = {
        condition = "花常酒等级升至40级=1",
        degreetype = 1,
        desc = "开启条件：花常酒等级升至40级",
        detail = "本字段策划暂时没用",
        id = 113114,
        name = "升级-伙伴等级",
        sub_type = 2,
        type = 1,
    },

    [113121] = {
        condition = "获得伊露=1",
        degreetype = 2,
        desc = "开启条件：与伊露成为伙伴",
        detail = "本字段策划暂时没用",
        id = 113121,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [113122] = {
        condition = "伊露提升技能次数=3",
        degreetype = 2,
        desc = "开启条件：技能升级3次",
        detail = "本字段策划暂时没用",
        id = 113122,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [113123] = {
        condition = "竞技场伊露白获胜=2",
        degreetype = 2,
        desc = "开启条件：比武场中，与伊露、白组队并累计获得2胜",
        detail = "本字段策划暂时没用",
        id = 113123,
        name = "两种竞技场",
        sub_type = 2,
        type = 1,
    },

    [113124] = {
        condition = "伊露伙伴升星到4星=1",
        degreetype = 2,
        desc = "开启条件：伊露星级达到四星",
        detail = "本字段策划暂时没用",
        id = 113124,
        name = "升级-升星",
        sub_type = 2,
        type = 1,
    },

    [113131] = {
        condition = "获得檀=1",
        degreetype = 2,
        desc = "开启条件：与檀成为伙伴",
        detail = "本字段策划暂时没用",
        id = 113131,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [113132] = {
        condition = "檀提升技能次数=3",
        degreetype = 2,
        desc = "开启条件：技能升级3次",
        detail = "本字段策划暂时没用",
        id = 113132,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [113133] = {
        condition = "获得白殊=1",
        degreetype = 2,
        desc = "开启条件：与檀、白殊成为伙伴",
        detail = "本字段策划暂时没用",
        id = 113133,
        name = "获得",
        sub_type = 2,
        type = 1,
    },

    [113134] = {
        condition = "地牢檀重华获胜=30",
        degreetype = 2,
        desc = "开启条件：与檀、重华组队勇闯地牢，累计获得30胜",
        detail = "本字段策划暂时没用",
        id = 113134,
        name = "地牢",
        sub_type = 2,
        type = 1,
    },

    [113141] = {
        condition = "获得执阳=1",
        degreetype = 2,
        desc = "开启条件：与执阳成为伙伴",
        detail = "本字段策划暂时没用",
        id = 113141,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [113142] = {
        condition = "竞技场执阳战胜青竹=1",
        degreetype = 2,
        desc = "开启条件：比武场中，和执阳组队对抗携带青竹的玩家并获胜",
        detail = "本字段策划暂时没用",
        id = 113142,
        name = "两种竞技场",
        sub_type = 2,
        type = 1,
    },

    [113143] = {
        condition = "获得执夷=1",
        degreetype = 2,
        desc = "开启条件：与执阳、执夷成为伙伴",
        detail = "本字段策划暂时没用",
        id = 113143,
        name = "获得",
        sub_type = 2,
        type = 1,
    },

    [113144] = {
        condition = "月见幻境执阳执夷获胜=10",
        degreetype = 2,
        desc = "开启条件：月见幻境中，与执阳、执夷组队战斗并累计获得10胜",
        detail = "本字段策划暂时没用",
        id = 113144,
        name = "月见幻境",
        sub_type = 2,
        type = 1,
    },

    [113151] = {
        condition = "获得白殊=1",
        degreetype = 2,
        desc = "开启条件：与白殊成为伙伴",
        detail = "本字段策划暂时没用",
        id = 113151,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [113152] = {
        condition = "觉醒白殊=1",
        degreetype = 2,
        desc = "开启条件：白殊觉醒",
        detail = "本字段策划暂时没用",
        id = 113152,
        name = "觉醒",
        sub_type = 2,
        type = 1,
    },

    [113153] = {
        condition = "白殊伙伴升星到4星=1",
        degreetype = 2,
        desc = "开启条件：白殊星级达到五星",
        detail = "本字段策划暂时没用",
        id = 113153,
        name = "升级-升星",
        sub_type = 2,
        type = 1,
    },

    [113154] = {
        condition = "竞技场白殊战胜奉主夜鹤=10",
        degreetype = 2,
        desc = "开启条件：比武场中，协助白殊对抗携带奉主夜鹤的玩家并累计获得10胜",
        detail = "本字段策划暂时没用",
        id = 113154,
        name = "两种竞技场",
        sub_type = 2,
        type = 1,
    },

    [113161] = {
        condition = "获得流褐=1",
        degreetype = 2,
        desc = "开启条件：与流褐成为伙伴",
        detail = "本字段策划暂时没用",
        id = 113161,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [113162] = {
        condition = "流褐提升技能次数=3",
        degreetype = 2,
        desc = "开启条件：技能升级3次",
        detail = "本字段策划暂时没用",
        id = 113162,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [113163] = {
        condition = "流褐伙伴升星到4星=1",
        degreetype = 2,
        desc = "开启条件：流褐星级达到四星",
        detail = "本字段策划暂时没用",
        id = 113163,
        name = "升级-升星",
        sub_type = 2,
        type = 1,
    },

    [113164] = {
        condition = "许愿池捐赠流褐碎片=15",
        degreetype = 2,
        desc = "开启条件：实现其他小伙伴的流褐碎片许愿15次",
        detail = "本字段策划暂时没用",
        id = 113164,
        name = "许愿池-捐赠",
        sub_type = 2,
        type = 1,
    },

    [114011] = {
        condition = "获得北溟=1",
        degreetype = 2,
        desc = "开启条件：与北溟成为伙伴",
        detail = "本字段策划暂时没用",
        id = 114011,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [114012] = {
        condition = "觉醒北溟=1",
        degreetype = 2,
        desc = "开启条件：北溟觉醒",
        detail = "本字段策划暂时没用",
        id = 114012,
        name = "觉醒",
        sub_type = 2,
        type = 1,
    },

    [114013] = {
        condition = "获得莲溟=1",
        degreetype = 2,
        desc = "开启条件：与北溟、莲成为伙伴",
        detail = "本字段策划暂时没用",
        id = 114013,
        name = "获得",
        sub_type = 2,
        type = 1,
    },

    [114014] = {
        condition = "北溟提升技能次数=3",
        degreetype = 2,
        desc = "开启条件：技能升级3次",
        detail = "本字段策划暂时没用",
        id = 114014,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [114021] = {
        condition = "获得稻荷=1",
        degreetype = 2,
        desc = "开启条件：与稻荷成为伙伴",
        detail = "本字段策划暂时没用",
        id = 114021,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [114022] = {
        condition = "觉醒稻荷=1",
        degreetype = 2,
        desc = "开启条件：稻荷觉醒",
        detail = "本字段策划暂时没用",
        id = 114022,
        name = "觉醒",
        sub_type = 2,
        type = 1,
    },

    [114023] = {
        condition = "竞技场稻荷战胜莲=2",
        degreetype = 2,
        desc = "开启条件：比武场中，与稻荷共同对抗携带莲的玩家并累计获得2胜",
        detail = "本字段策划暂时没用",
        id = 114023,
        name = "两种竞技场",
        sub_type = 2,
        type = 1,
    },

    [114024] = {
        condition = "许愿池捐赠稻荷碎片=10",
        degreetype = 2,
        desc = "开启条件：实现其他小伙伴的稻荷碎片许愿10次",
        detail = "本字段策划暂时没用",
        id = 114024,
        name = "许愿池-捐赠",
        sub_type = 2,
        type = 1,
    },

    [114031] = {
        condition = "获得蛇姬=1",
        degreetype = 2,
        desc = "开启条件：与蛇姬成为伙伴",
        detail = "本字段策划暂时没用",
        id = 114031,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [114032] = {
        condition = "蛇姬提升技能次数=3",
        degreetype = 2,
        desc = "开启条件：技能升级3次",
        detail = "本字段策划暂时没用",
        id = 114032,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [114033] = {
        condition = "竞技场蛇姬战胜犬妖=2",
        degreetype = 2,
        desc = "开启条件：比武场中，协助蛇姬对抗犬妖并累计获得2胜",
        detail = "本字段策划暂时没用",
        id = 114033,
        name = "两种竞技场",
        sub_type = 2,
        type = 1,
    },

    [114034] = {
        condition = "获得蛇姬碎片=30",
        degreetype = 2,
        desc = "开启条件：累计获得30片蛇姬碎片",
        detail = "本字段策划暂时没用",
        id = 114034,
        name = "获得",
        sub_type = 2,
        type = 1,
    },

    [114041] = {
        condition = "获得绿狸=1",
        degreetype = 2,
        desc = "开启条件：与绿狸成为伙伴",
        detail = "本字段策划暂时没用",
        id = 114041,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [114042] = {
        condition = "觉醒绿狸=1",
        degreetype = 2,
        desc = "开启条件：绿狸觉醒",
        detail = "本字段策划暂时没用",
        id = 114042,
        name = "觉醒",
        sub_type = 2,
        type = 1,
    },

    [114043] = {
        condition = "地牢绿狸莹月获胜=10",
        degreetype = 2,
        desc = "开启条件：与绿狸、莹月组队勇闯地牢，累计获得10胜",
        detail = "本字段策划暂时没用",
        id = 114043,
        name = "地牢",
        sub_type = 2,
        type = 1,
    },

    [114044] = {
        condition = "绿狸提升技能次数=6",
        degreetype = 2,
        desc = "开启条件：技能升级6次",
        detail = "本字段策划暂时没用",
        id = 114044,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [114051] = {
        condition = "获得莹月=1",
        degreetype = 2,
        desc = "开启条件：与莹月成为伙伴",
        detail = "本字段策划暂时没用",
        id = 114051,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [114052] = {
        condition = "觉醒莹月=1",
        degreetype = 2,
        desc = "开启条件：莹月觉醒",
        detail = "本字段策划暂时没用",
        id = 114052,
        name = "觉醒",
        sub_type = 2,
        type = 1,
    },

    [114053] = {
        condition = "莹月提升技能次数=6",
        degreetype = 2,
        desc = "开启条件：技能升级6次",
        detail = "本字段策划暂时没用",
        id = 114053,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [114054] = {
        condition = "月见幻境莹月绿狸获胜=20",
        degreetype = 2,
        desc = "开启条件：月见幻境中，与莹月、绿狸组队战斗并累计获得20胜",
        detail = "本字段策划暂时没用",
        id = 114054,
        name = "月见幻境",
        sub_type = 2,
        type = 1,
    },

    [114071] = {
        condition = "获得莲=1",
        degreetype = 2,
        desc = "开启条件：与莲成为伙伴",
        detail = "本字段策划暂时没用",
        id = 114071,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [114072] = {
        condition = "地牢莲获胜=100",
        degreetype = 2,
        desc = "开启条件：地牢中，与莲共同战斗并累计获得100胜",
        detail = "本字段策划暂时没用",
        id = 114072,
        name = "地牢",
        sub_type = 2,
        type = 1,
    },

    [114073] = {
        condition = "月见幻境莲北溟获胜=10",
        degreetype = 2,
        desc = "开启条件：月见幻境中与莲、北溟组队战斗并累计获得10胜",
        detail = "本字段策划暂时没用",
        id = 114073,
        name = "月见幻境",
        sub_type = 2,
        type = 1,
    },

    [114074] = {
        condition = "许愿池捐赠莲碎片=15",
        degreetype = 2,
        desc = "开启条件：实现其他小伙伴的莲碎片许愿15次",
        detail = "本字段策划暂时没用",
        id = 114074,
        name = "许愿池-捐赠",
        sub_type = 2,
        type = 1,
    },

    [114091] = {
        condition = "获得犬妖=1",
        degreetype = 2,
        desc = "开启条件：与犬妖成为伙伴",
        detail = "本字段策划暂时没用",
        id = 114091,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [114092] = {
        condition = "觉醒犬妖=1",
        degreetype = 2,
        desc = "开启条件：犬妖觉醒",
        detail = "本字段策划暂时没用",
        id = 114092,
        name = "觉醒",
        sub_type = 2,
        type = 1,
    },

    [114093] = {
        condition = "犬妖提升技能次数=3",
        degreetype = 2,
        desc = "开启条件：技能升级3次",
        detail = "本字段策划暂时没用",
        id = 114093,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [114094] = {
        condition = "犬妖等级升至40级=1",
        degreetype = 1,
        desc = "开启条件：犬妖等级升至40级",
        detail = "本字段策划暂时没用",
        id = 114094,
        name = "升级-伙伴等级",
        sub_type = 2,
        type = 1,
    },

    [114101] = {
        condition = "获得青竹=1",
        degreetype = 2,
        desc = "开启条件：与青竹成为伙伴",
        detail = "本字段策划暂时没用",
        id = 114101,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [114102] = {
        condition = "觉醒青竹=1",
        degreetype = 2,
        desc = "开启条件：青竹觉醒",
        detail = "本字段策划暂时没用",
        id = 114102,
        name = "觉醒",
        sub_type = 2,
        type = 1,
    },

    [114103] = {
        condition = "青竹提升技能次数=3",
        degreetype = 2,
        desc = "开启条件：技能升级3次",
        detail = "本字段策划暂时没用",
        id = 114103,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [114104] = {
        condition = "竞技场青竹战胜执夷=2",
        degreetype = 2,
        desc = "开启条件：比武场中，协助青竹攻打执夷并累计获得2胜",
        detail = "本字段策划暂时没用",
        id = 114104,
        name = "两种竞技场",
        sub_type = 2,
        type = 1,
    },

    [114121] = {
        condition = "获得执夷=1",
        degreetype = 2,
        desc = "开启条件：与执夷成为伙伴",
        detail = "本字段策划暂时没用",
        id = 114121,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [114122] = {
        condition = "执夷提升技能次数=3",
        degreetype = 2,
        desc = "开启条件：技能升级3次",
        detail = "本字段策划暂时没用",
        id = 114122,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [114123] = {
        condition = "获得青竹=1",
        degreetype = 2,
        desc = "开启条件：与执夷、青竹成为伙伴",
        detail = "本字段策划暂时没用",
        id = 114123,
        name = "获得",
        sub_type = 2,
        type = 1,
    },

    [114124] = {
        condition = "获得执夷碎片=30",
        degreetype = 2,
        desc = "开启条件：累计获得30片执夷碎片",
        detail = "本字段策划暂时没用",
        id = 114124,
        name = "获得",
        sub_type = 2,
        type = 1,
    },

    [114131] = {
        condition = "获得古娄=1",
        degreetype = 2,
        desc = "开启条件：与古娄成为伙伴",
        detail = "本字段策划暂时没用",
        id = 114131,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [114132] = {
        condition = "古娄提升技能次数=3",
        degreetype = 2,
        desc = "开启条件：技能升级3次",
        detail = "本字段策划暂时没用",
        id = 114132,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [114133] = {
        condition = "获得琥非=1",
        degreetype = 2,
        desc = "开启条件：与古娄、琥非成为伙伴",
        detail = "本字段策划暂时没用",
        id = 114133,
        name = "获得",
        sub_type = 2,
        type = 1,
    },

    [114134] = {
        condition = "获得古娄碎片=30",
        degreetype = 2,
        desc = "开启条件：累计获得30片古娄碎片",
        detail = "本字段策划暂时没用",
        id = 114134,
        name = "获得",
        sub_type = 2,
        type = 1,
    },

    [114141] = {
        condition = "获得蓝堂昼=1",
        degreetype = 2,
        desc = "开启条件：与蓝堂昼成为伙伴",
        detail = "本字段策划暂时没用",
        id = 114141,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [114142] = {
        condition = "蓝堂昼提升技能次数=3",
        degreetype = 2,
        desc = "开启条件：技能升级3次",
        detail = "本字段策划暂时没用",
        id = 114142,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [114143] = {
        condition = "地牢蓝堂昼获胜=15",
        degreetype = 2,
        desc = "开启条件：地牢中，与蓝堂昼组队战斗并累计获得15胜",
        detail = "本字段策划暂时没用",
        id = 114143,
        name = "地牢",
        sub_type = 2,
        type = 1,
    },

    [114144] = {
        condition = "获得蓝堂昼碎片=30",
        degreetype = 2,
        desc = "开启条件：累计获得30片蓝堂昼碎片",
        detail = "本字段策划暂时没用",
        id = 114144,
        name = "获得",
        sub_type = 2,
        type = 1,
    },

    [114151] = {
        condition = "获得琥非=1",
        degreetype = 2,
        desc = "开启条件：与琥非成为伙伴",
        detail = "本字段策划暂时没用",
        id = 114151,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [114152] = {
        condition = "觉醒琥非=1",
        degreetype = 2,
        desc = "开启条件：琥非觉醒",
        detail = "本字段策划暂时没用",
        id = 114152,
        name = "觉醒",
        sub_type = 2,
        type = 1,
    },

    [114153] = {
        condition = "地牢琥非获胜=15",
        degreetype = 2,
        desc = "开启条件：地牢中，与琥非组队战斗并累计获得15胜",
        detail = "本字段策划暂时没用",
        id = 114153,
        name = "地牢",
        sub_type = 2,
        type = 1,
    },

    [114154] = {
        condition = "竞技场琥非战胜古娄=2",
        degreetype = 2,
        desc = "开启条件：比武场中，与琥非奋战中意外打败了古娄2场",
        detail = "本字段策划暂时没用",
        id = 114154,
        name = "两种竞技场",
        sub_type = 2,
        type = 1,
    },

    [114161] = {
        condition = "获得观绪=1",
        degreetype = 2,
        desc = "开启条件：与观绪成为伙伴",
        detail = "本字段策划暂时没用",
        id = 114161,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [114162] = {
        condition = "观绪提升技能次数=3",
        degreetype = 2,
        desc = "开启条件：技能升级3次",
        detail = "本字段策划暂时没用",
        id = 114162,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [114163] = {
        condition = "获得松姑子=1",
        degreetype = 2,
        desc = "开启条件：与观绪、松姑子成为伙伴",
        detail = "本字段策划暂时没用",
        id = 114163,
        name = "获得",
        sub_type = 2,
        type = 1,
    },

    [114164] = {
        condition = "获得观绪碎片=30",
        degreetype = 2,
        desc = "开启条件：累计获得30片观绪碎片",
        detail = "本字段策划暂时没用",
        id = 114164,
        name = "获得",
        sub_type = 2,
        type = 1,
    },

    [114171] = {
        condition = "获得松姑子=1",
        degreetype = 2,
        desc = "开启条件：与松姑子成为伙伴",
        detail = "本字段策划暂时没用",
        id = 114171,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [114172] = {
        condition = "松姑子提升技能次数=3",
        degreetype = 2,
        desc = "开启条件：技能升级3次",
        detail = "本字段策划暂时没用",
        id = 114172,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [114173] = {
        condition = "获得松姑子碎片=30",
        degreetype = 2,
        desc = "开启条件：累计获得30片松姑子碎片",
        detail = "本字段策划暂时没用",
        id = 114173,
        name = "获得",
        sub_type = 2,
        type = 1,
    },

    [114174] = {
        condition = "获得观绪=1",
        degreetype = 2,
        desc = "开启条件：与松姑子、观绪成为伙伴",
        detail = "本字段策划暂时没用",
        id = 114174,
        name = "获得",
        sub_type = 2,
        type = 1,
    },

    [114181] = {
        condition = "获得嘟嘟噜=1",
        degreetype = 2,
        desc = "开启条件：与嘟嘟噜成为伙伴",
        detail = "本字段策划暂时没用",
        id = 114181,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [114182] = {
        condition = "觉醒嘟嘟噜=1",
        degreetype = 2,
        desc = "开启条件：嘟嘟噜觉醒",
        detail = "本字段策划暂时没用",
        id = 114182,
        name = "觉醒",
        sub_type = 2,
        type = 1,
    },

    [114183] = {
        condition = "嘟嘟噜提升技能次数=6",
        degreetype = 2,
        desc = "开启条件：技能升级6次",
        detail = "本字段策划暂时没用",
        id = 114183,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [114184] = {
        condition = "地牢嘟嘟噜获胜=50",
        degreetype = 2,
        desc = "开启条件：地牢中，和嘟嘟噜组队战斗并累计获得50胜",
        detail = "本字段策划暂时没用",
        id = 114184,
        name = "地牢",
        sub_type = 2,
        type = 1,
    },

    [115011] = {
        condition = "获得阿坊=1",
        degreetype = 2,
        desc = "开启条件：与阿坊成为伙伴",
        detail = "本字段策划暂时没用",
        id = 115011,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [115012] = {
        condition = "阿坊提升技能次数=3",
        degreetype = 2,
        desc = "开启条件：技能升级3次",
        detail = "本字段策划暂时没用",
        id = 115012,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [115013] = {
        condition = "竞技场阿坊马面面获胜=2",
        degreetype = 2,
        desc = "开启条件：比武场中，携带阿坊、马面面组队战斗并累计获得2胜",
        detail = "本字段策划暂时没用",
        id = 115013,
        name = "两种竞技场",
        sub_type = 2,
        type = 1,
    },

    [115014] = {
        condition = "获得马面面=1",
        degreetype = 2,
        desc = "开启条件：与阿坊、马面面成为伙伴",
        detail = "本字段策划暂时没用",
        id = 115014,
        name = "获得",
        sub_type = 2,
        type = 1,
    },

    [115021] = {
        condition = "获得马面面=1",
        degreetype = 2,
        desc = "开启条件：与马面面成为伙伴",
        detail = "本字段策划暂时没用",
        id = 115021,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [115022] = {
        condition = "马面面等级升至30级=1",
        degreetype = 1,
        desc = "开启条件：马面面等级升至30级",
        detail = "本字段策划暂时没用",
        id = 115022,
        name = "升级-伙伴等级",
        sub_type = 2,
        type = 1,
    },

    [115023] = {
        condition = "马面面提升技能次数=3",
        degreetype = 2,
        desc = "开启条件：技能升级3次",
        detail = "本字段策划暂时没用",
        id = 115023,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [115024] = {
        condition = "地牢阿坊马面面获胜=15",
        degreetype = 2,
        desc = "开启条件：地牢中，与马面面、阿坊组队战斗并累计获得15胜",
        detail = "本字段策划暂时没用",
        id = 115024,
        name = "地牢",
        sub_type = 2,
        type = 1,
    },

    [115031] = {
        condition = "获得黑=1",
        degreetype = 2,
        desc = "开启条件：与黑成为伙伴",
        detail = "本字段策划暂时没用",
        id = 115031,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [115032] = {
        condition = "觉醒黑=1",
        degreetype = 2,
        desc = "开启条件：黑觉醒",
        detail = "本字段策划暂时没用",
        id = 115032,
        name = "觉醒",
        sub_type = 2,
        type = 1,
    },

    [115033] = {
        condition = "月见幻境黑和白获胜=30",
        degreetype = 2,
        desc = "开启条件：月见幻境中，与黑、白组队战斗并累计获得30胜",
        detail = "本字段策划暂时没用",
        id = 115033,
        name = "月见幻境",
        sub_type = 2,
        type = 1,
    },

    [115034] = {
        condition = "竞技场黑战胜白殊=2",
        degreetype = 2,
        desc = "开启条件：比武场中，和黑组队对抗携带白殊的玩家并累计获得2胜",
        detail = "本字段策划暂时没用",
        id = 115034,
        name = "两种竞技场",
        sub_type = 2,
        type = 1,
    },

    [115041] = {
        condition = "获得白=1",
        degreetype = 2,
        desc = "开启条件：与白成为伙伴",
        detail = "本字段策划暂时没用",
        id = 115041,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [115042] = {
        condition = "白等级升至40级=1",
        degreetype = 1,
        desc = "开启条件：白等级升至40级",
        detail = "本字段策划暂时没用",
        id = 115042,
        name = "升级-伙伴等级",
        sub_type = 2,
        type = 1,
    },

    [115043] = {
        condition = "获得黑=1",
        degreetype = 2,
        desc = "开启条件：与黑、白成为伙伴",
        detail = "本字段策划暂时没用",
        id = 115043,
        name = "获得",
        sub_type = 2,
        type = 1,
    },

    [115044] = {
        condition = "竞技场黑战胜白=2",
        degreetype = 2,
        desc = "开启条件：比武场中，携带白出战，岂料被黑累计打败2场",
        detail = "本字段策划暂时没用",
        id = 115044,
        name = "两种竞技场",
        sub_type = 2,
        type = 1,
    },

    [115051] = {
        condition = "获得吞天=1",
        degreetype = 2,
        desc = "开启条件：与吞天成为伙伴",
        detail = "本字段策划暂时没用",
        id = 115051,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [115052] = {
        condition = "觉醒吞天=1",
        degreetype = 2,
        desc = "开启条件：吞天觉醒",
        detail = "本字段策划暂时没用",
        id = 115052,
        name = "觉醒",
        sub_type = 2,
        type = 1,
    },

    [115053] = {
        condition = "获得噬地=1",
        degreetype = 2,
        desc = "开启条件：与吞天、噬地成为伙伴",
        detail = "本字段策划暂时没用",
        id = 115053,
        name = "获得",
        sub_type = 2,
        type = 1,
    },

    [115054] = {
        condition = "地牢吞天噬地获胜=30",
        degreetype = 2,
        desc = "开启条件：地牢中，与吞天、噬地组队战斗并累计获得30胜",
        detail = "本字段策划暂时没用",
        id = 115054,
        name = "地牢",
        sub_type = 2,
        type = 1,
    },

    [115061] = {
        condition = "获得噬地=1",
        degreetype = 2,
        desc = "开启条件：与噬地成为伙伴",
        detail = "本字段策划暂时没用",
        id = 115061,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [115062] = {
        condition = "觉醒噬地=1",
        degreetype = 2,
        desc = "开启条件：噬地觉醒",
        detail = "本字段策划暂时没用",
        id = 115062,
        name = "觉醒",
        sub_type = 2,
        type = 1,
    },

    [115063] = {
        condition = "噬地等级升至40级=1",
        degreetype = 1,
        desc = "开启条件：噬地等级升至40级",
        detail = "本字段策划暂时没用",
        id = 115063,
        name = "升级-伙伴等级",
        sub_type = 2,
        type = 1,
    },

    [115064] = {
        condition = "获得吞天=1",
        degreetype = 2,
        desc = "开启条件：与噬地、吞天成为伙伴",
        detail = "本字段策划暂时没用",
        id = 115064,
        name = "获得",
        sub_type = 2,
        type = 1,
    },

    [115071] = {
        condition = "获得魃女=1",
        degreetype = 2,
        desc = "开启条件：与魃女成为伙伴",
        detail = "本字段策划暂时没用",
        id = 115071,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [115072] = {
        condition = "魃女提升技能次数=3",
        degreetype = 2,
        desc = "开启条件：技能升级3次",
        detail = "本字段策划暂时没用",
        id = 115072,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [115073] = {
        condition = "魃女等级升至30级=1",
        degreetype = 1,
        desc = "开启条件：魃女等级升至30级",
        detail = "本字段策划暂时没用",
        id = 115073,
        name = "升级-伙伴等级",
        sub_type = 2,
        type = 1,
    },

    [115074] = {
        condition = "月见幻境魃女判官获胜=15",
        degreetype = 2,
        desc = "开启条件：月见幻境中，与魃女、判官组队战斗并累计获得15胜",
        detail = "本字段策划暂时没用",
        id = 115074,
        name = "月见幻境",
        sub_type = 2,
        type = 1,
    },

    [115081] = {
        condition = "获得魂夕=1",
        degreetype = 2,
        desc = "开启条件：与魂夕成为伙伴",
        detail = "本字段策划暂时没用",
        id = 115081,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [115082] = {
        condition = "魂夕等级升至40级=1",
        degreetype = 1,
        desc = "开启条件：魂夕等级升至40级",
        detail = "本字段策划暂时没用",
        id = 115082,
        name = "升级-伙伴等级",
        sub_type = 2,
        type = 1,
    },

    [115083] = {
        condition = "魂夕伙伴升星到4星=1",
        degreetype = 2,
        desc = "开启条件：魂夕星级达到四星",
        detail = "本字段策划暂时没用",
        id = 115083,
        name = "升级-升星",
        sub_type = 2,
        type = 1,
    },

    [115084] = {
        condition = "许愿池捐赠魂夕碎片=15",
        degreetype = 2,
        desc = "开启条件：实现其他小伙伴的魂夕碎片许愿15次",
        detail = "本字段策划暂时没用",
        id = 115084,
        name = "许愿池-捐赠",
        sub_type = 2,
        type = 1,
    },

    [115091] = {
        condition = "获得判官=1",
        degreetype = 2,
        desc = "开启条件：与判官成为伙伴",
        detail = "本字段策划暂时没用",
        id = 115091,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [115092] = {
        condition = "觉醒判官=1",
        degreetype = 2,
        desc = "开启条件：判官觉醒",
        detail = "本字段策划暂时没用",
        id = 115092,
        name = "觉醒",
        sub_type = 2,
        type = 1,
    },

    [115093] = {
        condition = "月见幻境判官奉主夜鹤获胜=30",
        degreetype = 2,
        desc = "开启条件：月见幻境中，与判官、奉主夜鹤组队战斗并累计获得30胜",
        detail = "本字段策划暂时没用",
        id = 115093,
        name = "月见幻境",
        sub_type = 2,
        type = 1,
    },

    [115094] = {
        condition = "判官提升技能次数=3",
        degreetype = 2,
        desc = "开启条件：技能升级3次",
        detail = "本字段策划暂时没用",
        id = 115094,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [115101] = {
        condition = "获得奉主夜鹤=1",
        degreetype = 2,
        desc = "开启条件：与奉主夜鹤成为伙伴",
        detail = "本字段策划暂时没用",
        id = 115101,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [115102] = {
        condition = "觉醒奉主夜鹤=1",
        degreetype = 2,
        desc = "开启条件：奉主夜鹤觉醒",
        detail = "本字段策划暂时没用",
        id = 115102,
        name = "觉醒",
        sub_type = 2,
        type = 1,
    },

    [115103] = {
        condition = "奉主夜鹤伙伴升星到4星=1",
        degreetype = 2,
        desc = "开启条件：奉主夜鹤星级达到五星",
        detail = "本字段策划暂时没用",
        id = 115103,
        name = "升级-升星",
        sub_type = 2,
        type = 1,
    },

    [115104] = {
        condition = "获得判官=1",
        degreetype = 2,
        desc = "开启条件：与奉主夜鹤、判官成为伙伴",
        detail = "本字段策划暂时没用",
        id = 115104,
        name = "获得",
        sub_type = 2,
        type = 1,
    },

    [115111] = {
        condition = "获得片雾=1",
        degreetype = 2,
        desc = "开启条件：与片雾成为伙伴",
        detail = "本字段策划暂时没用",
        id = 115111,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [115112] = {
        condition = "觉醒片雾=1",
        degreetype = 2,
        desc = "开启条件：片雾觉醒",
        detail = "本字段策划暂时没用",
        id = 115112,
        name = "觉醒",
        sub_type = 2,
        type = 1,
    },

    [115113] = {
        condition = "片雾提升技能次数=6",
        degreetype = 2,
        desc = "开启条件：技能升级6次",
        detail = "本字段策划暂时没用",
        id = 115113,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [115114] = {
        condition = "片雾等级升至40级=1",
        degreetype = 1,
        desc = "开启条件：片雾等级升至40级",
        detail = "本字段策划暂时没用",
        id = 115114,
        name = "升级-伙伴等级",
        sub_type = 2,
        type = 1,
    },

    [115121] = {
        condition = "获得浮屠僧=1",
        degreetype = 2,
        desc = "开启条件：与浮屠僧成为伙伴",
        detail = "本字段策划暂时没用",
        id = 115121,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [115122] = {
        condition = "觉醒浮屠僧=1",
        degreetype = 2,
        desc = "开启条件：浮屠僧觉醒",
        detail = "本字段策划暂时没用",
        id = 115122,
        name = "觉醒",
        sub_type = 2,
        type = 1,
    },

    [115123] = {
        condition = "许愿浮屠僧碎片次数=10",
        degreetype = 2,
        desc = "开启条件：许愿浮屠僧碎片10次",
        detail = "本字段策划暂时没用",
        id = 115123,
        name = "许愿池-许愿",
        sub_type = 2,
        type = 1,
    },

    [115124] = {
        condition = "浮屠僧提升技能次数=6",
        degreetype = 2,
        desc = "开启条件：技能升级6次",
        detail = "本字段策划暂时没用",
        id = 115124,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [115131] = {
        condition = "获得夜叉=1",
        degreetype = 2,
        desc = "开启条件：与夜叉成为伙伴",
        detail = "本字段策划暂时没用",
        id = 115131,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [115132] = {
        condition = "夜叉提升技能次数=3",
        degreetype = 2,
        desc = "开启条件：技能升级3次",
        detail = "本字段策划暂时没用",
        id = 115132,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

    [115133] = {
        condition = "夜叉等级升至30级=1",
        degreetype = 1,
        desc = "开启条件：夜叉等级升至30级",
        detail = "本字段策划暂时没用",
        id = 115133,
        name = "升级-伙伴等级",
        sub_type = 2,
        type = 1,
    },

    [115134] = {
        condition = "获得夜叉碎片=30",
        degreetype = 2,
        desc = "开启条件：累计获得30片夜叉碎片",
        detail = "本字段策划暂时没用",
        id = 115134,
        name = "获得",
        sub_type = 2,
        type = 1,
    },

    [115141] = {
        condition = "获得曼珠沙华=1",
        degreetype = 2,
        desc = "开启条件：与曼珠沙华成为伙伴",
        detail = "本字段策划暂时没用",
        id = 115141,
        name = "获得",
        sub_type = 3,
        type = 1,
    },

    [115142] = {
        condition = "觉醒曼珠沙华=1",
        degreetype = 2,
        desc = "开启条件：曼珠沙华觉醒",
        detail = "本字段策划暂时没用",
        id = 115142,
        name = "觉醒",
        sub_type = 2,
        type = 1,
    },

    [115143] = {
        condition = "曼珠沙华等级升至40级=1",
        degreetype = 1,
        desc = "开启条件：曼珠沙华等级升至40级",
        detail = "本字段策划暂时没用",
        id = 115143,
        name = "升级-伙伴等级",
        sub_type = 2,
        type = 1,
    },

    [115144] = {
        condition = "曼珠沙华提升技能次数=3",
        degreetype = 2,
        desc = "开启条件：技能升级3次",
        detail = "本字段策划暂时没用",
        id = 115144,
        name = "升级-技能提升",
        sub_type = 2,
        type = 1,
    },

}
