-- ./excel/handbook/handbook.xlsx
return {

    [100301] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {313011},
        chapter_point = 1,
        condition_list = {113011},
        draw_repair_cost = 0,
        id = 100301,
        name = "祁连",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 301,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100302] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {313021, 313022},
        chapter_point = 1,
        condition_list = {113021},
        draw_repair_cost = 0,
        id = 100302,
        name = "重华",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 302,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100303] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {313031, 313032},
        chapter_point = 1,
        condition_list = {113031},
        draw_repair_cost = 0,
        id = 100303,
        name = "朵屠",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 303,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100305] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {313051},
        chapter_point = 1,
        condition_list = {113051},
        draw_repair_cost = 0,
        id = 100305,
        name = "亦候",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 305,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100306] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {313061, 313062},
        chapter_point = 1,
        condition_list = {113061},
        draw_repair_cost = 0,
        id = 100306,
        name = "袁雀",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 306,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100308] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {313081},
        chapter_point = 1,
        condition_list = {113081},
        draw_repair_cost = 0,
        id = 100308,
        name = "黑烈",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 308,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100311] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {313111},
        chapter_point = 1,
        condition_list = {113111},
        draw_repair_cost = 0,
        id = 100311,
        name = "花常酒",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 311,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100312] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {313121, 313122},
        chapter_point = 1,
        condition_list = {113121},
        draw_repair_cost = 0,
        id = 100312,
        name = "伊露",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 312,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100313] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {313131},
        chapter_point = 1,
        condition_list = {113131},
        draw_repair_cost = 0,
        id = 100313,
        name = "檀",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 313,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100314] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {313141, 313142, 313143},
        chapter_point = 1,
        condition_list = {113141},
        draw_repair_cost = 0,
        id = 100314,
        name = "执阳",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 314,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100315] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {313151},
        chapter_point = 1,
        condition_list = {113151},
        draw_repair_cost = 0,
        id = 100315,
        name = "白殊",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 315,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100316] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {313161},
        chapter_point = 1,
        condition_list = {113161},
        draw_repair_cost = 0,
        id = 100316,
        name = "流褐",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 316,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100401] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {314011},
        chapter_point = 1,
        condition_list = {114011},
        draw_repair_cost = 0,
        id = 100401,
        name = "北溟",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 401,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100402] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {314021},
        chapter_point = 1,
        condition_list = {114021},
        draw_repair_cost = 0,
        id = 100402,
        name = "稻荷",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 402,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100403] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {314031},
        chapter_point = 1,
        condition_list = {114031},
        draw_repair_cost = 0,
        id = 100403,
        name = "蛇姬",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 403,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100404] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {314041},
        chapter_point = 1,
        condition_list = {114041},
        draw_repair_cost = 0,
        id = 100404,
        name = "绿狸",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 404,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100405] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {314051},
        chapter_point = 1,
        condition_list = {114051},
        draw_repair_cost = 0,
        id = 100405,
        name = "莹月",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 405,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100407] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {314071},
        chapter_point = 1,
        condition_list = {114071},
        draw_repair_cost = 0,
        id = 100407,
        name = "莲",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 407,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100409] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {314091},
        chapter_point = 1,
        condition_list = {114091},
        draw_repair_cost = 0,
        id = 100409,
        name = "犬妖",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 409,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100410] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {314101},
        chapter_point = 1,
        condition_list = {114101},
        draw_repair_cost = 0,
        id = 100410,
        name = "青竹",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 410,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100412] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {314121},
        chapter_point = 1,
        condition_list = {114121},
        draw_repair_cost = 0,
        id = 100412,
        name = "执夷",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 412,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100413] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {314131},
        chapter_point = 1,
        condition_list = {114131},
        draw_repair_cost = 0,
        id = 100413,
        name = "古娄",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 413,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100414] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {314141},
        chapter_point = 1,
        condition_list = {114141},
        draw_repair_cost = 0,
        id = 100414,
        name = "蓝堂昼",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 414,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100415] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {314151},
        chapter_point = 1,
        condition_list = {114151},
        draw_repair_cost = 0,
        id = 100415,
        name = "琥非",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 415,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100416] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {314161},
        chapter_point = 1,
        condition_list = {114161},
        draw_repair_cost = 0,
        id = 100416,
        name = "观绪",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 416,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100417] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {314171},
        chapter_point = 1,
        condition_list = {114171},
        draw_repair_cost = 0,
        id = 100417,
        name = "松姑子",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 417,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100418] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {314181},
        chapter_point = 1,
        condition_list = {114181},
        draw_repair_cost = 0,
        id = 100418,
        name = "嘟嘟噜",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 418,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100501] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {315011, 315012},
        chapter_point = 1,
        condition_list = {115011},
        draw_repair_cost = 0,
        id = 100501,
        name = "阿坊",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 501,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100502] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {315021},
        chapter_point = 1,
        condition_list = {115021},
        draw_repair_cost = 0,
        id = 100502,
        name = "马面面",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 502,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100503] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {315031},
        chapter_point = 1,
        condition_list = {115031},
        draw_repair_cost = 0,
        id = 100503,
        name = "黑",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 503,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100504] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {315041, 315042},
        chapter_point = 1,
        condition_list = {115041},
        draw_repair_cost = 0,
        id = 100504,
        name = "白",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 504,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100505] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {315051},
        chapter_point = 1,
        condition_list = {115051},
        draw_repair_cost = 0,
        id = 100505,
        name = "吞天",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 505,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100506] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {315061, 315062},
        chapter_point = 1,
        condition_list = {115061},
        draw_repair_cost = 0,
        id = 100506,
        name = "噬地",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 506,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100507] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {315071},
        chapter_point = 1,
        condition_list = {115071},
        draw_repair_cost = 0,
        id = 100507,
        name = "魃女",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 507,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100508] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {315081},
        chapter_point = 1,
        condition_list = {115081},
        draw_repair_cost = 0,
        id = 100508,
        name = "魂夕",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 508,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100509] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {315091},
        chapter_point = 1,
        condition_list = {115091},
        draw_repair_cost = 0,
        id = 100509,
        name = "判官",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 509,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100510] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {315101},
        chapter_point = 1,
        condition_list = {115101},
        draw_repair_cost = 0,
        id = 100510,
        name = "奉主夜鹤",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 510,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100511] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {315111},
        chapter_point = 1,
        condition_list = {115111},
        draw_repair_cost = 0,
        id = 100511,
        name = "片雾",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 511,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100512] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {315121},
        chapter_point = 1,
        condition_list = {115121},
        draw_repair_cost = 0,
        id = 100512,
        name = "浮屠僧",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 512,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100513] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {315131},
        chapter_point = 1,
        condition_list = {115131},
        draw_repair_cost = 0,
        id = 100513,
        name = "夜叉",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 513,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [100514] = {
        book_point = 0,
        book_type = 1,
        chapter_list = {315141},
        chapter_point = 1,
        condition_list = {115141},
        draw_repair_cost = 0,
        id = 100514,
        name = "曼珠沙华",
        name_cost = 0,
        name_point = 0,
        repair_point = 0,
        show_number = 0,
        target_id = 514,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

}
