-- ./excel/handbook/handbook.xlsx
return {

    [400001] = {
        book_point = 0,
        book_type = 3,
        chapter_list = {},
        chapter_point = 1,
        condition_list = {400001},
        draw_repair_cost = 0,
        id = 400001,
        name = "仇大富",
        name_cost = 0,
        name_point = 0,
        npc_type = 5038,
        repair_point = 0,
        target_id = 10021,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [400002] = {
        book_point = 0,
        book_type = 3,
        chapter_list = {},
        chapter_point = 1,
        condition_list = {400003},
        draw_repair_cost = 0,
        id = 400002,
        name = "咸鱼飞",
        name_cost = 0,
        name_point = 0,
        npc_type = 5037,
        repair_point = 0,
        target_id = 10020,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [400003] = {
        book_point = 0,
        book_type = 3,
        chapter_list = {},
        chapter_point = 1,
        condition_list = {400005},
        draw_repair_cost = 0,
        id = 400003,
        name = "李铁蛋",
        name_cost = 0,
        name_point = 0,
        npc_type = 5036,
        repair_point = 0,
        target_id = 10019,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [400004] = {
        book_point = 0,
        book_type = 3,
        chapter_list = {},
        chapter_point = 1,
        condition_list = {400007},
        draw_repair_cost = 0,
        id = 400004,
        name = "乔焱",
        name_cost = 0,
        name_point = 0,
        npc_type = 5003,
        repair_point = 0,
        target_id = 10001,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [400005] = {
        book_point = 0,
        book_type = 3,
        chapter_list = {},
        chapter_point = 1,
        condition_list = {400009},
        draw_repair_cost = 0,
        id = 400005,
        name = "丽丝",
        name_cost = 0,
        name_point = 0,
        npc_type = 5056,
        repair_point = 0,
        target_id = 10002,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [400006] = {
        book_point = 0,
        book_type = 3,
        chapter_list = {},
        chapter_point = 1,
        condition_list = {400011},
        draw_repair_cost = 0,
        id = 400006,
        name = "遥",
        name_cost = 0,
        name_point = 0,
        npc_type = 5005,
        repair_point = 0,
        target_id = 10003,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [400007] = {
        book_point = 0,
        book_type = 3,
        chapter_list = {},
        chapter_point = 1,
        condition_list = {400013},
        draw_repair_cost = 0,
        id = 400007,
        name = "飞龙哥",
        name_cost = 0,
        name_point = 0,
        npc_type = 5010,
        repair_point = 0,
        target_id = 10004,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [400008] = {
        book_point = 0,
        book_type = 3,
        chapter_list = {},
        chapter_point = 1,
        condition_list = {400015},
        draw_repair_cost = 0,
        id = 400008,
        name = "邓酒爷",
        name_cost = 0,
        name_point = 0,
        npc_type = 5011,
        repair_point = 0,
        target_id = 10005,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [400009] = {
        book_point = 0,
        book_type = 3,
        chapter_list = {},
        chapter_point = 1,
        condition_list = {400017},
        draw_repair_cost = 0,
        id = 400009,
        name = "荆鸣",
        name_cost = 0,
        name_point = 0,
        npc_type = 5012,
        repair_point = 0,
        target_id = 10006,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [400010] = {
        book_point = 0,
        book_type = 3,
        chapter_list = {},
        chapter_point = 1,
        condition_list = {400019},
        draw_repair_cost = 0,
        id = 400010,
        name = "熊霸",
        name_cost = 0,
        name_point = 0,
        npc_type = 5014,
        repair_point = 0,
        target_id = 10007,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [400011] = {
        book_point = 0,
        book_type = 3,
        chapter_list = {},
        chapter_point = 1,
        condition_list = {400021},
        draw_repair_cost = 0,
        id = 400011,
        name = "甘",
        name_cost = 0,
        name_point = 0,
        npc_type = 5015,
        repair_point = 0,
        target_id = 10008,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [400012] = {
        book_point = 0,
        book_type = 3,
        chapter_list = {},
        chapter_point = 1,
        condition_list = {400023},
        draw_repair_cost = 0,
        id = 400012,
        name = "峰馆长",
        name_cost = 0,
        name_point = 0,
        npc_type = 5016,
        repair_point = 0,
        target_id = 10009,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [400013] = {
        book_point = 0,
        book_type = 3,
        chapter_list = {},
        chapter_point = 1,
        condition_list = {400025},
        draw_repair_cost = 0,
        id = 400013,
        name = "桀修",
        name_cost = 0,
        name_point = 0,
        npc_type = 5017,
        repair_point = 0,
        target_id = 10010,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [400015] = {
        book_point = 0,
        book_type = 3,
        chapter_list = {},
        chapter_point = 1,
        condition_list = {400027},
        draw_repair_cost = 0,
        id = 400015,
        name = "丑无",
        name_cost = 0,
        name_point = 0,
        npc_type = 5020,
        repair_point = 0,
        target_id = 10012,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [400017] = {
        book_point = 0,
        book_type = 3,
        chapter_list = {},
        chapter_point = 1,
        condition_list = {400029},
        draw_repair_cost = 0,
        id = 400017,
        name = "鬼幽子",
        name_cost = 0,
        name_point = 0,
        npc_type = 5023,
        repair_point = 0,
        target_id = 10000,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [400018] = {
        book_point = 0,
        book_type = 3,
        chapter_list = {},
        chapter_point = 1,
        condition_list = {400031},
        draw_repair_cost = 0,
        id = 400018,
        name = "熊猫爷爷",
        name_cost = 0,
        name_point = 0,
        npc_type = 5024,
        repair_point = 0,
        target_id = 10023,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [400019] = {
        book_point = 0,
        book_type = 3,
        chapter_list = {},
        chapter_point = 1,
        condition_list = {400033},
        draw_repair_cost = 0,
        id = 400019,
        name = "绯翼",
        name_cost = 0,
        name_point = 0,
        npc_type = 5026,
        repair_point = 0,
        target_id = 10014,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [400020] = {
        book_point = 0,
        book_type = 3,
        chapter_list = {},
        chapter_point = 1,
        condition_list = {400035},
        draw_repair_cost = 0,
        id = 400020,
        name = "青翼",
        name_cost = 0,
        name_point = 0,
        npc_type = 5027,
        repair_point = 0,
        target_id = 10015,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [400021] = {
        book_point = 0,
        book_type = 3,
        chapter_list = {},
        chapter_point = 1,
        condition_list = {400037},
        draw_repair_cost = 0,
        id = 400021,
        name = "猫蜀黍",
        name_cost = 0,
        name_point = 0,
        npc_type = 5033,
        repair_point = 0,
        target_id = 10016,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [400022] = {
        book_point = 0,
        book_type = 3,
        chapter_list = {},
        chapter_point = 1,
        condition_list = {400039},
        draw_repair_cost = 0,
        id = 400022,
        name = "喵小萌",
        name_cost = 0,
        name_point = 0,
        npc_type = 5034,
        repair_point = 0,
        target_id = 10017,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [400023] = {
        book_point = 0,
        book_type = 3,
        chapter_list = {},
        chapter_point = 1,
        condition_list = {400041},
        draw_repair_cost = 0,
        id = 400023,
        name = "白婆婆",
        name_cost = 0,
        name_point = 0,
        npc_type = 5035,
        repair_point = 0,
        target_id = 10018,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [400024] = {
        book_point = 0,
        book_type = 3,
        chapter_list = {},
        chapter_point = 1,
        condition_list = {400043},
        draw_repair_cost = 0,
        id = 400024,
        name = "克瑞斯汀",
        name_cost = 0,
        name_point = 0,
        npc_type = 5048,
        repair_point = 0,
        target_id = 10024,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [400025] = {
        book_point = 0,
        book_type = 3,
        chapter_list = {},
        chapter_point = 1,
        condition_list = {400045},
        draw_repair_cost = 0,
        id = 400025,
        name = "链",
        name_cost = 0,
        name_point = 0,
        npc_type = 5039,
        repair_point = 0,
        target_id = 10022,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

    [400026] = {
        book_point = 0,
        book_type = 3,
        chapter_list = {},
        chapter_point = 1,
        condition_list = {400047},
        draw_repair_cost = 0,
        id = 400026,
        name = "扳尾",
        name_cost = 0,
        name_point = 0,
        npc_type = 5021,
        repair_point = 0,
        target_id = 10013,
        unlock_cost_key = 0,
        unlock_point = 0,
    },

}
