-- ./excel/huodong/treasure/npc.xlsx
return {

    [63001] = {
        dialogId = 0,
        diglogface = 0,
        event = 100,
        grade = 1,
        id = 63001,
        lifeTime = 0,
        modelId = 404,
        mutateColor = {},
        mutateTexture = 0,
        name = "被挖出的绿狸",
        nameType = 1,
        ornamentId = 0,
        refreshCycle = 0,
        reuse = 1,
        rotateY = -145.0,
        scale = 1.0,
        sceneId = 101000,
        title = "",
        tollgateId = 0,
        type = 3,
        wpmodel = 0,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },

    [63002] = {
        dialogId = 0,
        diglogface = 0,
        event = 101,
        grade = 1,
        id = 63002,
        lifeTime = 0,
        modelId = 1150,
        mutateColor = {},
        mutateTexture = 0,
        name = "嗜赌的飞龙哥",
        nameType = 1,
        ornamentId = 0,
        refreshCycle = 0,
        reuse = 1,
        rotateY = -145.0,
        scale = 1.0,
        sceneId = 101000,
        title = "",
        tollgateId = 0,
        type = 3,
        wpmodel = 0,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },

    [63003] = {
        dialogId = 0,
        diglogface = 0,
        event = 300,
        grade = 1,
        id = 63003,
        lifeTime = 0,
        modelId = 1150,
        mutateColor = {},
        mutateTexture = 0,
        name = "飞龙哥的幻象",
        nameType = 1,
        ornamentId = 0,
        refreshCycle = 0,
        reuse = 1,
        rotateY = -145.0,
        scale = 1.0,
        sceneId = 101000,
        title = "",
        tollgateId = 0,
        type = 3,
        wpmodel = 0,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },

    [63004] = {
        dialogId = 0,
        diglogface = 0,
        event = 400,
        grade = 1,
        id = 63004,
        lifeTime = 0,
        modelId = 1150,
        mutateColor = {},
        mutateTexture = 0,
        name = "飞龙哥的幻象",
        nameType = 1,
        ornamentId = 0,
        refreshCycle = 0,
        reuse = 1,
        rotateY = -145.0,
        scale = 1.0,
        sceneId = 101000,
        title = "",
        tollgateId = 0,
        type = 3,
        wpmodel = 0,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },

}
