-- ./excel/reward/fieldboss.xlsx
return {

    [1] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 1,
        item = {{["rate"] = 10000, ["idx"] = 1}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [2] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 2,
        item = {{["rate"] = 10000, ["idx"] = 2}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [3] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 3,
        item = {{["rate"] = 10000, ["idx"] = 3}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [4] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 4,
        item = {{["rate"] = 10000, ["idx"] = 4}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [5] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 5,
        item = {{["rate"] = 10000, ["idx"] = 5}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [6] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 6,
        item = {{["rate"] = 10000, ["idx"] = 6}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [7] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 7,
        item = {{["rate"] = 10000, ["idx"] = 7}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [8] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 8,
        item = {{["rate"] = 10000, ["idx"] = 8}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [9] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 9,
        item = {{["rate"] = 10000, ["idx"] = 9}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [10] = {
        coin = "77777",
        desc = "",
        exp = "10000",
        id = 10,
        item = {},
        name = "",
        partnerexp = "500",
        rate = 10000,
        sid = 0,
    },

    [500] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 500,
        item = {{["rate"] = 10000, ["idx"] = 500}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [501] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 501,
        item = {{["rate"] = 10000, ["idx"] = 501}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [502] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 502,
        item = {{["rate"] = 10000, ["idx"] = 502}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [503] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 503,
        item = {{["rate"] = 10000, ["idx"] = 503}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [504] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 504,
        item = {{["rate"] = 10000, ["idx"] = 504}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [505] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 505,
        item = {{["rate"] = 10000, ["idx"] = 505}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [506] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 506,
        item = {{["rate"] = 10000, ["idx"] = 506}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [507] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 507,
        item = {{["rate"] = 10000, ["idx"] = 507}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [508] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 508,
        item = {{["rate"] = 10000, ["idx"] = 508}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [509] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 509,
        item = {{["rate"] = 10000, ["idx"] = 509}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [510] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 510,
        item = {{["rate"] = 10000, ["idx"] = 510}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [511] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 511,
        item = {{["rate"] = 10000, ["idx"] = 511}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [512] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 512,
        item = {{["rate"] = 10000, ["idx"] = 512}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [513] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 513,
        item = {{["rate"] = 10000, ["idx"] = 513}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [514] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 514,
        item = {{["rate"] = 10000, ["idx"] = 514}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [515] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 515,
        item = {{["rate"] = 10000, ["idx"] = 515}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [516] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 516,
        item = {{["rate"] = 10000, ["idx"] = 516}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [517] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 517,
        item = {{["rate"] = 10000, ["idx"] = 517}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [518] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 518,
        item = {{["rate"] = 10000, ["idx"] = 518}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [519] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 519,
        item = {{["rate"] = 10000, ["idx"] = 519}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [520] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 520,
        item = {{["rate"] = 10000, ["idx"] = 520}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [521] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 521,
        item = {{["rate"] = 10000, ["idx"] = 521}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [522] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 522,
        item = {{["rate"] = 10000, ["idx"] = 522}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [523] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 523,
        item = {{["rate"] = 10000, ["idx"] = 523}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [524] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 524,
        item = {{["rate"] = 10000, ["idx"] = 524}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [525] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 525,
        item = {{["rate"] = 10000, ["idx"] = 525}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [526] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 526,
        item = {{["rate"] = 10000, ["idx"] = 526}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [527] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 527,
        item = {{["rate"] = 10000, ["idx"] = 527}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [528] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 528,
        item = {{["rate"] = 10000, ["idx"] = 528}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

    [529] = {
        coin = "0",
        desc = "",
        exp = "0",
        id = 529,
        item = {{["rate"] = 10000, ["idx"] = 529}},
        name = "",
        partnerexp = "0",
        rate = 10000,
        sid = 0,
    },

}
