-- ./excel/reward/onlinegift.xlsx
return {

    [1] = {
        amount = 2,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1001,
        ratio = 100,
        sid = "10030",
        sys = 0,
    },

    [2] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1006,
        ratio = 100,
        sid = "1002(value=1000)",
        sys = 0,
    },

    [3] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1011,
        ratio = 100,
        sid = "27402",
        sys = 0,
    },

    [4] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1016,
        ratio = 100,
        sid = "27405",
        sys = 0,
    },

    [5] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1021,
        ratio = 100,
        sid = "27408",
        sys = 0,
    },

    [6] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1026,
        ratio = 100,
        sid = "27411",
        sys = 0,
    },

    [7] = {
        amount = 3,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1002,
        ratio = 100,
        sid = "10030",
        sys = 0,
    },

    [8] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1007,
        ratio = 100,
        sid = "1002(value=3000)",
        sys = 0,
    },

    [9] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1012,
        ratio = 100,
        sid = "18002",
        sys = 0,
    },

    [10] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1017,
        ratio = 100,
        sid = "18000",
        sys = 0,
    },

    [11] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1022,
        ratio = 100,
        sid = "18500",
        sys = 0,
    },

    [12] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1027,
        ratio = 100,
        sid = "18300",
        sys = 0,
    },

    [13] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1003,
        ratio = 100,
        sid = "1003(value=10)",
        sys = 0,
    },

    [14] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1008,
        ratio = 100,
        sid = "1002(value=4000)",
        sys = 0,
    },

    [15] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1013,
        ratio = 100,
        sid = "27403",
        sys = 0,
    },

    [16] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1018,
        ratio = 100,
        sid = "27406",
        sys = 0,
    },

    [17] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1023,
        ratio = 100,
        sid = "27409",
        sys = 0,
    },

    [18] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1028,
        ratio = 100,
        sid = "27412",
        sys = 0,
    },

    [19] = {
        amount = 5,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1004,
        ratio = 100,
        sid = "10030",
        sys = 0,
    },

    [20] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1009,
        ratio = 100,
        sid = "1002(value=5000)",
        sys = 0,
    },

    [21] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1014,
        ratio = 100,
        sid = "1003(value=80)",
        sys = 0,
    },

    [22] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1019,
        ratio = 100,
        sid = "10024",
        sys = 0,
    },

    [23] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1024,
        ratio = 100,
        sid = "1003(value=30)",
        sys = 0,
    },

    [24] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1029,
        ratio = 100,
        sid = "1003(value=15)",
        sys = 0,
    },

    [25] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1005,
        ratio = 100,
        sid = "10024",
        sys = 0,
    },

    [26] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1010,
        ratio = 100,
        sid = "1002(value=8000)",
        sys = 0,
    },

    [27] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1015,
        ratio = 100,
        sid = "1003(value=200)",
        sys = 0,
    },

    [28] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1020,
        ratio = 100,
        sid = "1003(value=100)",
        sys = 0,
    },

    [29] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1025,
        ratio = 100,
        sid = "1003(value=40)",
        sys = 0,
    },

    [30] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1030,
        ratio = 100,
        sid = "1003(value=20)",
        sys = 0,
    },

}
