-- ./excel/reward/story.xlsx
return {

    [1] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1001,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [2] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1002,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [3] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1003,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [4] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1004,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [5] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1005,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [6] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1006,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [7] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1007,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [8] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1008,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [9] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1009,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [10] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1010,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [11] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1011,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [12] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1012,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [13] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1015,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [14] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1016,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [15] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1017,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [16] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1018,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [17] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1019,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [18] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1020,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [19] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1021,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [20] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1022,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [21] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1023,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [22] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1026,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [23] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1027,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [24] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1028,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [25] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1029,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [26] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1030,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [27] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1031,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [28] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1032,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [29] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1033,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [30] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1034,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [31] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1035,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [32] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1038,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [33] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1039,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [34] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1040,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [35] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1041,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [36] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1042,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [37] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1043,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [38] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1053,
        ratio = 100,
        sid = "10040",
        sys = 0,
    },

    [39] = {
        amount = 3,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 1192,
        ratio = 100,
        sid = "14001",
        sys = 0,
    },

    [40] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 2000,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [41] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 3080,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [42] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 3087,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

    [43] = {
        amount = 1,
        bind = 0,
        equip_reward = "",
        grade = 1,
        idx = 3096,
        ratio = 100,
        sid = "10022",
        sys = 0,
    },

}
