-- ./excel/task/daily/taskdialog.xlsx
return {

    [1] = {
        content = "噗噗，你来了，可惜迟了。",
        dialog_id = 2000,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "5018,0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [2] = {
        content = "难道发生了不可挽回的事情？",
        dialog_id = 2000,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "85005,0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [3] = {
        content = "有客人？吃了吗？我们刚刚把饭吃完了，给你下个面？",
        dialog_id = 2000,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "85005,0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [4] = {
        content = "我不饿，请问你是花老板负责入货的伙计吗？",
        dialog_id = 2000,
        finish_event = "",
        last_action = {},
        next = "5",
        pre_id_list = "85005,0",
        status = 2,
        sub_talker_list = "",
        subid = 4,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [5] = {
        content = "是的，这两天沙尘暴不能运货，今天风沙停了正准备启程呢。",
        dialog_id = 2000,
        finish_event = "",
        last_action = {},
        next = "6",
        pre_id_list = "85005,0",
        status = 2,
        sub_talker_list = "",
        subid = 5,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [6] = {
        content = "正好，我送你回去吧，花老板很担心呢！",
        dialog_id = 2000,
        finish_event = "",
        last_action = {},
        next = "7",
        pre_id_list = "85005,0",
        status = 2,
        sub_talker_list = "",
        subid = 6,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [7] = {
        content = "不送啦噗噗。",
        dialog_id = 2000,
        finish_event = "TARGET5007,STARTTRACE,_SUBMIT",
        last_action = {},
        next = "0",
        pre_id_list = "5018",
        status = 2,
        sub_talker_list = "",
        subid = 7,
        type = 3,
        ui_mode = 2,
        voice = 0,
    },

    [8] = {
        content = "辛苦你跑一趟，这点金币你拿去，算是这事的酬劳。",
        dialog_id = 2000,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "5007,0",
        status = 1,
        sub_talker_list = "",
        subid = 8,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [9] = {
        content = "嘿嘿，不辛苦不辛苦。",
        dialog_id = 2000,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "5007,0",
        status = 1,
        sub_talker_list = "",
        subid = 9,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [10] = {
        content = "哎呀呀呀~好头痛啊！为什么总是这样子！",
        dialog_id = 2001,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "85000,0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [11] = {
        content = "白大人你怎么了？发生什么事？",
        dialog_id = 2001,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "85000,0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [12] = {
        content = "你知道天底下没有白吃的午餐这个道理吗？",
        dialog_id = 2001,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "85000,0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [13] = {
        content = "当然！三岁小孩都能懂呢！",
        dialog_id = 2001,
        finish_event = "",
        last_action = {},
        next = "5",
        pre_id_list = "85000,0",
        status = 2,
        sub_talker_list = "",
        subid = 4,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [14] = {
        content = "说得好，我决定要郑重地将这个案件交给你！你一定好好好给我盯着这名惯犯！有没有决心和信心！",
        dialog_id = 2001,
        finish_event = "",
        last_action = {},
        next = "6",
        pre_id_list = "85000,0",
        status = 2,
        sub_talker_list = "",
        subid = 5,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [15] = {
        content = "有！请大人放心，我一定负责到底，有锅我背！",
        dialog_id = 2001,
        finish_event = "",
        last_action = {},
        next = "7",
        pre_id_list = "85000,0",
        status = 2,
        sub_talker_list = "",
        subid = 6,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [16] = {
        content = "有你这句话，我就放心了。",
        dialog_id = 2001,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "85000,0",
        status = 2,
        sub_talker_list = "",
        subid = 7,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [17] = {
        content = "这位可爱的小姐姐，你已经吃第四碗面了，不会撑吗？",
        dialog_id = 2001,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "85038,85001",
        status = 1,
        sub_talker_list = "",
        subid = 8,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [18] = {
        content = "人家才吃了四分饱，请再来一碗！",
        dialog_id = 2001,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "85038,85001",
        status = 1,
        sub_talker_list = "",
        subid = 9,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [19] = {
        content = "生意难做，小姐姐不如先把账结了？",
        dialog_id = 2001,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "85038,85001",
        status = 1,
        sub_talker_list = "",
        subid = 10,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [20] = {
        content = "账？什么账？你又没有说吃面要钱！人家不吃了，走……",
        dialog_id = 2001,
        finish_event = "",
        last_action = {},
        next = "5",
        pre_id_list = "85038,85001",
        status = 1,
        sub_talker_list = "",
        subid = 11,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [21] = {
        content = "走？来人呐！有人吃霸王餐啦！",
        dialog_id = 2001,
        finish_event = "",
        last_action = {},
        next = "6",
        pre_id_list = "85038,85001",
        status = 1,
        sub_talker_list = "",
        subid = 12,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [22] = {
        content = "人家没有！",
        dialog_id = 2001,
        finish_event = "",
        last_action = {{["content"] = "呦呵捉到你了！", ["event"] = "F10001"}, {["content"] = "当做没看到！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 13,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [23] = {
        content = "不好意思又要麻烦你了，跟以前一样会给你报酬的。",
        dialog_id = 2002,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "85003,0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [24] = {
        content = "哇，好香，肯定是今年的新酿。这么有心意的礼物，花老板亲自送不是更好吗？",
        dialog_id = 2002,
        finish_event = "",
        last_action = {{["content"] = "搞怪姿势", ["event"] = "social;10002;2"}, {["content"] = "跳舞助兴", ["event"] = "social;10003;14"}},
        next = "3",
        pre_id_list = "85003,0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [25] = {
        content = "老头脾气那么臭我才不要送，你去矿场那边应该能找到他的。好了启程吧，小心别摔了！",
        dialog_id = 2002,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "85003,0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [26] = {
        content = "小意思安啦安啦！",
        dialog_id = 2002,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "85003,0",
        status = 2,
        sub_talker_list = "",
        subid = 4,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [27] = {
        content = "这是花常酒花老板托我给您送的，您收好。",
        dialog_id = 2002,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "85004,0",
        status = 1,
        sub_talker_list = "",
        subid = 5,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [28] = {
        content = "(把礼盒推回)不收！给我原路退回去，嫌碍事就丢掉！",
        dialog_id = 2002,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "85004,0",
        status = 1,
        sub_talker_list = "",
        subid = 6,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [29] = {
        content = "哎哎哎拿稳！差点就掉了，这么好的新酿不要浪费啊！",
        dialog_id = 2002,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "85004,0",
        status = 1,
        sub_talker_list = "",
        subid = 7,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [30] = {
        content = "把东西拿走！我不要！你回去告诉那个逆女，送多少我就丢多少！滚滚滚！",
        dialog_id = 2002,
        finish_event = "",
        last_action = {},
        next = "5",
        pre_id_list = "85004,0",
        status = 1,
        sub_talker_list = "",
        subid = 8,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [31] = {
        content = "(把礼盒推了一下发现对方抓的很牢)哎哎哎别推别推，我走我走，您收好再见！老馆长嘴里说不喜欢身体还是很诚实的嘛，嘿。",
        dialog_id = 2002,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "85004,0",
        status = 1,
        sub_talker_list = "",
        subid = 9,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [32] = {
        content = "这些钱就当是我买下的，以后不许再过来了！",
        dialog_id = 2002,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "85004,0",
        status = 1,
        sub_talker_list = "",
        subid = 10,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [33] = {
        content = "知不知道我很忙的，你找我什么事？话说在前头我不陪熊孩子玩。",
        dialog_id = 2003,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "85008,0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [34] = {
        content = "正经事！耳朵别过来，啧，快呀！",
        dialog_id = 2003,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "85008,0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [35] = {
        content = "行行行，聋了，说话小声点，别扭我耳朵！",
        dialog_id = 2003,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "85008,0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [36] = {
        content = "枫竹林……有鬼……",
        dialog_id = 2003,
        finish_event = "",
        last_action = {},
        next = "5",
        pre_id_list = "85008,0",
        status = 2,
        sub_talker_list = "",
        subid = 4,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [37] = {
        content = "明明昨晚才掏过耳朵，我没有听错吧？",
        dialog_id = 2003,
        finish_event = "",
        last_action = {},
        next = "6",
        pre_id_list = "85008,0",
        status = 2,
        sub_talker_list = "",
        subid = 5,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [38] = {
        content = "就是枫竹林那棵竹子，他肯定对执夷哥下咒了，执夷哥天天去找他都不跟我玩！你一定要把他逮捕了关进监牢去，不然我就叫阿大把你拍扁！",
        dialog_id = 2003,
        finish_event = "",
        last_action = {},
        next = "7",
        pre_id_list = "85008,0",
        status = 2,
        sub_talker_list = "",
        subid = 6,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [39] = {
        content = "停停停，不要吵！跟上，我们就去青竹家问他是不是鬼！",
        dialog_id = 2003,
        finish_event = "TARGET85010,STARTTRACE,_SUBMIT",
        last_action = {},
        next = "0",
        pre_id_list = "85008,0",
        status = 2,
        sub_talker_list = "",
        subid = 7,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [40] = {
        content = "你们怎么来了？",
        dialog_id = 2003,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "85009",
        status = 1,
        sub_talker_list = "",
        subid = 8,
        type = 3,
        ui_mode = 2,
        voice = 0,
    },

    [41] = {
        content = "大魔头、恶鬼，吃我一剑还我执夷哥！",
        dialog_id = 2003,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "85008,85010",
        status = 1,
        sub_talker_list = "",
        subid = 9,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [42] = {
        content = "（用一根手指抵住乱晃的执阳）哼。",
        dialog_id = 2003,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "85008,85010",
        status = 1,
        sub_talker_list = "",
        subid = 10,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [43] = {
        content = "执阳偷偷写信给我，说青竹是鬼，诅咒了……（看了执夷一眼）嗯，所以要我逮捕他，这样他就能跟你一起玩。噢当然，青竹肯定不是鬼，我没有别的意思就是送小孩过来。",
        dialog_id = 2003,
        finish_event = "",
        last_action = {},
        next = "5",
        pre_id_list = "85009,0",
        status = 1,
        sub_talker_list = "",
        subid = 11,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [44] = {
        content = "你这个叛徒！下次有什么事我都不告诉你了！阿大我们走，青竹鬼你等着瞧！",
        dialog_id = 2003,
        finish_event = "",
        last_action = {},
        next = "6",
        pre_id_list = "85008,0",
        status = 1,
        sub_talker_list = "",
        subid = 12,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [45] = {
        content = "执阳！我真的是来种竹子的，种好就走！唉，真是不好意思，小孩子淘气，这点金币当车马费。",
        dialog_id = 2003,
        finish_event = "",
        last_action = {},
        next = "7",
        pre_id_list = "85008,85009",
        status = 1,
        sub_talker_list = "",
        subid = 13,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [46] = {
        content = "刚刚执阳指挥阿大又踩踏了一大片幼林，加刑3个月。",
        dialog_id = 2003,
        finish_event = "",
        last_action = {},
        next = "8",
        pre_id_list = "85010,85009",
        status = 1,
        sub_talker_list = "",
        subid = 14,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [47] = {
        content = "没问题没问题，保证随传随到。",
        dialog_id = 2003,
        finish_event = "",
        last_action = {},
        next = "9",
        pre_id_list = "85010,85009",
        status = 1,
        sub_talker_list = "",
        subid = 15,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [48] = {
        content = "……",
        dialog_id = 2003,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 16,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [49] = {
        content = "演唱会结束了，让我偷偷潜入后台……",
        dialog_id = 2004,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [50] = {
        content = "那个鬼鬼祟祟的人是谁？保安！保安！",
        dialog_id = 2004,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [51] = {
        content = "嘘嘘，是我是我。我们之前在枫竹林见过的。",
        dialog_id = 2004,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "85012,0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [52] = {
        content = "你在这里查案吗？我的演唱会……",
        dialog_id = 2004,
        finish_event = "",
        last_action = {},
        next = "5",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 4,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [53] = {
        content = "不是查案，我的婆婆很喜欢你们，希望你们能给我一张亲笔签名的海报！",
        dialog_id = 2004,
        finish_event = "",
        last_action = {},
        next = "6",
        pre_id_list = "85012,0",
        status = 2,
        sub_talker_list = "",
        subid = 5,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [54] = {
        content = "当然可以！这场演唱会还有一些纪念版海报，给你，替我们向婆婆问好哟！",
        dialog_id = 2004,
        finish_event = "",
        last_action = {},
        next = "7",
        pre_id_list = "85011",
        status = 2,
        sub_talker_list = "",
        subid = 6,
        type = 3,
        ui_mode = 2,
        voice = 0,
    },

    [55] = {
        content = "非常感谢！",
        dialog_id = 2004,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "85011,0",
        status = 2,
        sub_talker_list = "",
        subid = 7,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [56] = {
        content = "唉……我竟然没有买到比翼鸟的演唱会门票，门口那么多人这把老骨头又挤不进去……",
        dialog_id = 2004,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "5035,0",
        status = 1,
        sub_talker_list = "",
        subid = 8,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [57] = {
        content = "婆婆别伤心，你看这是什么。",
        dialog_id = 2004,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "5035,0",
        status = 1,
        sub_talker_list = "",
        subid = 9,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [58] = {
        content = "海报？比翼鸟全身像绝版海报！啊啊啊每一张都好帅！这里还写了祝白婆婆身体健康！",
        dialog_id = 2004,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "5035,0",
        status = 1,
        sub_talker_list = "",
        subid = 10,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [59] = {
        content = "嘿嘿，婆婆下次我一定帮你抢到演唱会的票！",
        dialog_id = 2004,
        finish_event = "",
        last_action = {},
        next = "5",
        pre_id_list = "5035,0",
        status = 1,
        sub_talker_list = "",
        subid = 11,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [60] = {
        content = "算婆婆没白疼你！",
        dialog_id = 2004,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "5035,0",
        status = 1,
        sub_talker_list = "",
        subid = 12,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [61] = {
        content = "您好，请问今天有钓到鲜鱼吗？我想买点给婆婆。",
        dialog_id = 2005,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "85014,0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [62] = {
        content = "今天运气不错，钓到很多鱼每条都很新鲜还很肥！",
        dialog_id = 2005,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "85014,0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [63] = {
        content = "婆婆最喜欢沙丁鱼了……请问有沙丁鱼吗？",
        dialog_id = 2005,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "85014,0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [64] = {
        content = "有，都帮你装好了！",
        dialog_id = 2005,
        finish_event = "",
        last_action = {},
        next = "5",
        pre_id_list = "85014,0",
        status = 2,
        sub_talker_list = "",
        subid = 4,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [65] = {
        content = "谢啦！",
        dialog_id = 2005,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "85014,0",
        status = 2,
        sub_talker_list = "",
        subid = 5,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [66] = {
        content = "婆婆，你猜猜这是什么？",
        dialog_id = 2005,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "5035,0",
        status = 1,
        sub_talker_list = "",
        subid = 6,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [67] = {
        content = "远远就闻到鱼腥味了，这个问题难不倒婆婆，我猜肯定是沙丁鱼。",
        dialog_id = 2005,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "5035,0",
        status = 1,
        sub_talker_list = "",
        subid = 7,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [68] = {
        content = "好想念婆婆最拿手的豆腐沙丁鱼汤啊！",
        dialog_id = 2005,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "5035,0",
        status = 1,
        sub_talker_list = "",
        subid = 8,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [69] = {
        content = "就知道吃，等等吧！",
        dialog_id = 2005,
        finish_event = "",
        last_action = {},
        next = "5",
        pre_id_list = "5035,0",
        status = 1,
        sub_talker_list = "",
        subid = 9,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [70] = {
        content = "耶，婆婆我最爱你啦！",
        dialog_id = 2005,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "5035,0",
        status = 1,
        sub_talker_list = "",
        subid = 10,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [71] = {
        content = "你上次不是说过要装些包子给帝都的朋友吃吗，不会忘记了吧。",
        dialog_id = 2006,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [72] = {
        content = "是啊，我这不是来了。每样拿手的都给5个哈！",
        dialog_id = 2006,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "5034,0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [73] = {
        content = "5个这么少！做宣传都不够！小萌给他每样10个，叔不收你的钱，帮猫饭店好好宣传！",
        dialog_id = 2006,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "85017",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 3,
        ui_mode = 2,
        voice = 0,
    },

    [74] = {
        content = "保证完成任务！",
        dialog_id = 2006,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "85017,0",
        status = 2,
        sub_talker_list = "",
        subid = 4,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [75] = {
        content = "哇！又软又香，你们家的包子好好吃！",
        dialog_id = 2006,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0 ",
        status = 1,
        sub_talker_list = "",
        subid = 5,
        type = 2,
        ui_mode = 2,
        voice = 0,
    },

    [76] = {
        content = "这是八门村猫饭店的特制手工包子，认准猫咪形状，别家吃不到的！",
        dialog_id = 2006,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "85018,0",
        status = 1,
        sub_talker_list = "",
        subid = 6,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [77] = {
        content = "真好吃，我让其他人也尝尝！八门村猫饭店吗？",
        dialog_id = 2006,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "85018,0",
        status = 1,
        sub_talker_list = "",
        subid = 7,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [78] = {
        content = "对对对，手工包子！嘿，任务完成！",
        dialog_id = 2006,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "85018,0",
        status = 1,
        sub_talker_list = "",
        subid = 8,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [79] = {
        content = "她喜欢我她不喜欢我她喜欢我她不喜欢我，啊……她不喜欢我！为什么！",
        dialog_id = 2007,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "85019,0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [80] = {
        content = "别撒别撒，刚刚才打扫过怎么又一地的花瓣了，黑大人会生气的。",
        dialog_id = 2007,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "85019,0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [81] = {
        content = "她已经生气过了，这些花，都是她撕碎的，我只是捡了残存的一朵……",
        dialog_id = 2007,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "85019,0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [82] = {
        content = "可能黑大人不太喜欢黑玫瑰，白大人你别伤心。",
        dialog_id = 2007,
        finish_event = "",
        last_action = {},
        next = "5",
        pre_id_list = "85019,0",
        status = 2,
        sub_talker_list = "",
        subid = 4,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [83] = {
        content = "你帮我一个忙，报酬丰厚哦！ ",
        dialog_id = 2007,
        finish_event = "",
        last_action = {},
        next = "6",
        pre_id_list = "85019,0",
        status = 2,
        sub_talker_list = "",
        subid = 5,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [84] = {
        content = "成交！",
        dialog_id = 2007,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "85019,0",
        status = 2,
        sub_talker_list = "",
        subid = 6,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [85] = {
        content = "这次换成热情似火的红玫瑰肯定没问题了吧！",
        dialog_id = 2007,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 7,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [86] = {
        content = "阿嚏！阿嚏！阿嚏！我命令你赶紧把花给我拿开！",
        dialog_id = 2007,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "85020",
        status = 1,
        sub_talker_list = "",
        subid = 8,
        type = 3,
        ui_mode = 2,
        voice = 0,
    },

    [87] = {
        content = "不是，黑大人你先看看，里面有张小卡片噢……",
        dialog_id = 2007,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "85020,0",
        status = 1,
        sub_talker_list = "",
        subid = 9,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [88] = {
        content = "（把花丢远）啊啊啊，难受死了，我要洗手！你也是，不洗手不要靠近我！",
        dialog_id = 2007,
        finish_event = "",
        last_action = {},
        next = "5",
        pre_id_list = "85020,0",
        status = 1,
        sub_talker_list = "",
        subid = 10,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [89] = {
        content = "还好我准备了巧克力，黑大人……",
        dialog_id = 2007,
        finish_event = "",
        last_action = {},
        next = "6",
        pre_id_list = "85020,0",
        status = 1,
        sub_talker_list = "",
        subid = 11,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [90] = {
        content = "阿嚏阿嚏！再不滚开别怪我不客气！",
        dialog_id = 2007,
        finish_event = "",
        last_action = {},
        next = "7",
        pre_id_list = "85020,0",
        status = 1,
        sub_talker_list = "",
        subid = 12,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [91] = {
        content = "我滚！别动手我错了！",
        dialog_id = 2007,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "85020,0",
        status = 1,
        sub_talker_list = "",
        subid = 13,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [92] = {
        content = "你走来走去做什么，眼都花了！去，帮我把今年武道大会的通告交给矿石之城的武馆长峰！",
        dialog_id = 2008,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "85021,0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [93] = {
        content = "是是是，遵命女王大人。",
        dialog_id = 2008,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "85021,0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [94] = {
        content = "资料收到！",
        dialog_id = 2008,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "5016",
        status = 1,
        sub_talker_list = "",
        subid = 3,
        type = 3,
        ui_mode = 2,
        voice = 0,
    },

    [95] = {
        content = "你走来走去做什么，眼都花了！去，替我把药监资料送给矿石之城的医师甘。",
        dialog_id = 2009,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "85023,0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [96] = {
        content = "是是是",
        dialog_id = 2009,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "85023,0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [97] = {
        content = "哟，这回不是白大人来送资料了？",
        dialog_id = 2009,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "5015,0",
        status = 1,
        sub_talker_list = "",
        subid = 3,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [98] = {
        content = "白大人已经被丢去打扫花圃了……",
        dialog_id = 2009,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "5015,0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [99] = {
        content = "哈哈，黑大人还是那么雷厉风行啊！",
        dialog_id = 2009,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "5015,0",
        status = 1,
        sub_talker_list = "",
        subid = 5,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [100] = {
        content = "刚刚开会决定由我们接管矿石之城的护卫队，因为人手问题总统决定雇用原本的队员，帝都每个季度都会派发物资前往支援。你听懂了吗？",
        dialog_id = 2010,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "85024,0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [101] = {
        content = "我肚子突然有点痛……",
        dialog_id = 2010,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "85024,0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [102] = {
        content = "既然听懂了就马上出发！",
        dialog_id = 2010,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "85024,0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [103] = {
        content = "物资收到，感谢指挥部的关怀！",
        dialog_id = 2010,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "85028,0",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [104] = {
        content = "你高兴就好，能不能告诉我厕所在哪……",
        dialog_id = 2010,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "85028,0",
        status = 1,
        sub_talker_list = "",
        subid = 5,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [105] = {
        content = "矿石之城条件比较艰苦，大人你可以选个沙丘……",
        dialog_id = 2010,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "85028,0",
        status = 1,
        sub_talker_list = "",
        subid = 6,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [106] = {
        content = "好的再见。",
        dialog_id = 2010,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "85028,0",
        status = 1,
        sub_talker_list = "",
        subid = 7,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [107] = {
        content = "修行那么久总要有点长进，你跟白打一场看看。",
        dialog_id = 2011,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "85025,0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [108] = {
        content = "黑你坐这里，吃点水晶葡萄，还有红茶。",
        dialog_id = 2011,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "85025,85026",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [109] = {
        content = "嗯，不错，开始吧。",
        dialog_id = 2011,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "85025,85026",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [110] = {
        content = "……",
        dialog_id = 2011,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "85025,0",
        status = 2,
        sub_talker_list = "",
        subid = 4,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [111] = {
        content = "我让你十招，来吧！",
        dialog_id = 2011,
        finish_event = "",
        last_action = {{["content"] = "少看不起人！", ["event"] = "F10002"}, {["content"] = "大神饶命！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "85026",
        status = 1,
        sub_talker_list = "",
        subid = 5,
        type = 3,
        ui_mode = 2,
        voice = 0,
    },

    [112] = {
        content = "你又搞什么飞机！人呢绑哪里去了！",
        dialog_id = 2012,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "85029,0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [113] = {
        content = "我告诉你，这次一定要把他捉住，机不可失失不再来呀！",
        dialog_id = 2012,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "85029,0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [114] = {
        content = "你跟我过来！",
        dialog_id = 2012,
        finish_event = "TARGET85030,STARTTRACE,_SUBMIT",
        last_action = {},
        next = "0",
        pre_id_list = "85029,0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [115] = {
        content = "跑去哪里了，不是口渴吗，喝什么？",
        dialog_id = 2012,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "85030,85029",
        status = 1,
        sub_talker_list = "",
        subid = 4,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [116] = {
        content = "你看我遇到了谁！咳咳！咳咳咳！",
        dialog_id = 2012,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "85030,85029",
        status = 1,
        sub_talker_list = "",
        subid = 5,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [117] = {
        content = "喉咙不舒服？那喝雪梨水吧。热不热，把汗擦擦。",
        dialog_id = 2012,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "85030,85029",
        status = 1,
        sub_talker_list = "",
        subid = 6,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [118] = {
        content = "我不要雪梨水，要喝汽水，听说城里人都喝汽水！",
        dialog_id = 2012,
        finish_event = "",
        last_action = {},
        next = "5",
        pre_id_list = "85030,85029",
        status = 1,
        sub_talker_list = "",
        subid = 7,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [119] = {
        content = "那我们提几箱汽水回去，不知道新兵大人要喝什么？我们刚刚进城玩几天就回去了。",
        dialog_id = 2012,
        finish_event = "",
        last_action = {},
        next = "6",
        pre_id_list = "85030,85029",
        status = 1,
        sub_talker_list = "",
        subid = 8,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [120] = {
        content = "(完全无视执阳的疯狂眨眼和咳嗽)不用了，我还有事，你们玩得开心。",
        dialog_id = 2012,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "85030,0",
        status = 1,
        sub_talker_list = "",
        subid = 9,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [121] = {
        content = "不好意思麻烦你了，城里我只认识你一个人。",
        dialog_id = 2013,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "85031,0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [122] = {
        content = "没关系，执阳呢不跟来了吗？",
        dialog_id = 2013,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "85031,0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [123] = {
        content = "他说要监视青竹不来了，执阳口硬心软其实就是想多个玩伴。平时没少给青竹添麻烦，想买个礼物送给他，不知道选什么怕被骗有个熟人带路比较好。",
        dialog_id = 2013,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "85031,0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [124] = {
        content = "你们感情真好，行，我来帮你看看。嗯……左边有糕点店，右边有食品店，你们喜欢哪种？",
        dialog_id = 2013,
        finish_event = "",
        last_action = {},
        next = "5",
        pre_id_list = "85031,0",
        status = 2,
        sub_talker_list = "",
        subid = 4,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [125] = {
        content = "我看到街尾好像是花店？不知道有没有竹子的幼苗？青竹一定很喜欢，我去那里买吧，今天谢谢你啦！",
        dialog_id = 2013,
        finish_event = "",
        last_action = {},
        next = "6",
        pre_id_list = "85031,0",
        status = 2,
        sub_talker_list = "",
        subid = 5,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [126] = {
        content = "你们高兴就好。",
        dialog_id = 2013,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "85031,0",
        status = 2,
        sub_talker_list = "",
        subid = 6,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [127] = {
        content = "不好意思麻烦你了，城里我只认识你一个人。",
        dialog_id = 2013,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "85031,0",
        status = 1,
        sub_talker_list = "",
        subid = 7,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [128] = {
        content = "没关系，执阳呢不跟来了吗？",
        dialog_id = 2013,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "85031,0",
        status = 1,
        sub_talker_list = "",
        subid = 8,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [129] = {
        content = "他说要监视青竹不来了，执阳口硬心软其实就是想多个玩伴。平时没少给青竹添麻烦，想买个礼物送给他，不知道选什么怕被骗有个熟人带路比较好。",
        dialog_id = 2013,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "85031,0",
        status = 1,
        sub_talker_list = "",
        subid = 9,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [130] = {
        content = "你们感情真好，行，我来帮你看看。嗯……左边有糕点店，右边有食品店，你们喜欢哪种？",
        dialog_id = 2013,
        finish_event = "",
        last_action = {},
        next = "5",
        pre_id_list = "85031,0",
        status = 1,
        sub_talker_list = "",
        subid = 10,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [131] = {
        content = "我看到街尾好像是花店？不知道有没有竹子的幼苗？青竹一定很喜欢，我去那里买吧，今天谢谢你啦！",
        dialog_id = 2013,
        finish_event = "",
        last_action = {},
        next = "6",
        pre_id_list = "85031,0",
        status = 1,
        sub_talker_list = "",
        subid = 11,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [132] = {
        content = "你们高兴就好。",
        dialog_id = 2013,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "85031,0",
        status = 1,
        sub_talker_list = "",
        subid = 12,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [133] = {
        content = "听白说你跟枫竹林的管理很熟……我的理论还欠缺一点实际的证据，希望妖族能帮个忙，反正到最后一定没问题。",
        dialog_id = 2014,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "85032,0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [134] = {
        content = "还行吧，你给我摸摸你的头我就答应带你去。",
        dialog_id = 2014,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "85032,0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [135] = {
        content = "哼，我的头岂是你能摸的！你敢伸手我就丢试管了！",
        dialog_id = 2014,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "85032,0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [136] = {
        content = "带带带，不要丢！",
        dialog_id = 2014,
        finish_event = "TARGET5028,STARTTRACE,_SUBMIT",
        last_action = {},
        next = "0",
        pre_id_list = "85032,0",
        status = 2,
        sub_talker_list = "",
        subid = 4,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [137] = {
        content = "我明白了，我会召集一些妖怪过来配合你。年纪轻轻就成为科学家很厉害啊！",
        dialog_id = 2014,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "5028",
        status = 1,
        sub_talker_list = "",
        subid = 5,
        type = 3,
        ui_mode = 2,
        voice = 0,
    },

    [138] = {
        content = "噢、噢，那就……谢谢了。",
        dialog_id = 2014,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "85032,0",
        status = 1,
        sub_talker_list = "",
        subid = 6,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [139] = {
        content = "她就是害羞！",
        dialog_id = 2014,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "85032,0",
        status = 1,
        sub_talker_list = "",
        subid = 7,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [140] = {
        content = "这里没你的事拿了钱赶紧滚！",
        dialog_id = 2014,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "85032,0",
        status = 1,
        sub_talker_list = "",
        subid = 8,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [141] = {
        content = "花姐的酒馆缺人手，你最近不是闲着吗，过来帮帮忙吧！你做菜那么好吃，到时候一定大受欢迎！",
        dialog_id = 2015,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "85034,0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [142] = {
        content = "我走远了大哥和弟弟都没人煮饭吃了！",
        dialog_id = 2015,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "85034,0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [143] = {
        content = "就去帝都的酒馆露一手，不妨碍你多久的，而且报酬丰厚哦！",
        dialog_id = 2015,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "85034,0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [144] = {
        content = "我跟你去看看，不满意可不做！",
        dialog_id = 2015,
        finish_event = "",
        last_action = {},
        next = "5",
        pre_id_list = "85034,0",
        status = 2,
        sub_talker_list = "",
        subid = 4,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [145] = {
        content = "行行行，走吧！",
        dialog_id = 2015,
        finish_event = "TARGET5007,STARTTRACE,_SUBMIT",
        last_action = {},
        next = "0",
        pre_id_list = "85034,0",
        status = 2,
        sub_talker_list = "",
        subid = 5,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [146] = {
        content = "花老板，这就是我介绍的李大厨！",
        dialog_id = 2015,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "0",
        status = 1,
        sub_talker_list = "",
        subid = 6,
        type = 1,
        ui_mode = 2,
        voice = 0,
    },

    [147] = {
        content = "（钻到前面）这位美丽的小姐姐，能在这么高端大气的地方煮菜真是我的荣幸！我叫李铁，请问小姐姐怎么称呼？",
        dialog_id = 2015,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "85034,0",
        status = 1,
        sub_talker_list = "",
        subid = 7,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [148] = {
        content = "李师傅你真幽默，叫我花姐就好。听说你煮的菜很好吃，这几天宴会就拜托你了，先给你定金。",
        dialog_id = 2015,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "85034,5007",
        status = 1,
        sub_talker_list = "",
        subid = 8,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [149] = {
        content = "没问题没问题，你想怎么给就怎么给。",
        dialog_id = 2015,
        finish_event = "",
        last_action = {},
        next = "5",
        pre_id_list = "85034,5007",
        status = 1,
        sub_talker_list = "",
        subid = 9,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [150] = {
        content = "见利忘义重色轻友啊……",
        dialog_id = 2015,
        finish_event = "DONE",
        last_action = {},
        next = "0",
        pre_id_list = "85034,0",
        status = 1,
        sub_talker_list = "",
        subid = 10,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [151] = {
        content = "哎哎哎，我的心里好苦闷！",
        dialog_id = 2016,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "85037,0",
        status = 2,
        sub_talker_list = "",
        subid = 1,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [152] = {
        content = "白大人你听过不作死就不会死这个真理吗？",
        dialog_id = 2016,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "85037,0",
        status = 2,
        sub_talker_list = "",
        subid = 2,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [153] = {
        content = "哪有作！你过来，我出双倍价钱，你帮我一个忙。中央城市的房租伙食也不便宜，你的薪水又少……",
        dialog_id = 2016,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "85037,0",
        status = 2,
        sub_talker_list = "",
        subid = 3,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [154] = {
        content = "……",
        dialog_id = 2016,
        finish_event = "",
        last_action = {},
        next = "5",
        pre_id_list = "85037,0",
        status = 2,
        sub_talker_list = "",
        subid = 4,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [155] = {
        content = "不说话当你答应啦，够义气！呐呐，你这样……",
        dialog_id = 2016,
        finish_event = "",
        last_action = {},
        next = "6",
        pre_id_list = "85037,0",
        status = 2,
        sub_talker_list = "",
        subid = 5,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [156] = {
        content = "最后一次。",
        dialog_id = 2016,
        finish_event = "",
        last_action = {},
        next = "7",
        pre_id_list = "85037,0",
        status = 2,
        sub_talker_list = "",
        subid = 6,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [157] = {
        content = "嗯嗯，最后一次最后一次。",
        dialog_id = 2016,
        finish_event = "",
        last_action = {},
        next = "0",
        pre_id_list = "85037,0",
        status = 2,
        sub_talker_list = "",
        subid = 7,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [158] = {
        content = "（点燃蜡烛）黑大人，请坐。花老板，上红酒牛排，后排的烟花点起来！",
        dialog_id = 2016,
        finish_event = "",
        last_action = {},
        next = "2",
        pre_id_list = "85036,0",
        status = 1,
        sub_talker_list = "",
        subid = 8,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [159] = {
        content = "咳咳咳，乌烟瘴气。又整什么花花肠子，你哪里来的钱！",
        dialog_id = 2016,
        finish_event = "",
        last_action = {},
        next = "3",
        pre_id_list = "85036,0",
        status = 1,
        sub_talker_list = "",
        subid = 9,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [160] = {
        content = "（无视站在角落慌张眨眼的白）谈钱伤感情，这些都是白大人为您精心准备的。",
        dialog_id = 2016,
        finish_event = "",
        last_action = {},
        next = "4",
        pre_id_list = "85036,0",
        status = 1,
        sub_talker_list = "",
        subid = 10,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [161] = {
        content = "他怎么可能有钱！最近财政赤字频频，外勤班被乔大人警告了。你们还敢用公款吃吃喝喝？",
        dialog_id = 2016,
        finish_event = "",
        last_action = {},
        next = "5",
        pre_id_list = "85036,0",
        status = 1,
        sub_talker_list = "",
        subid = 11,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

    [162] = {
        content = "竟然有这种事？冤枉啊，白大人快解释……人呢！",
        dialog_id = 2016,
        finish_event = "",
        last_action = {},
        next = "6",
        pre_id_list = "85036,0",
        status = 1,
        sub_talker_list = "",
        subid = 12,
        type = 4,
        ui_mode = 2,
        voice = 0,
    },

    [163] = {
        content = "你做好惹火我的心理准备了吗！",
        dialog_id = 2016,
        finish_event = "",
        last_action = {{["content"] = "不关我的事！", ["event"] = "F10003"}, {["content"] = "女王饶命！", ["event"] = "giveup"}},
        next = "0",
        pre_id_list = "85036,0",
        status = 1,
        sub_talker_list = "",
        subid = 13,
        type = 5,
        ui_mode = 2,
        voice = 0,
    },

}
