-- ./excel/perform/buff.xlsx
return {

    [101] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "攻击力提升",
        die_clean = 1,
        group_type = 208,
        group_update_type = 4,
        icon = 101,
        id = 101,
        name = "攻击提升",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {1},
        tips_effect = "攻击提升",
        type = 2,
        update_type = 3,
    },

    [102] = {
        attr_set = "",
        buff_class = {2},
        delay_level = 0,
        desc = "被嘲讽，强制使用普攻攻击指定目标",
        die_clean = 1,
        group_type = 101,
        group_update_type = 1,
        icon = 102,
        id = 102,
        name = "嘲讽",
        show_effect = 1,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "嘲讽",
        type = 1,
        update_type = 1,
    },

    [103] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "分担队友所受的部分伤害",
        die_clean = 1,
        group_type = 313,
        group_update_type = 3,
        icon = 103,
        id = 103,
        name = "伤害吸收",
        show_effect = 0,
        skill_clean = 0,
        sub_type = {1},
        tips_effect = "伤害吸收",
        type = 3,
        update_type = 3,
    },

    [104] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "速度降低",
        die_clean = 1,
        group_type = 105,
        group_update_type = 1,
        icon = 104,
        id = 104,
        name = "减速",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "减速",
        type = 1,
        update_type = 1,
    },

    [105] = {
        attr_set = "{disable=1}",
        buff_class = {2},
        delay_level = 0,
        desc = "被封印，无法行动，效果无法净化",
        die_clean = 1,
        group_type = 102,
        group_update_type = 1,
        icon = 105,
        id = 105,
        name = "封印",
        show_effect = 1,
        skill_clean = 0,
        sub_type = {4},
        tips_effect = "封印",
        type = 1,
        update_type = 1,
    },

    [106] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "异常抗性降低",
        die_clean = 1,
        group_type = 115,
        group_update_type = 1,
        icon = 106,
        id = 106,
        name = "减异抗",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {1},
        tips_effect = "减异抗",
        type = 1,
        update_type = 1,
    },

    [107] = {
        attr_set = "{disable=1}",
        buff_class = {1},
        delay_level = 0,
        desc = "使用技能后受到反噬，无法行动且防御降低",
        die_clean = 1,
        group_type = 308,
        group_update_type = 1,
        icon = 107,
        id = 107,
        name = "休息",
        show_effect = 0,
        skill_clean = 0,
        sub_type = {4},
        tips_effect = "休息",
        type = 3,
        update_type = 1,
    },

    [108] = {
        attr_set = "{disable=1}",
        buff_class = {2},
        delay_level = 0,
        desc = "被封印，无法行动，效果无法净化",
        die_clean = 1,
        group_type = 102,
        group_update_type = 1,
        icon = 105,
        id = 108,
        name = "封印",
        show_effect = 1,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "封印",
        type = 1,
        update_type = 1,
    },

    [109] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "每回合结束造成伤害并可能受到封印效果",
        die_clean = 1,
        group_type = 107,
        group_update_type = 1,
        icon = 109,
        id = 109,
        name = "符咒",
        show_effect = 1,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "符咒",
        type = 1,
        update_type = 1,
    },

    [110] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "暴击伤害提高",
        die_clean = 1,
        group_type = 201,
        group_update_type = 4,
        icon = 110,
        id = 110,
        name = "暴伤提升",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "暴伤提升",
        type = 2,
        update_type = 3,
    },

    [111] = {
        attr_set = "",
        buff_class = {2},
        delay_level = 0,
        desc = "被沉默，无法使用普攻之外的技能",
        die_clean = 1,
        group_type = 104,
        group_update_type = 1,
        icon = 111,
        id = 111,
        name = "沉默",
        show_effect = 1,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "沉默",
        type = 1,
        update_type = 1,
    },

    [112] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "所受伤害降低且每回合回血",
        die_clean = 1,
        group_type = 202,
        group_update_type = 3,
        icon = 112,
        id = 112,
        name = "回血护盾",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {1},
        tips_effect = "回血护盾",
        type = 2,
        update_type = 3,
    },

    [113] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "刻印存在期间死亡，敌方单位将会获得气血恢复",
        die_clean = 1,
        group_type = 107,
        group_update_type = 1,
        icon = 113,
        id = 113,
        name = "血祭刻印",
        show_effect = 1,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "血祭刻印",
        type = 1,
        update_type = 1,
    },

    [114] = {
        attr_set = "{curse_hp=1}",
        buff_class = {1},
        delay_level = 0,
        desc = "持续期间受到的回血效果将扣除气血",
        die_clean = 1,
        group_type = 106,
        group_update_type = 1,
        icon = 114,
        id = 114,
        name = "诅咒",
        show_effect = 1,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "诅咒",
        type = 1,
        update_type = 1,
    },

    [1001] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "抵挡一定的伤害",
        die_clean = 1,
        group_type = 204,
        group_update_type = 1,
        icon = 1001,
        id = 1001,
        name = "护盾",
        show_effect = 1,
        skill_clean = 1,
        sub_type = {1},
        tips_effect = "护盾",
        type = 2,
        update_type = 1,
    },

    [1002] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "持续期间受到致死伤害，有概率保留1点气血；成功发动时，将为自己附加【多段攻击】状态",
        die_clean = 1,
        group_type = 301,
        group_update_type = 3,
        icon = 1002,
        id = 1002,
        name = "不死",
        show_effect = 0,
        skill_clean = 0,
        sub_type = {4},
        tips_effect = "不死",
        type = 3,
        update_type = 3,
    },

    [1003] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "根据技能等级，普攻段数随机提升",
        die_clean = 1,
        group_type = 303,
        group_update_type = 1,
        icon = 1003,
        id = 1003,
        name = "多段攻击",
        show_effect = 1,
        skill_clean = 0,
        sub_type = {2},
        tips_effect = "多段攻击",
        type = 3,
        update_type = 1,
    },

    [1004] = {
        attr_set = "{damage_ratio=3}",
        buff_class = {2},
        delay_level = 0,
        desc = "每回合损失相当于最大气血的3%的气血",
        die_clean = 1,
        group_type = 108,
        group_update_type = 1,
        icon = 1004,
        id = 1004,
        name = "出血",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "出血",
        type = 1,
        update_type = 1,
    },

    [1005] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "速度临时降为0",
        die_clean = 1,
        group_type = 311,
        group_update_type = 1,
        icon = 1005,
        id = 1005,
        name = "蓄力",
        show_effect = 1,
        skill_clean = 0,
        sub_type = {1},
        tips_effect = "蓄力",
        type = 3,
        update_type = 1,
    },

    [1006] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "暴击率提升",
        die_clean = 1,
        group_type = 316,
        group_update_type = 4,
        icon = 1006,
        id = 1006,
        name = "暴击提升",
        show_effect = 0,
        skill_clean = 0,
        sub_type = {1},
        tips_effect = "暴击提升",
        type = 3,
        update_type = 4,
    },

    [1007] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 5,
        desc = "攻击提升，最多叠加5次",
        die_clean = 1,
        group_type = 304,
        group_update_type = 4,
        icon = 1007,
        id = 1007,
        name = "复仇",
        show_effect = 0,
        skill_clean = 0,
        sub_type = {3},
        tips_effect = "攻击提升",
        type = 3,
        update_type = 2,
    },

    [1008] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 5,
        desc = "暴击率提升，最多叠加5次",
        die_clean = 1,
        group_type = 210,
        group_update_type = 2,
        icon = 1006,
        id = 1008,
        name = "暴击",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {3},
        tips_effect = "暴击提升",
        type = 2,
        update_type = 2,
    },

    [1009] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 5,
        desc = "根据标记数量提升技能目标数",
        die_clean = 1,
        group_type = 314,
        group_update_type = 2,
        icon = 1009,
        id = 1009,
        name = "范围标记",
        show_effect = 1,
        skill_clean = 0,
        sub_type = {3},
        tips_effect = "范围标记",
        type = 3,
        update_type = 2,
    },

    [1010] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 5,
        desc = "根据标记数量提升技能攻击次数",
        die_clean = 1,
        group_type = 315,
        group_update_type = 2,
        icon = 1010,
        id = 1010,
        name = "业火印记",
        show_effect = 1,
        skill_clean = 0,
        sub_type = {3},
        tips_effect = "业火印记",
        type = 3,
        update_type = 2,
    },

    [1011] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "持续期间不会死亡且必定暴击，效果结束后死亡",
        die_clean = 1,
        group_type = 302,
        group_update_type = 1,
        icon = 1011,
        id = 1011,
        name = "续命",
        show_effect = 1,
        skill_clean = 0,
        sub_type = {4},
        tips_effect = "续命",
        type = 3,
        update_type = 1,
    },

    [1012] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 3,
        desc = "会被技能引爆，造成叠加伤害",
        die_clean = 1,
        group_type = 116,
        group_update_type = 2,
        icon = 1012,
        id = 1012,
        name = "狐火印记",
        show_effect = 1,
        skill_clean = 1,
        sub_type = {3},
        tips_effect = "狐火印记",
        type = 1,
        update_type = 2,
    },

    [1013] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 10,
        desc = "每回合结束自身提高攻击",
        die_clean = 1,
        group_type = 304,
        group_update_type = 4,
        icon = 101,
        id = 1013,
        name = "马首之骨",
        show_effect = 0,
        skill_clean = 0,
        sub_type = {3},
        tips_effect = "马首之骨",
        type = 3,
        update_type = 2,
    },

    [1014] = {
        attr_set = "",
        buff_class = {2},
        delay_level = 0,
        desc = "被嘲讽，强制使用普攻攻击指定目标",
        die_clean = 1,
        group_type = 101,
        group_update_type = 1,
        icon = 102,
        id = 1014,
        name = "嘲讽",
        show_effect = 1,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "嘲讽",
        type = 1,
        update_type = 1,
    },

    [1015] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 5,
        desc = "根据已损失的气血，提升防御",
        die_clean = 1,
        group_type = 305,
        group_update_type = 4,
        icon = 1015,
        id = 1015,
        name = "防御提升",
        show_effect = 0,
        skill_clean = 0,
        sub_type = {4},
        tips_effect = "防御提升",
        type = 3,
        update_type = 2,
    },

    [1016] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "所受的伤害由全体队友分担",
        die_clean = 1,
        group_type = 312,
        group_update_type = 3,
        icon = 1016,
        id = 1016,
        name = "链接",
        show_effect = 1,
        skill_clean = 1,
        sub_type = {6},
        tips_effect = "链接",
        type = 2,
        update_type = 3,
    },

    [1017] = {
        attr_set = "{disable=1}",
        buff_class = {2},
        delay_level = 0,
        desc = "眩晕状态，不能行动",
        die_clean = 1,
        group_type = 102,
        group_update_type = 1,
        icon = 1017,
        id = 1017,
        name = "眩晕",
        show_effect = 1,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "眩晕",
        type = 1,
        update_type = 1,
    },

    [1018] = {
        attr_set = "",
        buff_class = {2},
        delay_level = 0,
        desc = "被沉默，无法使用普攻之外的技能",
        die_clean = 1,
        group_type = 104,
        group_update_type = 1,
        icon = 111,
        id = 1018,
        name = "沉默",
        show_effect = 1,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "沉默",
        type = 1,
        update_type = 1,
    },

    [1019] = {
        attr_set = "{disable=1}",
        buff_class = {2},
        delay_level = 0,
        desc = "无法行动，被攻击有50%概率解除",
        die_clean = 1,
        group_type = 103,
        group_update_type = 1,
        icon = 1019,
        id = 1019,
        name = "睡眠",
        show_effect = 1,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "睡眠",
        type = 1,
        update_type = 1,
    },

    [1020] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "速度降低",
        die_clean = 1,
        group_type = 105,
        group_update_type = 1,
        icon = 104,
        id = 1020,
        name = "减速",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "减速",
        type = 1,
        update_type = 1,
    },

    [1021] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "速度提升",
        die_clean = 1,
        group_type = 317,
        group_update_type = 4,
        icon = 1021,
        id = 1021,
        name = "加速",
        show_effect = 0,
        skill_clean = 0,
        sub_type = {4},
        tips_effect = "加速",
        type = 3,
        update_type = 4,
    },

    [1022] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "受到非状态类的伤害，机率使攻击者眩晕",
        die_clean = 1,
        group_type = 209,
        group_update_type = 3,
        icon = 1022,
        id = 1022,
        name = "反控",
        show_effect = 1,
        skill_clean = 1,
        sub_type = {5},
        tips_effect = "受击反控",
        type = 2,
        update_type = 3,
    },

    [1023] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "符文套装效果失效",
        die_clean = 1,
        group_type = 109,
        group_update_type = 1,
        icon = 1023,
        id = 1023,
        name = "套装失效",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "套装失效",
        type = 1,
        update_type = 1,
    },

    [1024] = {
        attr_set = "{disable_cure=1}",
        buff_class = {1},
        delay_level = 0,
        desc = "持续期间无法接受回血效果",
        die_clean = 1,
        group_type = 113,
        group_update_type = 1,
        icon = 1024,
        id = 1024,
        name = "禁疗",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "禁疗",
        type = 1,
        update_type = 1,
    },

    [1025] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "攻击提升一定百分比",
        die_clean = 1,
        group_type = 208,
        group_update_type = 4,
        icon = 101,
        id = 1025,
        name = "攻击提升",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "攻击提升",
        type = 2,
        update_type = 4,
    },

    [1026] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "使用怒气技能时，自身受到大量伤害",
        die_clean = 1,
        group_type = 111,
        group_update_type = 1,
        icon = 1026,
        id = 1026,
        name = "反噬",
        show_effect = 1,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "反噬",
        type = 1,
        update_type = 1,
    },

    [1027] = {
        attr_set = "",
        buff_class = {2},
        delay_level = 0,
        desc = "被沉默，无法使用普攻之外的技能",
        die_clean = 1,
        group_type = 104,
        group_update_type = 1,
        icon = 111,
        id = 1027,
        name = "沉默",
        show_effect = 1,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "沉默",
        type = 1,
        update_type = 1,
    },

    [1028] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "造成伤害提升",
        die_clean = 1,
        group_type = 211,
        group_update_type = 4,
        icon = 1028,
        id = 1028,
        name = "伤害提升",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "伤害提升",
        type = 2,
        update_type = 4,
    },

    [1029] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "速度提升",
        die_clean = 1,
        group_type = 205,
        group_update_type = 4,
        icon = 1029,
        id = 1029,
        name = "加速",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "加速",
        type = 2,
        update_type = 4,
    },

    [1030] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "强制最慢出手",
        die_clean = 1,
        group_type = 105,
        group_update_type = 1,
        icon = 1030,
        id = 1030,
        name = "强制末速",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "强制末速",
        type = 1,
        update_type = 1,
    },

    [1031] = {
        attr_set = "{damage_ratio=20}",
        buff_class = {1},
        delay_level = 0,
        desc = "中毒，每回合损失一定气血",
        die_clean = 1,
        group_type = 112,
        group_update_type = 1,
        icon = 1031,
        id = 1031,
        name = "中毒",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "中毒",
        type = 1,
        update_type = 1,
    },

    [1032] = {
        attr_set = "",
        buff_class = {2},
        delay_level = 0,
        desc = "被动技能失效",
        die_clean = 1,
        group_type = 110,
        group_update_type = 1,
        icon = 1032,
        id = 1032,
        name = "被动失效",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "能力封印",
        type = 1,
        update_type = 1,
    },

    [1033] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "符文效果－防御降低",
        die_clean = 1,
        group_type = 117,
        group_update_type = 1,
        icon = 1033,
        id = 1033,
        name = "减甲",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "防御降低",
        type = 1,
        update_type = 1,
    },

    [1034] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "符文效果－速度提升",
        die_clean = 1,
        group_type = 317,
        group_update_type = 4,
        icon = 1034,
        id = 1034,
        name = "临时加速",
        show_effect = 0,
        skill_clean = 0,
        sub_type = {2},
        tips_effect = "加速",
        type = 3,
        update_type = 4,
    },

    [1035] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "符文效果－护盾，抵挡一定伤害",
        die_clean = 1,
        group_type = 204,
        group_update_type = 1,
        icon = 1001,
        id = 1035,
        name = "护盾",
        show_effect = 1,
        skill_clean = 1,
        sub_type = {1},
        tips_effect = "护盾",
        type = 2,
        update_type = 1,
    },

    [1036] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 5,
        desc = "暴击伤害提升",
        die_clean = 1,
        group_type = 212,
        group_update_type = 4,
        icon = 110,
        id = 1036,
        name = "暴伤提升",
        show_effect = 0,
        skill_clean = 0,
        sub_type = {3},
        tips_effect = "暴伤提升",
        type = 2,
        update_type = 2,
    },

    [1037] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "暴击率提升",
        die_clean = 1,
        group_type = 203,
        group_update_type = 4,
        icon = 1006,
        id = 1037,
        name = "暴击提升",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "暴击提升",
        type = 2,
        update_type = 1,
    },

    [1038] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "我方队员每次行动，都会根据攻击恢复气血",
        die_clean = 1,
        group_type = 213,
        group_update_type = 1,
        icon = 1038,
        id = 1038,
        name = "迷糊",
        show_effect = 1,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "迷糊",
        type = 2,
        update_type = 1,
    },

    [1039] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 5,
        desc = "由于队友的献祭，攻击力大幅提升",
        die_clean = 1,
        group_type = 214,
        group_update_type = 2,
        icon = 1039,
        id = 1039,
        name = "献祭加攻",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {3},
        tips_effect = "献祭加攻",
        type = 2,
        update_type = 2,
    },

    [1040] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 5,
        desc = "每带有1个标记，免伤10%，但是每受到1次伤害减少1个标记",
        die_clean = 1,
        group_type = 319,
        group_update_type = 2,
        icon = 1040,
        id = 1040,
        name = "吞噬印记",
        show_effect = 0,
        skill_clean = 0,
        sub_type = {3},
        tips_effect = "吞噬印记",
        type = 3,
        update_type = 2,
    },

    [1041] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "符文效果－速度减低",
        die_clean = 1,
        group_type = 105,
        group_update_type = 1,
        icon = 1030,
        id = 1041,
        name = "减速",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "减速",
        type = 1,
        update_type = 1,
    },

    [1042] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "符文效果－防御降低",
        die_clean = 1,
        group_type = 117,
        group_update_type = 1,
        icon = 1033,
        id = 1042,
        name = "减甲",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "防御降低",
        type = 1,
        update_type = 1,
    },

    [1043] = {
        attr_set = "{disable=1}",
        buff_class = {2},
        delay_level = 0,
        desc = "击杀所有喽啰强制封印BOSS一回合",
        die_clean = 1,
        group_type = 102,
        group_update_type = 1,
        icon = 105,
        id = 1043,
        name = "强制封印",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {2},
        tips_effect = "强制封印",
        type = 4,
        update_type = 1,
    },

    [1044] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "伤害增加10%",
        die_clean = 1,
        group_type = 208,
        group_update_type = 1,
        icon = 110,
        id = 1044,
        name = "锋锐",
        show_effect = 0,
        skill_clean = 0,
        sub_type = {1},
        tips_effect = "提升攻击",
        type = 1,
        update_type = 1,
    },

    [1045] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "伤害减少10%",
        die_clean = 1,
        group_type = 215,
        group_update_type = 1,
        icon = 112,
        id = 1045,
        name = "坚盾",
        show_effect = 0,
        skill_clean = 0,
        sub_type = {1},
        tips_effect = "减少伤害",
        type = 1,
        update_type = 1,
    },

    [1049] = {
        attr_set = "{share_damage=70}",
        buff_class = {1},
        delay_level = 0,
        desc = "所受的伤害由敌人分担",
        die_clean = 1,
        group_type = 118,
        group_update_type = 3,
        icon = 1049,
        id = 1049,
        name = "黑暗链接",
        show_effect = 1,
        skill_clean = 1,
        sub_type = {1},
        tips_effect = "链接",
        type = 1,
        update_type = 3,
    },

    [1050] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "受到伤害增加50%",
        die_clean = 1,
        group_type = 119,
        group_update_type = 1,
        icon = 1033,
        id = 1050,
        name = "伤害放大",
        show_effect = 0,
        skill_clean = 0,
        sub_type = {4},
        tips_effect = "伤害放大",
        type = 4,
        update_type = 1,
    },

    [1051] = {
        attr_set = "{single_lock = 1}",
        buff_class = {1},
        delay_level = 0,
        desc = "单技能优先选择目标，优先级低于嘲讽",
        die_clean = 1,
        group_type = 101,
        group_update_type = 1,
        icon = 1051,
        id = 1051,
        name = "仇恨",
        show_effect = 1,
        skill_clean = 1,
        sub_type = {5},
        tips_effect = "仇恨",
        type = 1,
        update_type = 1,
    },

    [1052] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "减低攻击力",
        die_clean = 1,
        group_type = 114,
        group_update_type = 1,
        icon = 114,
        id = 1052,
        name = "减攻",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "减攻",
        type = 1,
        update_type = 1,
    },

    [1053] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 10,
        desc = "怨恨印记增加死亡自爆威力",
        die_clean = 1,
        group_type = 216,
        group_update_type = 2,
        icon = 1053,
        id = 1053,
        name = "死亡印记",
        show_effect = 0,
        skill_clean = 0,
        sub_type = {3},
        tips_effect = "死亡印记",
        type = 4,
        update_type = 2,
    },

    [1054] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "所有受伤变为回血",
        die_clean = 1,
        group_type = 320,
        group_update_type = 1,
        icon = 1054,
        id = 1054,
        name = "回光返照",
        show_effect = 0,
        skill_clean = 0,
        sub_type = {3},
        tips_effect = "回光返照",
        type = 2,
        update_type = 1,
    },

    [1055] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "单体技能威力提升",
        die_clean = 1,
        group_type = 208,
        group_update_type = 1,
        icon = 1055,
        id = 1055,
        name = "斗气",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "斗气",
        type = 2,
        update_type = 1,
    },

    [1056] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "攻击力随提升防御力的一定比例",
        die_clean = 1,
        group_type = 218,
        group_update_type = 4,
        icon = 1056,
        id = 1056,
        name = "攻击提升",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "攻击提升",
        type = 2,
        update_type = 1,
    },

    [1057] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "抗暴率降低",
        die_clean = 1,
        group_type = 120,
        group_update_type = 1,
        icon = 1057,
        id = 1057,
        name = "抗暴击降低",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "抗暴降低",
        type = 1,
        update_type = 1,
    },

    [1058] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "受到的伤害增加",
        die_clean = 1,
        group_type = 119,
        group_update_type = 1,
        icon = 1033,
        id = 1058,
        name = "伤害加深",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "伤害加深",
        type = 1,
        update_type = 1,
    },

    [1059] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "获得各种能力提升",
        die_clean = 1,
        group_type = 217,
        group_update_type = 1,
        icon = 1059,
        id = 1059,
        name = "能力提升",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "能力提升",
        type = 2,
        update_type = 1,
    },

    [1060] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "暴击率提升",
        die_clean = 1,
        group_type = 316,
        group_update_type = 1,
        icon = 1006,
        id = 1060,
        name = "暴击提升",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "暴击提升",
        type = 2,
        update_type = 1,
    },

    [1061] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "暴击率提升",
        die_clean = 1,
        group_type = 316,
        group_update_type = 1,
        icon = 1006,
        id = 1061,
        name = "暴击提升",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "暴击提升",
        type = 2,
        update_type = 1,
    },

    [1062] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "暴击率下降",
        die_clean = 1,
        group_type = 120,
        group_update_type = 1,
        icon = 1062,
        id = 1062,
        name = "暴击减低",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "暴击降低",
        type = 1,
        update_type = 1,
    },

    [1063] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "提升暴击伤害",
        die_clean = 1,
        group_type = 201,
        group_update_type = 1,
        icon = 110,
        id = 1063,
        name = "暴击伤害",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "加暴伤",
        type = 2,
        update_type = 1,
    },

    [1064] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "受害者死亡,攻击者将受到睡眠",
        die_clean = 1,
        group_type = 103,
        group_update_type = 1,
        icon = 1022,
        id = 1064,
        name = "睡眠陷阱",
        show_effect = 1,
        skill_clean = 1,
        sub_type = {1},
        tips_effect = "睡眠陷阱",
        type = 2,
        update_type = 1,
    },

    [1065] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "行动后进入睡眠",
        die_clean = 1,
        group_type = 121,
        group_update_type = 1,
        icon = 1011,
        id = 1065,
        name = "乏力",
        show_effect = 1,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "乏力",
        type = 1,
        update_type = 1,
    },

    [1066] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "临时提高普攻伤害并，对主怪目标发起攻击",
        die_clean = 1,
        group_type = 219,
        group_update_type = 1,
        icon = 101,
        id = 1066,
        name = "协同攻击",
        show_effect = 1,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "协同攻击",
        type = 2,
        update_type = 1,
    },

    [1067] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 3,
        desc = "伤害标记，受到的伤害提高",
        die_clean = 1,
        group_type = 122,
        group_update_type = 1,
        icon = 109,
        id = 1067,
        name = "伤害标记",
        show_effect = 1,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "伤害标记",
        type = 1,
        update_type = 2,
    },

    [1068] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "伤害加深",
        die_clean = 1,
        group_type = 119,
        group_update_type = 1,
        icon = 1033,
        id = 1068,
        name = "伤害加深",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "伤害加深",
        type = 2,
        update_type = 1,
    },

    [1069] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "异常命中提升",
        die_clean = 1,
        group_type = 220,
        group_update_type = 1,
        icon = 109,
        id = 1069,
        name = "异常命中提升",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "异常命中提升",
        type = 1,
        update_type = 1,
    },

    [1070] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "每次行动造成伤害",
        die_clean = 1,
        group_type = 123,
        group_update_type = 3,
        icon = 1033,
        id = 1070,
        name = "病毒",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {4},
        tips_effect = "病毒",
        type = 2,
        update_type = 3,
    },

    [1071] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 0,
        desc = "小怪获得boss的20%攻击力",
        die_clean = 1,
        group_type = 208,
        group_update_type = 3,
        icon = 101,
        id = 1071,
        name = "春哥祝福",
        show_effect = 0,
        skill_clean = 1,
        sub_type = {2},
        tips_effect = "攻击提升",
        type = 2,
        update_type = 4,
    },

    [1072] = {
        attr_set = "{disable=1}",
        buff_class = {1},
        delay_level = 0,
        desc = "存活的炸弹在2次行动后自爆，对全体敌方单位造成50%BOSS攻击力的伤害",
        die_clean = 1,
        group_type = 322,
        group_update_type = 3,
        icon = 1012,
        id = 1072,
        name = "拉登之心",
        show_effect = 0,
        skill_clean = 0,
        sub_type = {2},
        tips_effect = "自爆",
        type = 4,
        update_type = 4,
    },

    [2001] = {
        attr_set = "",
        buff_class = {1},
        delay_level = 5,
        desc = "在比武场每5回合伤害永久增加5%",
        die_clean = 0,
        group_type = 318,
        group_update_type = 2,
        icon = 1028,
        id = 2001,
        name = "叠加攻击",
        show_effect = 1,
        skill_clean = 0,
        sub_type = {1},
        tips_effect = "加伤害",
        type = 3,
        update_type = 2,
    },

}
