-- ./excel/perform/npc.xlsx
return {

    [5001] = {
        activeSkill = 1,
        attackBuff = {},
        attackDelBuff = {},
        cd = 0,
        desc = "150%伤害，全体，附带黑暗链",
        effectAction = 1,
        effectTime = {1200},
        effectType = 40101,
        extArgs = "",
        go_back_time = 0,
        hitRate = 200,
        id = 5001,
        is_anger = 1,
        name = "黑暗链",
        range = {{["range"] = "100", ["level"] = 0}},
        skillActionType = 1,
        skillGroupType = 2,
        skill_icon = 30101,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "全体攻击",
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5002] = {
        activeSkill = 1,
        attackBuff = {},
        attackDelBuff = {},
        cd = 0,
        desc = "150%伤害，全体，附带眩晕",
        effectAction = 1,
        effectTime = {1550},
        effectType = 40102,
        extArgs = "",
        go_back_time = 500,
        hitRate = 100,
        id = 5002,
        is_anger = 1,
        name = "眩晕",
        range = {{["range"] = "100", ["level"] = 0}},
        skillActionType = 1,
        skillGroupType = 2,
        skill_icon = 30102,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "全体攻击",
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5003] = {
        activeSkill = 1,
        attackBuff = {},
        attackDelBuff = {},
        cd = 0,
        desc = "150%伤害，全体，附带出血",
        effectAction = 1,
        effectTime = {1400},
        effectType = 40101,
        extArgs = "",
        go_back_time = 500,
        hitRate = 110,
        id = 5003,
        is_anger = 1,
        name = "出血",
        range = {{["range"] = "100", ["level"] = 0}},
        skillActionType = 1,
        skillGroupType = 2,
        skill_icon = 30201,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "全体攻击",
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5004] = {
        activeSkill = 1,
        attackBuff = {},
        attackDelBuff = {},
        cd = 0,
        desc = "3次50%伤害,全体",
        effectAction = 1,
        effectTime = {1400},
        effectType = 40101,
        extArgs = "",
        go_back_time = 500,
        hitRate = 110,
        id = 5004,
        is_anger = 1,
        name = "深渊咆哮",
        range = {{["range"] = "100", ["level"] = 0}},
        skillActionType = 1,
        skillGroupType = 2,
        skill_icon = 30201,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "全体攻击",
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5005] = {
        activeSkill = 1,
        attackBuff = {},
        attackDelBuff = {},
        cd = 0,
        desc = "5+友军数量次攻击，30%概率对目标造成10%的附加伤害",
        effectAction = 1,
        effectTime = {1400},
        effectType = 40101,
        extArgs = "",
        go_back_time = 500,
        hitRate = 110,
        id = 5005,
        is_anger = 1,
        name = "乱射",
        range = {{["range"] = "1", ["level"] = 0}},
        skillActionType = 1,
        skillGroupType = 1,
        skill_icon = 30201,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "随机攻击",
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5006] = {
        activeSkill = 1,
        attackBuff = {},
        attackDelBuff = {},
        cd = 0,
        desc = "全体攻击2次65%伤害，对目标附加伤害放大，仇恨",
        effectAction = 1,
        effectTime = {1400},
        effectType = 40101,
        extArgs = "",
        go_back_time = 500,
        hitRate = 110,
        id = 5006,
        is_anger = 1,
        name = "迷雾暗杀",
        range = {{["range"] = "100", ["level"] = 0}},
        skillActionType = 1,
        skillGroupType = 2,
        skill_icon = 30201,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "全体攻击",
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5007] = {
        activeSkill = 1,
        attackBuff = {},
        attackDelBuff = {},
        cd = 0,
        desc = "全体3次50%，杀死一只非BOSS小怪，15%附件小怪剩余血量",
        effectAction = 1,
        effectTime = {1400},
        effectType = 40101,
        extArgs = "",
        go_back_time = 500,
        hitRate = 110,
        id = 5007,
        is_anger = 1,
        name = "祭献",
        range = {{["range"] = "100", ["level"] = 0}},
        skillActionType = 1,
        skillGroupType = 2,
        skill_icon = 30201,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "全体攻击",
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5008] = {
        activeSkill = 1,
        attackBuff = {},
        attackDelBuff = {},
        cd = 0,
        desc = "攻击敌方全体单位3次，每次造成35%攻击的伤害，并10%概率使目标睡眠2回合",
        effectAction = 1,
        effectTime = {1400},
        effectType = 170001,
        extArgs = "",
        go_back_time = 500,
        hitRate = 110,
        id = 5008,
        is_anger = 0,
        name = "野外BOSS1普攻",
        range = {{["range"] = "1", ["level"] = 0}},
        skillActionType = 1,
        skillGroupType = 1,
        skill_icon = 30201,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "普攻",
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5009] = {
        activeSkill = 1,
        attackBuff = {},
        attackDelBuff = {},
        cd = 0,
        desc = "攻击敌方全体单位3次，每次造成35%攻击的伤害，并10%概率使目标睡眠2回合",
        effectAction = 1,
        effectTime = {1400},
        effectType = 170002,
        extArgs = "",
        go_back_time = 500,
        hitRate = 110,
        id = 5009,
        is_anger = 1,
        name = "野外BOSS1特攻",
        range = {{["range"] = "100", ["level"] = 0}},
        skillActionType = 1,
        skillGroupType = 2,
        skill_icon = 30201,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "全体攻击",
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5010] = {
        activeSkill = 1,
        attackBuff = {},
        attackDelBuff = {},
        cd = 0,
        desc = "对敌方任意1个单位造成100%攻击的伤害，30%概率溅射2名玩家30%的攻击伤害，30%概率使目标进入乏力效果",
        effectAction = 1,
        effectTime = {1400},
        effectType = 165001,
        extArgs = "",
        go_back_time = 500,
        hitRate = 110,
        id = 5010,
        is_anger = 0,
        name = "野外BOSS2普攻",
        range = {{["range"] = "1", ["level"] = 0}},
        skillActionType = 1,
        skillGroupType = 1,
        skill_icon = 30201,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "普攻",
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5011] = {
        activeSkill = 1,
        attackBuff = {},
        attackDelBuff = {},
        cd = 0,
        desc = "对一个单位造成1次90%的攻击伤害；每个存活喽啰有30%概率同时使用普通攻击攻击该目标",
        effectAction = 1,
        effectTime = {1400},
        effectType = 165001,
        extArgs = "",
        go_back_time = 500,
        hitRate = 110,
        id = 5011,
        is_anger = 1,
        name = "野外BOSS2特攻",
        range = {{["range"] = "1", ["level"] = 0}},
        skillActionType = 1,
        skillGroupType = 1,
        skill_icon = 30201,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "单体",
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5012] = {
        activeSkill = 1,
        attackBuff = {},
        attackDelBuff = {},
        cd = 0,
        desc = "对一个目标造成1次90%伤害，并有25%+效果命中概率标记目标",
        effectAction = 1,
        effectTime = {1400},
        effectType = 120001,
        extArgs = "",
        go_back_time = 500,
        hitRate = 110,
        id = 5012,
        is_anger = 0,
        name = "野外BOSS3普攻",
        range = {{["range"] = "1", ["level"] = 0}},
        skillActionType = 1,
        skillGroupType = 1,
        skill_icon = 30201,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "普攻",
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5013] = {
        activeSkill = 1,
        attackBuff = {},
        attackDelBuff = {},
        cd = 0,
        desc = "对全体单位造成3次40%的攻击伤害，技能冷却3回合并于第一回合施放",
        effectAction = 1,
        effectTime = {1400},
        effectType = 120002,
        extArgs = "",
        go_back_time = 500,
        hitRate = 110,
        id = 5013,
        is_anger = 1,
        name = "野外BOSS3特攻",
        range = {{["range"] = "100", ["level"] = 0}},
        skillActionType = 1,
        skillGroupType = 2,
        skill_icon = 30201,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "全体攻击",
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5014] = {
        activeSkill = 1,
        attackBuff = {},
        attackDelBuff = {},
        cd = 0,
        desc = "对全体单位造成90%伤害",
        effectAction = 1,
        effectTime = {1400},
        effectType = 165002,
        extArgs = "",
        go_back_time = 500,
        hitRate = 110,
        id = 5014,
        is_anger = 1,
        name = "野外BOSS3辅助",
        range = {{["range"] = "100", ["level"] = 0}},
        skillActionType = 1,
        skillGroupType = 2,
        skill_icon = 30201,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "全体攻击",
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5016] = {
        activeSkill = 1,
        attackBuff = {},
        attackDelBuff = {},
        cd = 0,
        desc = "对全体敌我单位造成两次45%攻击力的伤害，每个被此技能杀死的单位会对敌方全体单位造成一次30%攻击的伤害",
        effectAction = 1,
        effectTime = {1400},
        effectType = 165002,
        extArgs = "",
        go_back_time = 500,
        hitRate = 110,
        id = 5016,
        is_anger = 1,
        name = "杀必死",
        range = {{["range"] = "100", ["level"] = 0}},
        skillActionType = 1,
        skillGroupType = 2,
        skill_icon = 30201,
        sp = 0,
        speedRatio = 100,
        targetType = 5,
        type_desc = "全体攻击",
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5017] = {
        activeSkill = 1,
        attackBuff = {},
        attackDelBuff = {},
        cd = 0,
        desc = "对全体敌方单位造成一次108%攻击力的伤害，释放结束后，所有存活小怪获得boss的20%攻击力，持续2次行动（不包括刚召唤的",
        effectAction = 1,
        effectTime = {1400},
        effectType = 165002,
        extArgs = "",
        go_back_time = 500,
        hitRate = 110,
        id = 5017,
        is_anger = 1,
        name = "爱的教育",
        range = {{["range"] = "100", ["level"] = 0}},
        skillActionType = 1,
        skillGroupType = 2,
        skill_icon = 30201,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "全体攻击",
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5018] = {
        activeSkill = 1,
        attackBuff = {},
        attackDelBuff = {},
        cd = 0,
        desc = "对全体敌方单位造成两次45%攻击力的伤害，并将最多2个我方小怪（不包括刚召唤的）改造为炸弹，炸弹无法攻击，存活的炸弹在2次行动后自爆，对全体敌方单位造成50%BOSS攻击力的伤害",
        effectAction = 1,
        effectTime = {1400},
        effectType = 165002,
        extArgs = "",
        go_back_time = 500,
        hitRate = 110,
        id = 5018,
        is_anger = 1,
        name = "我来自阿富汗",
        range = {{["range"] = "100", ["level"] = 0}},
        skillActionType = 1,
        skillGroupType = 2,
        skill_icon = 30201,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "全体攻击",
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

}
