-- ./excel/perform/school.xlsx
return {

    [3001] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 0,
        desc = "单体攻击目标2次，造成攻击力50%的伤害。",
        effectAction = 1,
        effectTime = {1000},
        effectType = 3001,
        extArgs = "",
        go_back_time = 500,
        hitRate = 110,
        id = 3001,
        is_anger = 0,
        name = "落刃",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "单体攻击目标2次",
        skillActionType = 1,
        skillGroupType = 1,
        skill_icon = 3001,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "普攻",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3002] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 1,
        desc = "单体攻击目标3次，每次造成攻击力70%的伤害。冷却技能：1回合",
        effectAction = 1,
        effectTime = {1500},
        effectType = 3002,
        extArgs = "",
        go_back_time = 500,
        hitRate = 100,
        id = 3002,
        is_anger = 0,
        name = "疾风闪",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "单体攻击目标3次",
        skillActionType = 1,
        skillGroupType = 1,
        skill_icon = 3002,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "点杀。",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3003] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 1,
        desc = "加攻buff",
        effectAction = 0,
        effectTime = {2000},
        effectType = 3003,
        extArgs = "",
        go_back_time = 500,
        hitRate = 100,
        id = 3003,
        is_anger = 0,
        name = "加攻buff",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "简短描述",
        skillActionType = 3,
        skillGroupType = 1,
        skill_icon = 3003,
        sp = 0,
        speedRatio = 100,
        targetType = 1,
        type_desc = "加攻buff",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3004] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 2,
        desc = "对目标及随机单位进行总计为3次的随机性攻击，每次造成攻击力40%的伤害。击杀目标则有10%机率增加1次攻击次数。冷却技能：2回合",
        effectAction = 1,
        effectTime = {300},
        effectType = 3004,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3004,
        is_anger = 0,
        name = "狂影焚钺",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "对目标及随机单位进行3次随机攻击，击杀目标则概率增加攻击次数",
        skillActionType = 1,
        skillGroupType = 1,
        skill_icon = 3004,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "小群攻。",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3005] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 0,
        desc = "消耗当前血量的20%，攻击单体1次，造成200%攻击力伤害，附加相当于30%当前气血损失量的伤害。",
        effectAction = 0,
        effectTime = {5282},
        effectType = 3005,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3005,
        is_anger = 1,
        name = "瞬狱天冲",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "消耗当前一定血量，攻击单体1次，并附加30%当前气血损失量的伤害",
        skillActionType = 1,
        skillGroupType = 1,
        skill_icon = 3005,
        sp = 60,
        speedRatio = 100,
        targetType = 2,
        type_desc = "怒气技",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3006] = {
        activeSkill = 0,
        attackDelBuff = {},
        cd = 0,
        desc = "每击杀1个目标，回复等量于目标血量上限5%的气血，回复量不超过自己血量上限的30%。",
        effectAction = 0,
        effectTime = {0},
        effectType = 0,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3006,
        is_anger = 0,
        name = "血噬",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "简短描述",
        skillActionType = 3,
        skillGroupType = 1,
        skill_icon = 3006,
        sp = 0,
        speedRatio = 100,
        targetType = 1,
        type_desc = "被动",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3007] = {
        activeSkill = 0,
        attackDelBuff = {},
        cd = 0,
        desc = "受到伤害有5%机率对攻击者使用普攻。",
        effectAction = 0,
        effectTime = {0},
        effectType = 0,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3007,
        is_anger = 0,
        name = "暗刃",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "简短描述",
        skillActionType = 3,
        skillGroupType = 1,
        skill_icon = 3007,
        sp = 0,
        speedRatio = 100,
        targetType = 1,
        type_desc = "被动",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3101] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 0,
        desc = "单体攻击目标2次，每次造成攻击力50%的伤害。",
        effectAction = 1,
        effectTime = {1700},
        effectType = 3101,
        extArgs = "",
        go_back_time = 500,
        hitRate = 100,
        id = 3101,
        is_anger = 0,
        name = "开山",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "单体攻击目标2次",
        skillActionType = 1,
        skillGroupType = 1,
        skill_icon = 3101,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "普攻",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3102] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 1,
        desc = "对目标及随机1个单位进行攻击，每个单位有40%机率被嘲讽，被嘲讽者强制对自己使用普攻，伤害为正常的50%。持续2次行动。冷却技能：1回合",
        effectAction = 0,
        effectTime = {2000},
        effectType = 3102,
        extArgs = "",
        go_back_time = 500,
        hitRate = 100,
        id = 3102,
        is_anger = 0,
        name = "震天裂",
        range = {{["range"] = "2", ["level"] = 0}},
        short_desc = "对目标及随机1个单位进行攻击，概率嘲讽",
        skillActionType = 1,
        skillGroupType = 2,
        skill_icon = 3102,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "群嘲。",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3103] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 2,
        desc = "对目标及随机1个单位进行攻击，每次造成攻击力80%的伤害，有10%机率附加相当于10%防御的额外伤害。冷却技能：2回合",
        effectAction = 0,
        effectTime = {2000},
        effectType = 3103,
        extArgs = "",
        go_back_time = 500,
        hitRate = 100,
        id = 3103,
        is_anger = 0,
        name = "崩风掩骨",
        range = {{["range"] = "2", ["level"] = 0}},
        short_desc = "对目标及随机1个单位进行攻击，概率附加一定防御的额外伤害",
        skillActionType = 1,
        skillGroupType = 2,
        skill_icon = 3103,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "小群攻。",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3104] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 2,
        desc = "链接",
        effectAction = 0,
        effectTime = {2000},
        effectType = 3104,
        extArgs = "",
        go_back_time = 500,
        hitRate = 100,
        id = 3104,
        is_anger = 0,
        name = "链接",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "简短描述",
        skillActionType = 3,
        skillGroupType = 1,
        skill_icon = 3104,
        sp = 0,
        speedRatio = 100,
        targetType = 4,
        type_desc = "链接",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3105] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 0,
        desc = "对目标及随机1个单位进行攻击，造成150%攻击的伤害，同时自身在前2个回合所受的总伤害数值将随机分摊给这2个目标作为额外伤害。",
        effectAction = 0,
        effectTime = {5000},
        effectType = 3105,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3105,
        is_anger = 1,
        name = "怒卷流邪",
        range = {{["range"] = "2", ["level"] = 0}},
        short_desc = "对目标及随机1个单位进行攻击，同时分摊前2回合所受的总伤害",
        skillActionType = 1,
        skillGroupType = 2,
        skill_icon = 3105,
        sp = 60,
        speedRatio = 100,
        targetType = 2,
        type_desc = "怒气技",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3106] = {
        activeSkill = 0,
        attackDelBuff = {},
        cd = 0,
        desc = "受到致死伤害有5%机率保留1点气血。",
        effectAction = 0,
        effectTime = {0},
        effectType = 0,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3106,
        is_anger = 0,
        name = "魔陨",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "简短描述",
        skillActionType = 3,
        skillGroupType = 1,
        skill_icon = 3106,
        sp = 0,
        speedRatio = 100,
        targetType = 1,
        type_desc = "被动",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3107] = {
        activeSkill = 0,
        attackDelBuff = {},
        cd = 0,
        desc = "每回合结束有2%机率自动解除自身随机一个异常状态。",
        effectAction = 0,
        effectTime = {0},
        effectType = 0,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3107,
        is_anger = 0,
        name = "不魇",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "简短描述",
        skillActionType = 3,
        skillGroupType = 1,
        skill_icon = 3107,
        sp = 0,
        speedRatio = 100,
        targetType = 1,
        type_desc = "被动",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3201] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 0,
        desc = "单体攻击目标2次，每次造成攻击力50%的伤害",
        effectAction = 1,
        effectTime = {2200},
        effectType = 3101,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3201,
        is_anger = 0,
        name = "疾射",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "单体攻击目标2次",
        skillActionType = 1,
        skillGroupType = 1,
        skill_icon = 3201,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "单体攻击",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3202] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 1,
        desc = "对目标及随机2个单位进行攻击，造成攻击力90%的伤害。冷却技能：1回合",
        effectAction = 0,
        effectTime = {2000},
        effectType = 3202,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3202,
        is_anger = 0,
        name = "回鹰袭",
        range = {{["range"] = "3", ["level"] = 0}, {["range"] = "4", ["level"] = 6}},
        short_desc = "对目标及随机2个单位进行攻击",
        skillActionType = 1,
        skillGroupType = 2,
        skill_icon = 3202,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "群攻",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3203] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 2,
        desc = "清除自己或友方1个单位的随机一种异常状态，等级越高，可清除的种类越多",
        effectAction = 0,
        effectTime = {2200},
        effectType = 3203,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3203,
        is_anger = 0,
        name = "片羽流风",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "简短描述",
        skillActionType = 3,
        skillGroupType = 1,
        skill_icon = 3203,
        sp = 0,
        speedRatio = 100,
        targetType = 1,
        type_desc = "清buff",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3204] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 2,
        desc = "对目标及随机1个单位进行攻击，造成攻击力50%的伤害，有40%机率降低目标速度20%，持续2次行动。冷却技能：2回合",
        effectAction = 0,
        effectTime = {2250},
        effectType = 3204,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3204,
        is_anger = 0,
        name = "破空之矢",
        range = {{["range"] = "2", ["level"] = 0}},
        short_desc = "对目标及随机1个单位进行攻击，概率减速",
        skillActionType = 1,
        skillGroupType = 2,
        skill_icon = 3204,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "减速",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3205] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 0,
        desc = "对目标及随机2个单位进行3次攻击，每次造成攻击力40%的伤害，最后对选中目标进行额外1次攻击，造成80%的伤害",
        effectAction = 0,
        effectTime = {6350},
        effectType = 3205,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3205,
        is_anger = 1,
        name = "疾鹰重影",
        range = {{["range"] = "3", ["level"] = 0}, {["range"] = "4", ["level"] = 5}},
        short_desc = "对目标及随机2个单位进行3次攻击，最后对选中目标进行1次额外攻击",
        skillActionType = 1,
        skillGroupType = 2,
        skill_icon = 3205,
        sp = 60,
        speedRatio = 100,
        targetType = 2,
        type_desc = "怒气技",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3206] = {
        activeSkill = 0,
        attackDelBuff = {},
        cd = 0,
        desc = "被动",
        effectAction = 0,
        effectTime = {0},
        effectType = 0,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3206,
        is_anger = 0,
        name = "穷追",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "简短描述",
        skillActionType = 3,
        skillGroupType = 1,
        skill_icon = 3206,
        sp = 0,
        speedRatio = 100,
        targetType = 1,
        type_desc = "被动",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3207] = {
        activeSkill = 0,
        attackDelBuff = {},
        cd = 0,
        desc = "被动",
        effectAction = 0,
        effectTime = {0},
        effectType = 0,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3207,
        is_anger = 0,
        name = "无尽",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "简短描述",
        skillActionType = 3,
        skillGroupType = 1,
        skill_icon = 3207,
        sp = 0,
        speedRatio = 100,
        targetType = 1,
        type_desc = "被动",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3301] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 0,
        desc = "单体攻击目标2次，每次造成攻击力50%的伤害",
        effectAction = 1,
        effectTime = {1350},
        effectType = 3301,
        extArgs = "",
        go_back_time = 500,
        hitRate = 100,
        id = 3301,
        is_anger = 0,
        name = "斩魄",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "单体攻击目标2次",
        skillActionType = 1,
        skillGroupType = 1,
        skill_icon = 3301,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "单体攻击",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3302] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 1,
        desc = "对目标及随机1个单位进行攻击，造成攻击力70%的伤害，有40%机率封印目标，被封印者无法行动，持续2次行动。冷却技能：1回合",
        effectAction = 0,
        effectTime = {750, 150},
        effectType = 3302,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3302,
        is_anger = 0,
        name = "封灵阵",
        range = {{["range"] = "2", ["level"] = 0}},
        short_desc = "对目标及随机1个单位进行攻击，概率封印",
        skillActionType = 1,
        skillGroupType = 2,
        skill_icon = 3302,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "点控",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3303] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 2,
        desc = "攻击目标，造成100%攻击的伤害，随机目标进入弹射，最多弹射3次。每弹射一次，伤害递减20%，并有10%机率降低目标20%的异常抵抗，持续2回合。冷却技能：2回合",
        effectAction = 0,
        effectTime = {1200, 420},
        effectType = 3303,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3303,
        is_anger = 0,
        name = "断龙真斩",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "单体攻击目标1次，并随机进行弹射，概率降低异常抵抗",
        skillActionType = 1,
        skillGroupType = 1,
        skill_icon = 3303,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "小群攻",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3304] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 3,
        desc = "临时提升20%速度，100%封印1个目标2次行动，下回合无法行动，且自身防御降低70%",
        effectAction = 0,
        effectTime = {950},
        effectType = 3304,
        extArgs = "",
        go_back_time = 500,
        hitRate = 100,
        id = 3304,
        is_anger = 0,
        name = "绝对领域",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "简短描述",
        skillActionType = 3,
        skillGroupType = 1,
        skill_icon = 3304,
        sp = 0,
        speedRatio = 120,
        targetType = 2,
        type_desc = "强控",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3305] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 0,
        desc = "对目标及随机1个单位进行3次攻击，每次造成攻击力50%的伤害，同时目标身上附加符咒。符咒每回合结束会对目标造成10%攻击力的伤害，并有30%机率封印目标，封印效果持续1回合。符咒持续3回合",
        effectAction = 0,
        effectTime = {5700},
        effectType = 3305,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3305,
        is_anger = 1,
        name = "龙缚炎爆",
        range = {{["range"] = "2", ["level"] = 0}},
        short_desc = "对目标及随机1个单位进行3次攻击，同时附加符咒，回合造成伤害并概率封印",
        skillActionType = 1,
        skillGroupType = 2,
        skill_icon = 3305,
        sp = 60,
        speedRatio = 100,
        targetType = 2,
        type_desc = "怒气技",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3306] = {
        activeSkill = 0,
        attackDelBuff = {},
        cd = 0,
        desc = "被动",
        effectAction = 0,
        effectTime = {0},
        effectType = 0,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3306,
        is_anger = 0,
        name = "逆饮",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "简短描述",
        skillActionType = 3,
        skillGroupType = 1,
        skill_icon = 3306,
        sp = 0,
        speedRatio = 100,
        targetType = 1,
        type_desc = "被动",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3307] = {
        activeSkill = 0,
        attackDelBuff = {},
        cd = 0,
        desc = "被动",
        effectAction = 0,
        effectTime = {0},
        effectType = 0,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3307,
        is_anger = 0,
        name = "厄转",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "简短描述",
        skillActionType = 3,
        skillGroupType = 1,
        skill_icon = 3307,
        sp = 0,
        speedRatio = 100,
        targetType = 1,
        type_desc = "被动",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3401] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 0,
        desc = "单体攻击目标2次，每次造成攻击力50%的伤害",
        effectAction = 1,
        effectTime = {1600},
        effectType = 3401,
        extArgs = "",
        go_back_time = 500,
        hitRate = 100,
        id = 3401,
        is_anger = 0,
        name = "二旋拳",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "单体攻击目标2次",
        skillActionType = 1,
        skillGroupType = 1,
        skill_icon = 3401,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "单体攻击",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3402] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 1,
        desc = "单体攻击目标2次，每次造成攻击力60%的伤害，且有20%机率溅射到另外两个目标，溅身伤害为70%。冷却技能：1回合",
        effectAction = 1,
        effectTime = {1200},
        effectType = 3402,
        extArgs = "",
        go_back_time = 500,
        hitRate = 100,
        id = 3402,
        is_anger = 0,
        name = "雷霆贯穿",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "单体攻击目标2次，概率对其他2个目标造成溅射",
        skillActionType = 1,
        skillGroupType = 1,
        skill_icon = 3402,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "单体",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3403] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 3,
        desc = "为自己（一定等级可对友方单位）附加状态，消耗30%的血量，暴击伤害增加60%，持续1次行动。冷却技能：3回合",
        effectAction = 0,
        effectTime = {1000},
        effectType = 3403,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3403,
        is_anger = 0,
        name = "君临之境",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "消耗一定血量，为己方增加暴击伤害",
        skillActionType = 3,
        skillGroupType = 1,
        skill_icon = 3403,
        sp = 0,
        speedRatio = 100,
        targetType = 1,
        type_desc = "加buff",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3404] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 2,
        desc = "沉默",
        effectAction = 0,
        effectTime = {2000},
        effectType = 3404,
        extArgs = "",
        go_back_time = 500,
        hitRate = 100,
        id = 3404,
        is_anger = 0,
        name = "沉默",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "简短描述",
        skillActionType = 1,
        skillGroupType = 1,
        skill_icon = 3404,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "沉默",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3405] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 0,
        desc = "对目标进行4次攻击，每次造成攻击力40%的伤害，攻击期间目标死亡，则会继续对随机一个目标再次施放一次该技能，最多攻击2个目标",
        effectAction = 0,
        effectTime = {5493, 2800},
        effectType = 3405,
        extArgs = "",
        go_back_time = 500,
        hitRate = 100,
        id = 3405,
        is_anger = 1,
        name = "无限破坏",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "对目标进行4次攻击，如果单位死亡，随机对其他单位再施放一次技能",
        skillActionType = 1,
        skillGroupType = 1,
        skill_icon = 3405,
        sp = 60,
        speedRatio = 100,
        targetType = 2,
        type_desc = "怒气技",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3406] = {
        activeSkill = 0,
        attackDelBuff = {},
        cd = 0,
        desc = "被动",
        effectAction = 0,
        effectTime = {0},
        effectType = 0,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3406,
        is_anger = 0,
        name = "神谴",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "简短描述",
        skillActionType = 3,
        skillGroupType = 1,
        skill_icon = 3406,
        sp = 0,
        speedRatio = 100,
        targetType = 1,
        type_desc = "被动",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3407] = {
        activeSkill = 0,
        attackDelBuff = {},
        cd = 0,
        desc = "被动",
        effectAction = 0,
        effectTime = {0},
        effectType = 0,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3407,
        is_anger = 0,
        name = "修罗暴月",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "简短描述",
        skillActionType = 3,
        skillGroupType = 1,
        skill_icon = 3407,
        sp = 0,
        speedRatio = 100,
        targetType = 1,
        type_desc = "被动",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3501] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 0,
        desc = "单体攻击目标2次，每次造成攻击力50%的伤害",
        effectAction = 1,
        effectTime = {1500},
        effectType = 3501,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3501,
        is_anger = 0,
        name = "荆棘卷",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "单体攻击目标2次",
        skillActionType = 1,
        skillGroupType = 1,
        skill_icon = 3501,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "单体攻击",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3502] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 1,
        desc = "回复2个友方单位的气血，回复量为50%攻击+固定值，除所选目标优先选择气血比例较低的单位。冷却技能：1回合",
        effectAction = 0,
        effectTime = {1500},
        effectType = 3502,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3502,
        is_anger = 0,
        name = "贤之卷",
        range = {{["range"] = "2", ["level"] = 0}, {["range"] = "3", ["level"] = 6}},
        short_desc = "回复2个友方单位的气血",
        skillActionType = 4,
        skillGroupType = 2,
        skill_icon = 3502,
        sp = 0,
        speedRatio = 100,
        targetType = 1,
        type_desc = "群加血",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3503] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 1,
        desc = "对目标及随机2个单位进行攻击，造成攻击力90%的伤害。冷却技能：1回合",
        effectAction = 0,
        effectTime = {2000},
        effectType = 3503,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3503,
        is_anger = 0,
        name = "神庭黄昏",
        range = {{["range"] = "3", ["level"] = 0}, {["range"] = "4", ["level"] = 6}},
        short_desc = "对目标及随机2个单位进行攻击",
        skillActionType = 1,
        skillGroupType = 2,
        skill_icon = 3503,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "小群攻",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3504] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 3,
        desc = "回血护盾",
        effectAction = 0,
        effectTime = {2000},
        effectType = 3504,
        extArgs = "",
        go_back_time = 500,
        hitRate = 100,
        id = 3504,
        is_anger = 0,
        name = "回血护盾",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "简短描述",
        skillActionType = 3,
        skillGroupType = 1,
        skill_icon = 3504,
        sp = 0,
        speedRatio = 100,
        targetType = 1,
        type_desc = "回血护盾",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3505] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 0,
        desc = "对目标及随机2个单位进行3次攻击(每个单位承受3次)，每次造成攻击力40%的伤害，有30%对目标打上刻印，持续3回合。刻印存在时间内目标死亡，则我方单位将平均获得气血回复，总回复量为死亡单位的气血上限",
        effectAction = 0,
        effectTime = {6720},
        effectType = 3505,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3505,
        is_anger = 1,
        name = "星门咏唱",
        range = {{["range"] = "3", ["level"] = 0}},
        short_desc = "对目标及随机2个单位进行3次攻击，概率刻印，如果刻印单位死亡，己方恢复气血",
        skillActionType = 1,
        skillGroupType = 2,
        skill_icon = 3505,
        sp = 60,
        speedRatio = 100,
        targetType = 2,
        type_desc = "怒气技",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3506] = {
        activeSkill = 0,
        attackDelBuff = {},
        cd = 0,
        desc = "被动",
        effectAction = 0,
        effectTime = {0},
        effectType = 0,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3506,
        is_anger = 0,
        name = "溺境微光",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "简短描述",
        skillActionType = 3,
        skillGroupType = 1,
        skill_icon = 3506,
        sp = 0,
        speedRatio = 100,
        targetType = 1,
        type_desc = "被动",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3507] = {
        activeSkill = 0,
        attackDelBuff = {},
        cd = 0,
        desc = "被动",
        effectAction = 0,
        effectTime = {0},
        effectType = 0,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3507,
        is_anger = 0,
        name = "堕落之翼",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "简短描述",
        skillActionType = 3,
        skillGroupType = 1,
        skill_icon = 3507,
        sp = 0,
        speedRatio = 100,
        targetType = 1,
        type_desc = "被动",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

    [3901] = {
        activeSkill = 1,
        attackDelBuff = {},
        cd = 0,
        desc = "普攻",
        effectAction = 1,
        effectTime = {1500},
        effectType = 3501,
        extArgs = "",
        go_back_time = 0,
        hitRate = 100,
        id = 3901,
        is_anger = 0,
        name = "普攻",
        range = {{["range"] = "1", ["level"] = 0}},
        short_desc = "简短描述",
        skillActionType = 1,
        skillGroupType = 1,
        skill_icon = 3501,
        sp = 0,
        speedRatio = 100,
        targetType = 2,
        type_desc = "单体攻击",
        useTargetStatus = 1,
        victimDelBuff = {},
    },

}
