-- ./excel/fight/monster.xlsx
return {

    [10001] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 1114, ["ratio"] = 1}},
        attack = "level*5+30",
        critical_damage = 150,
        critical_ratio = "0",
        cure_critical_ratio = 5,
        defense = "level*2-15",
        desc = "测试NPC",
        hp = "100000",
        id = 10001,
        level = "LV",
        model_id = 11,
        mutate_color = {},
        mutate_texture = 0,
        name = "豆豆",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        speed = "level*1+5",
        texture = 11,
        wpmodel = 12,
    },

    [10002] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 1101, ["ratio"] = 1}},
        attack = "level*5+30",
        critical_damage = 150,
        critical_ratio = "0",
        cure_critical_ratio = 5,
        defense = "level*2-15",
        desc = "测试NPC",
        hp = "500",
        id = 10002,
        level = "LV",
        model_id = 11,
        mutate_color = {},
        mutate_texture = 0,
        name = "豆豆",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        speed = "level*1+5",
        texture = 11,
        wpmodel = 12,
    },

    [10003] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 1101, ["ratio"] = 1}},
        attack = "level*5+30",
        critical_damage = 150,
        critical_ratio = "0",
        cure_critical_ratio = 5,
        defense = "level*2-15",
        desc = "友军",
        hp = "500",
        id = 10003,
        level = "LV",
        model_id = 11,
        mutate_color = {},
        mutate_texture = 0,
        name = "豆豆",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        speed = "level*1+5",
        texture = 11,
        wpmodel = 12,
    },

    [11001] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 2101, ["ratio"] = 1}},
        attack = "level*5+30",
        critical_damage = 150,
        critical_ratio = "0",
        cure_critical_ratio = 5,
        defense = "level*2-15",
        desc = "2101技能",
        hp = "500",
        id = 11001,
        level = "LV",
        model_id = 11,
        mutate_color = {},
        mutate_texture = 0,
        name = "豆豆",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        speed = "level*1+5",
        texture = 11,
        wpmodel = 12,
    },

    [11002] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 2102, ["ratio"] = 1}},
        attack = "level*5+30",
        critical_damage = 150,
        critical_ratio = "0",
        cure_critical_ratio = 5,
        defense = "level*2-15",
        desc = "2102技能",
        hp = "500",
        id = 11002,
        level = "LV",
        model_id = 11,
        mutate_color = {},
        mutate_texture = 0,
        name = "技能",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        speed = "level*1+5",
        texture = 11,
        wpmodel = 12,
    },

    [11003] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 2103, ["ratio"] = 1}},
        attack = "level*5+30",
        critical_damage = 150,
        critical_ratio = "0",
        cure_critical_ratio = 5,
        defense = "level*2-15",
        desc = "2103技能",
        hp = "10000",
        id = 11003,
        level = "LV",
        model_id = 11,
        mutate_color = {},
        mutate_texture = 0,
        name = "2103技能",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        speed = "level*1+5",
        texture = 11,
        wpmodel = 12,
    },

    [11004] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 2104, ["ratio"] = 1}},
        attack = "level*5+30",
        critical_damage = 150,
        critical_ratio = "0",
        cure_critical_ratio = 5,
        defense = "level*2-15",
        desc = "2104技能",
        hp = "5000",
        id = 11004,
        level = "LV",
        model_id = 11,
        mutate_color = {},
        mutate_texture = 0,
        name = "2104技能",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        speed = "level*1+5",
        texture = 11,
        wpmodel = 12,
    },

    [11005] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 2106, ["ratio"] = 1}},
        attack = "level*5+30",
        critical_damage = 150,
        critical_ratio = "0",
        cure_critical_ratio = 5,
        defense = "level*2-15",
        desc = "2105技能",
        hp = "50000",
        id = 11005,
        level = "LV",
        model_id = 11,
        mutate_color = {},
        mutate_texture = 0,
        name = "2105技能",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        speed = "level*1+5",
        texture = 11,
        wpmodel = 12,
    },

    [11006] = {
        abnormal_attr_ratio = "0",
        activeSkills = {},
        attack = "level*5+30",
        critical_damage = 150,
        critical_ratio = "0",
        cure_critical_ratio = 5,
        defense = "level*2-15",
        desc = "2106技能",
        hp = "50000",
        id = 11006,
        level = "LV",
        model_id = 11,
        mutate_color = {},
        mutate_texture = 0,
        name = "2106技能",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        speed = "level*1+5",
        texture = 11,
        wpmodel = 12,
    },

    [11007] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 1114, ["ratio"] = 1}},
        attack = "level*5+30",
        critical_damage = 150,
        critical_ratio = "0",
        cure_critical_ratio = 5,
        defense = "level*2-15",
        desc = "比武场",
        hp = "50",
        id = 11007,
        level = "LV",
        model_id = 130,
        mutate_color = {},
        mutate_texture = 0,
        name = "主角1",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        speed = "level*1+5",
        texture = 11,
        wpmodel = 12,
    },

    [11008] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 1101, ["ratio"] = 1}},
        attack = "level*5+30",
        critical_damage = 150,
        critical_ratio = "0",
        cure_critical_ratio = 5,
        defense = "level*2-15",
        desc = "比武场",
        hp = "50",
        id = 11008,
        level = "LV",
        model_id = 140,
        mutate_color = {},
        mutate_texture = 0,
        name = "主角2",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        speed = "level*1+5",
        texture = 11,
        wpmodel = 12,
    },

    [11009] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 1101, ["ratio"] = 1}},
        attack = "level*5+30",
        critical_damage = 150,
        critical_ratio = "0",
        cure_critical_ratio = 5,
        defense = "level*2-15",
        desc = "比武场",
        hp = "10000",
        id = 11009,
        level = "LV",
        model_id = 150,
        mutate_color = {},
        mutate_texture = 0,
        name = "主角3",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        speed = "level*1+5",
        texture = 11,
        wpmodel = 12,
    },

    [11010] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 1101, ["ratio"] = 1}},
        attack = "level*5+30",
        critical_damage = 150,
        critical_ratio = "0",
        cure_critical_ratio = 5,
        defense = "level*2-15",
        desc = "比武场",
        hp = "50",
        id = 11010,
        level = "LV",
        model_id = 160,
        mutate_color = {},
        mutate_texture = 0,
        name = "主角4",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        speed = "level*1+5",
        texture = 11,
        wpmodel = 12,
    },

    [11011] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 1101, ["ratio"] = 1}},
        attack = "level*5+30",
        critical_damage = 150,
        critical_ratio = "0",
        cure_critical_ratio = 5,
        defense = "level*2-15",
        desc = "比武场",
        hp = "50",
        id = 11011,
        level = "LV",
        model_id = 130,
        mutate_color = {},
        mutate_texture = 0,
        name = "主角1",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        speed = "level*1+5",
        texture = 11,
        wpmodel = 12,
    },

    [11012] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 1101, ["ratio"] = 1}},
        attack = "level*5+30",
        critical_damage = 150,
        critical_ratio = "0",
        cure_critical_ratio = 5,
        defense = "level*2-15",
        desc = "茶会明雷",
        hp = "2800",
        id = 11012,
        level = "LV",
        model_id = 130,
        mutate_color = {},
        mutate_texture = 0,
        name = "主角1",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        speed = "level*1+5",
        texture = 11,
        wpmodel = 12,
    },

    [11013] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 1101, ["ratio"] = 1}},
        attack = "level*5+30",
        critical_damage = 150,
        critical_ratio = "0",
        cure_critical_ratio = 5,
        defense = "level*2-15",
        desc = "茶会明雷",
        hp = "1500",
        id = 11013,
        level = "LV",
        model_id = 130,
        mutate_color = {},
        mutate_texture = 0,
        name = "主角1",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        speed = "level*1+5",
        texture = 11,
        wpmodel = 12,
    },

    [11014] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 1101, ["ratio"] = 1}},
        attack = "level*5+30",
        critical_damage = 150,
        critical_ratio = "0",
        cure_critical_ratio = 5,
        defense = "level*2-15",
        desc = "茶会明雷",
        hp = "50",
        id = 11014,
        level = "LV",
        model_id = 130,
        mutate_color = {},
        mutate_texture = 0,
        name = "主角1",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        speed = "level*1+5",
        texture = 11,
        wpmodel = 12,
    },

    [11015] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 1101, ["ratio"] = 1}},
        attack = "level*5+30",
        critical_damage = 150,
        critical_ratio = "0",
        cure_critical_ratio = 5,
        defense = "level*2-15",
        desc = "茶会明雷",
        hp = "50",
        id = 11015,
        level = "LV",
        model_id = 130,
        mutate_color = {},
        mutate_texture = 0,
        name = "主角1",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        speed = "level*1+5",
        texture = 11,
        wpmodel = 12,
    },

    [11016] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 1101, ["ratio"] = 1}},
        attack = "level*5+30",
        critical_damage = 150,
        critical_ratio = "0",
        cure_critical_ratio = 5,
        defense = "level*2-15",
        desc = "茶会明雷",
        hp = "1000",
        id = 11016,
        level = "LV",
        model_id = 130,
        mutate_color = {},
        mutate_texture = 0,
        name = "主角1",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        speed = "level*1+5",
        texture = 11,
        wpmodel = 12,
    },

}
