-- ./excel/huodong/arenagame/npc.xlsx
return {

    [1001] = {
        diglogface = 0,
        event = 1001,
        grade = 1,
        id = 1001,
        lifeTime = 0,
        modelId = 5101,
        mutateColor = {},
        mutateTexture = 0,
        name = "闹事的大耳兔",
        nameType = 1,
        ornamentId = 0,
        refreshCycle = 0,
        rotateY = -145.0,
        scale = 1.0,
        sceneId = 101000,
        title = "",
        tollgateId = 101005,
        type = 3,
        wpmodel = 0,
        x = 23.0,
        y = 25.0,
        z = 0.0,
    },

    [1002] = {
        diglogface = 0,
        event = 1001,
        grade = 0,
        id = 1002,
        lifeTime = 0,
        modelId = 5109,
        mutateColor = {},
        mutateTexture = 0,
        name = "闹事的猴子",
        nameType = 1,
        ornamentId = 0,
        refreshCycle = 0,
        rotateY = 0.0,
        scale = 0.0,
        sceneId = 0,
        title = "",
        tollgateId = 0,
        type = 3,
        wpmodel = 0,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },

    [1003] = {
        diglogface = 0,
        event = 1001,
        grade = 0,
        id = 1003,
        lifeTime = 0,
        modelId = 5111,
        mutateColor = {},
        mutateTexture = 0,
        name = "闹事的螃蟹",
        nameType = 1,
        ornamentId = 0,
        refreshCycle = 0,
        rotateY = 0.0,
        scale = 0.0,
        sceneId = 0,
        title = "",
        tollgateId = 0,
        type = 3,
        wpmodel = 0,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },

    [1004] = {
        diglogface = 0,
        event = 1001,
        grade = 0,
        id = 1004,
        lifeTime = 0,
        modelId = 5114,
        mutateColor = {},
        mutateTexture = 0,
        name = "闹事的野猪",
        nameType = 1,
        ornamentId = 0,
        refreshCycle = 0,
        rotateY = 0.0,
        scale = 0.0,
        sceneId = 0,
        title = "",
        tollgateId = 0,
        type = 3,
        wpmodel = 0,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },

}
