-- ./excel/partner/awake.xlsx
return {

    [301] = {
        abnormal_attr_ratio = 500,
        attack = 251,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 54,
        maxhp = 1960,
        partner_type = 301,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 135,
    },

    [302] = {
        abnormal_attr_ratio = 500,
        attack = 251,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 50,
        maxhp = 2069,
        partner_type = 302,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 125,
    },

    [303] = {
        abnormal_attr_ratio = 500,
        attack = 283,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 49,
        maxhp = 1742,
        partner_type = 303,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 215,
    },

    [305] = {
        abnormal_attr_ratio = 500,
        attack = 285,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 41,
        maxhp = 2004,
        partner_type = 305,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 115,
    },

    [306] = {
        abnormal_attr_ratio = 500,
        attack = 293,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 40,
        maxhp = 2178,
        partner_type = 306,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 140,
    },

    [308] = {
        abnormal_attr_ratio = 500,
        attack = 207,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 54,
        maxhp = 2614,
        partner_type = 308,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 170,
    },

    [311] = {
        abnormal_attr_ratio = 500,
        attack = 210,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 47,
        maxhp = 2505,
        partner_type = 311,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 60,
    },

    [312] = {
        abnormal_attr_ratio = 500,
        attack = 234,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 47,
        maxhp = 2243,
        partner_type = 312,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 205,
    },

    [313] = {
        abnormal_attr_ratio = 500,
        attack = 249,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 54,
        maxhp = 2069,
        partner_type = 313,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 155,
    },

    [314] = {
        abnormal_attr_ratio = 500,
        attack = 276,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 42,
        maxhp = 2156,
        partner_type = 314,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 65,
    },

    [315] = {
        abnormal_attr_ratio = 500,
        attack = 268,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 45,
        maxhp = 2025,
        partner_type = 315,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 160,
    },

    [316] = {
        abnormal_attr_ratio = 500,
        attack = 256,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 46,
        maxhp = 2396,
        partner_type = 316,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 75,
    },

    [401] = {
        abnormal_attr_ratio = 500,
        attack = 202,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 50,
        maxhp = 2483,
        partner_type = 401,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 200,
    },

    [402] = {
        abnormal_attr_ratio = 500,
        attack = 234,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 50,
        maxhp = 2134,
        partner_type = 402,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 225,
    },

    [403] = {
        abnormal_attr_ratio = 500,
        attack = 258,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 49,
        maxhp = 2221,
        partner_type = 403,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 165,
    },

    [404] = {
        abnormal_attr_ratio = 500,
        attack = 207,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 54,
        maxhp = 2374,
        partner_type = 404,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 128,
    },

    [405] = {
        abnormal_attr_ratio = 500,
        attack = 219,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 43,
        maxhp = 2614,
        partner_type = 405,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 220,
    },

    [407] = {
        abnormal_attr_ratio = 500,
        attack = 195,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 48,
        maxhp = 2614,
        partner_type = 407,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 100,
    },

    [409] = {
        abnormal_attr_ratio = 500,
        attack = 261,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 44,
        maxhp = 2287,
        partner_type = 409,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 95,
    },

    [410] = {
        abnormal_attr_ratio = 500,
        attack = 276,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 45,
        maxhp = 1960,
        partner_type = 410,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 250,
    },

    [412] = {
        abnormal_attr_ratio = 500,
        attack = 280,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 41,
        maxhp = 2396,
        partner_type = 412,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 210,
    },

    [413] = {
        abnormal_attr_ratio = 500,
        attack = 256,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 50,
        maxhp = 2221,
        partner_type = 413,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 110,
    },

    [414] = {
        abnormal_attr_ratio = 500,
        attack = 239,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 48,
        maxhp = 2091,
        partner_type = 414,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 180,
    },

    [415] = {
        abnormal_attr_ratio = 500,
        attack = 195,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 59,
        maxhp = 2548,
        partner_type = 415,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 190,
    },

    [416] = {
        abnormal_attr_ratio = 500,
        attack = 212,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 55,
        maxhp = 2352,
        partner_type = 416,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 175,
    },

    [417] = {
        abnormal_attr_ratio = 500,
        attack = 249,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 46,
        maxhp = 2178,
        partner_type = 417,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 255,
    },

    [418] = {
        abnormal_attr_ratio = 500,
        attack = 263,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 59,
        maxhp = 2113,
        partner_type = 418,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 150,
    },

    [501] = {
        abnormal_attr_ratio = 500,
        attack = 268,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 46,
        maxhp = 1960,
        partner_type = 501,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 70,
    },

    [502] = {
        abnormal_attr_ratio = 500,
        attack = 258,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 48,
        maxhp = 2004,
        partner_type = 502,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 105,
    },

    [503] = {
        abnormal_attr_ratio = 500,
        attack = 271,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 50,
        maxhp = 1742,
        partner_type = 503,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 230,
    },

    [504] = {
        abnormal_attr_ratio = 500,
        attack = 224,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 44,
        maxhp = 2548,
        partner_type = 504,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 145,
    },

    [505] = {
        abnormal_attr_ratio = 500,
        attack = 276,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 40,
        maxhp = 2243,
        partner_type = 505,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 80,
    },

    [506] = {
        abnormal_attr_ratio = 500,
        attack = 263,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 50,
        maxhp = 1786,
        partner_type = 506,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 49,
    },

    [507] = {
        abnormal_attr_ratio = 500,
        attack = 224,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 44,
        maxhp = 2505,
        partner_type = 507,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 195,
    },

    [508] = {
        abnormal_attr_ratio = 500,
        attack = 234,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 47,
        maxhp = 2461,
        partner_type = 508,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 240,
    },

    [509] = {
        abnormal_attr_ratio = 500,
        attack = 258,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 44,
        maxhp = 2069,
        partner_type = 509,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 245,
    },

    [510] = {
        abnormal_attr_ratio = 500,
        attack = 278,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 43,
        maxhp = 2069,
        partner_type = 510,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 120,
    },

    [511] = {
        abnormal_attr_ratio = 500,
        attack = 244,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 46,
        maxhp = 2221,
        partner_type = 511,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 235,
    },

    [512] = {
        abnormal_attr_ratio = 500,
        attack = 263,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 43,
        maxhp = 2309,
        partner_type = 512,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 150,
    },

    [513] = {
        abnormal_attr_ratio = 500,
        attack = 276,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 54,
        maxhp = 1786,
        partner_type = 513,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 85,
    },

    [514] = {
        abnormal_attr_ratio = 500,
        attack = 249,
        critical_damage = 0,
        critical_ratio = 500,
        cure_critical_ratio = 500,
        defense = 49,
        maxhp = 2025,
        partner_type = 514,
        res_abnormal_ratio = 500,
        res_critical_ratio = 500,
        speed = 90,
    },

    [318] = {
        abnormal_attr_ratio = 1,
        attack = 1,
        critical_damage = 1,
        critical_ratio = 1,
        cure_critical_ratio = 1,
        defense = 1,
        maxhp = 1,
        partner_type = 318,
        res_abnormal_ratio = 1,
        res_critical_ratio = 1,
        speed = 1,
    },

}
