-- ./excel/partner/awake.xlsx
return {

    [301] = {
        abnormal_attr_ratio = 3,
        attack = 3,
        critical_damage = 2,
        critical_ratio = 2,
        cure_critical_ratio = 2,
        defense = 1,
        maxhp = 4,
        partner_type = 301,
        res_abnormal_ratio = 2,
        res_critical_ratio = 1,
        speed = 3,
    },

    [302] = {
        abnormal_attr_ratio = 3,
        attack = 3,
        critical_damage = 2,
        critical_ratio = 2,
        cure_critical_ratio = 2,
        defense = 2,
        maxhp = 3,
        partner_type = 302,
        res_abnormal_ratio = 2,
        res_critical_ratio = 1,
        speed = 3,
    },

    [303] = {
        abnormal_attr_ratio = 3,
        attack = 1,
        critical_damage = 2,
        critical_ratio = 1,
        cure_critical_ratio = 2,
        defense = 5,
        maxhp = 5,
        partner_type = 303,
        res_abnormal_ratio = 2,
        res_critical_ratio = 4,
        speed = 2,
    },

    [305] = {
        abnormal_attr_ratio = 1,
        attack = 1,
        critical_damage = 2,
        critical_ratio = 1,
        cure_critical_ratio = 2,
        defense = 4,
        maxhp = 4,
        partner_type = 305,
        res_abnormal_ratio = 2,
        res_critical_ratio = 2,
        speed = 4,
    },

    [306] = {
        abnormal_attr_ratio = 2,
        attack = 1,
        critical_damage = 2,
        critical_ratio = 1,
        cure_critical_ratio = 2,
        defense = 5,
        maxhp = 3,
        partner_type = 306,
        res_abnormal_ratio = 2,
        res_critical_ratio = 4,
        speed = 3,
    },

    [308] = {
        abnormal_attr_ratio = 2,
        attack = 5,
        critical_damage = 2,
        critical_ratio = 4,
        cure_critical_ratio = 2,
        defense = 1,
        maxhp = 1,
        partner_type = 308,
        res_abnormal_ratio = 2,
        res_critical_ratio = 1,
        speed = 2,
    },

    [311] = {
        abnormal_attr_ratio = 1,
        attack = 5,
        critical_damage = 2,
        critical_ratio = 4,
        cure_critical_ratio = 2,
        defense = 1,
        maxhp = 1,
        partner_type = 311,
        res_abnormal_ratio = 2,
        res_critical_ratio = 2,
        speed = 5,
    },

    [312] = {
        abnormal_attr_ratio = 5,
        attack = 4,
        critical_damage = 2,
        critical_ratio = 4,
        cure_critical_ratio = 2,
        defense = 3,
        maxhp = 2,
        partner_type = 312,
        res_abnormal_ratio = 2,
        res_critical_ratio = 2,
        speed = 2,
    },

    [313] = {
        abnormal_attr_ratio = 1,
        attack = 3,
        critical_damage = 2,
        critical_ratio = 2,
        cure_critical_ratio = 2,
        defense = 1,
        maxhp = 3,
        partner_type = 313,
        res_abnormal_ratio = 2,
        res_critical_ratio = 1,
        speed = 3,
    },

    [314] = {
        abnormal_attr_ratio = 1,
        attack = 1,
        critical_damage = 2,
        critical_ratio = 2,
        cure_critical_ratio = 2,
        defense = 4,
        maxhp = 3,
        partner_type = 314,
        res_abnormal_ratio = 2,
        res_critical_ratio = 4,
        speed = 5,
    },

    [315] = {
        abnormal_attr_ratio = 1,
        attack = 4,
        critical_damage = 2,
        critical_ratio = 4,
        cure_critical_ratio = 2,
        defense = 3,
        maxhp = 1,
        partner_type = 315,
        res_abnormal_ratio = 2,
        res_critical_ratio = 3,
        speed = 2,
    },

    [316] = {
        abnormal_attr_ratio = 1,
        attack = 2,
        critical_damage = 2,
        critical_ratio = 1,
        cure_critical_ratio = 2,
        defense = 3,
        maxhp = 2,
        partner_type = 316,
        res_abnormal_ratio = 2,
        res_critical_ratio = 3,
        speed = 5,
    },

    [401] = {
        abnormal_attr_ratio = 1,
        attack = 4,
        critical_damage = 2,
        critical_ratio = 4,
        cure_critical_ratio = 2,
        defense = 2,
        maxhp = 2,
        partner_type = 401,
        res_abnormal_ratio = 2,
        res_critical_ratio = 1,
        speed = 2,
    },

    [402] = {
        abnormal_attr_ratio = 3,
        attack = 4,
        critical_damage = 2,
        critical_ratio = 1,
        cure_critical_ratio = 2,
        defense = 2,
        maxhp = 3,
        partner_type = 402,
        res_abnormal_ratio = 2,
        res_critical_ratio = 1,
        speed = 1,
    },

    [403] = {
        abnormal_attr_ratio = 3,
        attack = 2,
        critical_damage = 2,
        critical_ratio = 4,
        cure_critical_ratio = 2,
        defense = 2,
        maxhp = 3,
        partner_type = 403,
        res_abnormal_ratio = 2,
        res_critical_ratio = 1,
        speed = 2,
    },

    [404] = {
        abnormal_attr_ratio = 2,
        attack = 5,
        critical_damage = 2,
        critical_ratio = 4,
        cure_critical_ratio = 2,
        defense = 1,
        maxhp = 2,
        partner_type = 404,
        res_abnormal_ratio = 2,
        res_critical_ratio = 2,
        speed = 3,
    },

    [405] = {
        abnormal_attr_ratio = 1,
        attack = 3,
        critical_damage = 2,
        critical_ratio = 1,
        cure_critical_ratio = 2,
        defense = 4,
        maxhp = 1,
        partner_type = 405,
        res_abnormal_ratio = 2,
        res_critical_ratio = 2,
        speed = 1,
    },

    [407] = {
        abnormal_attr_ratio = 1,
        attack = 4,
        critical_damage = 2,
        critical_ratio = 4,
        cure_critical_ratio = 2,
        defense = 2,
        maxhp = 2,
        partner_type = 407,
        res_abnormal_ratio = 2,
        res_critical_ratio = 2,
        speed = 4,
    },

    [409] = {
        abnormal_attr_ratio = 1,
        attack = 2,
        critical_damage = 2,
        critical_ratio = 1,
        cure_critical_ratio = 2,
        defense = 3,
        maxhp = 2,
        partner_type = 409,
        res_abnormal_ratio = 2,
        res_critical_ratio = 3,
        speed = 4,
    },

    [410] = {
        abnormal_attr_ratio = 5,
        attack = 2,
        critical_damage = 2,
        critical_ratio = 4,
        cure_critical_ratio = 2,
        defense = 3,
        maxhp = 4,
        partner_type = 410,
        res_abnormal_ratio = 2,
        res_critical_ratio = 3,
        speed = 1,
    },

    [412] = {
        abnormal_attr_ratio = 3,
        attack = 1,
        critical_damage = 2,
        critical_ratio = 2,
        cure_critical_ratio = 2,
        defense = 5,
        maxhp = 4,
        partner_type = 412,
        res_abnormal_ratio = 2,
        res_critical_ratio = 4,
        speed = 2,
    },

    [413] = {
        abnormal_attr_ratio = 3,
        attack = 2,
        critical_damage = 2,
        critical_ratio = 4,
        cure_critical_ratio = 2,
        defense = 2,
        maxhp = 3,
        partner_type = 413,
        res_abnormal_ratio = 2,
        res_critical_ratio = 1,
        speed = 4,
    },

    [414] = {
        abnormal_attr_ratio = 2,
        attack = 3,
        critical_damage = 2,
        critical_ratio = 2,
        cure_critical_ratio = 2,
        defense = 2,
        maxhp = 3,
        partner_type = 414,
        res_abnormal_ratio = 2,
        res_critical_ratio = 2,
        speed = 2,
    },

    [415] = {
        abnormal_attr_ratio = 5,
        attack = 5,
        critical_damage = 2,
        critical_ratio = 4,
        cure_critical_ratio = 2,
        defense = 3,
        maxhp = 1,
        partner_type = 415,
        res_abnormal_ratio = 2,
        res_critical_ratio = 2,
        speed = 3,
    },

    [416] = {
        abnormal_attr_ratio = 2,
        attack = 4,
        critical_damage = 2,
        critical_ratio = 2,
        cure_critical_ratio = 2,
        defense = 1,
        maxhp = 2,
        partner_type = 416,
        res_abnormal_ratio = 2,
        res_critical_ratio = 1,
        speed = 2,
    },

    [417] = {
        abnormal_attr_ratio = 1,
        attack = 3,
        critical_damage = 2,
        critical_ratio = 2,
        cure_critical_ratio = 2,
        defense = 3,
        maxhp = 3,
        partner_type = 417,
        res_abnormal_ratio = 2,
        res_critical_ratio = 3,
        speed = 1,
    },

    [418] = {
        abnormal_attr_ratio = 3,
        attack = 2,
        critical_damage = 2,
        critical_ratio = 2,
        cure_critical_ratio = 2,
        defense = 1,
        maxhp = 3,
        partner_type = 418,
        res_abnormal_ratio = 2,
        res_critical_ratio = 1,
        speed = 3,
    },

    [501] = {
        abnormal_attr_ratio = 3,
        attack = 2,
        critical_damage = 2,
        critical_ratio = 1,
        cure_critical_ratio = 2,
        defense = 4,
        maxhp = 4,
        partner_type = 501,
        res_abnormal_ratio = 2,
        res_critical_ratio = 3,
        speed = 5,
    },

    [502] = {
        abnormal_attr_ratio = 3,
        attack = 2,
        critical_damage = 2,
        critical_ratio = 2,
        cure_critical_ratio = 2,
        defense = 2,
        maxhp = 4,
        partner_type = 502,
        res_abnormal_ratio = 2,
        res_critical_ratio = 2,
        speed = 4,
    },

    [503] = {
        abnormal_attr_ratio = 3,
        attack = 1,
        critical_damage = 2,
        critical_ratio = 1,
        cure_critical_ratio = 2,
        defense = 1,
        maxhp = 2,
        partner_type = 503,
        res_abnormal_ratio = 2,
        res_critical_ratio = 2,
        speed = 3,
    },

    [504] = {
        abnormal_attr_ratio = 1,
        attack = 4,
        critical_damage = 2,
        critical_ratio = 4,
        cure_critical_ratio = 2,
        defense = 3,
        maxhp = 1,
        partner_type = 504,
        res_abnormal_ratio = 2,
        res_critical_ratio = 3,
        speed = 3,
    },

    [505] = {
        abnormal_attr_ratio = 1,
        attack = 1,
        critical_damage = 2,
        critical_ratio = 2,
        cure_critical_ratio = 2,
        defense = 5,
        maxhp = 2,
        partner_type = 505,
        res_abnormal_ratio = 2,
        res_critical_ratio = 4,
        speed = 5,
    },

    [506] = {
        abnormal_attr_ratio = 1,
        attack = 2,
        critical_damage = 2,
        critical_ratio = 2,
        cure_critical_ratio = 2,
        defense = 2,
        maxhp = 5,
        partner_type = 506,
        res_abnormal_ratio = 2,
        res_critical_ratio = 1,
        speed = 2,
    },

    [507] = {
        abnormal_attr_ratio = 3,
        attack = 4,
        critical_damage = 2,
        critical_ratio = 1,
        cure_critical_ratio = 2,
        defense = 3,
        maxhp = 2,
        partner_type = 507,
        res_abnormal_ratio = 2,
        res_critical_ratio = 3,
        speed = 2,
    },

    [508] = {
        abnormal_attr_ratio = 3,
        attack = 4,
        critical_damage = 2,
        critical_ratio = 4,
        cure_critical_ratio = 2,
        defense = 3,
        maxhp = 2,
        partner_type = 508,
        res_abnormal_ratio = 2,
        res_critical_ratio = 2,
        speed = 1,
    },

    [509] = {
        abnormal_attr_ratio = 3,
        attack = 3,
        critical_damage = 2,
        critical_ratio = 2,
        cure_critical_ratio = 2,
        defense = 3,
        maxhp = 3,
        partner_type = 509,
        res_abnormal_ratio = 2,
        res_critical_ratio = 3,
        speed = 1,
    },

    [510] = {
        abnormal_attr_ratio = 3,
        attack = 1,
        critical_damage = 2,
        critical_ratio = 1,
        cure_critical_ratio = 2,
        defense = 4,
        maxhp = 3,
        partner_type = 510,
        res_abnormal_ratio = 2,
        res_critical_ratio = 4,
        speed = 3,
    },

    [511] = {
        abnormal_attr_ratio = 1,
        attack = 3,
        critical_damage = 2,
        critical_ratio = 2,
        cure_critical_ratio = 2,
        defense = 1,
        maxhp = 1,
        partner_type = 511,
        res_abnormal_ratio = 2,
        res_critical_ratio = 2,
        speed = 1,
    },

    [512] = {
        abnormal_attr_ratio = 3,
        attack = 2,
        critical_damage = 2,
        critical_ratio = 1,
        cure_critical_ratio = 2,
        defense = 4,
        maxhp = 2,
        partner_type = 512,
        res_abnormal_ratio = 2,
        res_critical_ratio = 4,
        speed = 3,
    },

    [513] = {
        abnormal_attr_ratio = 3,
        attack = 3,
        critical_damage = 2,
        critical_ratio = 1,
        cure_critical_ratio = 2,
        defense = 5,
        maxhp = 5,
        partner_type = 513,
        res_abnormal_ratio = 2,
        res_critical_ratio = 3,
        speed = 5,
    },

    [514] = {
        abnormal_attr_ratio = 3,
        attack = 2,
        critical_damage = 2,
        critical_ratio = 2,
        cure_critical_ratio = 2,
        defense = 2,
        maxhp = 4,
        partner_type = 514,
        res_abnormal_ratio = 2,
        res_critical_ratio = 1,
        speed = 4,
    },

    [318] = {
        abnormal_attr_ratio = 1,
        attack = 1,
        critical_damage = 1,
        critical_ratio = 1,
        cure_critical_ratio = 1,
        defense = 1,
        maxhp = 1,
        partner_type = 318,
        res_abnormal_ratio = 1,
        res_critical_ratio = 1,
        speed = 1,
    },

}
