-- ./excel/partner/partner_convert_power.xlsx
return {

    [301] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 301,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 5497,
    },

    [302] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 302,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 5364,
    },

    [303] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 303,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 6561,
    },

    [305] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 305,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 150,
        speed = 200,
        sub_power = 5231,
    },

    [306] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 306,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 150,
        speed = 200,
        sub_power = 5564,
    },

    [308] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 308,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 5963,
    },

    [311] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 311,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 4500,
    },

    [312] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 312,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 6428,
    },

    [313] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 313,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 5763,
    },

    [314] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 314,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 4566,
    },

    [315] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 315,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 150,
        speed = 200,
        sub_power = 6229,
    },

    [316] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 316,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 4699,
    },

    [318] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 318,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 150,
        speed = 200,
        sub_power = 3229,
    },

    [401] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 401,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 6362,
    },

    [402] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 402,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 6694,
    },

    [403] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 403,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 5896,
    },

    [404] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 404,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 5404,
    },

    [405] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 405,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 150,
        speed = 200,
        sub_power = 6628,
    },

    [407] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 407,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 5032,
    },

    [409] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 409,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 4965,
    },

    [410] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 410,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 7027,
    },

    [412] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 412,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 6495,
    },

    [413] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 413,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 5165,
    },

    [414] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 414,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 6096,
    },

    [415] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 415,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 5830,
    },

    [416] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 416,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 6029,
    },

    [417] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 417,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 7093,
    },

    [418] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 418,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 150,
        speed = 200,
        sub_power = 5697,
    },

    [501] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 501,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 4633,
    },

    [502] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 502,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 5098,
    },

    [503] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 503,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 5298,
    },

    [504] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 504,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 5630,
    },

    [505] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 505,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 4766,
    },

    [506] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 506,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 6162,
    },

    [507] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 507,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 6295,
    },

    [508] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 508,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 6894,
    },

    [509] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 509,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 6960,
    },

    [510] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 510,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 150,
        speed = 200,
        sub_power = 5298,
    },

    [511] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 511,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 150,
        speed = 200,
        sub_power = 6827,
    },

    [512] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 512,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 150,
        speed = 200,
        sub_power = 5697,
    },

    [513] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 513,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 4832,
    },

    [514] = {
        abnormal_attr_ratio = 50,
        attack = 100,
        critical_damage = 20,
        critical_ratio = 50,
        cure_critical_ratio = 30,
        defense = 100,
        id = 514,
        maxhp = 20,
        res_abnormal_ratio = 50,
        res_critical_ratio = 50,
        skill = 50,
        speed = 200,
        sub_power = 4899,
    },

}
