-- ./excel/store/currencyguide.xlsx
return {

    [1] = {
        blockkey = "task",
        cls_name = "CTaskMainView",
        control_key = "task",
        desc = "完成游戏任务可获得",
        go_inwar = 1,
        id = 1,
        name = "委托",
        need_close = 0,
        open_id = 1012,
    },

    [2] = {
        blockkey = "trapmine",
        cls_name = "CMapMainView",
        control_key = "trapmine",
        desc = "在探索战斗中可获得",
        go_inwar = 1,
        id = 2,
        name = "探索",
        need_close = 0,
        open_id = 1011,
    },

    [3] = {
        blockkey = "pata",
        cls_name = "CPaTaView",
        control_key = "pata",
        desc = "在地牢战斗中可获得",
        go_inwar = 1,
        id = 3,
        name = "地牢",
        need_close = 0,
        open_id = 1003,
    },

    [4] = {
        blockkey = "treasure",
        cls_name = "CTreasureDescView",
        control_key = "treasure",
        desc = "在星象图宝箱中获得",
        go_inwar = 1,
        id = 4,
        name = "星象图",
        need_close = 0,
        open_id = 1010,
    },

    [5] = {
        blockkey = "shop",
        cls_name = "CNpcShopView",
        control_key = "shop",
        desc = "在杂货勋章页中购买",
        go_inwar = 0,
        id = 5,
        name = "勋章商店",
        need_close = 0,
        open_id = 504,
    },

    [6] = {
        blockkey = "schedule",
        cls_name = "CScheduleMainView",
        control_key = "schedule",
        desc = "完成日常任务可获得",
        go_inwar = 0,
        id = 6,
        name = "每日必做",
        need_close = 0,
        open_id = 702,
    },

    [7] = {
        blockkey = "worldboss",
        cls_name = "CWorldBossView",
        control_key = "worldboss",
        desc = "通关封印之地可获得",
        go_inwar = 1,
        id = 7,
        name = "封印之地",
        need_close = 0,
        open_id = 1006,
    },

    [8] = {
        blockkey = "arenagame",
        cls_name = "CArenaView",
        control_key = "arenagame",
        desc = "竞技玩法可获得荣誉",
        go_inwar = 1,
        id = 8,
        name = "竞技",
        need_close = 0,
        open_id = 1056,
    },

    [9] = {
        blockkey = "org",
        cls_name = "COrgChamberView",
        control_key = "org",
        desc = "完成公会建设可获得",
        go_inwar = 1,
        id = 9,
        name = "公会建设",
        need_close = 0,
        open_id = 601,
    },

    [10] = {
        blockkey = "shop",
        cls_name = "",
        control_key = "shop",
        desc = "可使用彩晶直接兑换",
        go_inwar = 1,
        id = 10,
        name = "兑换",
        need_close = 1,
        open_id = 1020,
    },

    [11] = {
        blockkey = "welfare",
        cls_name = "CWelfareView",
        control_key = "welfare",
        desc = "月卡特权每天可获得",
        go_inwar = 0,
        id = 11,
        name = "月卡",
        need_close = 0,
        open_id = 1018,
    },

    [12] = {
        blockkey = "achieve",
        cls_name = "CAchieveMainView",
        control_key = "achieve",
        desc = "达成成就可获得水晶",
        go_inwar = 0,
        id = 12,
        name = "成就",
        need_close = 0,
        open_id = 1016,
    },

    [13] = {
        blockkey = "org",
        cls_name = "COrgActivityCenterView",
        control_key = "org",
        desc = "参与公会活动可获得",
        go_inwar = 1,
        id = 13,
        name = "公会活动",
        need_close = 0,
        open_id = 603,
    },

    [14] = {
        blockkey = "welfare",
        cls_name = "CWelfareView",
        control_key = "welfare",
        desc = "购买成长基金可获得",
        go_inwar = 0,
        id = 14,
        name = "成长基金",
        need_close = 0,
        open_id = 1019,
    },

    [15] = {
        blockkey = "shop",
        cls_name = "CExchangeCoinView",
        control_key = "shop",
        desc = "可使用水晶直接兑换",
        go_inwar = 0,
        id = 15,
        name = "兑换",
        need_close = 1,
        open_id = 1017,
    },

    [16] = {
        blockkey = "shop",
        cls_name = "",
        control_key = "shop",
        desc = "可通过充值购买水晶",
        go_inwar = 0,
        id = 16,
        name = "充值",
        need_close = 1,
        open_id = 1034,
    },

    [17] = {
        blockkey = "shop",
        cls_name = "",
        control_key = "shop",
        desc = "可通过购买礼包获得",
        go_inwar = 0,
        id = 17,
        name = "礼包",
        need_close = 1,
        open_id = 512,
    },

    [18] = {
        blockkey = "MonsterAtk",
        cls_name = "CMonsterAtkCityMainView",
        control_key = "msattack",
        desc = "怪物攻城可获得勋章",
        go_inwar = 1,
        id = 18,
        name = "怪物攻城",
        need_close = 0,
        open_id = 1036,
    },

}
