-- ./excel/store/goldcoinstore.xlsx
return {

    [1001] = {
        RMB = 6,
        desc = "安卓充值",
        first_reward = 60,
        gold_coin_gains = 60,
        icon = "n1_bao_1",
        id = 1001,
        payid = "com.kaopu.ylq.6",
        reward_gold_coin = 0,
        reward_id = {},
        spc_key = "",
        tag = 0,
    },

    [1002] = {
        RMB = 12,
        desc = "",
        first_reward = 120,
        gold_coin_gains = 120,
        icon = "n1_bao_2",
        id = 1002,
        payid = "com.kaopu.ylq.12",
        reward_gold_coin = 0,
        reward_id = {},
        spc_key = "",
        tag = 0,
    },

    [1003] = {
        RMB = 30,
        desc = "",
        first_reward = 300,
        gold_coin_gains = 300,
        icon = "n1_bao_3",
        id = 1003,
        payid = "com.kaopu.ylq.30",
        reward_gold_coin = 0,
        reward_id = {},
        spc_key = "",
        tag = 0,
    },

    [1004] = {
        RMB = 68,
        desc = "",
        first_reward = 680,
        gold_coin_gains = 680,
        icon = "n1_bao_4",
        id = 1004,
        payid = "com.kaopu.ylq.68",
        reward_gold_coin = 0,
        reward_id = {},
        spc_key = "",
        tag = 0,
    },

    [1005] = {
        RMB = 128,
        desc = "",
        first_reward = 1280,
        gold_coin_gains = 1280,
        icon = "n1_bao_5",
        id = 1005,
        payid = "com.kaopu.ylq.128",
        reward_gold_coin = 0,
        reward_id = {},
        spc_key = "",
        tag = 1,
    },

    [1006] = {
        RMB = 328,
        desc = "",
        first_reward = 3280,
        gold_coin_gains = 3280,
        icon = "n1_bao_6",
        id = 1006,
        payid = "com.kaopu.ylq.328",
        reward_gold_coin = 0,
        reward_id = {1005},
        spc_key = "",
        tag = 1,
    },

    [1007] = {
        RMB = 648,
        desc = "",
        first_reward = 6480,
        gold_coin_gains = 6480,
        icon = "n1_bao_7",
        id = 1007,
        payid = "com.kaopu.ylq.648",
        reward_gold_coin = 0,
        reward_id = {1006},
        spc_key = "",
        tag = 1,
    },

    [1008] = {
        RMB = 0,
        desc = "",
        first_reward = 0,
        gold_coin_gains = 10,
        icon = "n1_bao_8",
        id = 1008,
        payid = "com.kaopu.ylq.001",
        reward_gold_coin = 0,
        reward_id = {},
        spc_key = "",
        tag = 0,
    },

    [2001] = {
        RMB = 6,
        desc = "ios充值",
        first_reward = 60,
        gold_coin_gains = 60,
        icon = "n1_bao_1",
        id = 2001,
        payid = "com.kaopu.ylq.appstore.6",
        reward_gold_coin = 0,
        reward_id = {},
        spc_key = "",
        tag = 0,
    },

    [2002] = {
        RMB = 12,
        desc = "",
        first_reward = 120,
        gold_coin_gains = 120,
        icon = "n1_bao_2",
        id = 2002,
        payid = "com.kaopu.ylq.appstore.12",
        reward_gold_coin = 0,
        reward_id = {},
        spc_key = "",
        tag = 0,
    },

    [2003] = {
        RMB = 30,
        desc = "",
        first_reward = 300,
        gold_coin_gains = 300,
        icon = "n1_bao_3",
        id = 2003,
        payid = "com.kaopu.ylq.appstore.30",
        reward_gold_coin = 0,
        reward_id = {},
        spc_key = "",
        tag = 0,
    },

    [2004] = {
        RMB = 68,
        desc = "",
        first_reward = 680,
        gold_coin_gains = 680,
        icon = "n1_bao_4",
        id = 2004,
        payid = "com.kaopu.ylq.appstore.68",
        reward_gold_coin = 0,
        reward_id = {},
        spc_key = "",
        tag = 0,
    },

    [2005] = {
        RMB = 128,
        desc = "",
        first_reward = 1280,
        gold_coin_gains = 1280,
        icon = "n1_bao_5",
        id = 2005,
        payid = "com.kaopu.ylq.appstore.128",
        reward_gold_coin = 0,
        reward_id = {},
        spc_key = "",
        tag = 1,
    },

    [2006] = {
        RMB = 328,
        desc = "",
        first_reward = 3280,
        gold_coin_gains = 3280,
        icon = "n1_bao_6",
        id = 2006,
        payid = "com.kaopu.ylq.appstore.328",
        reward_gold_coin = 0,
        reward_id = {1005},
        spc_key = "",
        tag = 1,
    },

    [2007] = {
        RMB = 648,
        desc = "",
        first_reward = 6480,
        gold_coin_gains = 6480,
        icon = "n1_bao_7",
        id = 2007,
        payid = "com.kaopu.ylq.appstore.648",
        reward_gold_coin = 0,
        reward_id = {1006},
        spc_key = "",
        tag = 1,
    },

}
