-- ./excel/store/store.xlsx
return {

    [201] = {
        coin_typ = 1,
        icon = "text_cebiaoqian_zhuangbei1",
        id = 201,
        name = "装备",
        open_grade = 1,
        refresh_rule = 0,
        refresh_tips = "",
        select_item = 0,
        selected_icon = "text_cebiaoqian_zhuangbei2",
        show_limit = 0,
    },

    [202] = {
        coin_typ = 1,
        icon = "text_cebiaoqian_huoban1",
        id = 202,
        name = "伙伴",
        open_grade = 1,
        refresh_rule = 0,
        refresh_tips = "",
        select_item = 0,
        selected_icon = "text_cebiaoqian_huoban2",
        show_limit = 0,
    },

    [203] = {
        coin_typ = 2,
        icon = "",
        id = 203,
        name = "全部",
        open_grade = 1,
        refresh_rule = 0,
        refresh_tips = "",
        select_item = 0,
        selected_icon = "",
        show_limit = 0,
    },

    [204] = {
        coin_typ = 3,
        icon = "text_cebiaoqian_xunzhang1",
        id = 204,
        name = "勋章",
        open_grade = 1,
        refresh_rule = 1003,
        refresh_tips = "【每天0点自动刷新】",
        select_item = 10,
        selected_icon = "text_cebiaoqian_xunzhang2",
        show_limit = 1,
    },

    [205] = {
        coin_typ = 4,
        icon = "text_cebiaoqian_yongyu1",
        id = 205,
        name = "荣誉",
        open_grade = 1,
        refresh_rule = 0,
        refresh_tips = "",
        select_item = 0,
        selected_icon = "text_cebiaoqian_yongyu2",
        show_limit = 1,
    },

    [206] = {
        coin_typ = 2,
        icon = "",
        id = 206,
        name = "全部",
        open_grade = 1,
        refresh_rule = 0,
        refresh_tips = "",
        select_item = 0,
        selected_icon = "",
        show_limit = 1,
    },

    [207] = {
        coin_typ = 6,
        icon = "text_cebiaoqian_gongxian1",
        id = 207,
        name = "贡献",
        open_grade = 1,
        refresh_rule = 0,
        refresh_tips = "",
        select_item = 0,
        selected_icon = "text_cebiaoqian_gongxian2",
        show_limit = 0,
    },

    [208] = {
        coin_typ = 5,
        icon = "text_cebiaoqian_huoyue1",
        id = 208,
        name = "活跃",
        open_grade = 1,
        refresh_rule = 0,
        refresh_tips = "",
        select_item = 0,
        selected_icon = "text_cebiaoqian_huoyue2",
        show_limit = 1,
    },

    [209] = {
        coin_typ = 7,
        icon = "",
        id = 209,
        name = "公会福利",
        open_grade = 1,
        refresh_rule = 0,
        refresh_tips = "",
        select_item = 0,
        selected_icon = "",
        show_limit = 1,
    },

    [210] = {
        coin_typ = 9,
        icon = "",
        id = 210,
        name = "常用",
        open_grade = 1,
        refresh_rule = 0,
        refresh_tips = "皮肤券可通过礼包商店、勋章商店和星象图等途径获得",
        select_item = 0,
        selected_icon = "",
        show_limit = 0,
    },

    [211] = {
        coin_typ = 10,
        icon = "",
        id = 211,
        name = "奇遇商人",
        open_grade = 1,
        refresh_rule = 0,
        refresh_tips = "",
        select_item = 0,
        selected_icon = "",
        show_limit = 0,
    },

    [212] = {
        coin_typ = 1,
        icon = "text_cebiaoqian_changyong1",
        id = 212,
        name = "常用",
        open_grade = 1,
        refresh_rule = 0,
        refresh_tips = "",
        select_item = 0,
        selected_icon = "text_cebiaoqian_changyong2",
        show_limit = 0,
    },

    [213] = {
        coin_typ = 2,
        icon = "text_cebiaoqian_jinbi1",
        id = 213,
        name = "金币",
        open_grade = 1,
        refresh_rule = 0,
        refresh_tips = "",
        select_item = 0,
        selected_icon = "text_cebiaoqian_jinbi2",
        show_limit = 0,
    },

    [214] = {
        coin_typ = 12,
        icon = "",
        id = 214,
        name = "彩晶",
        open_grade = 1,
        refresh_rule = 0,
        refresh_tips = "",
        select_item = 0,
        selected_icon = "",
        show_limit = 0,
    },

    [215] = {
        coin_typ = 12,
        icon = "",
        id = 215,
        name = "限定",
        open_grade = 1,
        refresh_rule = 0,
        refresh_tips = "",
        select_item = 0,
        selected_icon = "",
        show_limit = 0,
    },

}
