-- ./excel/huodong/chapterfb/chapter.xlsx
return {

    [1] = {
        content = "（吹口哨）对面的小姐姐看过来~看过来看过来~",
        emoji = "",
        end_time = 5.0,
        id = 1,
        key = 1,
        level = 1,
        sort = 1,
        start_time = 2.0,
    },

    [2] = {
        content = "再吵信不信我把你打进墙里抠都抠不出来！",
        emoji = "",
        end_time = 5.0,
        id = 1,
        key = 2,
        level = 2,
        sort = 2,
        start_time = 7.0,
    },

    [3] = {
        content = "",
        emoji = "weiqu",
        end_time = 3.0,
        id = 1,
        key = 3,
        level = 1,
        sort = 3,
        start_time = 12.0,
    },

    [4] = {
        content = "游戏禁止欺负主角！",
        emoji = "",
        end_time = 3.0,
        id = 2,
        key = 4,
        level = 3,
        sort = 1,
        start_time = 2.0,
    },

    [5] = {
        content = "警察叔叔你再过来我就喊了！",
        emoji = "",
        end_time = 4.0,
        id = 2,
        key = 5,
        level = 2,
        sort = 2,
        start_time = 5.0,
    },

    [6] = {
        content = "喊吧，你喊再大声也没人救你！",
        emoji = "",
        end_time = 4.0,
        id = 2,
        key = 6,
        level = 3,
        sort = 3,
        start_time = 9.0,
    },

    [7] = {
        content = "",
        emoji = "weiqu",
        end_time = 3.0,
        id = 2,
        key = 7,
        level = 2,
        sort = 4,
        start_time = 13.0,
    },

    [8] = {
        content = "走！放学咱两去喝一杯！",
        emoji = "",
        end_time = 4.0,
        id = 3,
        key = 8,
        level = 3,
        sort = 1,
        start_time = 2.0,
    },

    [9] = {
        content = "看你走路不稳的样子，该不会喝的是假酒吧……",
        emoji = "",
        end_time = 5.0,
        id = 3,
        key = 9,
        level = 4,
        sort = 2,
        start_time = 6.0,
    },

    [10] = {
        content = "哥俩好啊，走一个呀！",
        emoji = "",
        end_time = 4.0,
        id = 3,
        key = 10,
        level = 3,
        sort = 3,
        start_time = 11.0,
    },

    [11] = {
        content = "你到底走不走？",
        emoji = "",
        end_time = 3.0,
        id = 3,
        key = 11,
        level = 3,
        sort = 4,
        start_time = 15.0,
    },

    [12] = {
        content = "武道讲究用心，只要肯用心上天都不是难题！",
        emoji = "",
        end_time = 5.0,
        id = 4,
        key = 12,
        level = 4,
        sort = 1,
        start_time = 2.0,
    },

    [13] = {
        content = "让已经在空中的我情何以堪。",
        emoji = "",
        end_time = 3.0,
        id = 4,
        key = 13,
        level = 5,
        sort = 2,
        start_time = 7.0,
    },

    [14] = {
        content = "",
        emoji = "wuyu1",
        end_time = 3.0,
        id = 4,
        key = 14,
        level = 4,
        sort = 3,
        start_time = 10.0,
    },

    [15] = {
        content = "告诉我，你是不是认识我？",
        emoji = "",
        end_time = 4.0,
        id = 5,
        key = 15,
        level = 5,
        sort = 1,
        start_time = 2.0,
    },

    [16] = {
        content = "你不就是我幽溟镇上大叔公的堂妹的表舅家失散多年的二崽子的邻居的……",
        emoji = "",
        end_time = 5.0,
        id = 5,
        key = 16,
        level = 6,
        sort = 2,
        start_time = 6.0,
    },

    [17] = {
        content = "",
        emoji = "zhenjing",
        end_time = 3.0,
        id = 5,
        key = 17,
        level = 5,
        sort = 3,
        start_time = 11.0,
    },

    [18] = {
        content = "（亮出针剂）只要你乖乖听话，我一定会好好对待你的。",
        emoji = "",
        end_time = 5.0,
        id = 6,
        key = 18,
        level = 6,
        sort = 1,
        start_time = 2.0,
    },

    [19] = {
        content = "嘟噜！",
        emoji = "",
        end_time = 3.0,
        id = 6,
        key = 19,
        level = 7,
        sort = 2,
        start_time = 7.0,
    },

    [20] = {
        content = "站住别动，乖",
        emoji = "",
        end_time = 3.0,
        id = 6,
        key = 20,
        level = 6,
        sort = 3,
        start_time = 10.0,
    },

    [21] = {
        content = "",
        emoji = "shengqi",
        end_time = 3.0,
        id = 6,
        key = 21,
        level = 7,
        sort = 4,
        start_time = 13.0,
    },

    [22] = {
        content = "嘟嘟噜嘟嘟噜~嘟嘟噜嘟嘟噜~",
        emoji = "",
        end_time = 4.0,
        id = 7,
        key = 22,
        level = 7,
        sort = 1,
        start_time = 2.0,
    },

    [23] = {
        content = "哎呀哎呀~想不到你也看龙猫呀~",
        emoji = "",
        end_time = 4.0,
        id = 7,
        key = 23,
        level = 8,
        sort = 2,
        start_time = 6.0,
    },

    [24] = {
        content = "哎呀哎呀~你好面熟，从哪里来的我们以前认识吗？",
        emoji = "",
        end_time = 5.0,
        id = 7,
        key = 24,
        level = 8,
        sort = 3,
        start_time = 10.0,
    },

    [25] = {
        content = "我不记得了，你是谁?是不是认识我？",
        emoji = "",
        end_time = 4.0,
        id = 7,
        key = 25,
        level = 5,
        sort = 4,
        start_time = 15.0,
    },

    [26] = {
        content = "哎呀哎呀~第一次搭讪失败了呢。",
        emoji = "",
        end_time = 4.0,
        id = 7,
        key = 26,
        level = 8,
        sort = 5,
        start_time = 19.0,
    },

    [27] = {
        content = "",
        emoji = "wuyu3",
        end_time = 3.0,
        id = 7,
        key = 27,
        level = 5,
        sort = 6,
        start_time = 13.0,
    },

    [28] = {
        content = "嘎嘎嘎嘎嘎嘎嘎！",
        emoji = "",
        end_time = 3.0,
        id = 8,
        key = 28,
        level = 1,
        sort = 1,
        start_time = 2.0,
    },

    [29] = {
        content = "不得了，不得了，你都长这样了还会鸭子叫？",
        emoji = "",
        end_time = 5.0,
        id = 8,
        key = 29,
        level = 2,
        sort = 2,
        start_time = 5.0,
    },

    [30] = {
        content = "哈哈哈哈哈哈哈哈哈！笑死我了。",
        emoji = "",
        end_time = 4.0,
        id = 8,
        key = 30,
        level = 2,
        sort = 3,
        start_time = 10.0,
    },

    [31] = {
        content = "",
        emoji = "shengqi",
        end_time = 2.0,
        id = 8,
        key = 31,
        level = 1,
        sort = 4,
        start_time = 14.0,
    },

    [32] = {
        content = "啦啦啦啦~！我将会成为宇宙第一强者！哈哈哈~",
        emoji = "",
        end_time = 5.0,
        id = 9,
        key = 32,
        level = 2,
        sort = 1,
        start_time = 2.0,
    },

    [33] = {
        content = "各位不好意思她今天没吃药。",
        emoji = "",
        end_time = 4.0,
        id = 9,
        key = 33,
        level = 3,
        sort = 2,
        start_time = 7.0,
    },

    [34] = {
        content = "",
        emoji = "shenqi",
        end_time = 3.0,
        id = 9,
        key = 34,
        level = 2,
        sort = 3,
        start_time = 11.0,
    },

    [35] = {
        content = "你个神经病，我要报警，喂喂，请问是110吗？",
        emoji = "",
        end_time = 5.0,
        id = 9,
        key = 35,
        level = 3,
        sort = 4,
        start_time = 14.0,
    },

    [36] = {
        content = "不，这里是107。",
        emoji = "",
        end_time = 3.0,
        id = 9,
        key = 36,
        level = 4,
        sort = 5,
        start_time = 19.0,
    },

    [37] = {
        content = "",
        emoji = "zhenjing",
        end_time = 3.0,
        id = 9,
        key = 37,
        level = 3,
        sort = 6,
        start_time = 22.0,
    },

    [38] = {
        content = "你头上戴着的是包子吗？",
        emoji = "",
        end_time = 4.0,
        id = 10,
        key = 38,
        level = 4,
        sort = 1,
        start_time = 2.0,
    },

    [39] = {
        content = "是啊！储备粮每天一换保证新鲜，吃吗？",
        emoji = "",
        end_time = 5.0,
        id = 10,
        key = 39,
        level = 5,
        sort = 2,
        start_time = 6.0,
    },

    [40] = {
        content = "",
        emoji = "wuyu1",
        end_time = 3.0,
        id = 10,
        key = 40,
        level = 4,
        sort = 3,
        start_time = 11.0,
    },

    [41] = {
        content = "许愿三连，吃不胖、不掉发、脱单！",
        emoji = "",
        end_time = 4.0,
        id = 11,
        key = 41,
        level = 5,
        sort = 1,
        start_time = 2.0,
    },

    [42] = {
        content = "不好意思，观绪没有许愿功能。",
        emoji = "",
        end_time = 4.0,
        id = 11,
        key = 42,
        level = 6,
        sort = 2,
        start_time = 6.0,
    },

    [43] = {
        content = "",
        emoji = "wuyu3",
        end_time = 2.0,
        id = 11,
        key = 43,
        level = 6,
        sort = 3,
        start_time = 10.0,
    },

    [44] = {
        content = "",
        emoji = "mengbi",
        end_time = 2.0,
        id = 11,
        key = 44,
        level = 5,
        sort = 4,
        start_time = 12.0,
    },

    [45] = {
        content = "知道吗，你跟我的画风很不一样唉！",
        emoji = "",
        end_time = 4.0,
        id = 12,
        key = 45,
        level = 6,
        sort = 1,
        start_time = 2.0,
    },

    [46] = {
        content = "Whatever，咱都在妖灵契里。",
        emoji = "",
        end_time = 4.0,
        id = 12,
        key = 46,
        level = 7,
        sort = 2,
        start_time = 6.0,
    },

    [47] = {
        content = "",
        emoji = "kaixin",
        end_time = 3.0,
        id = 12,
        key = 47,
        level = 6,
        sort = 3,
        start_time = 10.0,
    },

    [48] = {
        content = "请问保持好身材的秘诀是什么？",
        emoji = "",
        end_time = 4.0,
        id = 13,
        key = 48,
        level = 7,
        sort = 1,
        start_time = 2.0,
    },

    [49] = {
        content = "拒绝近视从我做起。",
        emoji = "",
        end_time = 3.0,
        id = 13,
        key = 49,
        level = 8,
        sort = 2,
        start_time = 6.0,
    },

    [50] = {
        content = "",
        emoji = "shengqi",
        end_time = 3.0,
        id = 13,
        key = 50,
        level = 7,
        sort = 3,
        start_time = 9.0,
    },

    [51] = {
        content = "敢在我面前装模作样？",
        emoji = "",
        end_time = 4.0,
        id = 14,
        key = 51,
        level = 8,
        sort = 1,
        start_time = 2.0,
    },

    [52] = {
        content = "嘎嘎嘎嘎！",
        emoji = "",
        end_time = 3.0,
        id = 14,
        key = 52,
        level = 1,
        sort = 2,
        start_time = 6.0,
    },

    [53] = {
        content = "说人话！",
        emoji = "",
        end_time = 3.0,
        id = 14,
        key = 53,
        level = 8,
        sort = 3,
        start_time = 9.0,
    },

    [54] = {
        content = "女王大人请务必收我为仆人！",
        emoji = "",
        end_time = 4.0,
        id = 14,
        key = 54,
        level = 1,
        sort = 4,
        start_time = 12.0,
    },

    [55] = {
        content = "（吼！吼！吼！）",
        emoji = "",
        end_time = 3.0,
        id = 15,
        key = 55,
        level = 1,
        sort = 1,
        start_time = 2.0,
    },

    [56] = {
        content = "百分百还原大猩猩cos。",
        emoji = "",
        end_time = 4.0,
        id = 15,
        key = 56,
        level = 2,
        sort = 2,
        start_time = 5.0,
    },

    [57] = {
        content = "（吼！狂锤胸口）",
        emoji = "",
        end_time = 3.0,
        id = 15,
        key = 57,
        level = 1,
        sort = 3,
        start_time = 9.0,
    },

    [58] = {
        content = "作为我寒冬的后备口粮，你要有一定觉悟。",
        emoji = "",
        end_time = 5.0,
        id = 16,
        key = 58,
        level = 2,
        sort = 1,
        start_time = 2.0,
    },

    [59] = {
        content = "嘟噜？",
        emoji = "",
        end_time = 3.0,
        id = 16,
        key = 59,
        level = 3,
        sort = 2,
        start_time = 7.0,
    },

    [60] = {
        content = "嘟嘟噜嘟嘟噜~嘟嘟噜嘟嘟噜~",
        emoji = "",
        end_time = 4.0,
        id = 16,
        key = 60,
        level = 3,
        sort = 3,
        start_time = 10.0,
    },

    [61] = {
        content = "再吵封号！",
        emoji = "",
        end_time = 3.0,
        id = 16,
        key = 61,
        level = 4,
        sort = 4,
        start_time = 14.0,
    },

    [62] = {
        content = "",
        emoji = "zhengjing",
        end_time = 3.0,
        id = 16,
        key = 62,
        level = 2,
        sort = 5,
        start_time = 17.0,
    },

    [63] = {
        content = "身为海龟你为什么要来沙漠？",
        emoji = "",
        end_time = 4.0,
        id = 17,
        key = 63,
        level = 4,
        sort = 1,
        start_time = 2.0,
    },

    [64] = {
        content = "为沙漠退耕还林添一抹绿。",
        emoji = "",
        end_time = 4.0,
        id = 17,
        key = 64,
        level = 5,
        sort = 2,
        start_time = 6.0,
    },

    [65] = {
        content = "给你36个赞！",
        emoji = "",
        end_time = 3.0,
        id = 17,
        key = 65,
        level = 4,
        sort = 3,
        start_time = 10.0,
    },

    [66] = {
        content = "少白头是什么感觉？",
        emoji = "",
        end_time = 4.0,
        id = 18,
        key = 66,
        level = 5,
        sort = 1,
        start_time = 2.0,
    },

    [67] = {
        content = "千年萝莉是什么感觉？",
        emoji = "",
        end_time = 4.0,
        id = 18,
        key = 67,
        level = 6,
        sort = 2,
        start_time = 6.0,
    },

    [68] = {
        content = "",
        emoji = "mihu",
        end_time = 3.0,
        id = 18,
        key = 68,
        level = 4,
        sort = 3,
        start_time = 10.0,
    },

    [69] = {
        content = "",
        emoji = "wuyu2",
        end_time = 3.0,
        id = 18,
        key = 69,
        level = 5,
        sort = 4,
        start_time = 13.0,
    },

    [70] = {
        content = "请你让时间停在这里，停在我最美丽的时刻！",
        emoji = "",
        end_time = 5.0,
        id = 19,
        key = 70,
        level = 6,
        sort = 1,
        start_time = 2.0,
    },

    [71] = {
        content = "青春永驻1秒体验时间到，请问是否要办理月卡或年卡？",
        emoji = "",
        end_time = 5.0,
        id = 19,
        key = 71,
        level = 7,
        sort = 2,
        start_time = 7.0,
    },

    [72] = {
        content = "",
        emoji = "mengbi",
        end_time = 3.0,
        id = 19,
        key = 72,
        level = 6,
        sort = 3,
        start_time = 11.0,
    },

    [73] = {
        content = "瞧瞧那边，难道撑起雨伞可以上天吗？",
        emoji = "",
        end_time = 4.0,
        id = 20,
        key = 73,
        level = 7,
        sort = 1,
        start_time = 2.0,
    },

    [74] = {
        content = "转动指针可以穿越吗？",
        emoji = "",
        end_time = 4.0,
        id = 20,
        key = 74,
        level = 8,
        sort = 2,
        start_time = 6.0,
    },

    [75] = {
        content = "切~~！",
        emoji = "",
        end_time = 3.0,
        id = 20,
        key = 75,
        level = 8,
        sort = 3,
        start_time = 10.0,
    },

    [76] = {
        content = "打个赌，你猜我雨伞上的麻将会不会掉下来？",
        emoji = "",
        end_time = 5.0,
        id = 20,
        key = 76,
        level = 8,
        sort = 4,
        start_time = 13.0,
    },

    [77] = {
        content = "会的。",
        emoji = "",
        end_time = 2.0,
        id = 20,
        key = 77,
        level = 7,
        sort = 5,
        start_time = 18.0,
    },

    [78] = {
        content = "那你就看着吧！",
        emoji = "",
        end_time = 3.0,
        id = 20,
        key = 78,
        level = 8,
        sort = 6,
        start_time = 20.0,
    },

    [79] = {
        content = "很好，一切都在计划中。内心OS：能力发动时间停止，稳赢！",
        emoji = "",
        end_time = 3.0,
        id = 20,
        key = 79,
        level = 7,
        sort = 7,
        start_time = 23.0,
    },

    [80] = {
        content = "滑溜溜的这是什么？",
        emoji = "",
        end_time = 3.0,
        id = 21,
        key = 80,
        level = 1,
        sort = 1,
        start_time = 2.0,
    },

    [81] = {
        content = "放开我家的崽！",
        emoji = "",
        end_time = 3.0,
        id = 21,
        key = 81,
        level = 2,
        sort = 2,
        start_time = 5.0,
    },

    [82] = {
        content = "",
        emoji = "zhenjing",
        end_time = 3.0,
        id = 21,
        key = 82,
        level = 1,
        sort = 3,
        start_time = 8.0,
    },

    [83] = {
        content = "你们在玩什么，凑我一个呗。",
        emoji = "",
        end_time = 4.0,
        id = 22,
        key = 83,
        level = 2,
        sort = 1,
        start_time = 2.0,
    },

    [84] = {
        content = "拒绝玩蛇队友人人有责。",
        emoji = "",
        end_time = 4.0,
        id = 22,
        key = 84,
        level = 3,
        sort = 2,
        start_time = 6.0,
    },

    [85] = {
        content = "",
        emoji = "weiqu",
        end_time = 3.0,
        id = 22,
        key = 85,
        level = 2,
        sort = 3,
        start_time = 10.0,
    },

    [86] = {
        content = "这位美丽的小姐，能否告诉我你高贵的名字？",
        emoji = "",
        end_time = 5.0,
        id = 23,
        key = 86,
        level = 3,
        sort = 1,
        start_time = 2.0,
    },

    [87] = {
        content = "你好嘟噜！再见嘟噜！",
        emoji = "",
        end_time = 3.0,
        id = 23,
        key = 87,
        level = 4,
        sort = 2,
        start_time = 7.0,
    },

    [88] = {
        content = "",
        emoji = "haixiu",
        end_time = 3.0,
        id = 23,
        key = 88,
        level = 2,
        sort = 3,
        start_time = 10.0,
    },

    [89] = {
        content = "让嘟嘟噜不高兴的坏蛋都要跟沙尘暴一起上天！",
        emoji = "",
        end_time = 5.0,
        id = 24,
        key = 89,
        level = 4,
        sort = 1,
        start_time = 2.0,
    },

    [90] = {
        content = "没事，冥界没有沙尘暴。",
        emoji = "",
        end_time = 4.0,
        id = 24,
        key = 90,
        level = 5,
        sort = 2,
        start_time = 7.0,
    },

    [91] = {
        content = "秘书三连，上班-加班-忙成狗。",
        emoji = "",
        end_time = 4.0,
        id = 25,
        key = 91,
        level = 5,
        sort = 1,
        start_time = 2.0,
    },

    [92] = {
        content = "探子三连，潜伏-八卦-靠左手。",
        emoji = "",
        end_time = 4.0,
        id = 25,
        key = 92,
        level = 6,
        sort = 2,
        start_time = 6.0,
    },

    [93] = {
        content = "",
        emoji = "wuyu1",
        end_time = 3.0,
        id = 25,
        key = 93,
        level = 4,
        sort = 3,
        start_time = 10.0,
    },

    [94] = {
        content = "这个世界上有一个人无论如何我都必须逮捕。",
        emoji = "",
        end_time = 5.0,
        id = 26,
        key = 94,
        level = 6,
        sort = 1,
        start_time = 2.0,
    },

    [95] = {
        content = "之前还叫人家小甜甜，现在就反面了！",
        emoji = "",
        end_time = 4.0,
        id = 26,
        key = 95,
        level = 8,
        sort = 2,
        start_time = 7.0,
    },

    [96] = {
        content = "小甜甜，哈哈哈hhhaaaa~",
        emoji = "",
        end_time = 4.0,
        id = 26,
        key = 96,
        level = 3,
        sort = 3,
        start_time = 11.0,
    },

    [97] = {
        content = "",
        emoji = "shengqi",
        end_time = 3.0,
        id = 26,
        key = 97,
        level = 6,
        sort = 4,
        start_time = 15.0,
    },

    [98] = {
        content = "公共场合禁止吸烟！超级瞄准已经部署！",
        emoji = "",
        end_time = 5.0,
        id = 27,
        key = 98,
        level = 7,
        sort = 1,
        start_time = 2.0,
    },

    [99] = {
        content = "把我的意大利大炮拉出来！",
        emoji = "",
        end_time = 4.0,
        id = 27,
        key = 99,
        level = 8,
        sort = 2,
        start_time = 7.0,
    },

    [100] = {
        content = "",
        emoji = "mengbi",
        end_time = 3.0,
        id = 27,
        key = 100,
        level = 7,
        sort = 3,
        start_time = 11.0,
    },

    [101] = {
        content = "只要让我捉住主角，我就要这样那样再那样这样！",
        emoji = "",
        end_time = 5.0,
        id = 27,
        key = 101,
        level = 8,
        sort = 4,
        start_time = 14.0,
    },

    [102] = {
        content = "他再也别想逃出我的手掌心！",
        emoji = "",
        end_time = 4.0,
        id = 27,
        key = 102,
        level = 8,
        sort = 5,
        start_time = 19.0,
    },

    [103] = {
        content = "",
        emoji = "wuyu1",
        end_time = 3.0,
        id = 27,
        key = 103,
        level = 1,
        sort = 6,
        start_time = 23.0,
    },

    [104] = {
        content = "",
        emoji = "wuyu2",
        end_time = 3.0,
        id = 27,
        key = 104,
        level = 3,
        sort = 7,
        start_time = 23.0,
    },

    [105] = {
        content = "",
        emoji = "wuyu3",
        end_time = 3.0,
        id = 27,
        key = 105,
        level = 5,
        sort = 8,
        start_time = 23.0,
    },

    [106] = {
        content = "喂？妖妖灵吗，这里有个变态。",
        emoji = "",
        end_time = 4.0,
        id = 27,
        key = 106,
        level = 7,
        sort = 9,
        start_time = 26.0,
    },

    [107] = {
        content = "卖包子啦卖包子啦，新鲜出炉的包子喵！",
        emoji = "",
        end_time = 5.0,
        id = 28,
        key = 107,
        level = 1,
        sort = 1,
        start_time = 2.0,
    },

    [108] = {
        content = "打劫！",
        emoji = "",
        end_time = 3.0,
        id = 28,
        key = 108,
        level = 2,
        sort = 2,
        start_time = 7.0,
    },

    [109] = {
        content = "",
        emoji = "weiqu",
        end_time = 3.0,
        id = 28,
        key = 109,
        level = 1,
        sort = 3,
        start_time = 10.0,
    },

    [110] = {
        content = "嗯嗯嗯！这些包子实在太好吃了！",
        emoji = "",
        end_time = 4.0,
        id = 28,
        key = 110,
        level = 2,
        sort = 4,
        start_time = 13.0,
    },

    [111] = {
        content = "欺负我徒弟罚你穿一年的猫咪装帮忙在店里卖包子！",
        emoji = "",
        end_time = 5.0,
        id = 28,
        key = 111,
        level = 3,
        sort = 5,
        start_time = 17.0,
    },

    [112] = {
        content = "",
        emoji = "zhenjing",
        end_time = 3.0,
        id = 28,
        key = 112,
        level = 2,
        sort = 6,
        start_time = 22.0,
    },

    [113] = {
        content = "",
        emoji = "kaixin",
        end_time = 3.0,
        id = 28,
        key = 113,
        level = 1,
        sort = 7,
        start_time = 25.0,
    },

    [114] = {
        content = "前往猫咪乐园的班车将在五分钟后发车，请各位旅客准时上车。",
        emoji = "",
        end_time = 5.0,
        id = 29,
        key = 114,
        level = 3,
        sort = 1,
        start_time = 2.0,
    },

    [115] = {
        content = "嘀！恶人卡。",
        emoji = "",
        end_time = 2.0,
        id = 29,
        key = 115,
        level = 4,
        sort = 2,
        start_time = 7.0,
    },

    [116] = {
        content = "那个留着长胡子的黑鬼，你是在逗我吗？",
        emoji = "",
        end_time = 4.0,
        id = 29,
        key = 116,
        level = 3,
        sort = 3,
        start_time = 9.0,
    },

    [117] = {
        content = "",
        emoji = "shengqi",
        end_time = 2.0,
        id = 29,
        key = 117,
        level = 4,
        sort = 4,
        start_time = 13.0,
    },

    [118] = {
        content = "剪刀，哈哈~你输了，你去",
        emoji = "",
        end_time = 4.0,
        id = 30,
        key = 118,
        level = 5,
        sort = 1,
        start_time = 2.0,
    },

    [119] = {
        content = "比猜拳你怎可能赢得了我？",
        emoji = "",
        end_time = 4.0,
        id = 30,
        key = 119,
        level = 4,
        sort = 2,
        start_time = 6.0,
    },

    [120] = {
        content = "扎心了老铁。",
        emoji = "",
        end_time = 3.0,
        id = 30,
        key = 120,
        level = 5,
        sort = 3,
        start_time = 10.0,
    },

    [121] = {
        content = "老白啊，欢迎来教会本部参观游览。",
        emoji = "",
        end_time = 5.0,
        id = 31,
        key = 121,
        level = 5,
        sort = 1,
        start_time = 2.0,
    },

    [122] = {
        content = "不好意思，我只对你感兴趣。",
        emoji = "",
        end_time = 4.0,
        id = 31,
        key = 122,
        level = 6,
        sort = 2,
        start_time = 7.0,
    },

    [123] = {
        content = "红衣老太婆，我对你不敢兴趣。",
        emoji = "",
        end_time = 4.0,
        id = 31,
        key = 123,
        level = 5,
        sort = 3,
        start_time = 11.0,
    },

    [124] = {
        content = "",
        emoji = "shengqi",
        end_time = 3.0,
        id = 31,
        key = 124,
        level = 6,
        sort = 4,
        start_time = 15.0,
    },

    [125] = {
        content = "对面的反派不许欺负我孙子！",
        emoji = "",
        end_time = 4.0,
        id = 32,
        key = 125,
        level = 6,
        sort = 1,
        start_time = 2.0,
    },

    [126] = {
        content = "到底是谁欺负谁，每天来打我，你的良心不会痛吗？",
        emoji = "",
        end_time = 5.0,
        id = 32,
        key = 126,
        level = 4,
        sort = 2,
        start_time = 6.0,
    },

    [127] = {
        content = "你在说什么，风好大听不清！",
        emoji = "",
        end_time = 4.0,
        id = 32,
        key = 127,
        level = 6,
        sort = 3,
        start_time = 11.0,
    },

    [128] = {
        content = "你们都是坏人，呜呜呜~~！",
        emoji = "",
        end_time = 4.0,
        id = 32,
        key = 128,
        level = 4,
        sort = 4,
        start_time = 15.0,
    },

    [129] = {
        content = "狗子你变了，你以前不是这样的。",
        emoji = "",
        end_time = 4.0,
        id = 33,
        key = 129,
        level = 8,
        sort = 1,
        start_time = 2.0,
    },

    [130] = {
        content = "我以前没得选择现在我想做一个好人。",
        emoji = "",
        end_time = 4.0,
        id = 33,
        key = 130,
        level = 7,
        sort = 2,
        start_time = 6.0,
    },

    [131] = {
        content = "要记得你连人都不是。",
        emoji = "",
        end_time = 4.0,
        id = 33,
        key = 131,
        level = 8,
        sort = 3,
        start_time = 10.0,
    },

    [132] = {
        content = "斗天斗天，其乐无穷！",
        emoji = "",
        end_time = 4.0,
        id = 34,
        key = 132,
        level = 4,
        sort = 1,
        start_time = 2.0,
    },

    [133] = {
        content = "有也行，没有也行，不争不抢，不求输赢。",
        emoji = "",
        end_time = 5.0,
        id = 34,
        key = 133,
        level = 8,
        sort = 2,
        start_time = 6.0,
    },

    [134] = {
        content = "啧，出息！",
        emoji = "",
        end_time = 3.0,
        id = 34,
        key = 134,
        level = 4,
        sort = 3,
        start_time = 11.0,
    },

    [135] = {
        content = "都行，可以，没关系。",
        emoji = "",
        end_time = 3.0,
        id = 34,
        key = 135,
        level = 8,
        sort = 4,
        start_time = 14.0,
    },

    [136] = {
        content = "昨晚我夜观星象，算出今天必有贵人带我开启妖灵契的制霸之路。",
        emoji = "",
        end_time = 5.0,
        id = 35,
        key = 136,
        level = 1,
        sort = 1,
        start_time = 2.0,
    },

    [137] = {
        content = "发现幽魂，开始引渡回冥界！",
        emoji = "",
        end_time = 4.0,
        id = 35,
        key = 137,
        level = 2,
        sort = 2,
        start_time = 7.0,
    },

    [138] = {
        content = "冥界？那是哪里？",
        emoji = "",
        end_time = 3.0,
        id = 35,
        key = 138,
        level = 1,
        sort = 3,
        start_time = 11.0,
    },

    [139] = {
        content = "幽魂的养老院啊！",
        emoji = "",
        end_time = 3.0,
        id = 35,
        key = 139,
        level = 2,
        sort = 4,
        start_time = 14.0,
    },

    [140] = {
        content = "我打算参加一年一度冥界选美大赛。",
        emoji = "",
        end_time = 4.0,
        id = 36,
        key = 140,
        level = 4,
        sort = 1,
        start_time = 2.0,
    },

    [141] = {
        content = "比赛仅限女选手参加。",
        emoji = "",
        end_time = 3.0,
        id = 36,
        key = 141,
        level = 3,
        sort = 2,
        start_time = 6.0,
    },

    [142] = {
        content = "我比女选手漂亮多了！",
        emoji = "",
        end_time = 3.0,
        id = 36,
        key = 142,
        level = 4,
        sort = 3,
        start_time = 9.0,
    },

    [143] = {
        content = "行，只要你赢算我输。",
        emoji = "",
        end_time = 3.0,
        id = 36,
        key = 143,
        level = 3,
        sort = 4,
        start_time = 12.0,
    },

    [144] = {
        content = "你知道昨天我送你那520朵红玫瑰的意思吗？",
        emoji = "",
        end_time = 5.0,
        id = 37,
        key = 144,
        level = 2,
        sort = 1,
        start_time = 2.0,
    },

    [145] = {
        content = "在花店能换250个金币的意思？",
        emoji = "",
        end_time = 4.0,
        id = 37,
        key = 145,
        level = 3,
        sort = 2,
        start_time = 7.0,
    },

    [146] = {
        content = "无形狗粮最致命。",
        emoji = "",
        end_time = 3.0,
        id = 37,
        key = 146,
        level = 5,
        sort = 3,
        start_time = 11.0,
    },

    [147] = {
        content = "",
        emoji = "haixiu",
        end_time = 3.0,
        id = 37,
        key = 147,
        level = 2,
        sort = 4,
        start_time = 14.0,
    },

    [148] = {
        content = "你别出来好吗，我对长得丑的人过敏。",
        emoji = "",
        end_time = 4.0,
        id = 38,
        key = 148,
        level = 4,
        sort = 1,
        start_time = 2.0,
    },

    [149] = {
        content = "长成这样还嘚瑟，好了不起哦。",
        emoji = "",
        end_time = 4.0,
        id = 38,
        key = 149,
        level = 5,
        sort = 2,
        start_time = 6.0,
    },

    [150] = {
        content = "我其实最怕晚上洗澡，因为进厕所看到镜子总会被自己帅到。",
        emoji = "",
        end_time = 5.0,
        id = 38,
        key = 150,
        level = 5,
        sort = 3,
        start_time = 10.0,
    },

    [151] = {
        content = "长成这样还嘚瑟，好了不起哦。",
        emoji = "",
        end_time = 4.0,
        id = 38,
        key = 151,
        level = 6,
        sort = 4,
        start_time = 15.0,
    },

    [152] = {
        content = "看我切、切、切、切！",
        emoji = "",
        end_time = 4.0,
        id = 39,
        key = 152,
        level = 6,
        sort = 1,
        start_time = 2.0,
    },

    [153] = {
        content = "这根萝卜雕得不错。",
        emoji = "",
        end_time = 4.0,
        id = 39,
        key = 153,
        level = 8,
        sort = 2,
        start_time = 6.0,
    },

    [154] = {
        content = "师父我想学！",
        emoji = "",
        end_time = 3.0,
        id = 39,
        key = 154,
        level = 7,
        sort = 3,
        start_time = 10.0,
    },

    [155] = {
        content = "你有freestyle吗？",
        emoji = "",
        end_time = 4.0,
        id = 39,
        key = 155,
        level = 6,
        sort = 4,
        start_time = 13.0,
    },

    [156] = {
        content = "头上一片绿，我该怎么办？",
        emoji = "",
        end_time = 3.0,
        id = 40,
        key = 156,
        level = 7,
        sort = 1,
        start_time = 2.0,
    },

    [157] = {
        content = "当然是原谅她啊！",
        emoji = "",
        end_time = 3.0,
        id = 40,
        key = 157,
        level = 8,
        sort = 2,
        start_time = 5.0,
    },

    [158] = {
        content = "你再给我吃萝卜信不信我拿萝卜捶你胸口！",
        emoji = "",
        end_time = 5.0,
        id = 40,
        key = 158,
        level = 8,
        sort = 3,
        start_time = 8.0,
    },

    [159] = {
        content = "鸟那么可爱，可不可以不要吃小鸟？",
        emoji = "",
        end_time = 4.0,
        id = 40,
        key = 159,
        level = 7,
        sort = 4,
        start_time = 13.0,
    },

    [160] = {
        content = "不可以。",
        emoji = "",
        end_time = 3.0,
        id = 40,
        key = 160,
        level = 8,
        sort = 5,
        start_time = 17.0,
    },

    [161] = {
        content = "下一个目标，加入卡槽！",
        emoji = "",
        end_time = 3.0,
        id = 41,
        key = 161,
        level = 1,
        sort = 1,
        start_time = 2.0,
    },

    [162] = {
        content = "成为SSR！",
        emoji = "",
        end_time = 3.0,
        id = 41,
        key = 162,
        level = 2,
        sort = 2,
        start_time = 5.0,
    },

    [163] = {
        content = "打败主角！",
        emoji = "",
        end_time = 3.0,
        id = 41,
        key = 163,
        level = 1,
        sort = 3,
        start_time = 8.0,
    },

    [164] = {
        content = "走上人生巅峰！",
        emoji = "",
        end_time = 3.0,
        id = 41,
        key = 164,
        level = 2,
        sort = 4,
        start_time = 11.0,
    },

    [165] = {
        content = "神秘高手常驻枫竹林夜钓，握竿数十载竟毫无收获？",
        emoji = "",
        end_time = 5.0,
        id = 42,
        key = 165,
        level = 2,
        sort = 1,
        start_time = 2.0,
    },

    [166] = {
        content = "猛男蜗居枫竹林，知道真相的我眼泪掉下来！",
        emoji = "",
        end_time = 5.0,
        id = 42,
        key = 166,
        level = 3,
        sort = 2,
        start_time = 7.0,
    },

    [167] = {
        content = "这老家伙……",
        emoji = "",
        end_time = 3.0,
        id = 42,
        key = 167,
        level = 5,
        sort = 3,
        start_time = 12.0,
    },

    [168] = {
        content = "惊了！夜伴婴啼，竹林深处的真相！",
        emoji = "",
        end_time = 4.0,
        id = 42,
        key = 168,
        level = 3,
        sort = 4,
        start_time = 15.0,
    },

    [169] = {
        content = "执夷哥，爷爷又在写奇怪的东西！",
        emoji = "",
        end_time = 4.0,
        id = 42,
        key = 169,
        level = 4,
        sort = 5,
        start_time = 19.0,
    },

    [170] = {
        content = "咳咳，爷爷你……",
        emoji = "",
        end_time = 3.0,
        id = 42,
        key = 170,
        level = 5,
        sort = 6,
        start_time = 23.0,
    },

    [171] = {
        content = "丢人！天时地利不知反攻，你退群吧！",
        emoji = "",
        end_time = 4.0,
        id = 42,
        key = 171,
        level = 3,
        sort = 7,
        start_time = 26.0,
    },

    [172] = {
        content = "别的小朋友都回家了，你什么时候来接我？",
        emoji = "",
        end_time = 5.0,
        id = 43,
        key = 172,
        level = 4,
        sort = 1,
        start_time = 2.0,
    },

    [173] = {
        content = "别急，这不是去幼儿园的车！",
        emoji = "",
        end_time = 4.0,
        id = 43,
        key = 173,
        level = 5,
        sort = 2,
        start_time = 7.0,
    },

    [174] = {
        content = "",
        emoji = "weiqu2",
        end_time = 3.0,
        id = 43,
        key = 174,
        level = 4,
        sort = 3,
        start_time = 11.0,
    },

    [175] = {
        content = "听说我们在动物园特别好，我准备去那里打工了。",
        emoji = "",
        end_time = 5.0,
        id = 44,
        key = 175,
        level = 5,
        sort = 1,
        start_time = 2.0,
    },

    [176] = {
        content = "可以。来，请开始你的表演。",
        emoji = "",
        end_time = 3.0,
        id = 44,
        key = 176,
        level = 6,
        sort = 2,
        start_time = 7.0,
    },

    [177] = {
        content = "学习音律不仅讲究基本功，还要走心。",
        emoji = "",
        end_time = 4.0,
        id = 44,
        key = 177,
        level = 6,
        sort = 3,
        start_time = 10.0,
    },

    [178] = {
        content = "我觉得执阳挺走心的。",
        emoji = "",
        end_time = 3.0,
        id = 44,
        key = 178,
        level = 5,
        sort = 4,
        start_time = 14.0,
    },

    [179] = {
        content = "竹笛拿反了！",
        emoji = "",
        end_time = 3.0,
        id = 44,
        key = 179,
        level = 6,
        sort = 5,
        start_time = 17.0,
    },

    [180] = {
        content = "阿姨好！",
        emoji = "",
        end_time = 2.0,
        id = 45,
        key = 180,
        level = 4,
        sort = 1,
        start_time = 2.0,
    },

    [181] = {
        content = "你叫谁阿姨？",
        emoji = "",
        end_time = 2.0,
        id = 45,
        key = 181,
        level = 7,
        sort = 2,
        start_time = 4.0,
    },

    [182] = {
        content = "执阳，稻荷大人已经活了很久，不能叫阿姨。",
        emoji = "",
        end_time = 4.0,
        id = 45,
        key = 182,
        level = 5,
        sort = 3,
        start_time = 6.0,
    },

    [183] = {
        content = "嗯哼。",
        emoji = "",
        end_time = 2.0,
        id = 45,
        key = 183,
        level = 7,
        sort = 4,
        start_time = 10.0,
    },

    [184] = {
        content = "要叫曾祖太奶奶。",
        emoji = "",
        end_time = 2.0,
        id = 45,
        key = 184,
        level = 5,
        sort = 5,
        start_time = 12.0,
    },

    [185] = {
        content = "",
        emoji = "zhenjing",
        end_time = 2.0,
        id = 45,
        key = 185,
        level = 8,
        sort = 6,
        start_time = 14.0,
    },

    [186] = {
        content = "终有一天，上古妖族会卷土重来，夺回失落的土地！",
        emoji = "",
        end_time = 5.0,
        id = 46,
        key = 186,
        level = 8,
        sort = 1,
        start_time = 2.0,
    },

    [187] = {
        content = "有个中二病上司怎么破，急！在线等！",
        emoji = "",
        end_time = 4.0,
        id = 46,
        key = 187,
        level = 7,
        sort = 2,
        start_time = 7.0,
    },

    [188] = {
        content = "你就是那个天天修仙，一整夜就大半夜不睡觉的那个！",
        emoji = "",
        end_time = 5.0,
        id = 47,
        key = 188,
        level = 1,
        sort = 1,
        start_time = 2.0,
    },

    [189] = {
        content = "不不是我。",
        emoji = "",
        end_time = 3.0,
        id = 47,
        key = 189,
        level = 2,
        sort = 2,
        start_time = 7.0,
    },

    [190] = {
        content = "听说你肝很好，熬夜特别厉害！",
        emoji = "",
        end_time = 4.0,
        id = 47,
        key = 190,
        level = 1,
        sort = 3,
        start_time = 10.0,
    },

    [191] = {
        content = "你听我解释！",
        emoji = "",
        end_time = 3.0,
        id = 47,
        key = 191,
        level = 2,
        sort = 4,
        start_time = 14.0,
    },

    [192] = {
        content = "一睡十年，醒来怕是要吃吐的节奏。",
        emoji = "",
        end_time = 4.0,
        id = 48,
        key = 192,
        level = 2,
        sort = 1,
        start_time = 2.0,
    },

    [193] = {
        content = "拿去，随便花！",
        emoji = "",
        end_time = 3.0,
        id = 48,
        key = 193,
        level = 4,
        sort = 2,
        start_time = 6.0,
    },

    [194] = {
        content = "谢谢白殊爸爸！",
        emoji = "",
        end_time = 3.0,
        id = 48,
        key = 194,
        level = 2,
        sort = 3,
        start_time = 9.0,
    },

    [195] = {
        content = "世界那么大我想去看看。",
        emoji = "",
        end_time = 4.0,
        id = 49,
        key = 195,
        level = 3,
        sort = 1,
        start_time = 2.0,
    },

    [196] = {
        content = "但是钱包那么小，哪也去不了。",
        emoji = "",
        end_time = 4.0,
        id = 49,
        key = 196,
        level = 2,
        sort = 2,
        start_time = 6.0,
    },

    [197] = {
        content = "好好上班。",
        emoji = "",
        end_time = 3.0,
        id = 49,
        key = 197,
        level = 1,
        sort = 3,
        start_time = 10.0,
    },

    [198] = {
        content = "来，我的圣光会普照着你。",
        emoji = "",
        end_time = 3.0,
        id = 50,
        key = 198,
        level = 4,
        sort = 1,
        start_time = 2.0,
    },

    [199] = {
        content = "我感到内心的污秽被清洗，人生是那么美好，我要从良！",
        emoji = "",
        end_time = 5.0,
        id = 50,
        key = 199,
        level = 5,
        sort = 2,
        start_time = 5.0,
    },

    [200] = {
        content = "让你从良！让你从良！",
        emoji = "",
        end_time = 3.0,
        id = 50,
        key = 200,
        level = 6,
        sort = 3,
        start_time = 10.0,
    },

    [201] = {
        content = "三倍圣光，来接受感召吧。",
        emoji = "",
        end_time = 3.0,
        id = 50,
        key = 201,
        level = 4,
        sort = 4,
        start_time = 13.0,
    },

    [202] = {
        content = "我感觉自己即将在光芒之中融化。",
        emoji = "",
        end_time = 4.0,
        id = 50,
        key = 202,
        level = 5,
        sort = 5,
        start_time = 16.0,
    },

    [203] = {
        content = "要成功，先发疯，头脑简单向前冲！",
        emoji = "",
        end_time = 5.0,
        id = 51,
        key = 203,
        level = 5,
        sort = 1,
        start_time = 2.0,
    },

    [204] = {
        content = "要致富，找客户，成功没有回头路！",
        emoji = "",
        end_time = 5.0,
        id = 51,
        key = 204,
        level = 6,
        sort = 2,
        start_time = 7.0,
    },

    [205] = {
        content = "作为高新科技技术核心研究员，我们的口号是！",
        emoji = "",
        end_time = 5.0,
        id = 51,
        key = 205,
        level = 6,
        sort = 3,
        start_time = 12.0,
    },

    [206] = {
        content = "搞事搞事，没事就搞事！",
        emoji = "",
        end_time = 4.0,
        id = 51,
        key = 206,
        level = 8,
        sort = 4,
        start_time = 17.0,
    },

    [207] = {
        content = "天生异色瞳，让我十分苦恼。",
        emoji = "",
        end_time = 3.0,
        id = 52,
        key = 207,
        level = 7,
        sort = 1,
        start_time = 2.0,
    },

    [208] = {
        content = "为什么，看起来挺可爱的。",
        emoji = "",
        end_time = 3.0,
        id = 52,
        key = 208,
        level = 8,
        sort = 2,
        start_time = 5.0,
    },

    [209] = {
        content = "看，就是绅士太多了。",
        emoji = "",
        end_time = 3.0,
        id = 52,
        key = 209,
        level = 7,
        sort = 3,
        start_time = 8.0,
    },

    [210] = {
        content = "没有我卧不了的底，没有我潜不进的旮旯角角！",
        emoji = "",
        end_time = 5.0,
        id = 53,
        key = 210,
        level = 8,
        sort = 1,
        start_time = 2.0,
    },

    [211] = {
        content = "啊你不就好棒棒？要不要给你鼓鼓掌？",
        emoji = "",
        end_time = 5.0,
        id = 53,
        key = 211,
        level = 6,
        sort = 2,
        start_time = 7.0,
    },

    [212] = {
        content = "再举高高，是不是还想要亲亲？",
        emoji = "",
        end_time = 4.0,
        id = 53,
        key = 212,
        level = 6,
        sort = 3,
        start_time = 12.0,
    },

    [213] = {
        content = "我选择狗带。",
        emoji = "",
        end_time = 3.0,
        id = 53,
        key = 213,
        level = 8,
        sort = 4,
        start_time = 16.0,
    },

    [214] = {
        content = "嘿嘿嘿！吃我一爪子！",
        emoji = "",
        end_time = 3.0,
        id = 54,
        key = 214,
        level = 1,
        sort = 1,
        start_time = 2.0,
    },

    [215] = {
        content = "等下，那些房子不在拆迁范围内！",
        emoji = "",
        end_time = 4.0,
        id = 54,
        key = 215,
        level = 2,
        sort = 2,
        start_time = 5.0,
    },

    [216] = {
        content = "噢迟了。",
        emoji = "",
        end_time = 3.0,
        id = 54,
        key = 216,
        level = 1,
        sort = 3,
        start_time = 9.0,
    },

    [217] = {
        content = "传说像人家这种类型被称呼为吃货或者大胃王。",
        emoji = "",
        end_time = 5.0,
        id = 55,
        key = 217,
        level = 3,
        sort = 1,
        start_time = 2.0,
    },

    [218] = {
        content = "前辈谦虚，您这叫饿死鬼投胎。",
        emoji = "",
        end_time = 4.0,
        id = 55,
        key = 218,
        level = 2,
        sort = 2,
        start_time = 7.0,
    },

    [219] = {
        content = "大神大神，能借我10个亿吗？我想存嫁妆。",
        emoji = "",
        end_time = 5.0,
        id = 55,
        key = 219,
        level = 3,
        sort = 6,
        start_time = 11.0,
    },

    [220] = {
        content = "吃货嫁不掉。",
        emoji = "",
        end_time = 3.0,
        id = 55,
        key = 220,
        level = 4,
        sort = 7,
        start_time = 16.0,
    },

    [221] = {
        content = "",
        emoji = "zhenjing",
        end_time = 3.0,
        id = 55,
        key = 221,
        level = 1,
        sort = 8,
        start_time = 19.0,
    },

    [222] = {
        content = "",
        emoji = "shengqi",
        end_time = 3.0,
        id = 55,
        key = 222,
        level = 3,
        sort = 9,
        start_time = 20.0,
    },

    [223] = {
        content = "我……",
        emoji = "",
        end_time = 3.0,
        id = 56,
        key = 223,
        level = 6,
        sort = 1,
        start_time = 2.0,
    },

    [224] = {
        content = "我什么我！",
        emoji = "",
        end_time = 3.0,
        id = 56,
        key = 224,
        level = 5,
        sort = 2,
        start_time = 5.0,
    },

    [225] = {
        content = "你……",
        emoji = "",
        end_time = 3.0,
        id = 56,
        key = 225,
        level = 6,
        sort = 3,
        start_time = 8.0,
    },

    [226] = {
        content = "你什么你！失踪半天去哪儿了？",
        emoji = "",
        end_time = 3.0,
        id = 56,
        key = 226,
        level = 5,
        sort = 4,
        start_time = 11.0,
    },

    [227] = {
        content = "听说今天是前辈来到冥界的第156周年，我摘了一捧彼岸花送你。",
        emoji = "",
        end_time = 5.0,
        id = 56,
        key = 227,
        level = 6,
        sort = 5,
        start_time = 14.0,
    },

    [228] = {
        content = "嗯，这还差不多。",
        emoji = "",
        end_time = 3.0,
        id = 56,
        key = 228,
        level = 5,
        sort = 6,
        start_time = 19.0,
    },

    [229] = {
        content = "面瘫不是病，三无是属性，待到傲娇时，就要起火哩。",
        emoji = "",
        end_time = 5.0,
        id = 57,
        key = 229,
        level = 5,
        sort = 1,
        start_time = 2.0,
    },

    [230] = {
        content = "emmmmmm……",
        emoji = "",
        end_time = 3.0,
        id = 57,
        key = 230,
        level = 6,
        sort = 2,
        start_time = 7.0,
    },

    [231] = {
        content = "猜一个人！",
        emoji = "",
        end_time = 3.0,
        id = 57,
        key = 231,
        level = 4,
        sort = 3,
        start_time = 10.0,
    },

    [232] = {
        content = "猜，你妹。",
        emoji = "",
        end_time = 3.0,
        id = 57,
        key = 232,
        level = 6,
        sort = 4,
        start_time = 13.0,
    },

    [233] = {
        content = "对于今天解决不了的事情不要急。",
        emoji = "",
        end_time = 4.0,
        id = 58,
        key = 233,
        level = 7,
        sort = 1,
        start_time = 2.0,
    },

    [234] = {
        content = "因为明天也可能还是解决不了。",
        emoji = "",
        end_time = 4.0,
        id = 58,
        key = 234,
        level = 7,
        sort = 2,
        start_time = 6.0,
    },

    [235] = {
        content = "阿判！小判判！我要喝水！",
        emoji = "",
        end_time = 4.0,
        id = 58,
        key = 235,
        level = 8,
        sort = 3,
        start_time = 10.0,
    },

    [236] = {
        content = "所以最好的方法就是，从根源上杜绝。",
        emoji = "",
        end_time = 4.0,
        id = 58,
        key = 236,
        level = 7,
        sort = 4,
        start_time = 14.0,
    },

    [237] = {
        content = "鬼影都不见！怎么可以用这种态度对待上司！",
        emoji = "",
        end_time = 5.0,
        id = 58,
        key = 237,
        level = 8,
        sort = 5,
        start_time = 18.0,
    },

    [238] = {
        content = "",
        emoji = "zhenjing",
        end_time = 3.0,
        id = 58,
        key = 238,
        level = 1,
        sort = 6,
        start_time = 23.0,
    },

    [239] = {
        content = "",
        emoji = "mihu",
        end_time = 3.0,
        id = 58,
        key = 239,
        level = 3,
        sort = 7,
        start_time = 24.0,
    },

    [240] = {
        content = "",
        emoji = "wuyu1",
        end_time = 3.0,
        id = 58,
        key = 240,
        level = 5,
        sort = 8,
        start_time = 25.0,
    },

    [241] = {
        content = "年轻人嘛，现在没钱算什么。以后没钱的日子还多着呢。",
        emoji = "",
        end_time = 5.0,
        id = 59,
        key = 241,
        level = 8,
        sort = 1,
        start_time = 2.0,
    },

    [242] = {
        content = "把拖鞋拿起来，扫地了！",
        emoji = "",
        end_time = 4.0,
        id = 59,
        key = 242,
        level = 7,
        sort = 2,
        start_time = 7.0,
    },

    [243] = {
        content = "你扫地就扫地，拔我网线干什么！",
        emoji = "",
        end_time = 4.0,
        id = 59,
        key = 243,
        level = 8,
        sort = 3,
        start_time = 11.0,
    },

    [244] = {
        content = "没钱就是这样了。",
        emoji = "",
        end_time = 3.0,
        id = 59,
        key = 244,
        level = 7,
        sort = 4,
        start_time = 15.0,
    },

}
