-- ./excel/huodong/chapterfb/chapter.xlsx
return {

    [1] = {
        content = "漫画看多了以为自己真能代表月亮了？",
        emoji = "",
        end_time = 3.0,
        id = 1,
        key = 1,
        sort = 1,
        speeker = 0,
        start_time = 1.0,
    },

    [2] = {
        content = "不，我只为自己代言。",
        emoji = "",
        end_time = 2.5,
        id = 1,
        key = 2,
        sort = 2,
        speeker = 1,
        start_time = 4.5,
    },

    [3] = {
        content = "呸，我还为充满男子汉气息飞机头代言呢！",
        emoji = "",
        end_time = 3.5,
        id = 1,
        key = 3,
        sort = 3,
        speeker = 0,
        start_time = 7.5,
    },

    [4] = {
        content = "我老实跟你讲，真正的男子汉都不梳这种发型。",
        emoji = "",
        end_time = 3.5,
        id = 1,
        key = 4,
        sort = 4,
        speeker = 1,
        start_time = 12.5,
    },

    [5] = {
        content = "知道识相两个字怎么写吗？",
        emoji = "",
        end_time = 2.5,
        id = 2,
        key = 5,
        sort = 1,
        speeker = 0,
        start_time = 1.0,
    },

    [6] = {
        content = "只要你愿意反过来写都可以。",
        emoji = "",
        end_time = 2.5,
        id = 2,
        key = 6,
        sort = 2,
        speeker = 1,
        start_time = 4.0,
    },

    [7] = {
        content = "……",
        emoji = "",
        end_time = 2.5,
        id = 2,
        key = 7,
        sort = 3,
        speeker = 0,
        start_time = 7.0,
    },

    [8] = {
        content = "智慧的凝视·jpg",
        emoji = "",
        end_time = 2.5,
        id = 2,
        key = 8,
        sort = 4,
        speeker = 1,
        start_time = 10.0,
    },

    [9] = {
        content = "遇到纠纷第一要务就是找警察叔叔，这种常理还不懂吗？",
        emoji = "",
        end_time = 4.0,
        id = 3,
        key = 9,
        sort = 1,
        speeker = 0,
        start_time = 1.0,
    },

    [10] = {
        content = "不怕，我40米长刀已经准备好了！",
        emoji = "",
        end_time = 3.5,
        id = 3,
        key = 10,
        sort = 2,
        speeker = 1,
        start_time = 5.5,
    },

    [11] = {
        content = "疑似发现恐怖分子，准备立即实行逮捕！",
        emoji = "",
        end_time = 3.5,
        id = 3,
        key = 11,
        sort = 3,
        speeker = 0,
        start_time = 9.5,
    },

    [12] = {
        content = "请原谅我人生地不熟初来乍到年纪轻还小不懂事！",
        emoji = "",
        end_time = 4.0,
        id = 3,
        key = 12,
        sort = 4,
        speeker = 1,
        start_time = 13.5,
    },

    [13] = {
        content = "荆鸣小课堂开讲啦，请持单号数的同学进左边通道，双号数同学进右边通道。",
        emoji = "",
        end_time = 5.0,
        id = 4,
        key = 13,
        sort = 1,
        speeker = 0,
        start_time = 1.0,
    },

    [14] = {
        content = "我没有拿号该怎么办？",
        emoji = "",
        end_time = 3.0,
        id = 4,
        key = 14,
        sort = 2,
        speeker = 1,
        start_time = 6.5,
    },

    [15] = {
        content = "主角请走前面绿色特权通道。",
        emoji = "",
        end_time = 3.0,
        id = 4,
        key = 15,
        sort = 3,
        speeker = 0,
        start_time = 10.0,
    },

    [16] = {
        content = "告诉我，你是不是认识我？",
        emoji = "",
        end_time = 3.0,
        id = 5,
        key = 16,
        sort = 1,
        speeker = 0,
        start_time = 1.0,
    },

    [17] = {
        content = "你猜",
        emoji = "",
        end_time = 2.0,
        id = 5,
        key = 17,
        sort = 2,
        speeker = 1,
        start_time = 4.5,
    },

    [18] = {
        content = "好可爱的小妹妹啊哈哈！",
        emoji = "",
        end_time = 2.5,
        id = 6,
        key = 18,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [19] = {
        content = "科学组全体听命，只要把这个无耻的人类抓进实验室，未来一年都可以准时下班！",
        emoji = "",
        end_time = 5.0,
        id = 6,
        key = 19,
        sort = 2,
        speeker = 0,
        start_time = 4.0,
    },

    [20] = {
        content = "不用这么大阵仗吧……",
        emoji = "",
        end_time = 2.5,
        id = 6,
        key = 20,
        sort = 3,
        speeker = 1,
        start_time = 9.5,
    },

    [21] = {
        content = "好好体验被科学组追逐的乐趣吧！",
        emoji = "",
        end_time = 3.0,
        id = 6,
        key = 21,
        sort = 4,
        speeker = 0,
        start_time = 12.5,
    },

    [22] = {
        content = "傲娇什么的果然是王道啊！",
        emoji = "",
        end_time = 2.5,
        id = 6,
        key = 22,
        sort = 5,
        speeker = 1,
        start_time = 16.0,
    },

    [23] = {
        content = "嘟嘟噜嘟嘟噜~嘟嘟噜嘟嘟噜~",
        emoji = "",
        end_time = 2.5,
        id = 7,
        key = 23,
        sort = 1,
        speeker = 0,
        start_time = 1.0,
    },

    [24] = {
        content = "你在跟我说话吗，什么意思？",
        emoji = "",
        end_time = 2.5,
        id = 7,
        key = 24,
        sort = 2,
        speeker = 1,
        start_time = 4.0,
    },

    [25] = {
        content = "嘟嘟噜嘟嘟噜~嘟嘟噜嘟嘟噜~",
        emoji = "",
        end_time = 2.5,
        id = 7,
        key = 25,
        sort = 3,
        speeker = 0,
        start_time = 7.0,
    },

    [26] = {
        content = "卖萌也不能拯救你！",
        emoji = "",
        end_time = 2.5,
        id = 7,
        key = 26,
        sort = 4,
        speeker = 1,
        start_time = 10.0,
    },

    [27] = {
        content = "你长得好像我几年前在某个地方遇到的村子里失踪的小孩。",
        emoji = "",
        end_time = 4.0,
        id = 8,
        key = 27,
        sort = 1,
        speeker = 0,
        start_time = 1.0,
    },

    [28] = {
        content = "符合这种条件的人多到数不清，你会不会只是脸盲？",
        emoji = "",
        end_time = 3.5,
        id = 8,
        key = 28,
        sort = 2,
        speeker = 1,
        start_time = 5.5,
    },

    [29] = {
        content = "哎呀哎呀~被你发现啦。我们主要依靠气息寻人，请让我看看你的掌纹。",
        emoji = "",
        end_time = 4.0,
        id = 8,
        key = 29,
        sort = 3,
        speeker = 0,
        start_time = 9.5,
    },

    [30] = {
        content = "你还兼职算命吗！",
        emoji = "",
        end_time = 2.5,
        id = 8,
        key = 30,
        sort = 4,
        speeker = 1,
        start_time = 14.0,
    },

    [31] = {
        content = "嘎嘎嘎！",
        emoji = "",
        end_time = 2.0,
        id = 9,
        key = 31,
        sort = 1,
        speeker = 0,
        start_time = 1.0,
    },

    [32] = {
        content = "作为妖族的一员，你的颜值堪忧啊。",
        emoji = "",
        end_time = 3.0,
        id = 9,
        key = 32,
        sort = 2,
        speeker = 1,
        start_time = 3.5,
    },

    [33] = {
        content = "嘎嘎嘎嘎！",
        emoji = "",
        end_time = 2.0,
        id = 9,
        key = 33,
        sort = 3,
        speeker = 0,
        start_time = 7.0,
    },

    [34] = {
        content = "主要为什么还要学鸭子叫？",
        emoji = "",
        end_time = 2.5,
        id = 9,
        key = 34,
        sort = 4,
        speeker = 1,
        start_time = 10.0,
    },

    [35] = {
        content = "我的太刀已经饥渴难耐！",
        emoji = "",
        end_time = 2.5,
        id = 10,
        key = 35,
        sort = 1,
        speeker = 0,
        start_time = 1.0,
    },

    [36] = {
        content = "冷静，有话好好讲！",
        emoji = "",
        end_time = 2.5,
        id = 10,
        key = 36,
        sort = 2,
        speeker = 1,
        start_time = 4.0,
    },

    [37] = {
        content = "喝！",
        emoji = "",
        end_time = 2.5,
        id = 10,
        key = 37,
        sort = 3,
        speeker = 0,
        start_time = 7.0,
    },

    [38] = {
        content = "啧啧，还差半米才劈到西瓜，你输了。",
        emoji = "",
        end_time = 3.0,
        id = 10,
        key = 38,
        sort = 4,
        speeker = 1,
        start_time = 10.0,
    },

    [39] = {
        content = "切！",
        emoji = "",
        end_time = 2.0,
        id = 10,
        key = 39,
        sort = 5,
        speeker = 0,
        start_time = 13.5,
    },

    [40] = {
        content = "听说你的飞镖每次都能击中游乐场木板上的气球？",
        emoji = "",
        end_time = 3.5,
        id = 11,
        key = 40,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [41] = {
        content = "世界上没有我玩不转的飞镖。",
        emoji = "",
        end_time = 3.0,
        id = 11,
        key = 41,
        sort = 2,
        speeker = 0,
        start_time = 5.0,
    },

    [42] = {
        content = "那如果气球盖上金属挡板，你的飞镖会90度拐弯不？",
        emoji = "",
        end_time = 3.5,
        id = 11,
        key = 42,
        sort = 3,
        speeker = 1,
        start_time = 8.5,
    },

    [43] = {
        content = "",
        emoji = "wuyu1",
        end_time = 2.5,
        id = 11,
        key = 43,
        sort = 4,
        speeker = 0,
        start_time = 12.5,
    },

    [44] = {
        content = "听说作为种子选手，你在赛场上收获了很多女粉丝。请问现在心情如何？",
        emoji = "",
        end_time = 4.0,
        id = 12,
        key = 44,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [45] = {
        content = "我的内心毫无波动，甚至还想笑。",
        emoji = "",
        end_time = 3.5,
        id = 12,
        key = 45,
        sort = 2,
        speeker = 0,
        start_time = 5.5,
    },

    [46] = {
        content = "听说作为默默无闻的黑马，你在赛场上收获了很多男粉丝。请问现在心情如何？",
        emoji = "",
        end_time = 5.0,
        id = 12,
        key = 46,
        sort = 3,
        speeker = 0,
        start_time = 9.5,
    },

    [47] = {
        content = "从未见过如此厚颜无耻之人！",
        emoji = "",
        end_time = 3.0,
        id = 12,
        key = 47,
        sort = 4,
        speeker = 1,
        start_time = 15.0,
    },

    [48] = {
        content = "看招！",
        emoji = "",
        end_time = 2.5,
        id = 13,
        key = 48,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [49] = {
        content = "啊啊啊啊！请不要过来！",
        emoji = "",
        end_time = 2.5,
        id = 13,
        key = 49,
        sort = 2,
        speeker = 0,
        start_time = 4.0,
    },

    [50] = {
        content = "卡卡卡，导演这都NG99次了，这场打戏还能不能好！",
        emoji = "",
        end_time = 4.0,
        id = 13,
        key = 50,
        sort = 3,
        speeker = 1,
        start_time = 7.0,
    },

    [51] = {
        content = "对不起对不起，请再给重华一次机会！",
        emoji = "",
        end_time = 3.0,
        id = 13,
        key = 51,
        sort = 4,
        speeker = 0,
        start_time = 11.5,
    },

    [52] = {
        content = "唉，再来吧，不然媒体又要说主角耍大牌了。",
        emoji = "",
        end_time = 3.0,
        id = 13,
        key = 52,
        sort = 5,
        speeker = 1,
        start_time = 15.0,
    },

    [53] = {
        content = "为什么你总是趴在灯罩里呢？",
        emoji = "",
        end_time = 3.0,
        id = 14,
        key = 53,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [54] = {
        content = "我演的是灯灵，当然要在灯里面。",
        emoji = "",
        end_time = 3.0,
        id = 14,
        key = 54,
        sort = 2,
        speeker = 0,
        start_time = 4.5,
    },

    [55] = {
        content = "怎么可以对主角撒谎，再给你一次机会！",
        emoji = "",
        end_time = 3.5,
        id = 14,
        key = 55,
        sort = 3,
        speeker = 1,
        start_time = 8.0,
    },

    [56] = {
        content = "美术小姐姐来不及为观绪画好看的衣裳，只好躲在灯里了嘤嘤嘤……",
        emoji = "",
        end_time = 5.0,
        id = 14,
        key = 56,
        sort = 4,
        speeker = 0,
        start_time = 12.0,
    },

    [57] = {
        content = "请问可以看看你的书吗？",
        emoji = "",
        end_time = 2.5,
        id = 15,
        key = 57,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [58] = {
        content = "可以。",
        emoji = "",
        end_time = 2.5,
        id = 15,
        key = 58,
        sort = 2,
        speeker = 0,
        start_time = 4.0,
    },

    [59] = {
        content = "这……这是一本那谁和那谁的同人小本子，好辣眼睛！",
        emoji = "",
        end_time = 4.0,
        id = 15,
        key = 59,
        sort = 3,
        speeker = 1,
        start_time = 7.0,
    },

    [60] = {
        content = "年轻人tooyoung，只要书套符合人设就行。",
        emoji = "",
        end_time = 3.5,
        id = 15,
        key = 60,
        sort = 4,
        speeker = 0,
        start_time = 11.5,
    },

    [61] = {
        content = "黑姐姐，好多人让我帮忙问问，你有木有交男票啊？",
        emoji = "",
        end_time = 3.5,
        id = 16,
        key = 61,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [62] = {
        content = "男票是什么，我只知道船票粮票和银票！",
        emoji = "",
        end_time = 3.5,
        id = 16,
        key = 62,
        sort = 2,
        speeker = 0,
        start_time = 5.0,
    },

    [63] = {
        content = "就是有没有喜欢的人。",
        emoji = "",
        end_time = 2.5,
        id = 16,
        key = 63,
        sort = 3,
        speeker = 1,
        start_time = 9.0,
    },

    [64] = {
        content = "喜欢的人？你、重华、檀、阿坊、面面、吞天……",
        emoji = "",
        end_time = 3.5,
        id = 16,
        key = 64,
        sort = 4,
        speeker = 0,
        start_time = 12.0,
    },

    [65] = {
        content = "没有想到为了拍摄妖灵契这部大电影，制片人竟然请来了拳王级别的高手做龙套，失敬失敬。",
        emoji = "",
        end_time = 5.0,
        id = 17,
        key = 65,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [66] = {
        content = "下班后来练两拳？",
        emoji = "",
        end_time = 2.5,
        id = 17,
        key = 66,
        sort = 2,
        speeker = 0,
        start_time = 6.5,
    },

    [67] = {
        content = "不不不，我还有约会……",
        emoji = "",
        end_time = 2.5,
        id = 17,
        key = 67,
        sort = 3,
        speeker = 1,
        start_time = 9.5,
    },

    [68] = {
        content = "推了！这场戏你的动作不到位，我来教教你！",
        emoji = "",
        end_time = 3.5,
        id = 17,
        key = 68,
        sort = 4,
        speeker = 0,
        start_time = 12.5,
    },

    [69] = {
        content = "领便当了！哇！最后一份蜜汁猪排饭！",
        emoji = "",
        end_time = 3.0,
        id = 18,
        key = 69,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [70] = {
        content = "放下！那份是我的！",
        emoji = "",
        end_time = 2.5,
        id = 18,
        key = 70,
        sort = 2,
        speeker = 0,
        start_time = 4.5,
    },

    [71] = {
        content = "这是我的便当。",
        emoji = "",
        end_time = 2.5,
        id = 18,
        key = 71,
        sort = 3,
        speeker = 1,
        start_time = 7.5,
    },

    [72] = {
        content = "我的便当！待会我就要领便当了还不让吃份好的吗！",
        emoji = "",
        end_time = 3.5,
        id = 18,
        key = 72,
        sort = 4,
        speeker = 0,
        start_time = 10.5,
    },

    [73] = {
        content = "嘟噜嘟噜！",
        emoji = "",
        end_time = 2.5,
        id = 19,
        key = 73,
        sort = 1,
        speeker = 0,
        start_time = 1.0,
    },

    [74] = {
        content = "别咬我头发，刚刚才做好的造型！",
        emoji = "",
        end_time = 3.0,
        id = 19,
        key = 74,
        sort = 2,
        speeker = 1,
        start_time = 4.0,
    },

    [75] = {
        content = "嘟噜！嘟噜！",
        emoji = "",
        end_time = 2.5,
        id = 19,
        key = 75,
        sort = 3,
        speeker = 0,
        start_time = 7.5,
    },

    [76] = {
        content = "别咬我衣服！嗯……你头套掉了？",
        emoji = "",
        end_time = 3.0,
        id = 19,
        key = 76,
        sort = 4,
        speeker = 1,
        start_time = 10.5,
    },

    [77] = {
        content = "唉！这套衣服比克瑞斯汀的还闷人！",
        emoji = "",
        end_time = 3.0,
        id = 19,
        key = 77,
        sort = 5,
        speeker = 0,
        start_time = 14.0,
    },

    [78] = {
        content = "我的双眼！我的三观！",
        emoji = "",
        end_time = 2.5,
        id = 19,
        key = 78,
        sort = 6,
        speeker = 1,
        start_time = 17.5,
    },

    [79] = {
        content = "告诉你们多少次，要爱护片场的一草一木，这些都是谁弄坏的全部照价赔偿！",
        emoji = "",
        end_time = 5.0,
        id = 20,
        key = 79,
        sort = 1,
        speeker = 0,
        start_time = 1.0,
    },

    [80] = {
        content = "导演威武！",
        emoji = "",
        end_time = 2.5,
        id = 20,
        key = 80,
        sort = 2,
        speeker = 1,
        start_time = 6.5,
    },

    [81] = {
        content = "还有你，今天的打戏不过关，明天全部重拍！",
        emoji = "",
        end_time = 3.0,
        id = 20,
        key = 81,
        sort = 3,
        speeker = 0,
        start_time = 9.5,
    },

    [82] = {
        content = "是是是，导演大人说得对。",
        emoji = "",
        end_time = 2.5,
        id = 20,
        key = 82,
        sort = 4,
        speeker = 1,
        start_time = 13.0,
    },

    [83] = {
        content = "好重！你的行囊里装石头了吗！",
        emoji = "",
        end_time = 2.5,
        id = 21,
        key = 83,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [84] = {
        content = "是啊，有形状古怪的石头、具有艺术性质的骨头、方便保存的耐饱食物、足够深入沙漠地区的水、便捷帐篷……",
        emoji = "",
        end_time = 5.0,
        id = 21,
        key = 84,
        sort = 2,
        speeker = 0,
        start_time = 4.0,
    },

    [85] = {
        content = "好敬业的地摊摊主。",
        emoji = "",
        end_time = 2.5,
        id = 21,
        key = 85,
        sort = 3,
        speeker = 1,
        start_time = 9.5,
    },

    [86] = {
        content = "这些比背房子轻多了啵哟！",
        emoji = "",
        end_time = 2.5,
        id = 21,
        key = 86,
        sort = 4,
        speeker = 0,
        start_time = 12.5,
    },

    [87] = {
        content = "花姐你家是武馆，你却不继承家业去跳舞，最后当了酒馆老板，也是好任性的呢。",
        emoji = "",
        end_time = 5.0,
        id = 22,
        key = 87,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [88] = {
        content = "做人要有理想，为了实现目标而努力的过程让人很陶醉呢！",
        emoji = "",
        end_time = 4.0,
        id = 22,
        key = 88,
        sort = 2,
        speeker = 0,
        start_time = 6.5,
    },

    [89] = {
        content = "请问你下一个目标是什么？",
        emoji = "",
        end_time = 3.0,
        id = 22,
        key = 89,
        sort = 3,
        speeker = 1,
        start_time = 11.0,
    },

    [90] = {
        content = "例如，先挣他一个亿！",
        emoji = "",
        end_time = 3.0,
        id = 22,
        key = 90,
        sort = 4,
        speeker = 0,
        start_time = 14.5,
    },

    [91] = {
        content = "请问你真的拥有时光机功能吗？",
        emoji = "",
        end_time = 3.0,
        id = 23,
        key = 91,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [92] = {
        content = "我只能让你听到过去某个短时间的事情。",
        emoji = "",
        end_time = 3.5,
        id = 23,
        key = 92,
        sort = 2,
        speeker = 0,
        start_time = 4.5,
    },

    [93] = {
        content = "（无语1）同样都主打蓝色，你连半个蓝胖子都不如……",
        emoji = "",
        end_time = 3.5,
        id = 23,
        key = 93,
        sort = 3,
        speeker = 1,
        start_time = 8.5,
    },

    [94] = {
        content = "……至少我腿长。",
        emoji = "",
        end_time = 2.5,
        id = 23,
        key = 94,
        sort = 4,
        speeker = 0,
        start_time = 12.5,
    },

    [95] = {
        content = "作为赌神，你有什么在玩法上的建议给大家吗？",
        emoji = "",
        end_time = 3.5,
        id = 24,
        key = 95,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [96] = {
        content = "记得常洗脸，记得常洗脸，记得常洗脸，重要的事情说三遍。",
        emoji = "",
        end_time = 5.0,
        id = 24,
        key = 96,
        sort = 2,
        speeker = 0,
        start_time = 5.0,
    },

    [97] = {
        content = "我刚刚洗完，你看我有行大运的迹象吗？",
        emoji = "",
        end_time = 3.0,
        id = 24,
        key = 97,
        sort = 3,
        speeker = 1,
        start_time = 10.5,
    },

    [98] = {
        content = "你需要换个头。",
        emoji = "",
        end_time = 2.5,
        id = 24,
        key = 98,
        sort = 4,
        speeker = 0,
        start_time = 14.0,
    },

    [99] = {
        content = "你手上拿的是什么武器？",
        emoji = "",
        end_time = 2.5,
        id = 25,
        key = 99,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [100] = {
        content = "你猜。",
        emoji = "",
        end_time = 2.5,
        id = 25,
        key = 100,
        sort = 2,
        speeker = 0,
        start_time = 4.0,
    },

    [101] = {
        content = "有点像钥匙，可也太大了，哪里有那么大的门！",
        emoji = "",
        end_time = 3.0,
        id = 25,
        key = 101,
        sort = 3,
        speeker = 1,
        start_time = 7.0,
    },

    [102] = {
        content = "长白山上青铜门。",
        emoji = "",
        end_time = 2.5,
        id = 25,
        key = 102,
        sort = 4,
        speeker = 0,
        start_time = 10.5,
    },

    [103] = {
        content = "同为玩蛇艺人，你跟千年前那位白夫人有什么亲戚关系吗？",
        emoji = "",
        end_time = 4.0,
        id = 26,
        key = 103,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [104] = {
        content = "哎呀被你看出来啦？她是我八大姨家堂叔公表舅邻居的……",
        emoji = "",
        end_time = 4.0,
        id = 26,
        key = 104,
        sort = 2,
        speeker = 0,
        start_time = 5.5,
    },

    [105] = {
        content = "算了当我没问。",
        emoji = "",
        end_time = 2.5,
        id = 26,
        key = 105,
        sort = 3,
        speeker = 1,
        start_time = 10.0,
    },

    [106] = {
        content = "听说你跟妖族的小崽们挺熟的？",
        emoji = "",
        end_time = 3.0,
        id = 27,
        key = 106,
        sort = 1,
        speeker = 0,
        start_time = 1.0,
    },

    [107] = {
        content = "连幼崽也不放过，我绝对不会让你得逞！",
        emoji = "",
        end_time = 3.0,
        id = 27,
        key = 107,
        sort = 2,
        speeker = 1,
        start_time = 4.5,
    },

    [108] = {
        content = "不是……那个，能不能……让我，摸，摸一摸？",
        emoji = "",
        end_time = 4.0,
        id = 27,
        key = 108,
        sort = 3,
        speeker = 0,
        start_time = 8.0,
    },

    [109] = {
        content = "摸，摸一摸？",
        emoji = "",
        end_time = 2.5,
        id = 27,
        key = 109,
        sort = 4,
        speeker = 1,
        start_time = 12.5,
    },

    [110] = {
        content = "嘿嘿嘿。",
        emoji = "",
        end_time = 2.5,
        id = 27,
        key = 110,
        sort = 5,
        speeker = 0,
        start_time = 15.5,
    },

    [111] = {
        content = "别一副痴汉脸，你的人设要崩塌了！",
        emoji = "",
        end_time = 3.0,
        id = 27,
        key = 111,
        sort = 6,
        speeker = 1,
        start_time = 18.5,
    },

    [112] = {
        content = "从嘟噜鸟变成美貌小姐姐，你到底经历了什么？",
        emoji = "",
        end_time = 3.5,
        id = 28,
        key = 112,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [113] = {
        content = "错的不是我，是世界。",
        emoji = "",
        end_time = 2.5,
        id = 28,
        key = 113,
        sort = 2,
        speeker = 0,
        start_time = 5.0,
    },

    [114] = {
        content = "这个时候，你只要保持微笑就可以了。",
        emoji = "",
        end_time = 3.0,
        id = 28,
        key = 114,
        sort = 3,
        speeker = 0,
        start_time = 8.0,
    },

    [115] = {
        content = "这样啊……",
        emoji = "",
        end_time = 2.5,
        id = 28,
        key = 115,
        sort = 4,
        speeker = 1,
        start_time = 11.5,
    },

    [116] = {
        content = "这个判官跟我想象的有点不一样啊！",
        emoji = "",
        end_time = 3.5,
        id = 29,
        key = 116,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [117] = {
        content = "我就是我不一样的烟火。",
        emoji = "",
        end_time = 2.5,
        id = 29,
        key = 117,
        sort = 2,
        speeker = 0,
        start_time = 5.0,
    },

    [118] = {
        content = "所以你是炸了么？",
        emoji = "",
        end_time = 2.5,
        id = 29,
        key = 118,
        sort = 3,
        speeker = 1,
        start_time = 8.0,
    },

    [119] = {
        content = "丑无大人经过一系列重创依然无所畏惧，非常值得我们学习。",
        emoji = "",
        end_time = 4.0,
        id = 30,
        key = 119,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [120] = {
        content = "不，那些对我起不了实质的伤害。",
        emoji = "",
        end_time = 3.0,
        id = 30,
        key = 120,
        sort = 2,
        speeker = 0,
        start_time = 5.5,
    },

    [121] = {
        content = "为什么？",
        emoji = "",
        end_time = 2.5,
        id = 30,
        key = 121,
        sort = 3,
        speeker = 1,
        start_time = 9.0,
    },

    [122] = {
        content = "因为面具才是我的本体。",
        emoji = "",
        end_time = 2.5,
        id = 30,
        key = 122,
        sort = 4,
        speeker = 0,
        start_time = 12.0,
    },

    [123] = {
        content = "你知道你的画风跟大家比有种格格不入的感觉吗？",
        emoji = "",
        end_time = 4.0,
        id = 31,
        key = 123,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [124] = {
        content = "哪里格格不入了？",
        emoji = "",
        end_time = 2.5,
        id = 31,
        key = 124,
        sort = 2,
        speeker = 0,
        start_time = 5.5,
    },

    [125] = {
        content = "浑身上下都透露出一种现代化的气息，你是从三次元穿过来的么？",
        emoji = "",
        end_time = 5.0,
        id = 31,
        key = 125,
        sort = 3,
        speeker = 1,
        start_time = 8.5,
    },

    [126] = {
        content = "大惊小怪，穿透次元壁对于妖族来讲简直是小事一桩。",
        emoji = "",
        end_time = 4.0,
        id = 31,
        key = 126,
        sort = 4,
        speeker = 0,
        start_time = 14.0,
    },

    [127] = {
        content = "看起来很好爽的样子？",
        emoji = "",
        end_time = 2.5,
        id = 32,
        key = 127,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [128] = {
        content = "啧~啧~，要不要来一口？威力无穷",
        emoji = "",
        end_time = 3.0,
        id = 32,
        key = 128,
        sort = 2,
        speeker = 0,
        start_time = 4.0,
    },

    [129] = {
        content = "（x）吸烟有害健康，小心举不起武器",
        emoji = "",
        end_time = 3.5,
        id = 32,
        key = 129,
        sort = 3,
        speeker = 1,
        start_time = 7.5,
    },

    [130] = {
        content = "",
        emoji = "zhenjing",
        end_time = 2.5,
        id = 32,
        key = 130,
        sort = 4,
        speeker = 0,
        start_time = 11.5,
    },

    [131] = {
        content = "我知道包子很重要，但你能不能不要总是走到哪里都捧着，这样好奇怪！",
        emoji = "",
        end_time = 5.0,
        id = 33,
        key = 131,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [132] = {
        content = "这是美术小姐姐指定的看板娘标配。",
        emoji = "",
        end_time = 3.5,
        id = 33,
        key = 132,
        sort = 2,
        speeker = 0,
        start_time = 6.5,
    },

    [133] = {
        content = "你们能不能不要总是怪美术小姐姐，她们很辛苦的！",
        emoji = "",
        end_time = 4.0,
        id = 33,
        key = 133,
        sort = 3,
        speeker = 1,
        start_time = 10.5,
    },

    [134] = {
        content = "那就是策划爸爸的锅。",
        emoji = "",
        end_time = 2.5,
        id = 33,
        key = 134,
        sort = 4,
        speeker = 0,
        start_time = 15.0,
    },

    [135] = {
        content = "请问能拉下面罩看看您的真容吗？",
        emoji = "",
        end_time = 3.0,
        id = 34,
        key = 135,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [136] = {
        content = "不可以！",
        emoji = "",
        end_time = 2.5,
        id = 34,
        key = 136,
        sort = 2,
        speeker = 0,
        start_time = 4.5,
    },

    [137] = {
        content = "不要难为情，来呀~快活呀~怎么还有一层面罩？",
        emoji = "",
        end_time = 3.5,
        id = 34,
        key = 137,
        sort = 3,
        speeker = 1,
        start_time = 7.5,
    },

    [138] = {
        content = "哼！",
        emoji = "",
        end_time = 2.0,
        id = 34,
        key = 138,
        sort = 4,
        speeker = 0,
        start_time = 11.5,
    },

    [139] = {
        content = "来一打进口猫罐头，我还要新的猫爬架和猫窝！",
        emoji = "",
        end_time = 4.0,
        id = 35,
        key = 139,
        sort = 1,
        speeker = 0,
        start_time = 1.0,
    },

    [140] = {
        content = "小萌整天捧着包子卖也不容易……",
        emoji = "",
        end_time = 3.5,
        id = 35,
        key = 140,
        sort = 2,
        speeker = 1,
        start_time = 5.5,
    },

    [141] = {
        content = "啊，小萌说要买这三个色的猫咪套装！",
        emoji = "",
        end_time = 3.5,
        id = 35,
        key = 141,
        sort = 3,
        speeker = 0,
        start_time = 9.5,
    },

    [142] = {
        content = "你的样子一看就是个反派无疑。",
        emoji = "",
        end_time = 3.0,
        id = 36,
        key = 142,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [143] = {
        content = "好歹也是个BOSS，不要总怼我，反派不要面子啊？",
        emoji = "",
        end_time = 4.0,
        id = 36,
        key = 143,
        sort = 2,
        speeker = 0,
        start_time = 4.5,
    },

    [144] = {
        content = "反派没有人权，你身上还有什么好东西快交出来！",
        emoji = "",
        end_time = 4.0,
        id = 36,
        key = 144,
        sort = 3,
        speeker = 1,
        start_time = 9.0,
    },

    [145] = {
        content = "到底谁是反派！",
        emoji = "",
        end_time = 2.5,
        id = 36,
        key = 145,
        sort = 4,
        speeker = 0,
        start_time = 13.5,
    },

    [146] = {
        content = "一看你笑眯眯的就觉得不是什么好人，鉴定完毕。",
        emoji = "",
        end_time = 4.0,
        id = 37,
        key = 146,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [147] = {
        content = "你知道吗，剧透的下场通常都不是很好。",
        emoji = "",
        end_time = 4.0,
        id = 37,
        key = 147,
        sort = 2,
        speeker = 0,
        start_time = 5.5,
    },

    [148] = {
        content = "你知道吗，主角光环之下我是无敌的。",
        emoji = "",
        end_time = 3.5,
        id = 37,
        key = 148,
        sort = 3,
        speeker = 1,
        start_time = 10.0,
    },

    [149] = {
        content = "尽管好气但是也要保持微笑。",
        emoji = "",
        end_time = 3.0,
        id = 37,
        key = 149,
        sort = 4,
        speeker = 0,
        start_time = 14.0,
    },

    [150] = {
        content = "听说最近流行起网红食品？",
        emoji = "",
        end_time = 2.5,
        id = 38,
        key = 150,
        sort = 1,
        speeker = 0,
        start_time = 1.0,
    },

    [151] = {
        content = "噢！婆婆你给我买好吃的了？",
        emoji = "",
        end_time = 3.0,
        id = 38,
        key = 151,
        sort = 2,
        speeker = 1,
        start_time = 4.0,
    },

    [152] = {
        content = "瑞士鲱鱼罐头豆腐汤，惊不惊喜，意不意外？",
        emoji = "",
        end_time = 3.5,
        id = 38,
        key = 152,
        sort = 3,
        speeker = 0,
        start_time = 7.5,
    },

    [153] = {
        content = "……我可能有个假婆婆。",
        emoji = "",
        end_time = 2.5,
        id = 38,
        key = 153,
        sort = 4,
        speeker = 1,
        start_time = 11.5,
    },

    [154] = {
        content = "作为全剧最正直的狗子，为什么老是喜欢逗鸟？",
        emoji = "",
        end_time = 3.0,
        id = 39,
        key = 154,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [155] = {
        content = "你猜是狗子，你全家都是，哼！",
        emoji = "",
        end_time = 3.0,
        id = 39,
        key = 155,
        sort = 2,
        speeker = 0,
        start_time = 4.5,
    },

    [156] = {
        content = "",
        emoji = "wuyu1",
        end_time = 2.5,
        id = 39,
        key = 156,
        sort = 3,
        speeker = 1,
        start_time = 8.0,
    },

    [157] = {
        content = "我逗鸟，鸟逗鸟。",
        emoji = "",
        end_time = 2.5,
        id = 39,
        key = 157,
        sort = 4,
        speeker = 0,
        start_time = 11.0,
    },

    [158] = {
        content = "前辈你周游世界一定知道一些快速增加实力的修行方式吧？",
        emoji = "",
        end_time = 4.0,
        id = 40,
        key = 158,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [159] = {
        content = "每天三餐都要吃巧克力蛋糕，下午茶来点马卡龙或者提拉米苏，坚持下去！",
        emoji = "",
        end_time = 5.0,
        id = 40,
        key = 159,
        sort = 2,
        speeker = 0,
        start_time = 5.5,
    },

    [160] = {
        content = "坚持一周我胖了十斤！",
        emoji = "",
        end_time = 2.5,
        id = 40,
        key = 160,
        sort = 3,
        speeker = 1,
        start_time = 11.0,
    },

    [161] = {
        content = "不然你看看我编撰的《浮屠食记》，记录了世界各地甜食对修行的帮助。",
        emoji = "",
        end_time = 5.0,
        id = 40,
        key = 161,
        sort = 4,
        speeker = 0,
        start_time = 14.0,
    },

    [162] = {
        content = "信了你的邪。",
        emoji = "",
        end_time = 2.5,
        id = 40,
        key = 162,
        sort = 5,
        speeker = 1,
        start_time = 19.5,
    },

    [163] = {
        content = "你看不到我看不到我。",
        emoji = "",
        end_time = 2.5,
        id = 41,
        key = 163,
        sort = 1,
        speeker = 0,
        start_time = 1.0,
    },

    [164] = {
        content = "哈我捉到你了！轮到你当鬼！",
        emoji = "",
        end_time = 3.0,
        id = 41,
        key = 164,
        sort = 2,
        speeker = 1,
        start_time = 4.0,
    },

    [165] = {
        content = "我本来就是鬼啊。",
        emoji = "",
        end_time = 2.5,
        id = 41,
        key = 165,
        sort = 3,
        speeker = 0,
        start_time = 7.5,
    },

    [166] = {
        content = "大家好我是妖灵契八卦周刊总经理白，请各位多多支持。",
        emoji = "",
        end_time = 4.0,
        id = 42,
        key = 166,
        sort = 1,
        speeker = 0,
        start_time = 1.0,
    },

    [167] = {
        content = "作为八卦小王子，你有什么惊天大八卦可以告诉手机前的观让大家乐乐的吗？",
        emoji = "",
        end_time = 5.0,
        id = 42,
        key = 167,
        sort = 2,
        speeker = 1,
        start_time = 5.5,
    },

    [168] = {
        content = "我们之中，有两个NPC一直妄想加入卡槽成为SSR顺便替代主角登上妖生巅峰。",
        emoji = "",
        end_time = 5.0,
        id = 42,
        key = 168,
        sort = 3,
        speeker = 0,
        start_time = 11.0,
    },

    [169] = {
        content = "谁谁谁！",
        emoji = "",
        end_time = 2.0,
        id = 42,
        key = 169,
        sort = 4,
        speeker = 1,
        start_time = 16.5,
    },

    [170] = {
        content = "啊咧，你猜。",
        emoji = "",
        end_time = 2.0,
        id = 42,
        key = 170,
        sort = 5,
        speeker = 0,
        start_time = 19.0,
    },

    [171] = {
        content = "姐，你这顶帽子好高，一眼看去你仿佛有两米八，这样不好。",
        emoji = "",
        end_time = 4.0,
        id = 43,
        key = 171,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [172] = {
        content = "为什么？",
        emoji = "",
        end_time = 2.5,
        id = 43,
        key = 172,
        sort = 2,
        speeker = 0,
        start_time = 5.5,
    },

    [173] = {
        content = "因为会显得白大人很矮，看起来像姐弟不方便撒狗粮。",
        emoji = "",
        end_time = 4.0,
        id = 43,
        key = 173,
        sort = 3,
        speeker = 1,
        start_time = 8.5,
    },

    [174] = {
        content = "你给我立刻马上滚出去！",
        emoji = "",
        end_time = 3.0,
        id = 43,
        key = 174,
        sort = 4,
        speeker = 0,
        start_time = 13.0,
    },

    [175] = {
        content = "你看我这副打扮好看吗？",
        emoji = "",
        end_time = 2.5,
        id = 44,
        key = 175,
        sort = 1,
        speeker = 0,
        start_time = 1.0,
    },

    [176] = {
        content = "更像敦煌飞天了。",
        emoji = "",
        end_time = 2.5,
        id = 44,
        key = 176,
        sort = 2,
        speeker = 1,
        start_time = 4.0,
    },

    [177] = {
        content = "还不够，我再换一套衣裳。",
        emoji = "",
        end_time = 2.5,
        id = 44,
        key = 177,
        sort = 3,
        speeker = 0,
        start_time = 7.0,
    },

    [178] = {
        content = "哥，接到好多投诉，你的伪娘之路不好走啊。",
        emoji = "",
        end_time = 3.5,
        id = 44,
        key = 178,
        sort = 4,
        speeker = 1,
        start_time = 10.0,
    },

    [179] = {
        content = "你闭嘴。",
        emoji = "",
        end_time = 2.0,
        id = 44,
        key = 179,
        sort = 5,
        speeker = 0,
        start_time = 14.0,
    },

    [180] = {
        content = "你身上的纹身是有什么特殊含义吗？",
        emoji = "",
        end_time = 3.0,
        id = 45,
        key = 180,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [181] = {
        content = "这些都需要你自己去想，我不方便剧透的。",
        emoji = "",
        end_time = 3.5,
        id = 45,
        key = 181,
        sort = 2,
        speeker = 0,
        start_time = 4.5,
    },

    [182] = {
        content = "透露一点不打紧。",
        emoji = "",
        end_time = 2.5,
        id = 45,
        key = 182,
        sort = 3,
        speeker = 1,
        start_time = 8.5,
    },

    [183] = {
        content = "打紧打紧，这样我就少很多乐趣了嘿嘿嘿。",
        emoji = "",
        end_time = 3.5,
        id = 45,
        key = 183,
        sort = 4,
        speeker = 0,
        start_time = 11.5,
    },

    [184] = {
        content = "接到好多热心观众的来电，大家都问你的哥哥在哪里？",
        emoji = "",
        end_time = 4.0,
        id = 46,
        key = 184,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [185] = {
        content = "因为我们是龙凤胎，长得像技能也像策划爸爸将我的哥哥雪藏了。",
        emoji = "",
        end_time = 5.0,
        id = 46,
        key = 185,
        sort = 2,
        speeker = 0,
        start_time = 5.5,
    },

    [186] = {
        content = "那你还怎么找哥哥？",
        emoji = "",
        end_time = 2.5,
        id = 46,
        key = 186,
        sort = 3,
        speeker = 1,
        start_time = 11.0,
    },

    [187] = {
        content = "只能，依靠手机前的热心观众们了。",
        emoji = "",
        end_time = 3.0,
        id = 46,
        key = 187,
        sort = 4,
        speeker = 0,
        start_time = 14.0,
    },

    [188] = {
        content = "你喜欢莹月吗？",
        emoji = "",
        end_time = 2.5,
        id = 47,
        key = 188,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [189] = {
        content = "我对莹月就像对待前辈一样心怀敬畏。",
        emoji = "",
        end_time = 3.0,
        id = 47,
        key = 189,
        sort = 2,
        speeker = 0,
        start_time = 4.0,
    },

    [190] = {
        content = "老实点不好吗？",
        emoji = "",
        end_time = 2.5,
        id = 47,
        key = 190,
        sort = 3,
        speeker = 1,
        start_time = 7.5,
    },

    [191] = {
        content = "活着不好吗？",
        emoji = "",
        end_time = 2.5,
        id = 47,
        key = 191,
        sort = 4,
        speeker = 0,
        start_time = 10.5,
    },

    [192] = {
        content = "谁把我的睡衣染成绿色！",
        emoji = "",
        end_time = 2.5,
        id = 48,
        key = 192,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [193] = {
        content = "看到我送你的新衣服了？喜欢吗？",
        emoji = "",
        end_time = 3.5,
        id = 48,
        key = 193,
        sort = 2,
        speeker = 0,
        start_time = 4.0,
    },

    [194] = {
        content = "你是不是皮卡丘的弟弟皮在痒？皮这一下你真的开心吗！",
        emoji = "",
        end_time = 4.0,
        id = 48,
        key = 194,
        sort = 3,
        speeker = 1,
        start_time = 8.0,
    },

    [195] = {
        content = "皮这一下我很开心！",
        emoji = "",
        end_time = 2.5,
        id = 48,
        key = 195,
        sort = 4,
        speeker = 0,
        start_time = 12.5,
    },

    [196] = {
        content = "你真妖艳",
        emoji = "",
        end_time = 2.5,
        id = 49,
        key = 196,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [197] = {
        content = "谢谢夸奖",
        emoji = "",
        end_time = 2.5,
        id = 49,
        key = 197,
        sort = 2,
        speeker = 0,
        start_time = 4.0,
    },

    [198] = {
        content = "你这样子真的好吗？",
        emoji = "",
        end_time = 2.5,
        id = 49,
        key = 198,
        sort = 3,
        speeker = 1,
        start_time = 7.0,
    },

    [199] = {
        content = "我是美的化身",
        emoji = "",
        end_time = 2.5,
        id = 49,
        key = 199,
        sort = 4,
        speeker = 0,
        start_time = 10.0,
    },

    [200] = {
        content = "你是不是还有哥哥或者弟弟？",
        emoji = "",
        end_time = 3.0,
        id = 50,
        key = 200,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [201] = {
        content = "是的，是弟弟，有问题吗？",
        emoji = "",
        end_time = 2.5,
        id = 50,
        key = 201,
        sort = 2,
        speeker = 0,
        start_time = 4.5,
    },

    [202] = {
        content = "果然都是同一个爹妈生的，真够辣眼睛的。",
        emoji = "",
        end_time = 3.5,
        id = 50,
        key = 202,
        sort = 3,
        speeker = 1,
        start_time = 7.5,
    },

    [203] = {
        content = "请别老盯着人家看，人家会害羞的。",
        emoji = "",
        end_time = 3.5,
        id = 50,
        key = 203,
        sort = 4,
        speeker = 0,
        start_time = 11.5,
    },

    [204] = {
        content = "老爷爷，今天你钓到鱼了吗？",
        emoji = "",
        end_time = 2.5,
        id = 51,
        key = 204,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [205] = {
        content = "我们的目的不是钓鱼。",
        emoji = "",
        end_time = 2.5,
        id = 51,
        key = 205,
        sort = 2,
        speeker = 0,
        start_time = 4.0,
    },

    [206] = {
        content = "那是什么？",
        emoji = "",
        end_time = 2.5,
        id = 51,
        key = 206,
        sort = 3,
        speeker = 1,
        start_time = 7.0,
    },

    [207] = {
        content = "星辰大海！",
        emoji = "",
        end_time = 2.5,
        id = 51,
        key = 207,
        sort = 4,
        speeker = 0,
        start_time = 10.0,
    },

    [208] = {
        content = "作为全国年纪最小的野生大熊猫饲养员，小朋友们要好好向执阳学习哟！",
        emoji = "",
        end_time = 5.0,
        id = 52,
        key = 208,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [209] = {
        content = "采访结束了吗？",
        emoji = "",
        end_time = 2.5,
        id = 52,
        key = 209,
        sort = 2,
        speeker = 0,
        start_time = 6.5,
    },

    [210] = {
        content = "是的，执阳你好乖请你吃糖。",
        emoji = "",
        end_time = 3.0,
        id = 52,
        key = 210,
        sort = 3,
        speeker = 1,
        start_time = 9.5,
    },

    [211] = {
        content = "幼稚，只有小孩子才喜欢吃糖。助理！打个电话给我的投资顾问，有几只股票要抛出了。",
        emoji = "",
        end_time = 5.0,
        id = 52,
        key = 211,
        sort = 4,
        speeker = 0,
        start_time = 13.0,
    },

    [212] = {
        content = "前天做了一个噩梦，梦到青竹的竹林莫名其妙地全被砍倒了！",
        emoji = "",
        end_time = 4.0,
        id = 53,
        key = 212,
        sort = 1,
        speeker = 0,
        start_time = 1.0,
    },

    [213] = {
        content = "嗯？没错啊，刚刚我过来看到有一片竹林全倒了。",
        emoji = "",
        end_time = 3.5,
        id = 53,
        key = 213,
        sort = 2,
        speeker = 1,
        start_time = 5.5,
    },

    [214] = {
        content = "什么！",
        emoji = "",
        end_time = 2.5,
        id = 53,
        key = 214,
        sort = 3,
        speeker = 0,
        start_time = 9.5,
    },

    [215] = {
        content = "执阳在那里玩得可开心呢！",
        emoji = "",
        end_time = 2.5,
        id = 53,
        key = 215,
        sort = 4,
        speeker = 1,
        start_time = 12.5,
    },

    [216] = {
        content = "我愿意为你，我愿意为你~！",
        emoji = "",
        end_time = 3.0,
        id = 54,
        key = 216,
        sort = 1,
        speeker = 0,
        start_time = 1.0,
    },

    [217] = {
        content = "美男子，你愿意为我什么呢？",
        emoji = "",
        end_time = 3.5,
        id = 54,
        key = 217,
        sort = 2,
        speeker = 1,
        start_time = 4.5,
    },

    [218] = {
        content = "咳咳咳，你听错了，我是在歌唱！",
        emoji = "",
        end_time = 3.0,
        id = 54,
        key = 218,
        sort = 3,
        speeker = 0,
        start_time = 8.5,
    },

    [219] = {
        content = "",
        emoji = "wuyu3",
        end_time = 2.5,
        id = 54,
        key = 219,
        sort = 4,
        speeker = 1,
        start_time = 12.0,
    },

    [220] = {
        content = "小姐姐，你的戒尺能借我玩玩吗？",
        emoji = "",
        end_time = 3.5,
        id = 55,
        key = 220,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [221] = {
        content = "你啥眼神，这是戒尺吗？这是扇子",
        emoji = "",
        end_time = 3.5,
        id = 55,
        key = 221,
        sort = 2,
        speeker = 0,
        start_time = 5.0,
    },

    [222] = {
        content = "",
        emoji = "zhenjing",
        end_time = 2.5,
        id = 55,
        key = 222,
        sort = 3,
        speeker = 1,
        start_time = 9.0,
    },

    [223] = {
        content = "一边玩去。",
        emoji = "",
        end_time = 2.5,
        id = 55,
        key = 223,
        sort = 4,
        speeker = 0,
        start_time = 12.0,
    },

    [224] = {
        content = "万万没想到整个游戏颜值最高的竟然是藏得最深的大BOSS！",
        emoji = "",
        end_time = 4.5,
        id = 56,
        key = 224,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [225] = {
        content = "正好长得比你帅一点点。",
        emoji = "",
        end_time = 2.5,
        id = 56,
        key = 225,
        sort = 2,
        speeker = 0,
        start_time = 6.0,
    },

    [226] = {
        content = "你的存在已经威胁到了主角！",
        emoji = "",
        end_time = 3.0,
        id = 56,
        key = 226,
        sort = 3,
        speeker = 1,
        start_time = 9.0,
    },

    [227] = {
        content = "你怎么跑去快递行业了？",
        emoji = "",
        end_time = 3.0,
        id = 57,
        key = 227,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [228] = {
        content = "闲着无聊加点戏份做个NPC还是可以的。",
        emoji = "",
        end_time = 3.5,
        id = 57,
        key = 228,
        sort = 2,
        speeker = 0,
        start_time = 4.5,
    },

    [229] = {
        content = "想当初老总想空降嘟嘟噜，被我KO掉了。",
        emoji = "",
        end_time = 3.5,
        id = 57,
        key = 229,
        sort = 3,
        speeker = 0,
        start_time = 8.5,
    },

    [230] = {
        content = "不不不，我想SSR是不会在意有没有这份活的。",
        emoji = "",
        end_time = 4.0,
        id = 57,
        key = 230,
        sort = 4,
        speeker = 1,
        start_time = 12.5,
    },

    [231] = {
        content = "你走！我不想见到你！",
        emoji = "",
        end_time = 3.0,
        id = 57,
        key = 231,
        sort = 6,
        speeker = 1,
        start_time = 17.0,
    },

    [232] = {
        content = "今天天气甚好，反正闲着也是闲着我们出去走走？",
        emoji = "",
        end_time = 3.5,
        id = 58,
        key = 232,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [233] = {
        content = "不啊，我要睡觉！睡醒了还要肝游戏，补番，煲剧……我好忙一点都不闲。",
        emoji = "",
        end_time = 5.0,
        id = 58,
        key = 233,
        sort = 2,
        speeker = 0,
        start_time = 5.0,
    },

    [234] = {
        content = "你这样会注孤生的。",
        emoji = "",
        end_time = 2.5,
        id = 58,
        key = 234,
        sort = 3,
        speeker = 1,
        start_time = 10.5,
    },

    [235] = {
        content = "对方并不想跟你说话并向你扔了一只狗。",
        emoji = "",
        end_time = 3.0,
        id = 58,
        key = 235,
        sort = 4,
        speeker = 0,
        start_time = 13.5,
    },

    [236] = {
        content = "我用明灯照亮你前方的路。",
        emoji = "",
        end_time = 2.5,
        id = 59,
        key = 236,
        sort = 1,
        speeker = 0,
        start_time = 1.0,
    },

    [237] = {
        content = "什么鬼，你是要和我玩天黑请闭眼吗？",
        emoji = "",
        end_time = 3.5,
        id = 59,
        key = 237,
        sort = 2,
        speeker = 1,
        start_time = 4.0,
    },

    [238] = {
        content = "那是什么？",
        emoji = "",
        end_time = 2.5,
        id = 59,
        key = 238,
        sort = 3,
        speeker = 0,
        start_time = 8.0,
    },

    [239] = {
        content = "当我没说，你继续， 我先走了。",
        emoji = "",
        end_time = 3.0,
        id = 59,
        key = 239,
        sort = 4,
        speeker = 1,
        start_time = 11.0,
    },

    [240] = {
        content = "别低头，王冠会掉，别流泪，坏人会笑。",
        emoji = "",
        end_time = 3.5,
        id = 60,
        key = 240,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [241] = {
        content = "一无所有的我早已无所畏惧。",
        emoji = "",
        end_time = 3.0,
        id = 60,
        key = 241,
        sort = 2,
        speeker = 0,
        start_time = 5.0,
    },

    [242] = {
        content = "你还有个双胞胎妹妹哇。",
        emoji = "",
        end_time = 2.5,
        id = 60,
        key = 242,
        sort = 3,
        speeker = 1,
        start_time = 8.5,
    },

    [243] = {
        content = "这就很尴尬了。",
        emoji = "",
        end_time = 2.5,
        id = 60,
        key = 243,
        sort = 4,
        speeker = 0,
        start_time = 11.5,
    },

    [244] = {
        content = "作为与主角互怼的反派，我很欣赏你的勇气。",
        emoji = "",
        end_time = 3.5,
        id = 61,
        key = 244,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [245] = {
        content = "不要怂，让我证明我也能拿下最佳男主角。",
        emoji = "",
        end_time = 3.5,
        id = 61,
        key = 245,
        sort = 2,
        speeker = 0,
        start_time = 5.0,
    },

    [246] = {
        content = "我又不需要你的橘子，我的奖杯还是自己收好。",
        emoji = "",
        end_time = 3.5,
        id = 61,
        key = 246,
        sort = 3,
        speeker = 1,
        start_time = 9.0,
    },

    [247] = {
        content = "人族和妖族的进化有什么区别，无非就是DNA里的……",
        emoji = "",
        end_time = 3.5,
        id = 62,
        key = 247,
        sort = 1,
        speeker = 0,
        start_time = 1.0,
    },

    [248] = {
        content = "不明觉厉听不懂。",
        emoji = "",
        end_time = 2.5,
        id = 62,
        key = 248,
        sort = 2,
        speeker = 1,
        start_time = 5.0,
    },

    [249] = {
        content = "顾名思义，人族到最后都会变成……",
        emoji = "",
        end_time = 3.0,
        id = 62,
        key = 249,
        sort = 3,
        speeker = 0,
        start_time = 8.0,
    },

    [250] = {
        content = "裁判员请坐下不要剧透！",
        emoji = "",
        end_time = 2.5,
        id = 62,
        key = 250,
        sort = 4,
        speeker = 1,
        start_time = 11.5,
    },

    [251] = {
        content = "嘘！你不用说话，我知道你想说什么。",
        emoji = "",
        end_time = 3.5,
        id = 63,
        key = 251,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [252] = {
        content = "我真的不认识你。",
        emoji = "",
        end_time = 2.5,
        id = 63,
        key = 252,
        sort = 2,
        speeker = 1,
        start_time = 5.0,
    },

    [253] = {
        content = "你挡路了麻烦让让。",
        emoji = "",
        end_time = 2.5,
        id = 63,
        key = 253,
        sort = 3,
        speeker = 1,
        start_time = 8.0,
    },

    [254] = {
        content = "当二五仔是没有好下场的，及早醒悟回头是岸啊！",
        emoji = "",
        end_time = 4.0,
        id = 64,
        key = 254,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [255] = {
        content = "世界那么大却没有我的容身之处！",
        emoji = "",
        end_time = 3.0,
        id = 64,
        key = 255,
        sort = 2,
        speeker = 0,
        start_time = 5.5,
    },

    [256] = {
        content = "不，你还有我！感不感动？",
        emoji = "",
        end_time = 2.5,
        id = 64,
        key = 256,
        sort = 3,
        speeker = 1,
        start_time = 9.0,
    },

    [257] = {
        content = "不敢动不敢动。",
        emoji = "",
        end_time = 2.5,
        id = 64,
        key = 257,
        sort = 4,
        speeker = 0,
        start_time = 12.0,
    },

    [258] = {
        content = "听说你每天要扑倒的次数多达百次？",
        emoji = "",
        end_time = 3.0,
        id = 65,
        key = 258,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [259] = {
        content = "少则百次多则千次，我已经熟练掌握扑下的朝向、力度，力争完美展示动作需求。",
        emoji = "",
        end_time = 5.0,
        id = 65,
        key = 259,
        sort = 2,
        speeker = 0,
        start_time = 4.5,
    },

    [260] = {
        content = "作为全年度最佳扑街之王你还有什么想说的吗？",
        emoji = "",
        end_time = 3.5,
        id = 65,
        key = 260,
        sort = 3,
        speeker = 1,
        start_time = 10.0,
    },

    [261] = {
        content = "谢谢我的动作指导，谢谢我的爸爸妈妈，谢谢场景谢谢特效谢谢程序猿！",
        emoji = "",
        end_time = 5.0,
        id = 65,
        key = 261,
        sort = 4,
        speeker = 0,
        start_time = 14.0,
    },

    [262] = {
        content = "前辈，我有一个好主意可以让你以最快的速度还清阿坊前辈的债务。",
        emoji = "",
        end_time = 4.5,
        id = 66,
        key = 262,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [263] = {
        content = "说！",
        emoji = "",
        end_time = 2.0,
        id = 66,
        key = 263,
        sort = 2,
        speeker = 0,
        start_time = 6.0,
    },

    [264] = {
        content = "活人的世界中有一种叫职业叫做吃播，只要有土豪打赏就能赚大钱啦！",
        emoji = "",
        end_time = 5.0,
        id = 66,
        key = 264,
        sort = 3,
        speeker = 1,
        start_time = 8.5,
    },

    [265] = {
        content = "你信不信阿坊前辈能把土豪也吃穷了。",
        emoji = "",
        end_time = 3.0,
        id = 66,
        key = 265,
        sort = 4,
        speeker = 0,
        start_time = 14.0,
    },

    [266] = {
        content = "听说活人的世界最近流行起大胃王了是吗？",
        emoji = "",
        end_time = 3.5,
        id = 67,
        key = 266,
        sort = 1,
        speeker = 0,
        start_time = 1.0,
    },

    [267] = {
        content = "也不是最近，流行蛮久了的。",
        emoji = "",
        end_time = 3.0,
        id = 67,
        key = 267,
        sort = 2,
        speeker = 1,
        start_time = 5.0,
    },

    [268] = {
        content = "不管，人家就问哪里可以报名！",
        emoji = "",
        end_time = 3.0,
        id = 67,
        key = 268,
        sort = 3,
        speeker = 0,
        start_time = 8.5,
    },

    [269] = {
        content = "作为餐厅黑名单排行榜的第一名你还是别妄想了。",
        emoji = "",
        end_time = 3.5,
        id = 67,
        key = 269,
        sort = 4,
        speeker = 1,
        start_time = 12.0,
    },

    [270] = {
        content = "教练我想学鼓！",
        emoji = "",
        end_time = 2.5,
        id = 68,
        key = 270,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [271] = {
        content = "你什么都想学，到最后什么也学不成！",
        emoji = "",
        end_time = 3.0,
        id = 68,
        key = 271,
        sort = 2,
        speeker = 0,
        start_time = 4.0,
    },

    [272] = {
        content = "相信我，我可以的。",
        emoji = "",
        end_time = 2.5,
        id = 68,
        key = 272,
        sort = 3,
        speeker = 1,
        start_time = 7.5,
    },

    [273] = {
        content = "那好，先练基本功。挥动鼓棒一万次。",
        emoji = "",
        end_time = 3.0,
        id = 68,
        key = 273,
        sort = 4,
        speeker = 0,
        start_time = 10.5,
    },

    [274] = {
        content = "……21、22、23……我还是学吞天玩火吧。",
        emoji = "",
        end_time = 3.5,
        id = 68,
        key = 274,
        sort = 5,
        speeker = 1,
        start_time = 14.0,
    },

    [275] = {
        content = "新的一年里你有什么愿望呢？",
        emoji = "",
        end_time = 3.0,
        id = 69,
        key = 275,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [276] = {
        content = "希望我能永远跟噬地姐姐在一起永远不分开。",
        emoji = "",
        end_time = 3.0,
        id = 69,
        key = 276,
        sort = 2,
        speeker = 0,
        start_time = 4.5,
    },

    [277] = {
        content = "自古红蓝出CP，这个愿望没毛病。",
        emoji = "",
        end_time = 3.0,
        id = 69,
        key = 277,
        sort = 3,
        speeker = 1,
        start_time = 8.0,
    },

    [278] = {
        content = "教练我想学喷火！",
        emoji = "",
        end_time = 2.5,
        id = 70,
        key = 278,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [279] = {
        content = "你什么都想学。",
        emoji = "",
        end_time = 2.5,
        id = 70,
        key = 279,
        sort = 2,
        speeker = 0,
        start_time = 4.0,
    },

    [280] = {
        content = "求求你教教我！",
        emoji = "",
        end_time = 2.5,
        id = 70,
        key = 280,
        sort = 3,
        speeker = 1,
        start_time = 7.0,
    },

    [281] = {
        content = "可我也不懂喷火，这个技能是天生的。",
        emoji = "",
        end_time = 3.0,
        id = 70,
        key = 281,
        sort = 5,
        speeker = 0,
        start_time = 10.0,
    },

    [282] = {
        content = "为什么我讲了那么多笑话你还不笑？",
        emoji = "",
        end_time = 3.0,
        id = 71,
        key = 282,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [283] = {
        content = "你看到我嘴角微微上翘的弧度看吗？",
        emoji = "",
        end_time = 3.0,
        id = 71,
        key = 283,
        sort = 2,
        speeker = 0,
        start_time = 4.5,
    },

    [284] = {
        content = "没有看到。",
        emoji = "",
        end_time = 2.5,
        id = 71,
        key = 284,
        sort = 3,
        speeker = 1,
        start_time = 8.0,
    },

    [285] = {
        content = "嗯，可能是你的笑点跟我的笑点是两条平行线吧。",
        emoji = "",
        end_time = 3.5,
        id = 71,
        key = 285,
        sort = 4,
        speeker = 0,
        start_time = 11.0,
    },

    [286] = {
        content = "作为冥界最强的男人你有什么获奖感言吗？",
        emoji = "",
        end_time = 3.5,
        id = 72,
        key = 286,
        sort = 1,
        speeker = 1,
        start_time = 1.0,
    },

    [287] = {
        content = "闪开，你挡住我手动刷战役了！",
        emoji = "",
        end_time = 3.0,
        id = 72,
        key = 287,
        sort = 2,
        speeker = 0,
        start_time = 5.0,
    },

    [288] = {
        content = "震惊！自己打自己这么开心！",
        emoji = "",
        end_time = 3.0,
        id = 72,
        key = 288,
        sort = 3,
        speeker = 1,
        start_time = 8.5,
    },

    [289] = {
        content = "竟然来了顺便组队刷下茶会！我奉主夜鹤碎片还差点！",
        emoji = "",
        end_time = 4.0,
        id = 72,
        key = 289,
        sort = 4,
        speeker = 0,
        start_time = 12.0,
    },

    [290] = {
        content = "我可能玩了个假游戏。",
        emoji = "",
        end_time = 2.5,
        id = 72,
        key = 290,
        sort = 5,
        speeker = 1,
        start_time = 16.5,
    },

}
