-- ./excel/system/org/org.xlsx
return {

    [1] = {
        active_need = 0,
        agree_reject_join = 1,
        authorize_pos = {1, 2, 3, 4, 5},
        auto_appoint = 0,
        ban_chat = 1,
        bg = "bg_gonghui_huizhangdi",
        broadcast = 1,
        buy = 1,
        del_pos = {2, 3, 4, 5},
        edit_aim = 1,
        edit_flag = 1,
        exit_tips = 1,
        invite = 1,
        mail = 1,
        pos = "会长",
        posid = 1,
        rename = 1,
        show_sort = 1,
        target_pos = {1, 2, 3, 4},
        text_color = {["b"] = 0.15, ["g"] = 0.28, ["r"] = 0.73},
        upgrade = 1,
    },

    [2] = {
        active_need = 0,
        agree_reject_join = 1,
        authorize_pos = {3, 4, 5},
        auto_appoint = 0,
        ban_chat = 0,
        bg = "bg_gonghui_fuhuidi",
        broadcast = 1,
        buy = 1,
        del_pos = {3, 4, 5},
        edit_aim = 1,
        edit_flag = 1,
        exit_tips = 0,
        invite = 1,
        mail = 1,
        pos = "副会",
        posid = 2,
        rename = 0,
        show_sort = 2,
        target_pos = {3, 4},
        text_color = {["b"] = 0.49, ["g"] = 0.28, ["r"] = 0.42},
        upgrade = 1,
    },

    [3] = {
        active_need = 0,
        agree_reject_join = 0,
        authorize_pos = {},
        auto_appoint = 0,
        ban_chat = 0,
        bg = "bg_gonghui_jingyingdi",
        broadcast = 0,
        buy = 0,
        del_pos = {},
        edit_aim = 0,
        edit_flag = 0,
        exit_tips = 0,
        invite = 1,
        mail = 0,
        pos = "精英",
        posid = 3,
        rename = 0,
        show_sort = 3,
        target_pos = {},
        text_color = {["b"] = 0.52, ["g"] = 0.36, ["r"] = 0.16},
        upgrade = 0,
    },

    [4] = {
        active_need = 0,
        agree_reject_join = 0,
        authorize_pos = {},
        auto_appoint = 0,
        ban_chat = 0,
        bg = "bg_gonghui_chengyuandi",
        broadcast = 0,
        buy = 0,
        del_pos = {},
        edit_aim = 0,
        edit_flag = 0,
        exit_tips = 0,
        invite = 1,
        mail = 0,
        pos = "成员",
        posid = 4,
        rename = 0,
        show_sort = 4,
        target_pos = {},
        text_color = {["b"] = 0.48, ["g"] = 0.44, ["r"] = 0.09},
        upgrade = 0,
    },

    [5] = {
        active_need = 0,
        agree_reject_join = 0,
        authorize_pos = {},
        auto_appoint = 0,
        ban_chat = 0,
        bg = "bg_gonghui_xinrendi",
        broadcast = 0,
        buy = 0,
        del_pos = {},
        edit_aim = 0,
        edit_flag = 0,
        exit_tips = 0,
        invite = 1,
        mail = 0,
        pos = "新人",
        posid = 5,
        rename = 0,
        show_sort = 5,
        target_pos = {},
        text_color = {["b"] = 0.41, ["g"] = 0.53, ["r"] = 0.62},
        upgrade = 0,
    },

}
