-- ./excel/huodong/worldboss/npc.xlsx
return {

    [1001] = {
        id = 1001,
        lifeTime = 0,
        modelId = 1100,
        mutateColor = {},
        mutateTexture = 0,
        name = "邪靡",
        nameType = 1,
        ornamentId = 0,
        rotateY = 0.0,
        scale = 1.8,
        sceneId = 1001,
        title = "",
        type = 3,
        wpmodel = 0,
        x = 12.0,
        y = 8.0,
        z = 0.0,
    },

    [1002] = {
        id = 1002,
        lifeTime = 0,
        modelId = 1015,
        mutateColor = {},
        mutateTexture = 0,
        name = "链",
        nameType = 1,
        ornamentId = 0,
        rotateY = 0.0,
        scale = 1.8,
        sceneId = 1001,
        title = "",
        type = 3,
        wpmodel = 0,
        x = 12.0,
        y = 8.0,
        z = 0.0,
    },

    [1003] = {
        id = 1003,
        lifeTime = 0,
        modelId = 1501,
        mutateColor = {},
        mutateTexture = 0,
        name = "扳尾",
        nameType = 1,
        ornamentId = 0,
        rotateY = 0.0,
        scale = 1.8,
        sceneId = 1001,
        title = "",
        type = 3,
        wpmodel = 0,
        x = 12.0,
        y = 8.0,
        z = 0.0,
    },

    [1004] = {
        id = 1004,
        lifeTime = 0,
        modelId = 1511,
        mutateColor = {},
        mutateTexture = 0,
        name = "鸦",
        nameType = 1,
        ornamentId = 0,
        rotateY = 0.0,
        scale = 1.8,
        sceneId = 1001,
        title = "",
        type = 3,
        wpmodel = 0,
        x = 12.0,
        y = 8.0,
        z = 0.0,
    },

}
