-- ./excel/huodong/orgwar/npc.xlsx
return {

    [50001] = {
        diglogface = 0,
        event = 1001,
        grade = 1,
        id = 50001,
        lifeTime = 0,
        modelId = 1650,
        mutateColor = {},
        mutateTexture = 0,
        name = "丑无",
        nameType = 1,
        ornamentId = 0,
        rotateY = 125.0,
        scale = 0.0,
        sceneId = 1001,
        title = "公会战使者",
        tollgateId = 0,
        type = 3,
        wpmodel = 0,
        x = 2.147,
        y = 5.068,
        z = 0.0,
    },

    [50002] = {
        diglogface = 0,
        event = 1002,
        grade = 1,
        id = 50002,
        lifeTime = 0,
        modelId = 3009,
        mutateColor = {},
        mutateTexture = 0,
        name = "守护水晶",
        nameType = 1,
        ornamentId = 0,
        rotateY = -140.0,
        scale = 0.0,
        sceneId = 1027,
        title = "$orgname",
        tollgateId = 0,
        type = 3,
        wpmodel = 0,
        x = 6.0,
        y = 19.3,
        z = 0.0,
    },

    [50003] = {
        diglogface = 0,
        event = 1003,
        grade = 1,
        id = 50003,
        lifeTime = 0,
        modelId = 3010,
        mutateColor = {},
        mutateTexture = 0,
        name = "守护水晶",
        nameType = 1,
        ornamentId = 0,
        rotateY = -140.0,
        scale = 0.0,
        sceneId = 1027,
        title = "$orgname",
        tollgateId = 0,
        type = 3,
        wpmodel = 0,
        x = 25.5,
        y = 6.4,
        z = 0.0,
    },

    [50004] = {
        diglogface = 0,
        event = 1004,
        grade = 1,
        id = 50004,
        lifeTime = 0,
        modelId = 1650,
        mutateColor = {},
        mutateTexture = 0,
        name = "丑无",
        nameType = 1,
        ornamentId = 0,
        rotateY = -140.0,
        scale = 0.0,
        sceneId = 1026,
        title = "公会战使者",
        tollgateId = 0,
        type = 3,
        wpmodel = 0,
        x = 5.3,
        y = 13.2,
        z = 0.0,
    },

}
