-- ./excel/item/partner_awake.xlsx
return {

    [27401] = {
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {},
        buy_price = 0,
        circulation_type = 0,
        coin_cost = 0,
        composable = 0,
        compose_item = {},
        description = "记载着觉醒秘方的书卷。",
        gain_way_id = {7, 168, 180},
        gift_price = 0,
        giftable = 0,
        icon = 27401,
        id = 27401,
        introduction = "所有种族伙伴觉醒力量的通用材料",
        max_grade = 200,
        max_overlay = 999999,
        min_grade = 1,
        name = "梦觉书·零",
        quality = 2,
        quickable = 0,
        race_type = 0,
        sale_price = 1000,
        stallable = 0,
        taskid = 0,
        type = 8,
        use_type = "",
    },

    [27402] = {
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 20, ["discount"] = 0}},
        buy_price = 0,
        circulation_type = 0,
        coin_cost = 0,
        composable = 0,
        compose_item = {},
        description = "记载着觉醒秘方的书卷。",
        gain_way_id = {438, 168, 180},
        gift_price = 0,
        giftable = 0,
        icon = 27402,
        id = 27402,
        introduction = "所有种族伙伴觉醒力量的通用材料",
        max_grade = 200,
        max_overlay = 999999,
        min_grade = 1,
        name = "梦觉书·低",
        quality = 3,
        quickable = 0,
        race_type = 0,
        sale_price = 1500,
        stallable = 0,
        taskid = 0,
        type = 8,
        use_type = "partner_awake",
    },

    [27403] = {
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 100, ["discount"] = 0}},
        buy_price = 0,
        circulation_type = 0,
        coin_cost = 4000,
        composable = 1,
        compose_item = {{["amount"] = 5, ["sid"] = 27402}},
        description = "记载着觉醒秘方的书卷。",
        gain_way_id = {438, 168, 180, 30002},
        gift_price = 0,
        giftable = 0,
        icon = 27403,
        id = 27403,
        introduction = "所有种族伙伴觉醒力量的通用材料",
        max_grade = 200,
        max_overlay = 999999,
        min_grade = 1,
        name = "梦觉书·高",
        quality = 4,
        quickable = 0,
        race_type = 0,
        sale_price = 7500,
        stallable = 0,
        taskid = 0,
        type = 8,
        use_type = "partner_awake",
    },

    [27404] = {
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {},
        buy_price = 0,
        circulation_type = 0,
        coin_cost = 0,
        composable = 0,
        compose_item = {},
        description = "记载着觉醒秘方的书卷。",
        gain_way_id = {439, 168, 180},
        gift_price = 0,
        giftable = 0,
        icon = 27404,
        id = 27404,
        introduction = "人族伙伴觉醒力量的材料",
        max_grade = 200,
        max_overlay = 999999,
        min_grade = 1,
        name = "人灵决·零",
        quality = 2,
        quickable = 0,
        race_type = 1,
        sale_price = 1000,
        stallable = 0,
        taskid = 0,
        type = 8,
        use_type = "",
    },

    [27405] = {
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 20, ["discount"] = 0}},
        buy_price = 0,
        circulation_type = 0,
        coin_cost = 0,
        composable = 0,
        compose_item = {},
        description = "记载着觉醒秘方的书卷。",
        gain_way_id = {439, 168, 180},
        gift_price = 0,
        giftable = 0,
        icon = 27405,
        id = 27405,
        introduction = "人族伙伴觉醒力量的材料",
        max_grade = 200,
        max_overlay = 999999,
        min_grade = 1,
        name = "人灵决·低",
        quality = 3,
        quickable = 0,
        race_type = 1,
        sale_price = 1500,
        stallable = 0,
        taskid = 0,
        type = 8,
        use_type = "partner_awake",
    },

    [27406] = {
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 100, ["discount"] = 0}},
        buy_price = 0,
        circulation_type = 0,
        coin_cost = 4000,
        composable = 1,
        compose_item = {{["amount"] = 5, ["sid"] = 27405}},
        description = "记载着觉醒秘方的书卷。",
        gain_way_id = {439, 168, 180, 30002},
        gift_price = 0,
        giftable = 0,
        icon = 27406,
        id = 27406,
        introduction = "人族伙伴觉醒力量的材料",
        max_grade = 200,
        max_overlay = 999999,
        min_grade = 1,
        name = "人灵决·高",
        quality = 4,
        quickable = 0,
        race_type = 1,
        sale_price = 7500,
        stallable = 0,
        taskid = 0,
        type = 8,
        use_type = "partner_awake",
    },

    [27407] = {
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {},
        buy_price = 0,
        circulation_type = 0,
        coin_cost = 0,
        composable = 0,
        compose_item = {},
        description = "记载着觉醒秘方的书卷。",
        gain_way_id = {440, 168, 180},
        gift_price = 0,
        giftable = 0,
        icon = 27407,
        id = 27407,
        introduction = "妖族伙伴觉醒力量的材料",
        max_grade = 200,
        max_overlay = 999999,
        min_grade = 1,
        name = "妖风铃·零",
        quality = 2,
        quickable = 0,
        race_type = 2,
        sale_price = 1000,
        stallable = 0,
        taskid = 0,
        type = 8,
        use_type = "",
    },

    [27408] = {
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 20, ["discount"] = 0}},
        buy_price = 0,
        circulation_type = 0,
        coin_cost = 0,
        composable = 0,
        compose_item = {},
        description = "记载着觉醒秘方的书卷。",
        gain_way_id = {440, 168, 180},
        gift_price = 0,
        giftable = 0,
        icon = 27408,
        id = 27408,
        introduction = "妖族伙伴觉醒力量的材料",
        max_grade = 200,
        max_overlay = 999999,
        min_grade = 1,
        name = "妖风铃·低",
        quality = 3,
        quickable = 0,
        race_type = 2,
        sale_price = 1500,
        stallable = 0,
        taskid = 0,
        type = 8,
        use_type = "partner_awake",
    },

    [27409] = {
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 100, ["discount"] = 0}},
        buy_price = 0,
        circulation_type = 0,
        coin_cost = 4000,
        composable = 1,
        compose_item = {{["amount"] = 5, ["sid"] = 27408}},
        description = "记载着觉醒秘方的书卷。",
        gain_way_id = {440, 168, 180, 30002},
        gift_price = 0,
        giftable = 0,
        icon = 27409,
        id = 27409,
        introduction = "妖族伙伴觉醒力量的材料",
        max_grade = 200,
        max_overlay = 999999,
        min_grade = 1,
        name = "妖风铃·高",
        quality = 4,
        quickable = 0,
        race_type = 2,
        sale_price = 7500,
        stallable = 0,
        taskid = 0,
        type = 8,
        use_type = "partner_awake",
    },

    [27410] = {
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {},
        buy_price = 0,
        circulation_type = 0,
        coin_cost = 0,
        composable = 0,
        compose_item = {},
        description = "记载着觉醒秘方的书卷。",
        gain_way_id = {441, 168, 180},
        gift_price = 0,
        giftable = 0,
        icon = 27410,
        id = 27410,
        introduction = "鬼族伙伴觉醒力量的材料",
        max_grade = 200,
        max_overlay = 999999,
        min_grade = 1,
        name = "鬼云轮·零",
        quality = 2,
        quickable = 0,
        race_type = 3,
        sale_price = 1000,
        stallable = 0,
        taskid = 0,
        type = 8,
        use_type = "",
    },

    [27411] = {
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 20, ["discount"] = 0}},
        buy_price = 0,
        circulation_type = 0,
        coin_cost = 0,
        composable = 0,
        compose_item = {},
        description = "记载着觉醒秘方的书卷。",
        gain_way_id = {441, 168, 180},
        gift_price = 0,
        giftable = 0,
        icon = 27411,
        id = 27411,
        introduction = "鬼族伙伴觉醒力量的材料",
        max_grade = 200,
        max_overlay = 999999,
        min_grade = 1,
        name = "鬼云轮·低",
        quality = 3,
        quickable = 0,
        race_type = 3,
        sale_price = 1500,
        stallable = 0,
        taskid = 0,
        type = 8,
        use_type = "partner_awake",
    },

    [27412] = {
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 100, ["discount"] = 0}},
        buy_price = 0,
        circulation_type = 0,
        coin_cost = 4000,
        composable = 1,
        compose_item = {{["amount"] = 5, ["sid"] = 27411}},
        description = "记载着觉醒秘方的书卷。",
        gain_way_id = {441, 168, 180, 30002},
        gift_price = 0,
        giftable = 0,
        icon = 27412,
        id = 27412,
        introduction = "鬼族伙伴觉醒力量的材料",
        max_grade = 200,
        max_overlay = 999999,
        min_grade = 1,
        name = "鬼云轮·高",
        quality = 4,
        quickable = 0,
        race_type = 3,
        sale_price = 7500,
        stallable = 0,
        taskid = 0,
        type = 8,
        use_type = "partner_awake",
    },

}
