-- ./excel/item/housegift.xlsx
return {

    [30601] = {
        circulation_type = 0,
        client_extra = "use",
        description = [=[据说是执阳妈妈给喜欢熊猫的执阳做的蛋糕。
送礼至宅邸伙伴可获得650亲密度。]=],
        giftable = 1,
        icon = 30601,
        id = 30601,
        introduction = "获得650亲密度",
        loveship = 650,
        max_overlay = 999,
        name = "熊猫蛋糕",
        nimbus = 0,
        quality = 4,
        quickable = 0,
        sort = 3,
        stallable = 0,
        taskid = 0,
    },

    [30602] = {
        circulation_type = 0,
        client_extra = "use",
        description = [=[爱心满满蛋糕，吃了会有初恋的感觉。
送礼至宅邸伙伴可获得700亲密度。]=],
        giftable = 1,
        icon = 30602,
        id = 30602,
        introduction = "获得700亲密度",
        loveship = 700,
        max_overlay = 999,
        name = "爱心满满",
        nimbus = 0,
        quality = 4,
        quickable = 0,
        sort = 3,
        stallable = 0,
        taskid = 0,
    },

    [30603] = {
        circulation_type = 0,
        client_extra = "use",
        description = [=[贵族最爱的甜品，精致酥甜。
送礼至宅邸伙伴可获得850亲密度。]=],
        giftable = 1,
        icon = 30603,
        id = 30603,
        introduction = "获得850亲密度",
        loveship = 850,
        max_overlay = 999,
        name = "三彩马卡龙",
        nimbus = 0,
        quality = 4,
        quickable = 0,
        sort = 3,
        stallable = 0,
        taskid = 0,
    },

    [30604] = {
        circulation_type = 0,
        client_extra = "use",
        description = [=[蛋糕的食材是天上的彩虹。
送礼至宅邸伙伴可获得1000亲密度。]=],
        giftable = 1,
        icon = 30604,
        id = 30604,
        introduction = "获得1000亲密度",
        loveship = 1000,
        max_overlay = 999,
        name = "彩虹蛋糕",
        nimbus = 0,
        quality = 4,
        quickable = 0,
        sort = 3,
        stallable = 0,
        taskid = 0,
    },

    [30605] = {
        circulation_type = 0,
        client_extra = "use",
        description = [=[精致和果子，女神们无法抵抗它的魅力。
送礼至宅邸伙伴可获得1100亲密度。]=],
        giftable = 1,
        icon = 30605,
        id = 30605,
        introduction = "获得1100亲密度",
        loveship = 1100,
        max_overlay = 999,
        name = "和果子",
        nimbus = 0,
        quality = 4,
        quickable = 0,
        sort = 3,
        stallable = 0,
        taskid = 0,
    },

    [30606] = {
        circulation_type = 0,
        client_extra = "use",
        description = [=[曾经因为一句“喝了可以润肤”的广告语风靡全世界。
送礼至宅邸伙伴可获得650亲密度。]=],
        giftable = 1,
        icon = 30606,
        id = 30606,
        introduction = "获得650亲密度",
        loveship = 650,
        max_overlay = 999,
        name = "橙汁",
        nimbus = 0,
        quality = 4,
        quickable = 0,
        sort = 3,
        stallable = 0,
        taskid = 0,
    },

    [30607] = {
        circulation_type = 0,
        client_extra = "use",
        description = [=[“再看就把你喝掉哦”，会说话的饮料。
送礼至宅邸伙伴可获得750亲密度。]=],
        giftable = 1,
        icon = 30607,
        id = 30607,
        introduction = "获得750亲密度",
        loveship = 750,
        max_overlay = 999,
        name = "大嘴饮料",
        nimbus = 0,
        quality = 4,
        quickable = 0,
        sort = 3,
        stallable = 0,
        taskid = 0,
    },

    [30608] = {
        circulation_type = 0,
        client_extra = "use",
        description = [=[据说是仿造某大厂的品牌，味道真是分不出哪个是真的。
送礼至宅邸伙伴可获得900亲密度。]=],
        giftable = 1,
        icon = 30608,
        id = 30608,
        introduction = "获得900亲密度",
        loveship = 900,
        max_overlay = 999,
        name = "妖旋风",
        nimbus = 0,
        quality = 4,
        quickable = 0,
        sort = 3,
        stallable = 0,
        taskid = 0,
    },

    [30609] = {
        circulation_type = 0,
        client_extra = "use",
        description = [=[竟然还有会通灵的可乐，这世界真是无奇不有。
送礼至宅邸伙伴可获得1050亲密度。]=],
        giftable = 1,
        icon = 30609,
        id = 30609,
        introduction = "获得1050亲密度",
        loveship = 1050,
        max_overlay = 999,
        name = "灵度可乐",
        nimbus = 0,
        quality = 4,
        quickable = 0,
        sort = 3,
        stallable = 0,
        taskid = 0,
    },

    [30610] = {
        circulation_type = 0,
        client_extra = "use",
        description = [=[彩虹蛋糕的最佳搭配饮品，传闻一起吃会有奇妙的事情发生。
送礼至宅邸伙伴可获得1100亲密度。]=],
        giftable = 1,
        icon = 30610,
        id = 30610,
        introduction = "获得1100亲密度",
        loveship = 1100,
        max_overlay = 999,
        name = "彩虹饮料",
        nimbus = 0,
        quality = 4,
        quickable = 0,
        sort = 3,
        stallable = 0,
        taskid = 0,
    },

    [30611] = {
        circulation_type = 0,
        client_extra = "use",
        description = [=[你们世界有大雪人雪糕，我们世界有熊猫雪糕哦。
送礼至宅邸伙伴可获得650亲密度。]=],
        giftable = 1,
        icon = 30611,
        id = 30611,
        introduction = "获得650亲密度",
        loveship = 650,
        max_overlay = 999,
        name = "大熊雪糕",
        nimbus = 0,
        quality = 4,
        quickable = 0,
        sort = 3,
        stallable = 0,
        taskid = 0,
    },

    [30801] = {
        circulation_type = 0,
        client_extra = "use",
        description = [=[侠士们行走江路时留下的战斗经验
送礼至宅邸伙伴可获得1200亲密度。]=],
        giftable = 0,
        icon = 30801,
        id = 30801,
        introduction = "获得1200亲密度",
        loveship = 1200,
        max_overlay = 999,
        name = "胶囊",
        nimbus = 0,
        quality = 4,
        quickable = 0,
        sort = 3,
        stallable = 0,
        taskid = 0,
    },

    [30612] = {
        circulation_type = 0,
        client_extra = "use",
        description = [=[雪糕还能扒皮，还能不能好好的吃雪糕了。
送礼至宅邸伙伴可获得800亲密度。]=],
        giftable = 1,
        icon = 30612,
        id = 30612,
        introduction = "获得800亲密度",
        loveship = 800,
        max_overlay = 999,
        name = "香蕉雪糕",
        nimbus = 0,
        quality = 4,
        quickable = 0,
        sort = 3,
        stallable = 0,
        taskid = 0,
    },

    [30613] = {
        circulation_type = 0,
        client_extra = "use",
        description = [=[魔方的魅力加上雪糕，谁能阻挡其味道呢。
送礼至宅邸伙伴可获得950亲密度。]=],
        giftable = 1,
        icon = 30613,
        id = 30613,
        introduction = "获得950亲密度",
        loveship = 950,
        max_overlay = 999,
        name = "魔方雪糕",
        nimbus = 0,
        quality = 4,
        quickable = 0,
        sort = 3,
        stallable = 0,
        taskid = 0,
    },

    [30614] = {
        circulation_type = 0,
        client_extra = "use",
        description = [=[草莓都是咸鱼厨师去枫竹林一颗一颗摘得。
送礼至宅邸伙伴可获得1050亲密度。]=],
        giftable = 1,
        icon = 30614,
        id = 30614,
        introduction = "获得1050亲密度",
        loveship = 1050,
        max_overlay = 999,
        name = "草莓球",
        nimbus = 0,
        quality = 4,
        quickable = 0,
        sort = 3,
        stallable = 0,
        taskid = 0,
    },

    [30615] = {
        circulation_type = 0,
        client_extra = "use",
        description = [=[这不是雪糕，这是艺术。这不是雪糕，这是艺术。
送礼至宅邸伙伴可获得1100亲密度。]=],
        giftable = 1,
        icon = 30615,
        id = 30615,
        introduction = "获得1100亲密度",
        loveship = 1100,
        max_overlay = 999,
        name = "黄金字塔",
        nimbus = 0,
        quality = 4,
        quickable = 0,
        sort = 3,
        stallable = 0,
        taskid = 0,
    },

}
