-- ./excel/item/virtual.xlsx
return {

    [1001] = {
        description = "通过充值获得",
        gain_way_id = {},
        icon = 1001,
        id = 1001,
        introduction = "购买礼包以及兑换水晶和金币",
        more_detail = "",
        name = "彩晶",
        quality = 4,
    },

    [1002] = {
        description = "通过各玩法和水晶兑换获得",
        gain_way_id = {},
        icon = 1002,
        id = 1002,
        introduction = "用于购买商店道具、符文强化、伙伴培育等",
        more_detail = "",
        name = "金币",
        quality = 2,
    },

    [1003] = {
        description = "通过各玩法兑换获得",
        gain_way_id = {},
        icon = 1003,
        id = 1003,
        introduction = "用于金币兑换和礼包购买等",
        more_detail = "",
        name = "水晶",
        quality = 4,
    },

    [1004] = {
        description = "暂无",
        gain_way_id = {},
        icon = 1004,
        id = 1004,
        introduction = "暂无",
        more_detail = "",
        name = "绑定水晶",
        quality = 4,
    },

    [1005] = {
        description = "通过日常玩法和修行等方式获得",
        gain_way_id = {},
        icon = 1005,
        id = 1005,
        introduction = "用于提升玩家等级",
        more_detail = "",
        name = "人物经验",
        quality = 2,
    },

    [1006] = {
        description = "人物储备经验",
        gain_way_id = {},
        icon = 1006,
        id = 1006,
        introduction = "人物储备经验",
        more_detail = "",
        name = "储备经验",
        quality = 2,
    },

    [1007] = {
        description = "通过游历和吞食伙伴等方式获得",
        gain_way_id = {},
        icon = 1007,
        id = 1007,
        introduction = "用于提升伙伴等级",
        more_detail = "",
        name = "伙伴经验",
        quality = 2,
    },

    [1008] = {
        description = "爱心匹配奖励",
        gain_way_id = {},
        icon = 1008,
        id = 1008,
        introduction = "用于兑换商店道具",
        more_detail = "",
        name = "爱心积分",
        quality = 2,
    },

    [1009] = {
        description = "通过竞技场获得",
        gain_way_id = {47},
        icon = 1009,
        id = 1009,
        introduction = "用于兑换商店道具",
        more_detail = "",
        name = "荣誉",
        quality = 2,
    },

    [1010] = {
        description = "任务奖励",
        gain_way_id = {},
        icon = 1010,
        id = 1010,
        introduction = "赠送玩家一个伙伴",
        more_detail = "格式:1010(partner=301)",
        name = "伙伴",
        quality = 2,
    },

    [1011] = {
        description = "通过地牢、封印之地和怪物攻城奖励",
        gain_way_id = {},
        icon = 1011,
        id = 1011,
        introduction = "用于兑换商店道具",
        more_detail = "",
        name = "勋章",
        quality = 2,
    },

    [1012] = {
        description = "通过装备副本和合成获得",
        gain_way_id = {},
        icon = 1012,
        id = 1012,
        introduction = "用于装备在角色身上提高属性",
        more_detail = "",
        name = "装备",
        quality = 2,
    },

    [1013] = {
        description = "完成冒险中的任务获得",
        gain_way_id = {},
        icon = 1013,
        id = 1013,
        introduction = "用于兑换商店道具",
        more_detail = "",
        name = "活跃度",
        quality = 2,
    },

    [1014] = {
        description = "通过公会建设、击杀赏金头领、据点攻防战获得",
        gain_way_id = {},
        icon = 1014,
        id = 1014,
        introduction = "用于购买公会商店道具",
        more_detail = "",
        name = "公会贡献",
        quality = 2,
    },

    [1015] = {
        description = "通过公会建设、击杀赏金头领、据点攻防战获得",
        gain_way_id = {},
        icon = 1015,
        id = 1015,
        introduction = "用于购买祈坛道具以及重置赏金进度",
        more_detail = "",
        name = "公会资金",
        quality = 2,
    },

    [1016] = {
        description = "通过探索和符文副本获得",
        gain_way_id = {},
        icon = 1016,
        id = 1016,
        introduction = "可获得随机伙伴符文",
        more_detail = "",
        name = "伙伴符文",
        quality = 2,
    },

    [1017] = {
        description = "通过商店和比武获得",
        gain_way_id = {},
        icon = 1017,
        id = 1017,
        introduction = "用于兑换商店皮肤",
        more_detail = "",
        name = "皮肤券",
        quality = 4,
    },

    [1018] = {
        description = "通过月见幻境和茶会获得",
        gain_way_id = {},
        icon = 1018,
        id = 1018,
        introduction = "集齐碎片可以合成对应伙伴",
        more_detail = "",
        name = "伙伴碎片",
        quality = 2,
    },

    [1019] = {
        description = "通过公会建设和击杀赏金头领获得",
        gain_way_id = {},
        icon = 1019,
        id = 1019,
        introduction = "用于公会升级",
        more_detail = "",
        name = "公会经验",
        quality = 2,
    },

    [1020] = {
        description = "通过时间和道具恢复体力",
        gain_way_id = {},
        icon = 1020,
        id = 1020,
        introduction = "用于战役战斗消耗",
        more_detail = "",
        name = "体力",
        quality = 2,
    },

    [1022] = {
        description = "通过升级和任务获得",
        gain_way_id = {},
        icon = 11615,
        id = 1022,
        introduction = "角色技能升级",
        more_detail = "",
        name = "技能点",
        quality = 2,
    },

    [1023] = {
        description = "完成相关成就获得",
        gain_way_id = {},
        icon = 1023,
        id = 1023,
        introduction = "可领取成就奖励",
        more_detail = "",
        name = "成就点",
        quality = 2,
    },

    [1024] = {
        description = "通过奇遇商人翻牌玩法获得",
        gain_way_id = {},
        icon = 1024,
        id = 1024,
        introduction = "可在奇遇商人处够买觉醒材料和游历道具",
        more_detail = "",
        name = "游历积分",
        quality = 2,
    },

    [1025] = {
        description = "宅邸伙伴",
        gain_way_id = {},
        icon = 1010,
        id = 1025,
        introduction = "获得宅邸伙伴",
        more_detail = "格式:1025(house_partner=1003)",
        name = "宅邸伙伴",
        quality = 4,
    },

    [1026] = {
        description = "通过击杀赏金头领以及据点战获得",
        gain_way_id = {},
        icon = 1026,
        id = 1026,
        introduction = "用于公会排名",
        more_detail = "格式:1026(value=100)",
        name = "公会声望",
        quality = 2,
    },

    [1027] = {
        description = "主角皮肤",
        gain_way_id = {},
        icon = 1027,
        id = 1027,
        introduction = "主角皮肤",
        more_detail = "格式:1027(gain_way=1)",
        name = "角色皮肤",
        quality = 2,
    },

    [1028] = {
        description = "通过猎灵以及御灵副本获取",
        gain_way_id = {},
        icon = 1028,
        id = 1028,
        introduction = "穿戴在伙伴身上可提供核心效果和属性效果",
        more_detail = "(type=1,star=2,pos=3,value=1)",
        name = "御灵",
        quality = 2,
    },

}
