-- ./excel/item/partnerattr.xlsx
return {

    [1] = {
        description = "踏着同伴的血肉白骨换来的强大力量，是燃尽了未来的绝望，我已经看不到未来了。",
        icon = 210,
        id = 1,
        name = "血衣客",
        sex = 1,
        simple_desc = "伤害吸血",
        skill = 210,
        skill_desc = "造成伤害的23%将转化为自身气血",
    },

    [2] = {
        description = "",
        icon = 211,
        id = 2,
        name = "墨菲",
        sex = 2,
        simple_desc = "低血加伤",
        skill = 211,
        skill_desc = "对气血低于30%的单位额外造成38%伤害",
    },

    [3] = {
        description = "啧啧，那个正在看文字的人，来陪我玩玩一局吧。",
        icon = 212,
        id = 3,
        name = "博戏鬼",
        sex = 1,
        simple_desc = "满血加伤",
        skill = 212,
        skill_desc = "对气血高于70%的单位额外造成30%伤害",
    },

    [4] = {
        description = "烈焰只能毁掉身体却不能烧毁灵魂。它将舞于烈焰之尖，化作空气，化作颗粒，无所不在！",
        icon = 213,
        id = 4,
        name = "归无处",
        sex = 1,
        simple_desc = "击杀连击",
        skill = 213,
        skill_desc = "击杀目标时，随机对另外一个目标使用普攻",
    },

    [5] = {
        description = "野心勃勃的黑帝，终其一生，依然不得所愿。",
        icon = 214,
        id = 5,
        name = "黑帝",
        sex = 1,
        simple_desc = "被打反击",
        skill = 214,
        skill_desc = "受伤害时有18%机率使用普攻进行反击",
    },

    [6] = {
        description = "我一直为能遇到你和孩子而感到幸福，请不要为我悲伤。",
        icon = 215,
        id = 6,
        name = "洛迦",
        sex = 2,
        simple_desc = "对控增伤",
        skill = 215,
        skill_desc = "对处于封印、眩晕、睡眠状态的单位额外造成40%伤害",
    },

    [8] = {
        description = "“不要抵抗我，接受它，跟随它。”",
        icon = 217,
        id = 8,
        name = "诡象之匣",
        sex = 1,
        simple_desc = "受控增伤",
        skill = 217,
        skill_desc = "自己拥有异常状态时，造成35%额外伤害",
    },

    [9] = {
        description = "",
        icon = 218,
        id = 9,
        name = "乌琪琪",
        sex = 1,
        simple_desc = "舍身加伤",
        skill = 218,
        skill_desc = "技能基础伤害提升25%，伤害结束后自身损失总伤害15%的气血",
    },

    [10] = {
        description = "我的王啊，用他腰间的佩剑，将这生最深的恨意镌刻在了长眠于此的人的石刻之上。",
        icon = 219,
        id = 10,
        name = "红雨将军",
        sex = 1,
        simple_desc = "暴击增伤",
        skill = 219,
        skill_desc = "每次暴击时，45%概率附加自己攻击60%的真实伤害",
    },

    [22] = {
        description = "无知是这个世间最黑暗的恶意，任其肆意滋长的话……",
        icon = 231,
        id = 22,
        name = "颜无月",
        sex = 2,
        simple_desc = "伤害减免",
        skill = 231,
        skill_desc = "减免受到伤害的20%",
    },

    [23] = {
        description = "",
        icon = 232,
        id = 23,
        name = "萧衍",
        sex = 2,
        simple_desc = "受伤回怒",
        skill = 232,
        skill_desc = "受到伤害时18%机率额外提升1格怒气",
    },

    [24] = {
        description = "“呜呜~我明明是想要保护他的，明明只是想带他看看漂亮的大海，他说他从没见过。”",
        icon = 233,
        id = 24,
        name = "漓渚",
        sex = 2,
        simple_desc = "初始开盾",
        skill = 233,
        skill_desc = "战斗开始时给全队附加一个装备者气血上限5%的护盾，持续2回合",
    },

    [25] = {
        description = "苦难之所以成诗篇，是因为苦难的背后能孕育出这世间最美好的事物。",
        icon = 234,
        id = 25,
        name = "流莺",
        sex = 1,
        simple_desc = "概率免死",
        skill = 234,
        skill_desc = "受到致死伤害时有30%机率抵消该次伤害，每回合最多触发2次",
    },

    [26] = {
        description = "喂，这个世界太大了，我怕你找不到我。所以，我要成为世界第一的歌姬！",
        icon = 235,
        id = 26,
        name = "梓童",
        sex = 1,
        simple_desc = "回合自愈",
        skill = 235,
        skill_desc = "每次行动结束后，45%概率恢复上次行动结束至此受到的总伤害的50%气血",
    },

    [31] = {
        description = "",
        icon = 240,
        id = 31,
        name = "偃月无夜",
        sex = 1,
        simple_desc = "攻击眩晕",
        skill = 240,
        skill_desc = "造成伤害有8%机率眩晕目标，持续1次行动",
    },

    [32] = {
        description = "",
        icon = 241,
        id = 32,
        name = "星遥",
        sex = 2,
        simple_desc = "攻击睡眠",
        skill = 241,
        skill_desc = "造成伤害有10%机率睡眠目标，持续1次行动",
    },

    [33] = {
        description = "你只是一个靠着这种小聪明去获得不该获得力量的卑劣人类。",
        icon = 242,
        id = 33,
        name = "铃音",
        sex = 2,
        simple_desc = "攻击禁疗",
        skill = 242,
        skill_desc = "造成伤害有20%机率禁疗目标，无法获得回血效果，持续2次行动",
    },

    [34] = {
        description = "大炮的广泛使用，导致死伤无数。陶磊磊良心受到强烈谴责，自愿被人杀死后成为了残识。",
        icon = 243,
        id = 34,
        name = "陶磊磊",
        sex = 2,
        simple_desc = "被打眩晕",
        skill = 243,
        skill_desc = "受到非状态类的直接伤害时，有8%机率使攻击者眩晕，持续1次行动",
    },

    [35] = {
        description = "时君成游魂野鬼了？如果是，那真是太惨了！为什么我还要自己走路？说好的轻飘飘呢？",
        icon = 244,
        id = 35,
        name = "巳日时君",
        sex = 2,
        simple_desc = "对控减速",
        skill = 244,
        skill_desc = "对存在异常状态的单位造成伤害有50%机率降低其50%的速度，持续1次行动",
    },

    [36] = {
        description = "热衷于蛊术的巫蛊师，渴望长生不死，因使用禁术招至死亡。",
        icon = 245,
        id = 36,
        name = "花月巫",
        sex = 1,
        simple_desc = "被打抽怒",
        skill = 245,
        skill_desc = "受到怒气技能伤害时，30%机率使对方损失1格怒气",
    },

    [41] = {
        description = "",
        icon = 250,
        id = 41,
        name = "星罗",
        sex = 2,
        simple_desc = "初始得怒",
        skill = 250,
        skill_desc = "战斗开始额外获得2格怒气",
    },

    [42] = {
        description = "我喜欢热闹，咚咚锵，咚咚锵……直到温热鲜血沾染鼓身，才知道这热闹是多么的讽刺。",
        icon = 251,
        id = 42,
        name = "锵明",
        sex = 2,
        simple_desc = "行动回怒",
        skill = 251,
        skill_desc = "行动开始前50%机率提升1格怒气",
    },

    [43] = {
        description = "人，能信的果然只有自己，友情真是廉价而可笑。",
        icon = 252,
        id = 43,
        name = "流臾之须",
        sex = 1,
        simple_desc = "全队回血",
        skill = 252,
        skill_desc = "我方单位每次行动有24%机率回复装备者气血上限的5%的气血",
    },

    [45] = {
        description = "“吾生于人心而死于人性，这茫茫雪地深处掩埋着的是吾作为守护者时的善和恶。”",
        icon = 254,
        id = 45,
        name = "一阕秋",
        sex = 2,
        simple_desc = "提升治疗",
        skill = 254,
        skill_desc = "治疗效果增加25%",
    },

    [46] = {
        description = "商量个事，以后表情内容不要这么丰富，我不想出门被人发现自家儿砸中二病末期。",
        icon = 255,
        id = 46,
        name = "斑曜",
        sex = 1,
        simple_desc = "回合加速",
        skill = 255,
        skill_desc = "行动结束后40%机率临时提升20%速度，持续1次行动",
    },

}
