-- ./excel/item/partner.xlsx
return {

    [310001] = {
        attr = "{attack=7}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 12, ["discount"] = 0}},
        buy_price = 0,
        buyable = 1,
        description = "由火和猩红文字组合而成的符石纹样。",
        equip_pos = 1,
        gain_way_id = {462, 416, 48},
        icon = 310001,
        id = 310001,
        introduction = "可用于攻击符文吞食，攻击+4",
        level = 1,
        max_overlay = 9999,
        name = "破坏符石·Ⅰ",
        quality = 2,
        sale_price = 2400,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [310002] = {
        attr = "{attack=10}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 36, ["discount"] = 0}},
        buy_price = 0,
        buyable = 1,
        description = "由火和猩红文字组合而成的符石纹样。",
        equip_pos = 1,
        gain_way_id = {463, 6, 48, 30001},
        icon = 310002,
        id = 310002,
        introduction = "可用于攻击符文吞食，攻击+9",
        level = 2,
        max_overlay = 9999,
        name = "破坏符石·Ⅱ",
        quality = 2,
        sale_price = 4800,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [310003] = {
        attr = "{attack=13}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 108, ["discount"] = 0}},
        buy_price = 0,
        buyable = 1,
        description = "由火和猩红文字组合而成的符石纹样。",
        equip_pos = 1,
        gain_way_id = {464, 417, 48, 30001},
        icon = 310003,
        id = 310003,
        introduction = "可用于攻击符文吞食，攻击+13",
        level = 3,
        max_overlay = 9999,
        name = "破坏符石·Ⅲ",
        quality = 2,
        sale_price = 9600,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [310004] = {
        attr = "{attack=16}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 324, ["discount"] = 0}},
        buy_price = 0,
        buyable = 1,
        description = "由火和猩红文字组合而成的符石纹样。",
        equip_pos = 1,
        gain_way_id = {6, 48, 30001},
        icon = 310004,
        id = 310004,
        introduction = "可用于攻击符文吞食，攻击+18",
        level = 4,
        max_overlay = 9999,
        name = "破坏符石·Ⅳ",
        quality = 2,
        sale_price = 19200,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [310005] = {
        attr = "{attack=23}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 972, ["discount"] = 0}},
        buy_price = 0,
        buyable = 1,
        description = "由火和猩红文字组合而成的符石纹样。",
        equip_pos = 1,
        gain_way_id = {418, 48, 30001},
        icon = 310005,
        id = 310005,
        introduction = "可用于攻击符文吞食，攻击+22",
        level = 5,
        max_overlay = 9999,
        name = "破坏符石·Ⅴ",
        quality = 3,
        sale_price = 38400,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [310006] = {
        attr = "{attack=29}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {},
        buy_price = 0,
        buyable = 0,
        description = "由火和猩红文字组合而成的符石纹样。",
        equip_pos = 1,
        gain_way_id = {6, 48, 30001},
        icon = 310006,
        id = 310006,
        introduction = "可用于攻击符文吞食，攻击+29",
        level = 6,
        max_overlay = 9999,
        name = "破坏符石·Ⅵ",
        quality = 3,
        sale_price = 76800,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [310007] = {
        attr = "{attack=36}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {},
        buy_price = 0,
        buyable = 0,
        description = "由火和猩红文字组合而成的符石纹样。",
        equip_pos = 1,
        gain_way_id = {6, 48, 30001},
        icon = 310007,
        id = 310007,
        introduction = "可用于攻击符文吞食，攻击+38",
        level = 7,
        max_overlay = 9999,
        name = "破坏符石·Ⅶ",
        quality = 4,
        sale_price = 153600,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [320001] = {
        attr = "{maxhp=75}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 12, ["discount"] = 0}},
        buy_price = 0,
        buyable = 1,
        description = "“神爱世人并原谅宽恕所有罪人”圣子从中领悟出生命的的文字。",
        equip_pos = 2,
        gain_way_id = {468, 422, 48},
        icon = 330001,
        id = 320001,
        introduction = "可用于气血符文吞食，气血+51",
        level = 1,
        max_overlay = 9999,
        name = "圣灵符石·Ⅰ",
        quality = 2,
        sale_price = 2400,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [320002] = {
        attr = "{maxhp=113}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 36, ["discount"] = 0}},
        buy_price = 0,
        buyable = 1,
        description = "“神爱世人并原谅宽恕所有罪人”圣子从中领悟出生命的的文字。",
        equip_pos = 2,
        gain_way_id = {469, 6, 48, 30001},
        icon = 330002,
        id = 320002,
        introduction = "可用于气血符文吞食，气血+102",
        level = 2,
        max_overlay = 9999,
        name = "圣灵符石·Ⅱ",
        quality = 2,
        sale_price = 4800,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [320003] = {
        attr = "{maxhp=150}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 108, ["discount"] = 0}},
        buy_price = 0,
        buyable = 1,
        description = "“神爱世人并原谅宽恕所有罪人”圣子从中领悟出生命的的文字。",
        equip_pos = 2,
        gain_way_id = {470, 423, 48, 30001},
        icon = 330003,
        id = 320003,
        introduction = "可用于气血符文吞食，气血+153",
        level = 3,
        max_overlay = 9999,
        name = "圣灵符石·Ⅲ",
        quality = 2,
        sale_price = 9600,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [320004] = {
        attr = "{maxhp=188}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 324, ["discount"] = 0}},
        buy_price = 0,
        buyable = 1,
        description = "“神爱世人并原谅宽恕所有罪人”圣子从中领悟出生命的的文字。",
        equip_pos = 2,
        gain_way_id = {6, 48, 30001},
        icon = 330004,
        id = 320004,
        introduction = "可用于气血符文吞食，气血+204",
        level = 4,
        max_overlay = 9999,
        name = "圣灵符石·Ⅳ",
        quality = 2,
        sale_price = 19200,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [320005] = {
        attr = "{maxhp=263}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 972, ["discount"] = 0}},
        buy_price = 0,
        buyable = 1,
        description = "“神爱世人并原谅宽恕所有罪人”圣子从中领悟出生命的的文字。",
        equip_pos = 2,
        gain_way_id = {424, 48, 30001},
        icon = 330005,
        id = 320005,
        introduction = "可用于气血符文吞食，气血+255",
        level = 5,
        max_overlay = 9999,
        name = "圣灵符石·Ⅴ",
        quality = 3,
        sale_price = 38400,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [320006] = {
        attr = "{maxhp=338}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {},
        buy_price = 0,
        buyable = 0,
        description = "“神爱世人并原谅宽恕所有罪人”圣子从中领悟出生命的的文字。",
        equip_pos = 2,
        gain_way_id = {6, 48, 30001},
        icon = 330006,
        id = 320006,
        introduction = "可用于气血符文吞食，气血+332",
        level = 6,
        max_overlay = 9999,
        name = "圣灵符石·Ⅵ",
        quality = 3,
        sale_price = 76800,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [320007] = {
        attr = "{maxhp=414}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {},
        buy_price = 0,
        buyable = 0,
        description = "“神爱世人并原谅宽恕所有罪人”圣子从中领悟出生命的的文字。",
        equip_pos = 2,
        gain_way_id = {6, 48, 30001},
        icon = 330007,
        id = 320007,
        introduction = "可用于气血符文吞食，气血+434",
        level = 7,
        max_overlay = 9999,
        name = "圣灵符石·Ⅶ",
        quality = 4,
        sale_price = 153600,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [330001] = {
        attr = "{critical_ratio=20,res_abnormal_ratio=20}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 12, ["discount"] = 0}},
        buy_price = 0,
        buyable = 1,
        description = "太阳与月亮组合的赠礼。",
        equip_pos = 3,
        gain_way_id = {465, 419, 48},
        icon = 320001,
        id = 330001,
        introduction = "可用于防御符文吞食，异常抵抗+0.2%   暴击+0.2%",
        level = 1,
        max_overlay = 9999,
        name = "光辉符石·Ⅰ",
        quality = 2,
        sale_price = 2400,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [330002] = {
        attr = "{critical_ratio=30,res_abnormal_ratio=30}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 36, ["discount"] = 0}},
        buy_price = 0,
        buyable = 1,
        description = "太阳与月亮组合的赠礼。",
        equip_pos = 3,
        gain_way_id = {466, 6, 48, 30001},
        icon = 320002,
        id = 330002,
        introduction = "可用于防御符文吞食，异常抵抗+0.3%   暴击+0.3%",
        level = 2,
        max_overlay = 9999,
        name = "光辉符石·Ⅱ",
        quality = 2,
        sale_price = 4800,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [330003] = {
        attr = "{critical_ratio=40,res_abnormal_ratio=40}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 108, ["discount"] = 0}},
        buy_price = 0,
        buyable = 1,
        description = "太阳与月亮组合的赠礼。",
        equip_pos = 3,
        gain_way_id = {467, 420, 48, 30001},
        icon = 320003,
        id = 330003,
        introduction = "可用于防御符文吞食，异常抵抗+0.4%   暴击+0.4%",
        level = 3,
        max_overlay = 9999,
        name = "光辉符石·Ⅲ",
        quality = 2,
        sale_price = 9600,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [330004] = {
        attr = "{critical_ratio=60,res_abnormal_ratio=60}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 324, ["discount"] = 0}},
        buy_price = 0,
        buyable = 1,
        description = "太阳与月亮组合的赠礼。",
        equip_pos = 3,
        gain_way_id = {6, 48, 30001},
        icon = 320004,
        id = 330004,
        introduction = "可用于防御符文吞食，异常抵抗+0.6%   暴击+0.6%",
        level = 4,
        max_overlay = 9999,
        name = "光辉符石·Ⅳ",
        quality = 2,
        sale_price = 19200,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [330005] = {
        attr = "{critical_ratio=70,res_abnormal_ratio=70}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 972, ["discount"] = 0}},
        buy_price = 0,
        buyable = 1,
        description = "太阳与月亮组合的赠礼。",
        equip_pos = 3,
        gain_way_id = {421, 48, 30001},
        icon = 320005,
        id = 330005,
        introduction = "可用于防御符文吞食，异常抵抗+0.7%   暴击+0.7%",
        level = 5,
        max_overlay = 9999,
        name = "光辉符石·Ⅴ",
        quality = 3,
        sale_price = 38400,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [330006] = {
        attr = "{critical_ratio=90,res_abnormal_ratio=90}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {},
        buy_price = 0,
        buyable = 0,
        description = "太阳与月亮组合的赠礼。",
        equip_pos = 3,
        gain_way_id = {6, 48, 30001},
        icon = 320006,
        id = 330006,
        introduction = "可用于防御符文吞食，异常抵抗+0.9%   暴击+0.9%",
        level = 6,
        max_overlay = 9999,
        name = "光辉符石·Ⅵ",
        quality = 3,
        sale_price = 76800,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [330007] = {
        attr = "{critical_ratio=120,res_abnormal_ratio=120}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {},
        buy_price = 0,
        buyable = 0,
        description = "太阳与月亮组合的赠礼。",
        equip_pos = 3,
        gain_way_id = {6, 48, 30001},
        icon = 320007,
        id = 330007,
        introduction = "可用于防御符文吞食，异常抵抗+1.2%   暴击+1.2%",
        level = 7,
        max_overlay = 9999,
        name = "光辉符石·Ⅶ",
        quality = 4,
        sale_price = 153600,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [340001] = {
        attr = "{critical_damage=20,abnormal_attr_ratio=20}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 12, ["discount"] = 0}},
        buy_price = 0,
        buyable = 1,
        description = "咏叹初代教皇在生命终结之时，洞察到的文字组合。由于其力量强大，一度被称为“禁忌的文字”。",
        equip_pos = 4,
        gain_way_id = {471, 425, 48},
        icon = 340001,
        id = 340001,
        introduction = "可用于双灵符文吞食，异常命中+0.2%   暴击伤害+0.2%",
        level = 1,
        max_overlay = 9999,
        name = "禁忌符石·Ⅰ",
        quality = 2,
        sale_price = 2400,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [340002] = {
        attr = "{critical_damage=40,abnormal_attr_ratio=30}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 36, ["discount"] = 0}},
        buy_price = 0,
        buyable = 1,
        description = "咏叹初代教皇在生命终结之时，洞察到的文字组合。由于其力量强大，一度被称为“禁忌的文字”。",
        equip_pos = 4,
        gain_way_id = {472, 6, 48, 30001},
        icon = 340002,
        id = 340002,
        introduction = "可用于双灵符文吞食，异常命中+0.3%   暴击伤害+0.3%",
        level = 2,
        max_overlay = 9999,
        name = "禁忌符石·Ⅱ",
        quality = 2,
        sale_price = 4800,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [340003] = {
        attr = "{critical_damage=60,abnormal_attr_ratio=40}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 108, ["discount"] = 0}},
        buy_price = 0,
        buyable = 1,
        description = "咏叹初代教皇在生命终结之时，洞察到的文字组合。由于其力量强大，一度被称为“禁忌的文字”。",
        equip_pos = 4,
        gain_way_id = {473, 426, 48, 30001},
        icon = 340003,
        id = 340003,
        introduction = "可用于双灵符文吞食，异常命中+0.4%   暴击伤害+0.4%",
        level = 3,
        max_overlay = 9999,
        name = "禁忌符石·Ⅲ",
        quality = 2,
        sale_price = 9600,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [340004] = {
        attr = "{critical_damage=70,abnormal_attr_ratio=60}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 324, ["discount"] = 0}},
        buy_price = 0,
        buyable = 1,
        description = "咏叹初代教皇在生命终结之时，洞察到的文字组合。由于其力量强大，一度被称为“禁忌的文字”。",
        equip_pos = 4,
        gain_way_id = {6, 48, 30001},
        icon = 340004,
        id = 340004,
        introduction = "可用于双灵符文吞食，异常命中+0.6%   暴击伤害+0.6%",
        level = 4,
        max_overlay = 9999,
        name = "禁忌符石·Ⅳ",
        quality = 2,
        sale_price = 19200,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [340005] = {
        attr = "{critical_damage=90,abnormal_attr_ratio=70}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {{["limit"] = 1000, ["coin"] = 1, ["cost"] = 972, ["discount"] = 0}},
        buy_price = 0,
        buyable = 1,
        description = "咏叹初代教皇在生命终结之时，洞察到的文字组合。由于其力量强大，一度被称为“禁忌的文字”。",
        equip_pos = 4,
        gain_way_id = {427, 48, 30001},
        icon = 340005,
        id = 340005,
        introduction = "可用于双灵符文吞食，异常命中+0.7%   暴击伤害+0.7%",
        level = 5,
        max_overlay = 9999,
        name = "禁忌符石·Ⅴ",
        quality = 3,
        sale_price = 38400,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [340006] = {
        attr = "{critical_damage=120,abnormal_attr_ratio=90}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {},
        buy_price = 0,
        buyable = 0,
        description = "咏叹初代教皇在生命终结之时，洞察到的文字组合。由于其力量强大，一度被称为“禁忌的文字”。",
        equip_pos = 4,
        gain_way_id = {6, 48, 30001},
        icon = 340006,
        id = 340006,
        introduction = "可用于双灵符文吞食，异常命中+0.9%   暴击伤害+0.9%",
        level = 6,
        max_overlay = 9999,
        name = "禁忌符石·Ⅵ",
        quality = 3,
        sale_price = 76800,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

    [340007] = {
        attr = "{critical_damage=150,abnormal_attr_ratio=120}",
        bag_show_type = 4,
        bat_use = 0,
        buy_cost = {},
        buy_price = 0,
        buyable = 0,
        description = "咏叹初代教皇在生命终结之时，洞察到的文字组合。由于其力量强大，一度被称为“禁忌的文字”。",
        equip_pos = 4,
        gain_way_id = {6, 48, 30001},
        icon = 340007,
        id = 340007,
        introduction = "可用于双灵符文吞食，异常命中+1.2%   暴击伤害+1.2%",
        level = 7,
        max_overlay = 9999,
        name = "禁忌符石·Ⅶ",
        quality = 4,
        sale_price = 153600,
        sort = 1,
        type = 11,
        use_type = "partner_equip_upstone",
    },

}
