-- ./excel/item/ui_item.xlsx
return {

    [16001] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 16001,
        id = 16001,
        introduction = "随机获取1个3星传说伙伴",
        name = "3星传说伙伴",
        quality = 4,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16002] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 16002,
        id = 16002,
        introduction = "随机获取1个2星精英伙伴",
        name = "2星精英伙伴",
        quality = 4,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16005] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 16005,
        id = 16005,
        introduction = "随机获取传说/精英伙伴",
        name = "伙伴",
        quality = 4,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16006] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 16006,
        id = 16006,
        introduction = "获取传说伙伴碎片，可用于合成伙伴",
        name = "传说伙伴碎片",
        quality = 4,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16007] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 16007,
        id = 16007,
        introduction = "获取精英伙伴碎片，可用于合成伙伴",
        name = "精英伙伴碎片",
        quality = 3,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16010] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 16010,
        id = 16010,
        introduction = "获取传说/精英伙伴碎片，可用于合成伙伴",
        name = "伙伴碎片",
        quality = 3,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16020] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 16020,
        id = 16020,
        introduction = "获取装备强化材料，用于装备突破",
        name = "装备材料",
        quality = 2,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16021] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {4, 7, 45, 41},
        icon = 16021,
        id = 16021,
        introduction = "获取任意一种宝石，可镶嵌在装备上提高属性",
        name = "宝石",
        quality = 2,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16022] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 16022,
        id = 16022,
        introduction = "伙伴觉醒需要消耗的材料",
        name = "伙伴觉醒材料",
        quality = 2,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16023] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 16023,
        id = 16023,
        introduction = [=[获取除武器原石外的任意一种装备原石
用于合成橙色套装的装备材料]=],
        name = "装备原石",
        quality = 2,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16024] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 16024,
        id = 16024,
        introduction = [=[获取任意一种附魔材料
用于合成橙色套装的装备材料]=],
        name = "附魔材料",
        quality = 2,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16031] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {183, 6, 22, 48, 186},
        icon = 16031,
        id = 16031,
        introduction = "获得符石材料，可用于强化符文的符石属性",
        name = "符石",
        quality = 3,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16032] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {2173},
        icon = 16032,
        id = 16032,
        introduction = "获得1~5星云母材料，可用于符文升星",
        name = "云母",
        quality = 3,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16041] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {46184},
        icon = 1016,
        id = 16041,
        introduction = "获得伙伴御灵，可提供核心效果和伙伴属性",
        name = "御灵",
        quality = 3,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16101] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 16101,
        id = 16101,
        introduction = "A礼包1",
        name = "A礼包图标1",
        quality = 2,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16102] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 16102,
        id = 16102,
        introduction = "A礼包2",
        name = "A礼包图标2",
        quality = 2,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16103] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 16103,
        id = 16103,
        introduction = "A礼包3",
        name = "A礼包图标3",
        quality = 2,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16104] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 16104,
        id = 16104,
        introduction = "A礼包4",
        name = "A礼包图标4",
        quality = 2,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16105] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 16105,
        id = 16105,
        introduction = "A礼包5",
        name = "A礼包图标5",
        quality = 2,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16111] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 16111,
        id = 16111,
        introduction = "B礼包1",
        name = "B礼包图标1",
        quality = 2,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16112] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 16112,
        id = 16112,
        introduction = "B礼包2",
        name = "B礼包图标2",
        quality = 2,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16113] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 16113,
        id = 16113,
        introduction = "B礼包3",
        name = "B礼包图标3",
        quality = 2,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16121] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 16121,
        id = 16121,
        introduction = "C礼包1",
        name = "C礼包图标1",
        quality = 2,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16122] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 16122,
        id = 16122,
        introduction = "C礼包2",
        name = "C礼包图标2",
        quality = 2,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16123] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 16123,
        id = 16123,
        introduction = "C礼包3",
        name = "C礼包图标3",
        quality = 2,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16124] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 16124,
        id = 16124,
        introduction = "获取对应通关层数的蓝色、紫色品质装备",
        name = "人物装备",
        quality = 3,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16131] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 16131,
        id = 16131,
        introduction = "获取相应的称号",
        name = "称号",
        quality = 3,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16141] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 16131,
        id = 16141,
        introduction = "显示现在奖励",
        name = "在线奖励",
        quality = 3,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16150] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 3500300,
        id = 16150,
        introduction = "主角的武器装备，增加攻击/暴击率",
        name = "武器",
        quality = 3,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16151] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 4000300,
        id = 16151,
        introduction = "主角的项链装备，增加气血/暴击率",
        name = "项链",
        quality = 3,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16152] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 4100300,
        id = 16152,
        introduction = "主角的衣服装备，增加防御/抗暴率",
        name = "衣服",
        quality = 3,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16153] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 4200300,
        id = 16153,
        introduction = "主角的戒指装备，增加攻击/暴击伤害",
        name = "戒指",
        quality = 3,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16154] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 4300300,
        id = 16154,
        introduction = "主角的腰带装备，增加气血/抗暴率",
        name = "腰带",
        quality = 3,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16155] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 4400300,
        id = 16155,
        introduction = "主角的鞋子装备，增加防御/速度",
        name = "鞋子",
        quality = 3,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16160] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 18005,
        id = 16160,
        introduction = "可镶嵌于主角装备上，增加攻击力",
        name = "绯红宝石",
        quality = 3,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16161] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 18105,
        id = 16161,
        introduction = "可镶嵌于主角装备上，增加抗暴率",
        name = "八云宝石",
        quality = 3,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16162] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 18205,
        id = 16162,
        introduction = "可镶嵌于主角装备上，增加防御力",
        name = "双生宝石",
        quality = 3,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16163] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 18305,
        id = 16163,
        introduction = "可镶嵌于主角装备上，增加暴击率",
        name = "黄金宝石",
        quality = 3,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16164] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 18405,
        id = 16164,
        introduction = "可镶嵌于主角装备上，增加气血",
        name = "翠星宝石",
        quality = 3,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

    [16165] = {
        compose_amount = 0,
        compose_item = {},
        de_compose = {},
        description = "",
        gain_way_id = {},
        icon = 18505,
        id = 16165,
        introduction = "可镶嵌于主角装备上，增加速度",
        name = "疾风宝石",
        quality = 3,
        sort = 1,
        use_reward = {},
        use_type = "",
    },

}
