-- ./excel/achieve/achievetask.xlsx
return {

    [31001] = {
        achievetype = 1,
        condition = "领取在线奖励=1",
        degreetype = 1,
        describe = "领取1次在线奖励",
        id = 31001,
        name = "在线奖励",
        open_id = 1042,
        pre_condition = {"主角等级=6"},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=5000)"}},
        tasktype = 1,
        type = 3,
    },

    [31002] = {
        achievetype = 1,
        condition = "好友数量=1",
        degreetype = 1,
        describe = "拥有1个好友",
        id = 31002,
        name = "结伴同游",
        open_id = 1041,
        pre_condition = {"完成成就任务=31001", "主角等级=10"},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=8000)"}},
        tasktype = 1,
        type = 3,
    },

    [31003] = {
        achievetype = 1,
        condition = "主角技能2级次数=1",
        degreetype = 2,
        describe = "主角任意技能升至2级",
        id = 31003,
        name = "提升技能",
        open_id = 102,
        pre_condition = {"完成成就任务=31002"},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=10000)"}},
        tasktype = 1,
        type = 3,
    },

    [31010] = {
        achievetype = 1,
        condition = "公会等级大于等于1级的数量=1",
        degreetype = 1,
        describe = "加入1个公会",
        id = 31010,
        name = "加入公会",
        open_id = 600,
        pre_condition = {"完成成就任务=31003", "主角等级=14"},
        rewarditem = {{["num"] = 1, ["sid"] = "1014(value=200)"}},
        tasktype = 1,
        type = 3,
    },

    [31011] = {
        achievetype = 1,
        condition = "公会建设次数=1",
        degreetype = 1,
        describe = "完成1次公会建设",
        id = 31011,
        name = "公会建设",
        open_id = 601,
        pre_condition = {"完成成就任务=31010"},
        rewarditem = {{["num"] = 1, ["sid"] = "1014(value=300)"}},
        tasktype = 1,
        type = 3,
    },

    [31012] = {
        achievetype = 1,
        condition = "伙伴碎片许愿次数=1",
        degreetype = 1,
        describe = "进行1次伙伴碎片许愿",
        id = 31012,
        name = "许愿",
        open_id = 1044,
        pre_condition = {"完成成就任务=31011"},
        rewarditem = {{["num"] = 1, ["sid"] = "1014(value=100)"}},
        tasktype = 1,
        type = 3,
    },

    [31013] = {
        achievetype = 1,
        condition = "挑战公会赏金=1",
        degreetype = 1,
        describe = "挑战1次公会赏金",
        id = 31013,
        name = "赏金",
        open_id = 603,
        pre_condition = {"完成成就任务=31012"},
        rewarditem = {{["num"] = 1, ["sid"] = "1014(value=500)"}},
        tasktype = 1,
        type = 3,
    },

    [31018] = {
        achievetype = 1,
        condition = "师门任务=3",
        degreetype = 2,
        describe = "完成3次杂务巡查",
        id = 31018,
        name = "杂务巡察",
        open_id = 1039,
        pre_condition = {"完成成就任务=31013", "主角等级=15"},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=20000)"}},
        tasktype = 1,
        type = 3,
    },

    [31015] = {
        achievetype = 1,
        condition = "主角技能3级次数=2",
        degreetype = 2,
        describe = "主角任意2个技能升至3级",
        id = 31015,
        name = "强化技能",
        open_id = 102,
        pre_condition = {},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=15000)"}},
        tasktype = 1,
        type = 3,
    },

    [31026] = {
        achievetype = 1,
        condition = "拜访好友宅邸=1",
        degreetype = 1,
        describe = "拜访好友宅邸1次",
        id = 31026,
        name = "宅邸拜访",
        open_id = 1052,
        pre_condition = {"完成成就任务=31018", "主角等级=20"},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=15000)"}},
        tasktype = 1,
        type = 3,
    },

    [31022] = {
        achievetype = 1,
        condition = "每日修行次数=10",
        degreetype = 2,
        describe = "参与10次每日修行",
        id = 31022,
        name = "每日修行",
        open_id = 1053,
        pre_condition = {"完成成就任务=31026", "主角等级=25"},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=20000)"}},
        tasktype = 1,
        type = 3,
    },

    [31030] = {
        achievetype = 1,
        condition = "成功开启灵魂宝箱次数=1",
        degreetype = 1,
        describe = "开启灵魂宝箱1次",
        id = 31030,
        name = "开启灵魂宝箱",
        open_id = 1057,
        pre_condition = {"完成成就任务=31022", "主角等级=28"},
        rewarditem = {{["num"] = 1, ["sid"] = "1003(value=20)"}},
        tasktype = 1,
        type = 3,
    },

    [31027] = {
        achievetype = 1,
        condition = "通关埋骨之地－前庭=1",
        degreetype = 1,
        describe = "通关1次装备副本－前庭",
        id = 31027,
        name = "装备副本-前庭",
        open_id = 1049,
        pre_condition = {"完成成就任务=31030", "主角等级=30"},
        rewarditem = {{["num"] = 4, ["sid"] = "11001"}},
        tasktype = 1,
        type = 3,
    },

    [31004] = {
        achievetype = 1,
        condition = "通关埋骨之地－暗道=1",
        degreetype = 1,
        describe = "通关1次装备副本－暗道",
        id = 31004,
        name = "装备副本-暗道",
        open_id = 1050,
        pre_condition = {"完成成就任务=31027"},
        rewarditem = {{["num"] = 4, ["sid"] = "11001"}},
        tasktype = 1,
        type = 3,
    },

    [31005] = {
        achievetype = 1,
        condition = "通关埋骨之地－秘牢=1",
        degreetype = 1,
        describe = "通关1次装备副本－秘牢",
        id = 31005,
        name = "装备副本-秘牢",
        open_id = 1051,
        pre_condition = {"完成成就任务=31004"},
        rewarditem = {{["num"] = 4, ["sid"] = "11001"}},
        tasktype = 1,
        type = 3,
    },

    [31006] = {
        achievetype = 1,
        condition = "穿齐30级装备=1",
        degreetype = 1,
        describe = "主角穿齐6件30级装备",
        id = 31006,
        name = "穿戴装备",
        open_id = 101,
        pre_condition = {"完成成就任务=31005"},
        rewarditem = {{["num"] = 8, ["sid"] = "11001"}},
        tasktype = 1,
        type = 3,
    },

    [31008] = {
        achievetype = 1,
        condition = "装备突破3级=6",
        degreetype = 2,
        describe = "全身6件装备突破+3",
        id = 31008,
        name = "突破",
        open_id = 301,
        pre_condition = {"完成成就任务=31006"},
        rewarditem = {{["num"] = 12, ["sid"] = "11001"}},
        tasktype = 1,
        type = 3,
    },

    [31017] = {
        achievetype = 1,
        condition = "宝石3级次数=1",
        degreetype = 2,
        describe = "任意位置宝石达到3级",
        id = 31017,
        name = "宝石升级",
        open_id = 303,
        pre_condition = {"完成成就任务=31008"},
        rewarditem = {{["num"] = 1, ["sid"] = "18001"}},
        tasktype = 1,
        type = 3,
    },

    [31028] = {
        achievetype = 1,
        condition = "武馆挑战=1",
        degreetype = 1,
        describe = "挑战1次武馆",
        id = 31028,
        name = "武馆挑战",
        open_id = 1056,
        pre_condition = {"完成成就任务=31017", "主角等级=35"},
        rewarditem = {{["num"] = 1, ["sid"] = "1009(value=150)"}},
        tasktype = 1,
        type = 3,
    },

    [31014] = {
        achievetype = 1,
        condition = "主角技能3级次数=1",
        degreetype = 2,
        describe = "主角任意技能升至3级",
        id = 31014,
        name = "提升技能",
        open_id = 102,
        pre_condition = {"完成成就任务=31028", "主角等级=40"},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=12000)"}},
        tasktype = 1,
        type = 3,
    },

    [31029] = {
        achievetype = 1,
        condition = "猎灵次数=10",
        degreetype = 2,
        describe = "进行10次猎灵",
        id = 31029,
        name = "猎灵",
        open_id = 1055,
        pre_condition = {"完成成就任务=31014", "主角等级=41"},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=20000)"}},
        tasktype = 1,
        type = 3,
    },

    [31019] = {
        achievetype = 1,
        condition = "成功完成帝都宅急便任务次数=2",
        degreetype = 2,
        describe = "完成2次帝都宅急便",
        id = 31019,
        name = "宅急便",
        open_id = 1037,
        pre_condition = {"完成成就任务=31029", "主角等级=43"},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=18000)"}},
        tasktype = 1,
        type = 3,
    },

    [31021] = {
        achievetype = 1,
        condition = "通关地牢层数=5",
        degreetype = 1,
        describe = "通关第5层地牢",
        id = 31021,
        name = "地牢",
        open_id = 1003,
        pre_condition = {"完成成就任务=31019", "主角等级=45"},
        rewarditem = {{["num"] = 5, ["sid"] = "11101"}},
        tasktype = 1,
        type = 3,
    },

    [31023] = {
        achievetype = 1,
        condition = "通关梦魇副本次数=1",
        degreetype = 1,
        describe = "通关梦魇狩猎",
        id = 31023,
        name = "梦魇狩猎",
        open_id = 1029,
        pre_condition = {"完成成就任务=31021", "主角等级=50"},
        rewarditem = {{["num"] = 1, ["sid"] = "13213"}},
        tasktype = 1,
        type = 3,
    },

    [31025] = {
        achievetype = 1,
        condition = "人形讨伐=1",
        degreetype = 1,
        describe = "挑战1次人形讨伐",
        id = 31025,
        name = "人形讨伐",
        open_id = 1045,
        pre_condition = {"完成成就任务=31023", "主角等级=55"},
        rewarditem = {{["num"] = 3, ["sid"] = "11010"}},
        tasktype = 1,
        type = 3,
    },

    [31024] = {
        achievetype = 1,
        condition = "挑战NPC=1",
        degreetype = 2,
        describe = "成功挑战任意1个图鉴人物",
        id = 31024,
        name = "挑战图鉴",
        open_id = 1027,
        pre_condition = {"完成成就任务=31025", "主角等级=60"},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=10000)"}},
        tasktype = 1,
        type = 3,
    },

    [31524] = {
        achievetype = 2,
        condition = "穿戴符文=1",
        degreetype = 2,
        describe = "穿戴一件符文",
        id = 31524,
        name = "穿戴符文（1）",
        open_id = 203,
        pre_condition = {"主角等级=5"},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=5000)"}},
        tasktype = 1,
        type = 3,
    },

    [31525] = {
        achievetype = 2,
        condition = "穿戴整套符文=1",
        degreetype = 2,
        describe = "为1名伙伴穿戴4件符文",
        id = 31525,
        name = "穿戴符文（2）",
        open_id = 203,
        pre_condition = {},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=5000)"}},
        tasktype = 1,
        type = 3,
    },

    [31502] = {
        achievetype = 2,
        condition = "领取第1章第1个宝箱=1",
        degreetype = 1,
        describe = "领取第一章12星宝箱",
        id = 31502,
        name = "领取宝箱（1）",
        open_id = 1035,
        pre_condition = {},
        rewarditem = {{["num"] = 1, ["sid"] = "20302"}},
        tasktype = 1,
        type = 3,
    },

    [31533] = {
        achievetype = 2,
        condition = "穿戴符文=2",
        degreetype = 2,
        describe = "穿戴两件符文",
        id = 31533,
        name = "穿戴符文（2）",
        open_id = 203,
        pre_condition = {"完成成就任务=31524", "主角等级=7"},
        rewarditem = {{["num"] = 5, ["sid"] = "14021"}},
        tasktype = 1,
        type = 3,
    },

    [31526] = {
        achievetype = 2,
        condition = "3级符文=1",
        degreetype = 2,
        describe = "升级任意符文到3级",
        id = 31526,
        name = "升级符文（1）",
        open_id = 203,
        pre_condition = {"完成成就任务=31533"},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=5000)"}},
        tasktype = 1,
        type = 3,
    },

    [31527] = {
        achievetype = 2,
        condition = "穿戴整套符文=2",
        degreetype = 2,
        describe = "为2名伙伴穿戴4件符文",
        id = 31527,
        name = "穿戴符文（3）",
        open_id = 203,
        pre_condition = {},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=5000)"}},
        tasktype = 1,
        type = 3,
    },

    [31534] = {
        achievetype = 2,
        condition = "穿戴符文=3",
        degreetype = 2,
        describe = "穿戴三件符文",
        id = 31534,
        name = "穿戴符文（3）",
        open_id = 203,
        pre_condition = {"完成成就任务=31526", "主角等级=9"},
        rewarditem = {{["num"] = 8, ["sid"] = "14021"}},
        tasktype = 1,
        type = 3,
    },

    [31506] = {
        achievetype = 2,
        condition = "领取第1章第2个宝箱=1",
        degreetype = 1,
        describe = "领取第一章24星宝箱",
        id = 31506,
        name = "领取宝箱（2）",
        open_id = 1035,
        pre_condition = {},
        rewarditem = {{["num"] = 1, ["sid"] = "20302"}},
        tasktype = 1,
        type = 3,
    },

    [31528] = {
        achievetype = 2,
        condition = "3级符文=2",
        degreetype = 2,
        describe = "升级任意2件符文到+3",
        id = 31528,
        name = "升级符文（2）",
        open_id = 203,
        pre_condition = {"完成成就任务=31534"},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=5000)"}},
        tasktype = 1,
        type = 3,
    },

    [31529] = {
        achievetype = 2,
        condition = "穿戴整套符文=3",
        degreetype = 2,
        describe = "为3名伙伴穿戴4件符文",
        id = 31529,
        name = "穿戴符文（4）",
        open_id = 203,
        pre_condition = {},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=5000)"}},
        tasktype = 1,
        type = 3,
    },

    [31510] = {
        achievetype = 2,
        condition = "领取成就奖励=1",
        degreetype = 1,
        describe = "领取1次成就奖励",
        id = 31510,
        name = "成就奖励",
        open_id = 1016,
        pre_condition = {"完成成就任务=31528", "主角等级=13"},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=5000)"}},
        tasktype = 1,
        type = 3,
    },

    [31530] = {
        achievetype = 2,
        condition = "穿戴整套符文=4",
        degreetype = 2,
        describe = "为4名伙伴穿戴4件符文",
        id = 31530,
        name = "穿戴符文（5）",
        open_id = 203,
        pre_condition = {},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=5000)"}},
        tasktype = 1,
        type = 3,
    },

    [31535] = {
        achievetype = 2,
        condition = "穿戴符文=4",
        degreetype = 2,
        describe = "穿戴四件符文",
        id = 31535,
        name = "穿戴符文（4）",
        open_id = 203,
        pre_condition = {"完成成就任务=31510"},
        rewarditem = {{["num"] = 15, ["sid"] = "14021"}},
        tasktype = 1,
        type = 3,
    },

    [31531] = {
        achievetype = 2,
        condition = "3级符文=4",
        degreetype = 2,
        describe = "升级任意4件符文到+3",
        id = 31531,
        name = "升级符文（3）",
        open_id = 203,
        pre_condition = {"完成成就任务=31535"},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=5000)"}},
        tasktype = 1,
        type = 3,
    },

    [31515] = {
        achievetype = 2,
        condition = "互动=2",
        degreetype = 2,
        describe = "对宅邸的重华抚摸2次",
        id = 31515,
        name = "宅邸抚摸",
        open_id = 1004,
        pre_condition = {"完成成就任务=31531", "主角等级=20"},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=8000)"}},
        tasktype = 1,
        type = 3,
    },

    [31516] = {
        achievetype = 2,
        condition = "特训=1",
        degreetype = 2,
        describe = "宅邸重华开始1次娱乐项目",
        id = 31516,
        name = "宅邸娱乐",
        open_id = 1004,
        pre_condition = {"完成成就任务=31515"},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=8000)"}},
        tasktype = 1,
        type = 3,
    },

    [31518] = {
        achievetype = 2,
        condition = "击败茶会相关怪物次数=1",
        degreetype = 1,
        describe = "在喵萌茶会战斗中胜利1次",
        id = 31518,
        name = "喵萌茶会",
        open_id = 1023,
        pre_condition = {"完成成就任务=31516", "主角等级=38"},
        rewarditem = {{["num"] = 1, ["sid"] = "14002"}},
        tasktype = 1,
        type = 3,
    },

    [31519] = {
        achievetype = 2,
        condition = "探索=20",
        degreetype = 2,
        describe = "消耗20点探索点",
        id = 31519,
        name = "探索",
        open_id = 1011,
        pre_condition = {"完成成就任务=31518", "主角等级=40"},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=20000)"}},
        tasktype = 1,
        type = 3,
    },

    [31532] = {
        achievetype = 2,
        condition = "穿戴御灵数量=4",
        degreetype = 2,
        describe = "穿戴4个御灵",
        id = 31532,
        name = "穿戴御灵",
        open_id = 205,
        pre_condition = {"完成成就任务=31519", "主角等级=41"},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=5000)"}},
        tasktype = 1,
        type = 3,
    },

    [31520] = {
        achievetype = 2,
        condition = "通关异空流放第1层次数=1",
        degreetype = 2,
        describe = "通关御灵副本1层",
        id = 31520,
        name = "御灵副本",
        open_id = 1040,
        pre_condition = {"完成成就任务=31532", "主角等级=42"},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=8000)"}},
        tasktype = 1,
        type = 3,
    },

    [31521] = {
        achievetype = 2,
        condition = "开始伙伴游历次数=1",
        degreetype = 2,
        describe = "开始1次伙伴游历",
        id = 31521,
        name = "伙伴游历",
        open_id = 1013,
        pre_condition = {"完成成就任务=31520", "主角等级=44"},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=20000)"}},
        tasktype = 1,
        type = 3,
    },

    [31522] = {
        achievetype = 2,
        condition = "伙伴觉醒次数=1",
        degreetype = 2,
        describe = "觉醒任意1个伙伴",
        id = 31522,
        name = "伙伴觉醒",
        open_id = 204,
        pre_condition = {"完成成就任务=31521", "主角等级=45"},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=20000)"}},
        tasktype = 1,
        type = 3,
    },

    [31523] = {
        achievetype = 2,
        condition = "通过月见击败第2波怪物=1",
        degreetype = 2,
        describe = "至少通关2波月见幻境",
        id = 31523,
        name = "月见幻境",
        open_id = 1007,
        pre_condition = {"完成成就任务=31522", "主角等级=46"},
        rewarditem = {{["num"] = 1, ["sid"] = "1002(value=20000)"}},
        tasktype = 1,
        type = 3,
    },

}
