-- ./excel/monster/pefuben.xlsx
return {

    [50231] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 100701, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "323",
        boss = 0,
        critical_damage = "15720",
        critical_ratio = "0",
        cure_critical_ratio = "792.5",
        defense = "133.92",
        desc = "LV1小怪",
        double_attack_suspend = 0,
        id = 50231,
        level = "5",
        maxhp = "2516",
        model_id = 1007,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "40",
        show_skill = {},
        special_skill = {},
        speed = "93.72",
        texture = 11,
        wpmodel = 2100,
    },

    [50092] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 100501, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "323",
        boss = 0,
        critical_damage = "15720",
        critical_ratio = "0",
        cure_critical_ratio = "792.5",
        defense = "133.92",
        desc = "LV1小怪",
        double_attack_suspend = 0,
        id = 50092,
        level = "5",
        maxhp = "2516",
        model_id = 1005,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "40",
        show_skill = {},
        special_skill = {},
        speed = "93.72",
        texture = 11,
        wpmodel = 2100,
    },

    [50233] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 175301, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "323",
        boss = 0,
        critical_damage = "15720",
        critical_ratio = "0",
        cure_critical_ratio = "792.5",
        defense = "133.92",
        desc = "LV1小怪",
        double_attack_suspend = 0,
        id = 50233,
        level = "5",
        maxhp = "2516",
        model_id = 1753,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "40",
        show_skill = {},
        special_skill = {},
        speed = "93.72",
        texture = 11,
        wpmodel = 2100,
    },

    [50164] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "382",
        boss = 0,
        critical_damage = "15720",
        critical_ratio = "1188.75",
        cure_critical_ratio = "792.5",
        defense = "132.48",
        desc = "LV1小怪",
        double_attack_suspend = 0,
        id = 50164,
        level = "5",
        maxhp = "2435",
        model_id = 410,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "40",
        show_skill = {},
        special_skill = {},
        speed = "1483.9",
        texture = 11,
        wpmodel = 2100,
    },

    [50355] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 40101, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "330",
        boss = 0,
        critical_damage = "15720",
        critical_ratio = "1188.75",
        cure_critical_ratio = "792.5",
        defense = "148.32",
        desc = "LV1小怪",
        double_attack_suspend = 0,
        id = 50355,
        level = "5",
        maxhp = "3085",
        model_id = 401,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "40",
        show_skill = {},
        special_skill = {},
        speed = "1093.4",
        texture = 11,
        wpmodel = 2100,
    },

    [51016] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 102001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "854",
        boss = 1,
        critical_damage = "15720",
        critical_ratio = "1585",
        cure_critical_ratio = "792.5",
        defense = "144",
        desc = "LV1BOSS",
        double_attack_suspend = 1,
        id = 51016,
        level = "5",
        maxhp = "9809",
        model_id = 1020,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆破坏者",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 1004}},
        petId = 0,
        res_abnormal_ratio = "900",
        res_critical_ratio = "0",
        scale = 150,
        show_lv = "40",
        show_skill = {102002, 1004},
        special_skill = {{["pfid"] = 102002, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "796",
        texture = 11,
        wpmodel = 2100,
    },

    [120331] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50701, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "554",
        boss = 0,
        critical_damage = "15720",
        critical_ratio = "1981.25",
        cure_critical_ratio = "792.5",
        defense = "129.6",
        desc = "LV2小怪",
        double_attack_suspend = 0,
        id = 120331,
        level = "5",
        maxhp = "7606",
        model_id = 507,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 50703}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "48",
        show_skill = {},
        special_skill = {{["pfid"] = 50702, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "1054.35",
        texture = 11,
        wpmodel = 2100,
    },

    [120232] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50901, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "620",
        boss = 0,
        critical_damage = "15720",
        critical_ratio = "1585",
        cure_critical_ratio = "792.5",
        defense = "129.6",
        desc = "LV2小怪",
        double_attack_suspend = 0,
        id = 120232,
        level = "5",
        maxhp = "6283",
        model_id = 509,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 50903}, {["pfid"] = 50904}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "48",
        show_skill = {},
        special_skill = {{["pfid"] = 50902, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "1444.85",
        texture = 11,
        wpmodel = 2100,
    },

    [120403] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41701, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "614",
        boss = 0,
        critical_damage = "15720",
        critical_ratio = "1585",
        cure_critical_ratio = "792.5",
        defense = "136.8",
        desc = "LV2小怪",
        double_attack_suspend = 0,
        id = 120403,
        level = "5",
        maxhp = "6614",
        model_id = 417,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 41703}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "48",
        show_skill = {},
        special_skill = {{["pfid"] = 41702, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "1522.95",
        texture = 11,
        wpmodel = 2100,
    },

    [120174] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 31201, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "578",
        boss = 0,
        critical_damage = "15720",
        critical_ratio = "1188.75",
        cure_critical_ratio = "792.5",
        defense = "138.24",
        desc = "LV2小怪",
        double_attack_suspend = 0,
        id = 120174,
        level = "5",
        maxhp = "6812",
        model_id = 312,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 31203}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "48",
        show_skill = {},
        special_skill = {{["pfid"] = 31202, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "1132.45",
        texture = 11,
        wpmodel = 2100,
    },

    [120145] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50101, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "662",
        boss = 0,
        critical_damage = "15720",
        critical_ratio = "1981.25",
        cure_critical_ratio = "792.5",
        defense = "122.4",
        desc = "LV2小怪",
        double_attack_suspend = 0,
        id = 120145,
        level = "5",
        maxhp = "5952",
        model_id = 501,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 50103}, {["pfid"] = 50104}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "48",
        show_skill = {},
        special_skill = {{["pfid"] = 50102, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "78.1",
        texture = 11,
        wpmodel = 2100,
    },

    [120236] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41401, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "590",
        boss = 0,
        critical_damage = "15720",
        critical_ratio = "1585",
        cure_critical_ratio = "792.5",
        defense = "142.56",
        desc = "LV2小怪",
        double_attack_suspend = 0,
        id = 120236,
        level = "5",
        maxhp = "6349",
        model_id = 414,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 30103}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "48",
        show_skill = {},
        special_skill = {{["pfid"] = 41402, ["sum_grid"] = 2, ["cur_grid"] = 2}},
        speed = "937.2",
        texture = 11,
        wpmodel = 2100,
    },

    [120377] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "662",
        boss = 0,
        critical_damage = "15720",
        critical_ratio = "1188.75",
        cure_critical_ratio = "792.5",
        defense = "132.48",
        desc = "LV2小怪",
        double_attack_suspend = 0,
        id = 120377,
        level = "5",
        maxhp = "5952",
        model_id = 410,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 41003}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "48",
        show_skill = {},
        special_skill = {{["pfid"] = 41002, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "1483.9",
        texture = 11,
        wpmodel = 2100,
    },

    [120388] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50601, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "650",
        boss = 0,
        critical_damage = "15720",
        critical_ratio = "1585",
        cure_critical_ratio = "792.5",
        defense = "146.88",
        desc = "LV2小怪",
        double_attack_suspend = 0,
        id = 120388,
        level = "5",
        maxhp = "5423",
        model_id = 506,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 50603}, {["pfid"] = 50604}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "48",
        show_skill = {},
        special_skill = {{["pfid"] = 50602, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "976.25",
        texture = 11,
        wpmodel = 2100,
    },

    [121019] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 102001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "1357",
        boss = 1,
        critical_damage = "15720",
        critical_ratio = "1585",
        cure_critical_ratio = "792.5",
        defense = "144",
        desc = "LV2BOSS",
        double_attack_suspend = 1,
        id = 121019,
        level = "5",
        maxhp = "14252",
        model_id = 1020,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆破坏者",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 1004}},
        petId = 0,
        res_abnormal_ratio = "1800",
        res_critical_ratio = "0",
        scale = 150,
        show_lv = "48",
        show_skill = {102002, 1004},
        special_skill = {{["pfid"] = 102002, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "796",
        texture = 11,
        wpmodel = 2100,
    },

    [190211] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50901, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "1131",
        boss = 0,
        critical_damage = "16520",
        critical_ratio = "2235",
        cure_critical_ratio = "1117.5",
        defense = "232.2",
        desc = "LV3小怪",
        double_attack_suspend = 0,
        id = 190211,
        level = "5",
        maxhp = "11581",
        model_id = 509,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 50903}, {["pfid"] = 50904}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "56",
        show_skill = {},
        special_skill = {{["pfid"] = 50902, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "1518.85",
        texture = 11,
        wpmodel = 2100,
    },

    [190332] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 30201, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "1131",
        boss = 0,
        critical_damage = "16520",
        critical_ratio = "2235",
        cure_critical_ratio = "1117.5",
        defense = "265.74",
        desc = "LV3小怪",
        double_attack_suspend = 0,
        id = 190332,
        level = "5",
        maxhp = "11581",
        model_id = 302,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 30203}, {["pfid"] = 30204}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "56",
        show_skill = {},
        special_skill = {{["pfid"] = 30202, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "533.65",
        texture = 11,
        wpmodel = 2100,
    },

    [190373] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41501, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "879",
        boss = 0,
        critical_damage = "16520",
        critical_ratio = "1676.25",
        cure_critical_ratio = "1117.5",
        defense = "245.1",
        desc = "LV3小怪",
        double_attack_suspend = 0,
        id = 190373,
        level = "5",
        maxhp = "14263",
        model_id = 415,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 41503}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "56",
        show_skill = {},
        special_skill = {{["pfid"] = 41502, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "821",
        texture = 11,
        wpmodel = 2100,
    },

    [190234] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41401, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "1077",
        boss = 0,
        critical_damage = "16520",
        critical_ratio = "2235",
        cure_critical_ratio = "1117.5",
        defense = "255.42",
        desc = "LV3小怪",
        double_attack_suspend = 0,
        id = 190234,
        level = "5",
        maxhp = "11703",
        model_id = 414,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 30103}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "56",
        show_skill = {},
        special_skill = {{["pfid"] = 41402, ["sum_grid"] = 2, ["cur_grid"] = 2}},
        speed = "985.2",
        texture = 11,
        wpmodel = 2100,
    },

    [190255] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41401, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "1077",
        boss = 0,
        critical_damage = "16520",
        critical_ratio = "2235",
        cure_critical_ratio = "1117.5",
        defense = "255.42",
        desc = "LV3小怪",
        double_attack_suspend = 0,
        id = 190255,
        level = "5",
        maxhp = "11703",
        model_id = 414,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 30103}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "56",
        show_skill = {},
        special_skill = {{["pfid"] = 41402, ["sum_grid"] = 2, ["cur_grid"] = 2}},
        speed = "985.2",
        texture = 11,
        wpmodel = 2100,
    },

    [190096] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 30301, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "1274",
        boss = 0,
        critical_damage = "16520",
        critical_ratio = "3352.5",
        cure_critical_ratio = "1117.5",
        defense = "206.4",
        desc = "LV3小怪",
        double_attack_suspend = 0,
        id = 190096,
        level = "5",
        maxhp = "9752",
        model_id = 303,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 30303}, {["pfid"] = 30304}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "56",
        show_skill = {},
        special_skill = {{["pfid"] = 30302, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "1272.55",
        texture = 11,
        wpmodel = 2100,
    },

    [190257] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50101, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "1208",
        boss = 0,
        critical_damage = "16520",
        critical_ratio = "2793.75",
        cure_critical_ratio = "1117.5",
        defense = "219.3",
        desc = "LV3小怪",
        double_attack_suspend = 0,
        id = 190257,
        level = "5",
        maxhp = "10971",
        model_id = 501,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 50103}, {["pfid"] = 50104}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "56",
        show_skill = {},
        special_skill = {{["pfid"] = 50102, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "82.1",
        texture = 11,
        wpmodel = 2100,
    },

    [190238] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50801, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "1055",
        boss = 0,
        critical_damage = "16520",
        critical_ratio = "1676.25",
        cure_critical_ratio = "1117.5",
        defense = "247.68",
        desc = "LV3小怪",
        double_attack_suspend = 0,
        id = 190238,
        level = "5",
        maxhp = "13775",
        model_id = 508,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 50803}, {["pfid"] = 50804}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "56",
        show_skill = {},
        special_skill = {{["pfid"] = 50802, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "1477.8",
        texture = 11,
        wpmodel = 2100,
    },

    [191019] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 102001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "2484",
        boss = 1,
        critical_damage = "16520",
        critical_ratio = "2235",
        cure_critical_ratio = "1117.5",
        defense = "258",
        desc = "LV3BOSS",
        double_attack_suspend = 1,
        id = 191019,
        level = "5",
        maxhp = "26270",
        model_id = 1020,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆破坏者",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 1004}},
        petId = 0,
        res_abnormal_ratio = "2700",
        res_critical_ratio = "0",
        scale = 150,
        show_lv = "56",
        show_skill = {102002, 1004},
        special_skill = {{["pfid"] = 102002, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "836",
        texture = 11,
        wpmodel = 2100,
    },

    [260101] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 31101, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "1440",
        boss = 0,
        critical_damage = "17320",
        critical_ratio = "2163.75",
        cure_critical_ratio = "2885",
        defense = "464.4",
        desc = "LV4小怪",
        double_attack_suspend = 0,
        id = 260101,
        level = "5",
        maxhp = "22663",
        model_id = 311,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 31103}, {["pfid"] = 31104}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "64",
        show_skill = {},
        special_skill = {{["pfid"] = 31102, ["sum_grid"] = 4, ["cur_grid"] = 3}},
        speed = "0",
        texture = 11,
        wpmodel = 2100,
    },

    [260162] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 30801, ["ratio"] = 1}},
        ai_arg = 50,
        attack = "1423",
        boss = 0,
        critical_damage = "17320",
        critical_ratio = "2163.75",
        cure_critical_ratio = "1442.5",
        defense = "425.7",
        desc = "LV4小怪",
        double_attack_suspend = 0,
        id = 260162,
        level = "5",
        maxhp = "22663",
        model_id = 308,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 30803}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "64",
        show_skill = {},
        special_skill = {{["pfid"] = 30802, ["sum_grid"] = 2, ["cur_grid"] = 1}},
        speed = "947.1",
        texture = 11,
        wpmodel = 2100,
    },

    [260173] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41301, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "1758",
        boss = 0,
        critical_damage = "17320",
        critical_ratio = "2163.75",
        cure_critical_ratio = "1442.5",
        defense = "398.61",
        desc = "LV4小怪",
        double_attack_suspend = 0,
        id = 260173,
        level = "5",
        maxhp = "19264",
        model_id = 413,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 41303}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "64",
        show_skill = {},
        special_skill = {{["pfid"] = 41302, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "430.5",
        texture = 11,
        wpmodel = 2100,
    },

    [260234] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50901, ["ratio"] = 1}},
        ai_arg = 50,
        attack = "1724",
        boss = 0,
        critical_damage = "17320",
        critical_ratio = "2885",
        cure_critical_ratio = "1442.5",
        defense = "348.3",
        desc = "LV4小怪",
        double_attack_suspend = 0,
        id = 260234,
        level = "5",
        maxhp = "17942",
        model_id = 509,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 50903}, {["pfid"] = 50904}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "64",
        show_skill = {},
        special_skill = {{["pfid"] = 50902, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "1592.85",
        texture = 11,
        wpmodel = 2100,
    },

    [260325] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 51401, ["ratio"] = 1}},
        ai_arg = 80,
        attack = "1791",
        boss = 0,
        critical_damage = "17320",
        critical_ratio = "2885",
        cure_critical_ratio = "1442.5",
        defense = "387",
        desc = "LV4小怪",
        double_attack_suspend = 0,
        id = 260325,
        level = "5",
        maxhp = "17564",
        model_id = 514,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 51403}, {["pfid"] = 51404}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "64",
        show_skill = {},
        special_skill = {{["pfid"] = 51402, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "258.3",
        texture = 11,
        wpmodel = 2100,
    },

    [260216] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 51101, ["ratio"] = 1}},
        ai_arg = 50,
        attack = "1707",
        boss = 0,
        critical_damage = "17320",
        critical_ratio = "2885",
        cure_critical_ratio = "1442.5",
        defense = "464.4",
        desc = "LV4小怪",
        double_attack_suspend = 0,
        id = 260216,
        level = "5",
        maxhp = "22663",
        model_id = 511,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 51103}, {["pfid"] = 51104}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "64",
        show_skill = {},
        special_skill = {{["pfid"] = 51102, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "1506.75",
        texture = 11,
        wpmodel = 2100,
    },

    [260327] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41001, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "1841",
        boss = 0,
        critical_damage = "17320",
        critical_ratio = "2163.75",
        cure_critical_ratio = "1442.5",
        defense = "356.04",
        desc = "LV4小怪",
        double_attack_suspend = 0,
        id = 260327,
        level = "5",
        maxhp = "16998",
        model_id = 410,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 41003}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "64",
        show_skill = {},
        special_skill = {{["pfid"] = 41002, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "1635.9",
        texture = 11,
        wpmodel = 2100,
    },

    [260328] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 40301, ["ratio"] = 1}},
        ai_arg = 50,
        attack = "1774",
        boss = 0,
        critical_damage = "17320",
        critical_ratio = "2163.75",
        cure_critical_ratio = "1442.5",
        defense = "387",
        desc = "LV4小怪",
        double_attack_suspend = 0,
        id = 260328,
        level = "5",
        maxhp = "19264",
        model_id = 403,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 40303}, {["pfid"] = 40304}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "64",
        show_skill = {},
        special_skill = {{["pfid"] = 40302, ["sum_grid"] = 2, ["cur_grid"] = 1}},
        speed = "904.05",
        texture = 11,
        wpmodel = 2100,
    },

    [261019] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 102001, ["ratio"] = 1}},
        ai_arg = 30,
        attack = "3795",
        boss = 1,
        critical_damage = "17320",
        critical_ratio = "2885",
        cure_critical_ratio = "1442.5",
        defense = "387",
        desc = "LV4BOSS",
        double_attack_suspend = 1,
        id = 261019,
        level = "5",
        maxhp = "40700",
        model_id = 1020,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆破坏者",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 1004}},
        petId = 0,
        res_abnormal_ratio = "3600",
        res_critical_ratio = "0",
        scale = 150,
        show_lv = "64",
        show_skill = {102002, 1004},
        special_skill = {{["pfid"] = 102002, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "876",
        texture = 11,
        wpmodel = 2100,
    },

    [330171] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 40701, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "2196",
        boss = 0,
        critical_damage = "18120",
        critical_ratio = "2651.25",
        cure_critical_ratio = "3535.0",
        defense = "520.74",
        desc = "LV5小怪",
        double_attack_suspend = 0,
        id = 330171,
        level = "5",
        maxhp = "29290",
        model_id = 407,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 40703}, {["pfid"] = 40704}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "72",
        show_skill = {},
        special_skill = {{["pfid"] = 40702, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "360.4",
        texture = 11,
        wpmodel = 2100,
    },

    [330252] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41501, ["ratio"] = 1}},
        ai_arg = 50,
        attack = "1849",
        boss = 0,
        critical_damage = "18120",
        critical_ratio = "2651.25",
        cure_critical_ratio = "1767.5",
        defense = "499.7",
        desc = "LV5小怪",
        double_attack_suspend = 0,
        id = 330252,
        level = "5",
        maxhp = "31154",
        model_id = 415,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 41503}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "72",
        show_skill = {},
        special_skill = {{["pfid"] = 41502, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "901",
        texture = 11,
        wpmodel = 2100,
    },

    [330233] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 51301, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "2312",
        boss = 0,
        critical_damage = "18120",
        critical_ratio = "4418.75",
        cure_critical_ratio = "1767.5",
        defense = "436.58",
        desc = "LV5小怪",
        double_attack_suspend = 0,
        id = 330233,
        level = "5",
        maxhp = "21834",
        model_id = 513,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 51303}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "72",
        show_skill = {},
        special_skill = {{["pfid"] = 51302, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "225.25",
        texture = 11,
        wpmodel = 2100,
    },

    [330324] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50201, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "2450",
        boss = 0,
        critical_damage = "18120",
        critical_ratio = "3535.0",
        cure_critical_ratio = "1767.5",
        defense = "520.74",
        desc = "LV5小怪",
        double_attack_suspend = 0,
        id = 330324,
        level = "5",
        maxhp = "24497",
        model_id = 502,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 50203}, {["pfid"] = 50204}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "72",
        show_skill = {},
        special_skill = {{["pfid"] = 50202, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "405.45",
        texture = 11,
        wpmodel = 2100,
    },

    [330235] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50201, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "2450",
        boss = 0,
        critical_damage = "18120",
        critical_ratio = "3535.0",
        cure_critical_ratio = "1767.5",
        defense = "520.74",
        desc = "LV5小怪",
        double_attack_suspend = 0,
        id = 330235,
        level = "5",
        maxhp = "24497",
        model_id = 502,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 50203}, {["pfid"] = 50204}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "72",
        show_skill = {},
        special_skill = {{["pfid"] = 50202, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "405.45",
        texture = 11,
        wpmodel = 2100,
    },

    [330106] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 40101, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "2196",
        boss = 0,
        critical_damage = "18120",
        critical_ratio = "2651.25",
        cure_critical_ratio = "1767.5",
        defense = "541.78",
        desc = "LV5小怪",
        double_attack_suspend = 0,
        id = 330106,
        level = "5",
        maxhp = "30355",
        model_id = 401,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 40103}, {["pfid"] = 40104}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "72",
        show_skill = {},
        special_skill = {{["pfid"] = 40102, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "1261.4",
        texture = 11,
        wpmodel = 2100,
    },

    [330337] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 30101, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "2381",
        boss = 0,
        critical_damage = "18120",
        critical_ratio = "3535.0",
        cure_critical_ratio = "1767.5",
        defense = "578.6",
        desc = "LV5小怪",
        double_attack_suspend = 0,
        id = 330337,
        level = "5",
        maxhp = "23965",
        model_id = 301,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 30103}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "72",
        show_skill = {},
        special_skill = {{["pfid"] = 30102, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "675.75",
        texture = 11,
        wpmodel = 2100,
    },

    [330238] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 30101, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "2381",
        boss = 0,
        critical_damage = "18120",
        critical_ratio = "3535.0",
        cure_critical_ratio = "1767.5",
        defense = "578.6",
        desc = "LV5小怪",
        double_attack_suspend = 0,
        id = 330238,
        level = "5",
        maxhp = "23965",
        model_id = 301,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 30103}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "72",
        show_skill = {},
        special_skill = {{["pfid"] = 30102, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "675.75",
        texture = 11,
        wpmodel = 2100,
    },

    [331019] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 102001, ["ratio"] = 1}},
        ai_arg = 30,
        attack = "5254",
        boss = 1,
        critical_damage = "18120",
        critical_ratio = "3535.0",
        cure_critical_ratio = "1767.5",
        defense = "526",
        desc = "LV5BOSS",
        double_attack_suspend = 1,
        id = 331019,
        level = "5",
        maxhp = "57382",
        model_id = 1020,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆破坏者",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 1004}},
        petId = 0,
        res_abnormal_ratio = "4500",
        res_critical_ratio = "0",
        scale = 150,
        show_lv = "72",
        show_skill = {102002, 1004},
        special_skill = {{["pfid"] = 102002, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "916",
        texture = 11,
        wpmodel = 2100,
    },

    [400351] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 40501, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "3117",
        boss = 0,
        critical_damage = "18920",
        critical_ratio = "5231.25",
        cure_critical_ratio = "2092.5",
        defense = "592.24",
        desc = "LV6小怪",
        double_attack_suspend = 0,
        id = 400351,
        level = "5",
        maxhp = "41097",
        model_id = 405,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 40503}, {["pfid"] = 40504}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "80",
        show_skill = {},
        special_skill = {{["pfid"] = 40502, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "1505.6",
        texture = 11,
        wpmodel = 2100,
    },

    [400232] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41601, ["ratio"] = 1}},
        ai_arg = 50,
        attack = "2758",
        boss = 0,
        critical_damage = "18920",
        critical_ratio = "4185",
        cure_critical_ratio = "2092.5",
        defense = "760.49",
        desc = "LV6小怪",
        double_attack_suspend = 0,
        id = 400232,
        level = "5",
        maxhp = "38263",
        model_id = 416,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 41603}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "80",
        show_skill = {},
        special_skill = {{["pfid"] = 41602, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "1082.15",
        texture = 11,
        wpmodel = 2100,
    },

    [400383] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 40401, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "2548",
        boss = 0,
        critical_damage = "18920",
        critical_ratio = "3138.75",
        cure_critical_ratio = "4185",
        defense = "740.3",
        desc = "LV6小怪",
        double_attack_suspend = 0,
        id = 400383,
        level = "5",
        maxhp = "38617",
        model_id = 404,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 40403}, {["pfid"] = 40404}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "80",
        show_skill = {},
        special_skill = {{["pfid"] = 40402, ["sum_grid"] = 2, ["cur_grid"] = 1}},
        speed = "639.88",
        texture = 11,
        wpmodel = 2100,
    },

    [400094] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 30801, ["ratio"] = 1}},
        ai_arg = 50,
        attack = "2548",
        boss = 0,
        critical_damage = "18920",
        critical_ratio = "3138.75",
        cure_critical_ratio = "2092.5",
        defense = "740.3",
        desc = "LV6小怪",
        double_attack_suspend = 0,
        id = 400094,
        level = "5",
        maxhp = "42514",
        model_id = 308,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 30803}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "80",
        show_skill = {},
        special_skill = {{["pfid"] = 30802, ["sum_grid"] = 2, ["cur_grid"] = 1}},
        speed = "1035.1",
        texture = 11,
        wpmodel = 2100,
    },

    [400175] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 40201, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "2878",
        boss = 0,
        critical_damage = "18920",
        critical_ratio = "5231.25",
        cure_critical_ratio = "2092.5",
        defense = "686.46",
        desc = "LV6小怪",
        double_attack_suspend = 0,
        id = 400175,
        level = "5",
        maxhp = "34720",
        model_id = 402,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 40203}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "80",
        show_skill = {},
        special_skill = {{["pfid"] = 40202, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "1552.65",
        texture = 11,
        wpmodel = 2100,
    },

    [400176] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 40201, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "2878",
        boss = 0,
        critical_damage = "18920",
        critical_ratio = "5231.25",
        cure_critical_ratio = "2092.5",
        defense = "686.46",
        desc = "LV6小怪",
        double_attack_suspend = 0,
        id = 400176,
        level = "5",
        maxhp = "34720",
        model_id = 402,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 40203}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "80",
        show_skill = {},
        special_skill = {{["pfid"] = 40202, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "1552.65",
        texture = 11,
        wpmodel = 2100,
    },

    [400377] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 31501, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "2758",
        boss = 0,
        critical_damage = "18920",
        critical_ratio = "3138.75",
        cure_critical_ratio = "2092.5",
        defense = "625.89",
        desc = "LV6小怪",
        double_attack_suspend = 0,
        id = 400377,
        level = "5",
        maxhp = "41806",
        model_id = 315,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 31503}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "80",
        show_skill = {},
        special_skill = {{["pfid"] = 31502, ["sum_grid"] = 4, ["cur_grid"] = 3}},
        speed = "1223.3",
        texture = 11,
        wpmodel = 2100,
    },

    [400358] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 40901, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "3207",
        boss = 0,
        critical_damage = "18920",
        critical_ratio = "5231.25",
        cure_critical_ratio = "2092.5",
        defense = "605.7",
        desc = "LV6小怪",
        double_attack_suspend = 0,
        id = 400358,
        level = "5",
        maxhp = "37200",
        model_id = 409,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 40903}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "80",
        show_skill = {},
        special_skill = {{["pfid"] = 40902, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "329.35",
        texture = 11,
        wpmodel = 2100,
    },

    [401019] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 102001, ["ratio"] = 1}},
        ai_arg = 30,
        attack = "6828",
        boss = 1,
        critical_damage = "18920",
        critical_ratio = "4185",
        cure_critical_ratio = "2092.5",
        defense = "673",
        desc = "LV6BOSS",
        double_attack_suspend = 1,
        id = 401019,
        level = "5",
        maxhp = "76349",
        model_id = 1020,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆破坏者",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 1004}},
        petId = 0,
        res_abnormal_ratio = "5400",
        res_critical_ratio = "0",
        scale = 150,
        show_lv = "80",
        show_skill = {102002, 1004},
        special_skill = {{["pfid"] = 102002, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "956",
        texture = 11,
        wpmodel = 2100,
    },

    [470231] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50401, ["ratio"] = 1}},
        ai_arg = 50,
        attack = "3419",
        boss = 0,
        critical_damage = "19720",
        critical_ratio = "3626.25",
        cure_critical_ratio = "2417.5",
        defense = "741.6",
        desc = "LV7小怪",
        double_attack_suspend = 0,
        id = 470231,
        level = "5",
        maxhp = "52940",
        model_id = 504,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 50403}, {["pfid"] = 50404}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "88",
        show_skill = {},
        special_skill = {{["pfid"] = 50402, ["sum_grid"] = 3, ["cur_grid"] = 3}},
        speed = "833.85",
        texture = 11,
        wpmodel = 2100,
    },

    [470372] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 31601, ["ratio"] = 1}},
        ai_arg = 30,
        attack = "3903",
        boss = 0,
        critical_damage = "19720",
        critical_ratio = "6043.75",
        cure_critical_ratio = "2417.5",
        defense = "782.8",
        desc = "LV7小怪",
        double_attack_suspend = 0,
        id = 470372,
        level = "5",
        maxhp = "49773",
        model_id = 316,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 31603}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "88",
        show_skill = {},
        special_skill = {{["pfid"] = 31602, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "147.15",
        texture = 11,
        wpmodel = 2100,
    },

    [470323] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50601, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "4014",
        boss = 0,
        critical_damage = "19720",
        critical_ratio = "4835",
        cure_critical_ratio = "2417.5",
        defense = "840.48",
        desc = "LV7小怪",
        double_attack_suspend = 0,
        id = 470323,
        level = "5",
        maxhp = "37104",
        model_id = 506,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 50603}, {["pfid"] = 50604}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "88",
        show_skill = {},
        special_skill = {{["pfid"] = 50602, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "1226.25",
        texture = 11,
        wpmodel = 2100,
    },

    [470334] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41801, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "4014",
        boss = 0,
        critical_damage = "19720",
        critical_ratio = "4835",
        cure_critical_ratio = "2417.5",
        defense = "988.8",
        desc = "LV7小怪",
        double_attack_suspend = 0,
        id = 470334,
        level = "5",
        maxhp = "43891",
        model_id = 418,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 41803}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "88",
        show_skill = {},
        special_skill = {{["pfid"] = 41802, ["sum_grid"] = 3, ["cur_grid"] = 3}},
        speed = "882.9",
        texture = 11,
        wpmodel = 2100,
    },

    [470385] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41501, ["ratio"] = 1}},
        ai_arg = 50,
        attack = "2973",
        boss = 0,
        critical_damage = "19720",
        critical_ratio = "3626.25",
        cure_critical_ratio = "2417.5",
        defense = "782.8",
        desc = "LV7小怪",
        double_attack_suspend = 0,
        id = 470385,
        level = "5",
        maxhp = "52940",
        model_id = 415,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 41503}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "88",
        show_skill = {},
        special_skill = {{["pfid"] = 41502, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "981",
        texture = 11,
        wpmodel = 2100,
    },

    [470256] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41201, ["ratio"] = 1}},
        ai_arg = 30,
        attack = "4274",
        boss = 0,
        critical_damage = "19720",
        critical_ratio = "4835",
        cure_critical_ratio = "2417.5",
        defense = "683.92",
        desc = "LV7小怪",
        double_attack_suspend = 0,
        id = 470256,
        level = "5",
        maxhp = "40723",
        model_id = 412,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 41203}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "88",
        show_skill = {},
        special_skill = {{["pfid"] = 41202, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "1471.5",
        texture = 11,
        wpmodel = 2100,
    },

    [470377] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50501, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "4200",
        boss = 0,
        critical_damage = "19720",
        critical_ratio = "4835",
        cure_critical_ratio = "2417.5",
        defense = "675.68",
        desc = "LV7小怪",
        double_attack_suspend = 0,
        id = 470377,
        level = "5",
        maxhp = "46606",
        model_id = 505,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 50503}, {["pfid"] = 50504}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "88",
        show_skill = {},
        special_skill = {{["pfid"] = 50502, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "196.2",
        texture = 11,
        wpmodel = 2100,
    },

    [470238] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50501, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "4200",
        boss = 0,
        critical_damage = "19720",
        critical_ratio = "4835",
        cure_critical_ratio = "2417.5",
        defense = "675.68",
        desc = "LV7小怪",
        double_attack_suspend = 0,
        id = 470238,
        level = "5",
        maxhp = "46606",
        model_id = 505,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 50503}, {["pfid"] = 50504}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "88",
        show_skill = {},
        special_skill = {{["pfid"] = 50502, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "196.2",
        texture = 11,
        wpmodel = 2100,
    },

    [471019] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 102001, ["ratio"] = 1}},
        ai_arg = 30,
        attack = "8484",
        boss = 1,
        critical_damage = "19720",
        critical_ratio = "4835",
        cure_critical_ratio = "2417.5",
        defense = "824",
        desc = "LV7BOSS",
        double_attack_suspend = 1,
        id = 471019,
        level = "5",
        maxhp = "97510",
        model_id = 1020,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆破坏者",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 1004}},
        petId = 0,
        res_abnormal_ratio = "6300",
        res_critical_ratio = "0",
        scale = 150,
        show_lv = "88",
        show_skill = {102002, 1004},
        special_skill = {{["pfid"] = 102002, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "996",
        texture = 11,
        wpmodel = 2100,
    },

    [540331] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50301, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "4946",
        boss = 0,
        critical_damage = "20520",
        critical_ratio = "6856.25",
        cure_critical_ratio = "2742.5",
        defense = "878.4",
        desc = "LV8小怪",
        double_attack_suspend = 0,
        id = 540331,
        level = "5",
        maxhp = "44816",
        model_id = 503,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 50303}, {["pfid"] = 50304}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "96",
        show_skill = {},
        special_skill = {{["pfid"] = 50302, ["sum_grid"] = 3, ["cur_grid"] = 3}},
        speed = "612.6",
        texture = 11,
        wpmodel = 2100,
    },

    [540352] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 31301, ["ratio"] = 1}},
        ai_arg = 30,
        attack = "4545",
        boss = 0,
        critical_damage = "20520",
        critical_ratio = "5485",
        cure_critical_ratio = "2742.5",
        defense = "1073.6",
        desc = "LV8小怪",
        double_attack_suspend = 0,
        id = 540352,
        level = "5",
        maxhp = "53219",
        model_id = 313,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 31303}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "96",
        show_skill = {},
        special_skill = {{["pfid"] = 31302, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "969.95",
        texture = 11,
        wpmodel = 2100,
    },

    [540163] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 30201, ["ratio"] = 1}},
        ai_arg = 50,
        attack = "4590",
        boss = 0,
        critical_damage = "20520",
        critical_ratio = "5485",
        cure_critical_ratio = "2742.5",
        defense = "1005.28",
        desc = "LV8小怪",
        double_attack_suspend = 0,
        id = 540163,
        level = "5",
        maxhp = "53219",
        model_id = 302,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 30203}, {["pfid"] = 30204}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "96",
        show_skill = {},
        special_skill = {{["pfid"] = 30202, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "663.65",
        texture = 11,
        wpmodel = 2100,
    },

    [540174] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 31601, ["ratio"] = 1}},
        ai_arg = 30,
        attack = "4679",
        boss = 0,
        critical_damage = "20520",
        critical_ratio = "6856.25",
        cure_critical_ratio = "2742.5",
        defense = "927.2",
        desc = "LV8小怪",
        double_attack_suspend = 0,
        id = 540174,
        level = "5",
        maxhp = "61622",
        model_id = 316,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 31603}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "96",
        show_skill = {},
        special_skill = {{["pfid"] = 31602, ["sum_grid"] = 3, ["cur_grid"] = 3}},
        speed = "153.15",
        texture = 11,
        wpmodel = 2100,
    },

    [540175] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 31401, ["ratio"] = 1}},
        ai_arg = 30,
        attack = "5035",
        boss = 0,
        critical_damage = "20520",
        critical_ratio = "5485",
        cure_critical_ratio = "2742.5",
        defense = "849.12",
        desc = "LV8小怪",
        double_attack_suspend = 0,
        id = 540175,
        level = "5",
        maxhp = "55460",
        model_id = 314,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 31403}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "96",
        show_skill = {},
        special_skill = {{["pfid"] = 31402, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "51.05",
        texture = 11,
        wpmodel = 2100,
    },

    [540166] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 51301, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "4456",
        boss = 0,
        critical_damage = "20520",
        critical_ratio = "6856.25",
        cure_critical_ratio = "2742.5",
        defense = "810.08",
        desc = "LV8小怪",
        double_attack_suspend = 0,
        id = 540166,
        level = "5",
        maxhp = "45937",
        model_id = 513,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 51303}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "96",
        show_skill = {},
        special_skill = {{["pfid"] = 51302, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "255.25",
        texture = 11,
        wpmodel = 2100,
    },

    [540357] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 30601, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "5347",
        boss = 0,
        critical_damage = "20520",
        critical_ratio = "6856.25",
        cure_critical_ratio = "2742.5",
        defense = "800.32",
        desc = "LV8小怪",
        double_attack_suspend = 0,
        id = 540357,
        level = "5",
        maxhp = "53219",
        model_id = 306,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 30603}, {["pfid"] = 30604}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "96",
        show_skill = {},
        special_skill = {{["pfid"] = 30602, ["sum_grid"] = 4, ["cur_grid"] = 3}},
        speed = "816.8",
        texture = 11,
        wpmodel = 2100,
    },

    [540238] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 31501, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "4100",
        boss = 0,
        critical_damage = "20520",
        critical_ratio = "4113.75",
        cure_critical_ratio = "2742.5",
        defense = "907.68",
        desc = "LV8小怪",
        double_attack_suspend = 0,
        id = 540238,
        level = "5",
        maxhp = "66104",
        model_id = 315,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 31503}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "96",
        show_skill = {},
        special_skill = {{["pfid"] = 31502, ["sum_grid"] = 4, ["cur_grid"] = 3}},
        speed = "1327.3",
        texture = 11,
        wpmodel = 2100,
    },

    [541019] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 102001, ["ratio"] = 1}},
        ai_arg = 30,
        attack = "10191",
        boss = 1,
        critical_damage = "20520",
        critical_ratio = "5485",
        cure_critical_ratio = "2742.5",
        defense = "976",
        desc = "LV8BOSS",
        double_attack_suspend = 1,
        id = 541019,
        level = "5",
        maxhp = "120724",
        model_id = 1020,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆破坏者",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 1004}},
        petId = 0,
        res_abnormal_ratio = "7200",
        res_critical_ratio = "0",
        scale = 150,
        show_lv = "96",
        show_skill = {102002, 1004},
        special_skill = {{["pfid"] = 102002, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "1036",
        texture = 11,
        wpmodel = 2100,
    },

    [610211] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41401, ["ratio"] = 1}},
        ai_arg = 50,
        attack = "5100",
        boss = 0,
        critical_damage = "21320",
        critical_ratio = "6135.0",
        cure_critical_ratio = "3067.5",
        defense = "1115.73",
        desc = "LV9小怪",
        double_attack_suspend = 0,
        id = 610211,
        level = "5",
        maxhp = "65025",
        model_id = 414,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 30103}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "100",
        show_skill = {},
        special_skill = {{["pfid"] = 41402, ["sum_grid"] = 2, ["cur_grid"] = 2}},
        speed = "1273.2",
        texture = 11,
        wpmodel = 2100,
    },

    [610232] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41301, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "5465",
        boss = 0,
        critical_damage = "21320",
        critical_ratio = "4601.25",
        cure_critical_ratio = "3067.5",
        defense = "1160.81",
        desc = "LV9小怪",
        double_attack_suspend = 0,
        id = 610232,
        level = "5",
        maxhp = "69089",
        model_id = 413,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 41303}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "100",
        show_skill = {},
        special_skill = {{["pfid"] = 41302, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "530.5",
        texture = 11,
        wpmodel = 2100,
    },

    [610143] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 40301, ["ratio"] = 1}},
        ai_arg = 50,
        attack = "5517",
        boss = 0,
        critical_damage = "21320",
        critical_ratio = "4601.25",
        cure_critical_ratio = "3067.5",
        defense = "1127",
        desc = "LV9小怪",
        double_attack_suspend = 0,
        id = 610143,
        level = "5",
        maxhp = "69089",
        model_id = 403,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 40303}, {["pfid"] = 40304}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "100",
        show_skill = {},
        special_skill = {{["pfid"] = 40302, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "1114.05",
        texture = 11,
        wpmodel = 2100,
    },

    [610354] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 51201, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "5621",
        boss = 0,
        critical_damage = "21320",
        critical_ratio = "9202.5",
        cure_critical_ratio = "6135.0",
        defense = "991.76",
        desc = "LV9小怪",
        double_attack_suspend = 0,
        id = 610354,
        level = "5",
        maxhp = "71798",
        model_id = 512,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 51203}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "100",
        show_skill = {},
        special_skill = {{["pfid"] = 51202, ["sum_grid"] = 3, ["cur_grid"] = 3}},
        speed = "954.9",
        texture = 11,
        wpmodel = 2100,
    },

    [610175] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 30801, ["ratio"] = 1}},
        ai_arg = 50,
        attack = "4424",
        boss = 0,
        critical_damage = "21320",
        critical_ratio = "4601.25",
        cure_critical_ratio = "3067.5",
        defense = "1239.7",
        desc = "LV9小怪",
        double_attack_suspend = 0,
        id = 610175,
        level = "5",
        maxhp = "81281",
        model_id = 308,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 30803}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "100",
        show_skill = {},
        special_skill = {{["pfid"] = 30802, ["sum_grid"] = 2, ["cur_grid"] = 1}},
        speed = "1167.1",
        texture = 11,
        wpmodel = 2100,
    },

    [610386] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50201, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "5517",
        boss = 0,
        critical_damage = "21320",
        critical_ratio = "6135.0",
        cure_critical_ratio = "3067.5",
        defense = "1115.73",
        desc = "LV9小怪",
        double_attack_suspend = 0,
        id = 610386,
        level = "5",
        maxhp = "62316",
        model_id = 502,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 50203}, {["pfid"] = 50204}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "100",
        show_skill = {},
        special_skill = {{["pfid"] = 50202, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "477.45",
        texture = 11,
        wpmodel = 2100,
    },

    [610337] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 51001, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "5985",
        boss = 0,
        critical_damage = "21320",
        critical_ratio = "7668.75",
        cure_critical_ratio = "3067.5",
        defense = "1003.03",
        desc = "LV9小怪",
        double_attack_suspend = 0,
        id = 610337,
        level = "5",
        maxhp = "64348",
        model_id = 510,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 51003}, {["pfid"] = 51004}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "100",
        show_skill = {},
        special_skill = {{["pfid"] = 51002, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "636.6",
        texture = 11,
        wpmodel = 2100,
    },

    [610168] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41601, ["ratio"] = 1}},
        ai_arg = 50,
        attack = "4788",
        boss = 0,
        critical_damage = "21320",
        critical_ratio = "6135.0",
        cure_critical_ratio = "3067.5",
        defense = "1273.51",
        desc = "LV9小怪",
        double_attack_suspend = 0,
        id = 610168,
        level = "5",
        maxhp = "73153",
        model_id = 416,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 41603}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "100",
        show_skill = {},
        special_skill = {{["pfid"] = 41602, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "1220.15",
        texture = 11,
        wpmodel = 2100,
    },

    [611019] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 102001, ["ratio"] = 1}},
        ai_arg = 30,
        attack = "11924",
        boss = 1,
        critical_damage = "21320",
        critical_ratio = "6135.0",
        cure_critical_ratio = "3067.5",
        defense = "1127",
        desc = "LV9BOSS",
        double_attack_suspend = 1,
        id = 611019,
        level = "5",
        maxhp = "145968",
        model_id = 1020,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆破坏者",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 1004}},
        petId = 0,
        res_abnormal_ratio = "8100",
        res_critical_ratio = "0",
        scale = 150,
        show_lv = "100",
        show_skill = {102002, 1004},
        special_skill = {{["pfid"] = 102002, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "1076",
        texture = 11,
        wpmodel = 2100,
    },

    [680171] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50901, ["ratio"] = 1}},
        ai_arg = 50,
        attack = "6132",
        boss = 0,
        critical_damage = "22120.0",
        critical_ratio = "6785",
        cure_critical_ratio = "3392.5",
        defense = "1148.4",
        desc = "LV10小怪",
        double_attack_suspend = 0,
        id = 680171,
        level = "5",
        maxhp = "76424",
        model_id = 509,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 50903}, {["pfid"] = 50904}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "100",
        show_skill = {},
        special_skill = {{["pfid"] = 50902, ["sum_grid"] = 3, ["cur_grid"] = 3}},
        speed = "2036.85",
        texture = 11,
        wpmodel = 2100,
    },

    [680252] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50101, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "6548",
        boss = 0,
        critical_damage = "22120.0",
        critical_ratio = "8481.25",
        cure_critical_ratio = "3392.5",
        defense = "1084.6",
        desc = "LV10小怪",
        double_attack_suspend = 0,
        id = 680252,
        level = "5",
        maxhp = "72402",
        model_id = 501,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 50103}, {["pfid"] = 50104}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "100",
        show_skill = {},
        special_skill = {{["pfid"] = 50102, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "110.1",
        texture = 11,
        wpmodel = 2100,
    },

    [680353] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 40501, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "6191",
        boss = 0,
        critical_damage = "22120.0",
        critical_ratio = "8481.25",
        cure_critical_ratio = "3392.5",
        defense = "1122.88",
        desc = "LV10小怪",
        double_attack_suspend = 0,
        id = 680353,
        level = "5",
        maxhp = "93318",
        model_id = 405,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 40503}, {["pfid"] = 40504}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "100",
        show_skill = {},
        special_skill = {{["pfid"] = 40502, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "1761.6",
        texture = 11,
        wpmodel = 2100,
    },

    [680164] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 40901, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "6370",
        boss = 0,
        critical_damage = "22120.0",
        critical_ratio = "8481.25",
        cure_critical_ratio = "3392.5",
        defense = "1148.4",
        desc = "LV10小怪",
        double_attack_suspend = 0,
        id = 680164,
        level = "5",
        maxhp = "84469",
        model_id = 409,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 40903}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "100",
        show_skill = {},
        special_skill = {{["pfid"] = 40902, ["sum_grid"] = 3, ["cur_grid"] = 3}},
        speed = "385.35",
        texture = 11,
        wpmodel = 2100,
    },

    [680385] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 30301, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "6906",
        boss = 0,
        critical_damage = "22120.0",
        critical_ratio = "10177.5",
        cure_critical_ratio = "3392.5",
        defense = "1020.8",
        desc = "LV10小怪",
        double_attack_suspend = 0,
        id = 680385,
        level = "5",
        maxhp = "64357",
        model_id = 303,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 30303}, {["pfid"] = 30304}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "100",
        show_skill = {},
        special_skill = {{["pfid"] = 30302, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "1706.55",
        texture = 11,
        wpmodel = 2100,
    },

    [680176] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 30201, ["ratio"] = 1}},
        ai_arg = 50,
        attack = "6132",
        boss = 0,
        critical_damage = "22120.0",
        critical_ratio = "6785",
        cure_critical_ratio = "3392.5",
        defense = "1314.28",
        desc = "LV10小怪",
        double_attack_suspend = 0,
        id = 680176,
        level = "5",
        maxhp = "76424",
        model_id = 302,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 30203}, {["pfid"] = 30204}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "100",
        show_skill = {},
        special_skill = {{["pfid"] = 30202, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "715.65",
        texture = 11,
        wpmodel = 2100,
    },

    [680147] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 30501, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "6965",
        boss = 0,
        critical_damage = "22120.0",
        critical_ratio = "8481.25",
        cure_critical_ratio = "3392.5",
        defense = "1084.6",
        desc = "LV10小怪",
        double_attack_suspend = 0,
        id = 680147,
        level = "5",
        maxhp = "74011",
        model_id = 305,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 30503}, {["pfid"] = 30504}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "100",
        show_skill = {},
        special_skill = {{["pfid"] = 30502, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "605.55",
        texture = 11,
        wpmodel = 2100,
    },

    [680218] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50601, ["ratio"] = 1}},
        ai_arg = 10,
        attack = "6429",
        boss = 0,
        critical_damage = "22120.0",
        critical_ratio = "6785",
        cure_critical_ratio = "3392.5",
        defense = "1301.52",
        desc = "LV10小怪",
        double_attack_suspend = 0,
        id = 680218,
        level = "5",
        maxhp = "65966",
        model_id = 506,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆之痕",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 50603}, {["pfid"] = 50604}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "100",
        show_skill = {},
        special_skill = {{["pfid"] = 50602, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "1376.25",
        texture = 11,
        wpmodel = 2100,
    },

    [681019] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 102001, ["ratio"] = 1}},
        ai_arg = 30,
        attack = "13661",
        boss = 1,
        critical_damage = "22120.0",
        critical_ratio = "6785",
        cure_critical_ratio = "3392.5",
        defense = "1276",
        desc = "LV10BOSS",
        double_attack_suspend = 1,
        id = 681019,
        level = "5",
        maxhp = "173362",
        model_id = 1020,
        mutate_color = {},
        mutate_texture = 0,
        name = "记忆破坏者",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 1004}},
        petId = 0,
        res_abnormal_ratio = "9000",
        res_critical_ratio = "0",
        scale = 150,
        show_lv = "100",
        show_skill = {102002, 1004},
        special_skill = {{["pfid"] = 102002, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "1116",
        texture = 11,
        wpmodel = 2100,
    },

}
