-- ./excel/monster/perform_summon.xlsx
return {

    [31502] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 5015, ["ratio"] = 1, ["level"] = 1}},
        attack = "100",
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "315召唤精灵使用",
        double_attack_suspend = 1,
        id = 31502,
        level = "0",
        maxhp = "10000",
        model_id = 317,
        mutate_color = {},
        mutate_texture = 0,
        name = "精灵",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 1007}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        shape_exchange = "{[604]=605,[608]=609}",
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [41602] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 5015, ["ratio"] = 1, ["level"] = 1}},
        attack = "100",
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "416召唤使用",
        double_attack_suspend = 1,
        id = 41602,
        level = "0",
        maxhp = "10000",
        model_id = 419,
        mutate_color = {},
        mutate_texture = 0,
        name = "梦魇",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        shape_exchange = "{[712]=419}",
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

}
