-- ./excel/monster/story.xlsx
return {

    [11001] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 102001, ["ratio"] = 1}},
        attack = "199",
        critical_damage = "15050",
        critical_ratio = "1040",
        cure_critical_ratio = "520",
        defense = "48",
        desc = "任务10001",
        id = 11001,
        level = "LV",
        maxhp = "241",
        model_id = 1020,
        mutate_color = {},
        mutate_texture = 0,
        name = "人族闯入者",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {},
        speed = "754.8",
        texture = 11,
        wpmodel = 2100,
    },

    [11002] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 101501, ["ratio"] = 1}},
        attack = "97",
        critical_damage = "15050",
        critical_ratio = "1040",
        cure_critical_ratio = "520",
        defense = "48",
        desc = "任务10001",
        id = 11002,
        level = "LV",
        maxhp = "344",
        model_id = 1015,
        mutate_color = {},
        mutate_texture = 0,
        name = "人族侵略者",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {},
        speed = "754.8",
        texture = 11,
        wpmodel = 2100,
    },

    [11003] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 102001, ["ratio"] = 1}},
        attack = "116",
        critical_damage = "15100",
        critical_ratio = "1080",
        cure_critical_ratio = "540",
        defense = "56",
        desc = "任务10004",
        id = 11003,
        level = "LV",
        maxhp = "563",
        model_id = 1020,
        mutate_color = {},
        mutate_texture = 0,
        name = "人族入侵者",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 102002, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "759.6",
        texture = 11,
        wpmodel = 2100,
    },

    [11004] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 101101, ["ratio"] = 1}},
        attack = "116",
        critical_damage = "15100",
        critical_ratio = "1080",
        cure_critical_ratio = "540",
        defense = "56",
        desc = "任务10004",
        id = 11004,
        level = "LV",
        maxhp = "563",
        model_id = 1011,
        mutate_color = {},
        mutate_texture = 0,
        name = "使徒",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 101102, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "759.6",
        texture = 11,
        wpmodel = 2100,
    },

    [11005] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 31501, ["ratio"] = 2}},
        attack = "281",
        critical_damage = "15150",
        critical_ratio = "1120",
        cure_critical_ratio = "560",
        defense = "66",
        desc = "任务10007",
        id = 11005,
        level = "LV",
        maxhp = "332",
        model_id = 315,
        mutate_color = {},
        mutate_texture = 0,
        name = "狂沼",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 31502, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "764.4",
        texture = 11,
        wpmodel = 2100,
    },

    [11006] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 102001, ["ratio"] = 1}},
        attack = "136",
        critical_damage = "15150",
        critical_ratio = "1120",
        cure_critical_ratio = "560",
        defense = "66",
        desc = "任务10007",
        id = 11006,
        level = "LV",
        maxhp = "475",
        model_id = 1020,
        mutate_color = {},
        mutate_texture = 0,
        name = "神秘人",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 102002, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "764.4",
        texture = 11,
        wpmodel = 2100,
    },

    [11007] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 115101, ["ratio"] = 2}},
        attack = "156",
        critical_damage = "15200",
        critical_ratio = "1160",
        cure_critical_ratio = "580",
        defense = "75",
        desc = "任务10010",
        id = 11007,
        level = "LV",
        maxhp = "758",
        model_id = 1151,
        mutate_color = {},
        mutate_texture = 0,
        name = "邓酒爷",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 115102, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "769.2",
        texture = 11,
        wpmodel = 2100,
    },

    [11008] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 100701, ["ratio"] = 2}},
        attack = "156",
        critical_damage = "15200",
        critical_ratio = "1160",
        cure_critical_ratio = "580",
        defense = "75",
        desc = "任务10010",
        id = 11008,
        level = "LV",
        maxhp = "758",
        model_id = 1007,
        mutate_color = {},
        mutate_texture = 0,
        name = "跟班",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 100702, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "769.2",
        texture = 11,
        wpmodel = 2100,
    },

    [11009] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 100501, ["ratio"] = 2}},
        attack = "156",
        critical_damage = "15200",
        critical_ratio = "1160",
        cure_critical_ratio = "580",
        defense = "75",
        desc = "任务10010",
        id = 11009,
        level = "LV",
        maxhp = "758",
        model_id = 1005,
        mutate_color = {},
        mutate_texture = 0,
        name = "跟班",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 100502, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "769.2",
        texture = 11,
        wpmodel = 2100,
    },

    [11010] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 100601, ["ratio"] = 2}},
        attack = "316",
        critical_damage = "15250",
        critical_ratio = "0",
        cure_critical_ratio = "600",
        defense = "85",
        desc = "任务10014",
        id = 11010,
        level = "LV",
        maxhp = "2153",
        model_id = 1006,
        mutate_color = {},
        mutate_texture = 0,
        name = "大肉兄",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 100602, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "774",
        texture = 11,
        wpmodel = 2100,
    },

    [11011] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 100501, ["ratio"] = 2}},
        attack = "316",
        critical_damage = "15250",
        critical_ratio = "0",
        cure_critical_ratio = "600",
        defense = "85",
        desc = "任务10014",
        id = 11011,
        level = "LV",
        maxhp = "2153",
        model_id = 1005,
        mutate_color = {},
        mutate_texture = 0,
        name = "咸鱼兄",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 100502, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "774",
        texture = 11,
        wpmodel = 2100,
    },

    [11012] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 100701, ["ratio"] = 2}},
        attack = "316",
        critical_damage = "15250",
        critical_ratio = "0",
        cure_critical_ratio = "600",
        defense = "85",
        desc = "任务10014",
        id = 11012,
        level = "LV",
        maxhp = "2153",
        model_id = 1007,
        mutate_color = {},
        mutate_texture = 0,
        name = "锅铲兄",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {},
        speed = "774",
        texture = 11,
        wpmodel = 2100,
    },

    [11013] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 115001, ["ratio"] = 2}},
        attack = "369",
        critical_damage = "15250",
        critical_ratio = "0",
        cure_critical_ratio = "600",
        defense = "85",
        desc = "任务10016",
        id = 11013,
        level = "LV",
        maxhp = "2368",
        model_id = 1150,
        mutate_color = {},
        mutate_texture = 0,
        name = "飞龙哥",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 115002, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "608.75",
        texture = 11,
        wpmodel = 2100,
    },

    [11014] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41301, ["ratio"] = 2}},
        attack = "247",
        critical_damage = "15250",
        critical_ratio = "0",
        cure_critical_ratio = "600",
        defense = "85",
        desc = "任务10016",
        id = 11014,
        level = "LV",
        maxhp = "1077",
        model_id = 413,
        mutate_color = {},
        mutate_texture = 0,
        name = "古娄",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 41302, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "608.75",
        texture = 11,
        wpmodel = 2100,
    },

    [11015] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41701, ["ratio"] = 2}},
        attack = "247",
        critical_damage = "15250",
        critical_ratio = "0",
        cure_critical_ratio = "600",
        defense = "85",
        desc = "任务10016",
        id = 11015,
        level = "LV",
        maxhp = "1077",
        model_id = 417,
        mutate_color = {},
        mutate_texture = 0,
        name = "松姑子",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 41702, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "608.75",
        texture = 11,
        wpmodel = 2100,
    },

    [11016] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 30201, ["ratio"] = 2}},
        attack = "424",
        critical_damage = "15300",
        critical_ratio = "0",
        cure_critical_ratio = "620",
        defense = "95",
        desc = "任务10017",
        id = 11016,
        level = "LV",
        maxhp = "2702",
        model_id = 302,
        mutate_color = {},
        mutate_texture = 0,
        name = "重华",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 30202, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "612.5",
        texture = 11,
        wpmodel = 2100,
    },

    [11017] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41001, ["ratio"] = 2}},
        attack = "282",
        critical_damage = "15300",
        critical_ratio = "0",
        cure_critical_ratio = "620",
        defense = "95",
        desc = "任务10017",
        id = 11017,
        level = "LV",
        maxhp = "1255",
        model_id = 410,
        mutate_color = {},
        mutate_texture = 0,
        name = "青竹",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 41002, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "612.5",
        texture = 11,
        wpmodel = 2100,
    },

    [11018] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41201, ["ratio"] = 2}},
        attack = "282",
        critical_damage = "15300",
        critical_ratio = "0",
        cure_critical_ratio = "620",
        defense = "95",
        desc = "任务10017",
        id = 11018,
        level = "LV",
        maxhp = "1255",
        model_id = 412,
        mutate_color = {},
        mutate_texture = 0,
        name = "执夷",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 41202, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "612.5",
        texture = 11,
        wpmodel = 2100,
    },

    [11019] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 100601, ["ratio"] = 2}},
        attack = "645",
        critical_damage = "15500",
        critical_ratio = "0",
        cure_critical_ratio = "700",
        defense = "138",
        desc = "任务10032",
        id = 11019,
        level = "LV",
        maxhp = "4040",
        model_id = 1006,
        mutate_color = {},
        mutate_texture = 0,
        name = "护卫队队长",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 100602, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "627.5",
        texture = 11,
        wpmodel = 2100,
    },

    [11020] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50701, ["ratio"] = 2}},
        attack = "425",
        critical_damage = "15500",
        critical_ratio = "0",
        cure_critical_ratio = "700",
        defense = "138",
        desc = "任务10032",
        id = 11020,
        level = "LV",
        maxhp = "1913",
        model_id = 507,
        mutate_color = {},
        mutate_texture = 0,
        name = "护卫队成员",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 50702, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "627.5",
        texture = 11,
        wpmodel = 2100,
    },

    [11021] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 51301, ["ratio"] = 2}},
        attack = "425",
        critical_damage = "15500",
        critical_ratio = "0",
        cure_critical_ratio = "700",
        defense = "138",
        desc = "任务10032",
        id = 11021,
        level = "LV",
        maxhp = "1913",
        model_id = 513,
        mutate_color = {},
        mutate_texture = 0,
        name = "护卫队成员",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 51302, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "627.5",
        texture = 11,
        wpmodel = 2100,
    },

    [11022] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 160001, ["ratio"] = 2}},
        attack = "470",
        critical_damage = "15550",
        critical_ratio = "0",
        cure_critical_ratio = "720",
        defense = "149",
        desc = "任务10034",
        id = 11022,
        level = "LV",
        maxhp = "2916",
        model_id = 1600,
        mutate_color = {},
        mutate_texture = 0,
        name = "熊霸",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 160002, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "631.25",
        texture = 11,
        wpmodel = 2100,
    },

    [11023] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 101801, ["ratio"] = 2}},
        attack = "470",
        critical_damage = "15550",
        critical_ratio = "0",
        cure_critical_ratio = "720",
        defense = "149",
        desc = "任务10034",
        id = 11023,
        level = "LV",
        maxhp = "2916",
        model_id = 1018,
        mutate_color = {},
        mutate_texture = 0,
        name = "甘",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 101802, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "631.25",
        texture = 11,
        wpmodel = 2100,
    },

    [11024] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 100901, ["ratio"] = 2}},
        attack = "470",
        critical_damage = "15550",
        critical_ratio = "0",
        cure_critical_ratio = "720",
        defense = "149",
        desc = "任务10034",
        id = 11024,
        level = "LV",
        maxhp = "2916",
        model_id = 1009,
        mutate_color = {},
        mutate_texture = 0,
        name = "神父",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 100902, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "631.25",
        texture = 11,
        wpmodel = 2100,
    },

    [11025] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41801, ["ratio"] = 2}},
        attack = "891",
        critical_damage = "15650",
        critical_ratio = "0",
        cure_critical_ratio = "760",
        defense = "173",
        desc = "任务10041",
        id = 11025,
        level = "LV",
        maxhp = "5288",
        model_id = 418,
        mutate_color = {},
        mutate_texture = 0,
        name = "疯狂的妖怪",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 41802, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 3}},
        speed = "638.75",
        texture = 11,
        wpmodel = 2100,
    },

    [11026] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41301, ["ratio"] = 2}},
        attack = "560",
        critical_damage = "15650",
        critical_ratio = "0",
        cure_critical_ratio = "760",
        defense = "173",
        desc = "任务10041",
        id = 11026,
        level = "LV",
        maxhp = "2599",
        model_id = 413,
        mutate_color = {},
        mutate_texture = 0,
        name = "癫狂的妖怪",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 41302, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "638.75",
        texture = 11,
        wpmodel = 2100,
    },

    [11027] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 110001, ["ratio"] = 2}},
        attack = "857",
        critical_damage = "15700",
        critical_ratio = "1560",
        cure_critical_ratio = "780",
        defense = "186",
        desc = "任务10044",
        id = 11027,
        level = "LV",
        maxhp = "5507",
        model_id = 1100,
        mutate_color = {},
        mutate_texture = 0,
        name = "邪靡",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 110002, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "642.5",
        texture = 11,
        wpmodel = 2100,
    },

    [11028] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 100401, ["ratio"] = 2}},
        attack = "451",
        critical_damage = "15700",
        critical_ratio = "0",
        cure_critical_ratio = "780",
        defense = "186",
        desc = "任务10044",
        id = 11028,
        level = "LV",
        maxhp = "1740",
        model_id = 1004,
        mutate_color = {},
        mutate_texture = 0,
        name = "癫狂的妖怪",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {},
        speed = "642.5",
        texture = 11,
        wpmodel = 2100,
    },

    [11029] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 30601, ["ratio"] = 2}},
        attack = "1696.8",
        critical_damage = "15800",
        critical_ratio = "2050",
        cure_critical_ratio = "820",
        defense = "173.02",
        desc = "任务10047",
        id = 11029,
        level = "LV",
        maxhp = "14633",
        model_id = 306,
        mutate_color = {},
        mutate_texture = 0,
        name = "袁雀",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 30602, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "555",
        texture = 11,
        wpmodel = 2100,
    },

    [11030] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 165001, ["ratio"] = 2}},
        attack = "1441",
        critical_damage = "15800",
        critical_ratio = "1640",
        cure_critical_ratio = "820",
        defense = "211",
        desc = "任务10047",
        id = 11030,
        level = "LV",
        maxhp = "14633",
        model_id = 1650,
        mutate_color = {},
        mutate_texture = 0,
        name = "丑无",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 165002, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "695",
        texture = 11,
        wpmodel = 2100,
    },

    [11031] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 175101, ["ratio"] = 2}},
        attack = "1825",
        critical_damage = "16000",
        critical_ratio = "1800",
        cure_critical_ratio = "900",
        defense = "266",
        desc = "任务10056",
        id = 11031,
        level = "LV",
        maxhp = "17442",
        model_id = 1751,
        mutate_color = {},
        mutate_texture = 0,
        name = "猫蜀黍",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 175102, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "710",
        texture = 11,
        wpmodel = 2100,
    },

    [11032] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 175201, ["ratio"] = 2}},
        attack = "1825",
        critical_damage = "16000",
        critical_ratio = "1800",
        cure_critical_ratio = "900",
        defense = "266",
        desc = "任务10056",
        id = 11032,
        level = "LV",
        maxhp = "17442",
        model_id = 1752,
        mutate_color = {},
        mutate_texture = 0,
        name = "喵小萌",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 175202, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "710",
        texture = 11,
        wpmodel = 2100,
    },

    [11033] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 175301, ["ratio"] = 1}},
        attack = "1314",
        critical_damage = "16000",
        critical_ratio = "1800",
        cure_critical_ratio = "900",
        defense = "266",
        desc = "任务10056",
        id = 11033,
        level = "LV",
        maxhp = "9967",
        model_id = 1753,
        mutate_color = {},
        mutate_texture = 0,
        name = "豆沙包",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {},
        speed = "710",
        texture = 11,
        wpmodel = 2100,
    },

    [11034] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 175501, ["ratio"] = 1}},
        attack = "1314",
        critical_damage = "16000",
        critical_ratio = "1800",
        cure_critical_ratio = "900",
        defense = "266",
        desc = "任务10056",
        id = 11034,
        level = "LV",
        maxhp = "9967",
        model_id = 1755,
        mutate_color = {},
        mutate_texture = 0,
        name = "焦糖包子",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {},
        speed = "710",
        texture = 11,
        wpmodel = 2100,
    },

    [11035] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 100401, ["ratio"] = 2}},
        attack = "1465",
        critical_damage = "16100",
        critical_ratio = "1880",
        cure_critical_ratio = "940",
        defense = "294",
        desc = "任务10065",
        id = 11035,
        level = "LV",
        maxhp = "11091",
        model_id = 1004,
        mutate_color = {},
        mutate_texture = 0,
        name = "癫狂的妖怪",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 100402, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "717.5",
        texture = 11,
        wpmodel = 2100,
    },

    [11036] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 30301, ["ratio"] = 2}},
        attack = "2038",
        critical_damage = "16100",
        critical_ratio = "1880",
        cure_critical_ratio = "940",
        defense = "294",
        desc = "任务10065",
        id = 11036,
        level = "LV",
        maxhp = "19408",
        model_id = 303,
        mutate_color = {},
        mutate_texture = 0,
        name = "朵屠",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 30302, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "717.5",
        texture = 11,
        wpmodel = 2100,
    },

    [11037] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 100401, ["ratio"] = 2}},
        attack = "1465",
        critical_damage = "16100",
        critical_ratio = "1880",
        cure_critical_ratio = "940",
        defense = "294",
        desc = "任务10065",
        id = 11037,
        level = "LV",
        maxhp = "11091",
        model_id = 1004,
        mutate_color = {},
        mutate_texture = 0,
        name = "疯狂的妖怪",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 100402, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "717.5",
        texture = 11,
        wpmodel = 2100,
    },

    [11038] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 40401, ["ratio"] = 2}},
        attack = "1623",
        critical_damage = "16200",
        critical_ratio = "1960",
        cure_critical_ratio = "980",
        defense = "324",
        desc = "任务10067",
        id = 11038,
        level = "LV",
        maxhp = "12308",
        model_id = 404,
        mutate_color = {},
        mutate_texture = 0,
        name = "绿狸",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {},
        speed = "725",
        texture = 11,
        wpmodel = 2100,
    },

    [11039] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 40501, ["ratio"] = 2}},
        attack = "2263",
        critical_damage = "16200",
        critical_ratio = "1960",
        cure_critical_ratio = "980",
        defense = "324",
        desc = "任务10067",
        id = 11039,
        level = "LV",
        maxhp = "21537",
        model_id = 405,
        mutate_color = {},
        mutate_texture = 0,
        name = "莹月",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 40502, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "725",
        texture = 11,
        wpmodel = 2100,
    },

    [11040] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 40401, ["ratio"] = 2}},
        attack = "1623",
        critical_damage = "16200",
        critical_ratio = "1960",
        cure_critical_ratio = "980",
        defense = "324",
        desc = "任务10067",
        id = 11040,
        level = "LV",
        maxhp = "12308",
        model_id = 1506,
        mutate_color = {},
        mutate_texture = 0,
        name = "小狸猫",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {},
        speed = "725",
        texture = 11,
        wpmodel = 2100,
    },

    [11041] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 100201, ["ratio"] = 2}},
        attack = "1786",
        critical_damage = "16300",
        critical_ratio = "2040",
        cure_critical_ratio = "1020",
        defense = "354",
        desc = "任务10069",
        id = 11041,
        level = "LV",
        maxhp = "16929",
        model_id = 1002,
        mutate_color = {},
        mutate_texture = 0,
        name = "人类幽灵",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 100202, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "732.5",
        texture = 11,
        wpmodel = 2100,
    },

    [11042] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 100201, ["ratio"] = 2}},
        attack = "1786",
        critical_damage = "16300",
        critical_ratio = "2040",
        cure_critical_ratio = "1020",
        defense = "354",
        desc = "任务10069",
        id = 11042,
        level = "LV",
        maxhp = "16929",
        model_id = 1002,
        mutate_color = {},
        mutate_texture = 0,
        name = "妖怪幽灵",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 100202, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "732.5",
        texture = 11,
        wpmodel = 2100,
    },

    [11043] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 100201, ["ratio"] = 2}},
        attack = "1786",
        critical_damage = "16300",
        critical_ratio = "2040",
        cure_critical_ratio = "1020",
        defense = "354",
        desc = "任务10069",
        id = 11043,
        level = "LV",
        maxhp = "16929",
        model_id = 1300,
        mutate_color = {},
        mutate_texture = 0,
        name = "玉藏",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {},
        speed = "732.5",
        texture = 11,
        wpmodel = 2100,
    },

    [11044] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50101, ["ratio"] = 2}},
        attack = "3245",
        critical_damage = "16600",
        critical_ratio = "2280",
        cure_critical_ratio = "1140",
        defense = "451",
        desc = "任务10074",
        id = 11044,
        level = "LV",
        maxhp = "33087",
        model_id = 501,
        mutate_color = {},
        mutate_texture = 0,
        name = "阿坊",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 50102, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "755",
        texture = 11,
        wpmodel = 2100,
    },

    [11045] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50201, ["ratio"] = 2}},
        attack = "3245",
        critical_damage = "16600",
        critical_ratio = "2280",
        cure_critical_ratio = "1140",
        defense = "451",
        desc = "任务10074",
        id = 11045,
        level = "LV",
        maxhp = "33087",
        model_id = 502,
        mutate_color = {},
        mutate_texture = 0,
        name = "马面面",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 50202, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "755",
        texture = 11,
        wpmodel = 2100,
    },

    [11046] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 160001, ["ratio"] = 2}},
        attack = "2309",
        critical_damage = "16900",
        critical_ratio = "2520",
        cure_critical_ratio = "1260",
        defense = "554",
        desc = "任务10086",
        id = 11046,
        level = "LV",
        maxhp = "20814",
        model_id = 1600,
        mutate_color = {},
        mutate_texture = 0,
        name = "改造人",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 160002, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "777.5",
        texture = 11,
        wpmodel = 2100,
    },

    [11047] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 100401, ["ratio"] = 2}},
        attack = "2309",
        critical_damage = "16900",
        critical_ratio = "2520",
        cure_critical_ratio = "1260",
        defense = "554",
        desc = "任务10086",
        id = 11047,
        level = "LV",
        maxhp = "20814",
        model_id = 1004,
        mutate_color = {},
        mutate_texture = 0,
        name = "改造人",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 100402, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "777.5",
        texture = 11,
        wpmodel = 2100,
    },

    [11048] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 31401, ["ratio"] = 2}},
        attack = "3099",
        critical_damage = "17000",
        critical_ratio = "2600",
        cure_critical_ratio = "1300",
        defense = "590",
        desc = "任务10091",
        id = 11048,
        level = "LV",
        maxhp = "23841",
        model_id = 314,
        mutate_color = {},
        mutate_texture = 0,
        name = "执阳",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 31402, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "785",
        texture = 11,
        wpmodel = 2100,
    },

    [11049] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 170001, ["ratio"] = 2}},
        attack = "4411",
        critical_damage = "17000",
        critical_ratio = "2600",
        cure_critical_ratio = "1300",
        defense = "590",
        desc = "任务10091",
        id = 11049,
        level = "LV",
        maxhp = "41723",
        model_id = 1700,
        mutate_color = {},
        mutate_texture = 0,
        name = "熊猫爷爷",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 170002, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "785",
        texture = 11,
        wpmodel = 2100,
    },

    [11050] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 40201, ["ratio"] = 2}},
        attack = "3525",
        critical_damage = "17200",
        critical_ratio = "2760",
        cure_critical_ratio = "1380",
        defense = "663",
        desc = "任务10097",
        id = 11050,
        level = "LV",
        maxhp = "34065",
        model_id = 402,
        mutate_color = {},
        mutate_texture = 0,
        name = "稻荷",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 40202, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "800",
        texture = 11,
        wpmodel = 2100,
    },

    [11051] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41001, ["ratio"] = 2}},
        attack = "3525",
        critical_damage = "17200",
        critical_ratio = "2760",
        cure_critical_ratio = "1380",
        defense = "663",
        desc = "任务10097",
        id = 11051,
        level = "LV",
        maxhp = "34065",
        model_id = 410,
        mutate_color = {},
        mutate_texture = 0,
        name = "青竹",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 41002, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "800",
        texture = 11,
        wpmodel = 2100,
    },

    [11052] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41201, ["ratio"] = 2}},
        attack = "3525",
        critical_damage = "17200",
        critical_ratio = "2760",
        cure_critical_ratio = "1380",
        defense = "663",
        desc = "任务10097",
        id = 11052,
        level = "LV",
        maxhp = "34065",
        model_id = 412,
        mutate_color = {},
        mutate_texture = 0,
        name = "执夷",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 41202, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "800",
        texture = 11,
        wpmodel = 2100,
    },

    [11053] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 120101, ["ratio"] = 2}},
        attack = "3163",
        critical_damage = "17400",
        critical_ratio = "2920",
        cure_critical_ratio = "1460",
        defense = "738",
        desc = "任务10100",
        id = 11053,
        level = "LV",
        maxhp = "28944",
        model_id = 1201,
        mutate_color = {},
        mutate_texture = 0,
        name = "绯翼",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 120102, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "815",
        texture = 11,
        wpmodel = 2100,
    },

    [11054] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 120001, ["ratio"] = 2}},
        attack = "3163",
        critical_damage = "17400",
        critical_ratio = "2920",
        cure_critical_ratio = "1460",
        defense = "738",
        desc = "任务10100",
        id = 11054,
        level = "LV",
        maxhp = "28944",
        model_id = 1200,
        mutate_color = {},
        mutate_texture = 0,
        name = "青翼",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {{["pfid"] = 120002, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 2}},
        speed = "815",
        texture = 11,
        wpmodel = 2100,
    },

    [11055] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 40401, ["ratio"] = 2}},
        attack = "3163",
        critical_damage = "17400",
        critical_ratio = "2920",
        cure_critical_ratio = "1460",
        defense = "738",
        desc = "任务10100",
        id = 11055,
        level = "LV",
        maxhp = "28944",
        model_id = 1506,
        mutate_color = {},
        mutate_texture = 0,
        name = "小狸猫",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {},
        speed = "815",
        texture = 11,
        wpmodel = 2100,
    },

    [11056] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 40401, ["ratio"] = 2}},
        attack = "3163",
        critical_damage = "17400",
        critical_ratio = "2920",
        cure_critical_ratio = "1460",
        defense = "738",
        desc = "任务10100",
        id = 11056,
        level = "LV",
        maxhp = "28944",
        model_id = 1506,
        mutate_color = {},
        mutate_texture = 0,
        name = "小狸猫",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        special_skill = {},
        speed = "815",
        texture = 11,
        wpmodel = 2100,
    },

}
