-- ./excel/monster/test.xlsx
return {

    [10001] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3001, ["ratio"] = 1, ["level"] = 2}, {["pfid"] = 3002, ["ratio"] = 1, ["level"] = 2}, {["pfid"] = 3003, ["ratio"] = 1, ["level"] = 2}, {["pfid"] = 3004, ["ratio"] = 1, ["level"] = 2}},
        ai_arg = 0,
        attack = "100",
        boss = 1,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "测试NPC1",
        double_attack_suspend = 1,
        id = 10001,
        level = "LV",
        maxhp = "10000",
        model_id = 140,
        mutate_color = {},
        mutate_texture = 0,
        name = "豆豆1",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 3006}, {["pfid"] = 3007}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "1231",
        special_skill = {{["pfid"] = 3005, ["level"] = 2, ["sum_grid"] = 5, ["cur_grid"] = 1}},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [10002] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3101, ["ratio"] = 1}, {["pfid"] = 3102, ["ratio"] = 1}, {["pfid"] = 3103, ["ratio"] = 1}, {["pfid"] = 3104, ["ratio"] = 1}, {["pfid"] = 3105, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "1000",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "测试NPC2",
        double_attack_suspend = 1,
        id = 10002,
        level = "LV",
        maxhp = "10000",
        model_id = 140,
        mutate_color = {},
        mutate_texture = 0,
        name = "豆豆2",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 3106}, {["pfid"] = 3107}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "1",
        special_skill = {{["pfid"] = 3105, ["sum_grid"] = 5, ["cur_grid"] = 1}},
        speed = "300",
        texture = 11,
        wpmodel = 2100,
    },

    [10003] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3201, ["ratio"] = 1}, {["pfid"] = 3202, ["ratio"] = 1}, {["pfid"] = 3203, ["ratio"] = 1}, {["pfid"] = 3204, ["ratio"] = 1}, {["pfid"] = 3205, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "测试NPC3",
        double_attack_suspend = 1,
        id = 10003,
        level = "LV",
        maxhp = "10000",
        model_id = 140,
        mutate_color = {},
        mutate_texture = 0,
        name = "豆豆3",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 3206}, {["pfid"] = 3207}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "1",
        special_skill = {{["pfid"] = 3205, ["sum_grid"] = 5, ["cur_grid"] = 1}},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [10004] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3301, ["ratio"] = 1}, {["pfid"] = 3302, ["ratio"] = 1}, {["pfid"] = 3303, ["ratio"] = 1}, {["pfid"] = 3304, ["ratio"] = 1}, {["pfid"] = 3305, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "测试NPC4",
        double_attack_suspend = 1,
        id = 10004,
        level = "LV",
        maxhp = "500",
        model_id = 140,
        mutate_color = {},
        mutate_texture = 0,
        name = "豆豆4",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 3306}, {["pfid"] = 3307}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "13",
        special_skill = {{["pfid"] = 3305, ["sum_grid"] = 5, ["cur_grid"] = 1}},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [10005] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3401, ["ratio"] = 1}, {["pfid"] = 3402, ["ratio"] = 1}, {["pfid"] = 3403, ["ratio"] = 1}, {["pfid"] = 3404, ["ratio"] = 1}, {["pfid"] = 3405, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "测试NPC5",
        double_attack_suspend = 1,
        id = 10005,
        level = "LV",
        maxhp = "500",
        model_id = 140,
        mutate_color = {},
        mutate_texture = 0,
        name = "豆豆5",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 3406}, {["pfid"] = 3407}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "1",
        special_skill = {{["pfid"] = 3405, ["sum_grid"] = 5, ["cur_grid"] = 1}},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [10006] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3501, ["ratio"] = 1}, {["pfid"] = 3502, ["ratio"] = 1}, {["pfid"] = 3503, ["ratio"] = 1}, {["pfid"] = 3504, ["ratio"] = 1}, {["pfid"] = 3505, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "测试NPC6",
        double_attack_suspend = 1,
        id = 10006,
        level = "LV",
        maxhp = "500",
        model_id = 140,
        mutate_color = {},
        mutate_texture = 0,
        name = "豆豆6",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 3506}, {["pfid"] = 3507}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "1",
        special_skill = {{["pfid"] = 3505, ["sum_grid"] = 5, ["cur_grid"] = 1}},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [10007] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 30501, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "50",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "20180331备注",
        double_attack_suspend = 1,
        id = 10007,
        level = "LV",
        maxhp = "5000",
        model_id = 305,
        mutate_color = {},
        mutate_texture = 0,
        name = "这里的怪物不忧伤",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "5",
        special_skill = {{["pfid"] = 30501, ["sum_grid"] = 4, ["cur_grid"] = 2}},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [10008] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 30101, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "150",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "有个大怪物bs备注",
        double_attack_suspend = 1,
        id = 10008,
        level = "LV",
        maxhp = "20000",
        model_id = 301,
        mutate_color = {},
        mutate_texture = 0,
        name = "悦涌bs你够胆",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "25",
        special_skill = {{["pfid"] = 30101, ["sum_grid"] = 4, ["cur_grid"] = 2}},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [10009] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 30201, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "小小小兵备注",
        double_attack_suspend = 1,
        id = 10009,
        level = "LV",
        maxhp = "10000",
        model_id = 302,
        mutate_color = {},
        mutate_texture = 0,
        name = "悦涌小兵别想逃跑",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "10",
        special_skill = {{["pfid"] = 30201, ["sum_grid"] = 4, ["cur_grid"] = 2}},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [11004] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "2104技能",
        double_attack_suspend = 1,
        id = 11004,
        level = "LV",
        maxhp = "5000",
        model_id = 140,
        mutate_color = {},
        mutate_texture = 0,
        name = "2104技能",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "1",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [11005] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "2105技能",
        double_attack_suspend = 1,
        id = 11005,
        level = "LV",
        maxhp = "50000",
        model_id = 140,
        mutate_color = {},
        mutate_texture = 0,
        name = "2105技能",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "1",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [11006] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "2106技能",
        double_attack_suspend = 1,
        id = 11006,
        level = "LV",
        maxhp = "50000",
        model_id = 140,
        mutate_color = {},
        mutate_texture = 0,
        name = "2106技能",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "1",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [11007] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "5000",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "张闯3003技能",
        double_attack_suspend = 1,
        id = 11007,
        level = "LV",
        maxhp = "5000",
        model_id = 140,
        mutate_color = {},
        mutate_texture = 0,
        name = "测试3003",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 3006}, {["pfid"] = 3007}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "2",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [11008] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "5000",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "高攻怪",
        double_attack_suspend = 1,
        id = 11008,
        level = "LV",
        maxhp = "500000",
        model_id = 140,
        mutate_color = {},
        mutate_texture = 0,
        name = "测试",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "2",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [11009] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "高血低攻",
        double_attack_suspend = 1,
        id = 11009,
        level = "LV",
        maxhp = "1000000",
        model_id = 140,
        mutate_color = {},
        mutate_texture = 0,
        name = "测试",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "2",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [11010] = {
        abnormal_attr_ratio = "10000",
        activeSkills = {{["pfid"] = 3201, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "高血低防",
        double_attack_suspend = 1,
        id = 11010,
        level = "LV",
        maxhp = "1000000",
        model_id = 140,
        mutate_color = {},
        mutate_texture = 0,
        name = "测试",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "1",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [11011] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "5000",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "高血低防2",
        double_attack_suspend = 1,
        id = 11011,
        level = "LV",
        maxhp = "20000",
        model_id = 140,
        mutate_color = {},
        mutate_texture = 0,
        name = "测试",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "2",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [11012] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3502, ["ratio"] = 1}, {["pfid"] = 3504, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "5000",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "加血怪",
        double_attack_suspend = 1,
        id = 11012,
        level = "LV",
        maxhp = "200000",
        model_id = 140,
        mutate_color = {},
        mutate_texture = 0,
        name = "测试",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "2",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [11013] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3204, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "减速怪",
        double_attack_suspend = 1,
        id = 11013,
        level = "LV",
        maxhp = "200000",
        model_id = 140,
        mutate_color = {},
        mutate_texture = 0,
        name = "测试",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "2",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [11014] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "诅咒怪",
        double_attack_suspend = 1,
        id = 11014,
        level = "LV",
        maxhp = "200000",
        model_id = 140,
        mutate_color = {},
        mutate_texture = 0,
        name = "测试",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 3507}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "2",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [11015] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3302, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "点控怪",
        double_attack_suspend = 1,
        id = 11015,
        level = "LV",
        maxhp = "200000",
        model_id = 140,
        mutate_color = {},
        mutate_texture = 0,
        name = "测试",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "2",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [11016] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "1000",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "测伙伴1",
        double_attack_suspend = 1,
        id = 11016,
        level = "LV",
        maxhp = "200000",
        model_id = 140,
        mutate_color = {},
        mutate_texture = 0,
        name = "测伙伴1",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "2",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [11017] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100000",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "测伙伴2",
        double_attack_suspend = 1,
        id = 11017,
        level = "LV",
        maxhp = "200000",
        model_id = 140,
        mutate_color = {},
        mutate_texture = 0,
        name = "测伙伴2",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "2",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [11018] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100000",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "1800",
        desc = "高速高攻怪",
        double_attack_suspend = 1,
        id = 11018,
        level = "LV",
        maxhp = "200000",
        model_id = 140,
        mutate_color = {},
        mutate_texture = 0,
        name = "高速高攻",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "2",
        special_skill = {},
        speed = "1800",
        texture = 11,
        wpmodel = 2100,
    },

    [11019] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3301, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "1000",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "1800",
        desc = "高速低功怪",
        double_attack_suspend = 1,
        id = 11019,
        level = "LV",
        maxhp = "200000",
        model_id = 140,
        mutate_color = {},
        mutate_texture = 0,
        name = "高速低功",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "1",
        special_skill = {},
        speed = "1800",
        texture = 11,
        wpmodel = 2100,
    },

    [11020] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 110001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "235",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "150",
        desc = "演示用怪物",
        double_attack_suspend = 1,
        id = 11020,
        level = "LV",
        maxhp = "2000",
        model_id = 1100,
        mutate_color = {},
        mutate_texture = 0,
        name = "演示用怪物",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "2",
        special_skill = {},
        speed = "1000",
        texture = 11,
        wpmodel = 2100,
    },

    [11021] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 110001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "230",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "150",
        desc = "演示用怪物",
        double_attack_suspend = 1,
        id = 11021,
        level = "LV",
        maxhp = "2000",
        model_id = 1100,
        mutate_color = {},
        mutate_texture = 0,
        name = "演示用怪物",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "1",
        special_skill = {},
        speed = "975",
        texture = 11,
        wpmodel = 2100,
    },

    [11022] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 110001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "225",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "150",
        desc = "演示用怪物",
        double_attack_suspend = 1,
        id = 11022,
        level = "LV",
        maxhp = "2000",
        model_id = 1100,
        mutate_color = {},
        mutate_texture = 0,
        name = "演示用怪物",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "950",
        texture = 11,
        wpmodel = 2100,
    },

    [11023] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 110001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "220",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "150",
        desc = "演示用怪物",
        double_attack_suspend = 1,
        id = 11023,
        level = "LV",
        maxhp = "2000",
        model_id = 1100,
        mutate_color = {},
        mutate_texture = 0,
        name = "演示用怪物",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "925",
        texture = 11,
        wpmodel = 2100,
    },

    [11024] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 110001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "250",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "150",
        desc = "演示用怪物",
        double_attack_suspend = 1,
        id = 11024,
        level = "LV",
        maxhp = "2000",
        model_id = 1100,
        mutate_color = {},
        mutate_texture = 0,
        name = "演示用男主角",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 2,
        show_lv = "2",
        special_skill = {},
        speed = "1025",
        texture = 11,
        wpmodel = 2000,
    },

    [11025] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 110001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "250",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "150",
        desc = "演示用怪物",
        double_attack_suspend = 1,
        id = 11025,
        level = "LV",
        maxhp = "2000",
        model_id = 1100,
        mutate_color = {},
        mutate_texture = 0,
        name = "演示用女主角",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 2,
        show_lv = "",
        special_skill = {},
        speed = "1025",
        texture = 11,
        wpmodel = 2100,
    },

    [11026] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 110001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "1000",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "1800",
        desc = "演示用怪物",
        double_attack_suspend = 1,
        id = 11026,
        level = "LV",
        maxhp = "2000",
        model_id = 1100,
        mutate_color = {},
        mutate_texture = 0,
        name = "演示用怪物",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "1800",
        texture = 11,
        wpmodel = 2100,
    },

    [11027] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 110001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "1000",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "1800",
        desc = "演示用怪物",
        double_attack_suspend = 1,
        id = 11027,
        level = "LV",
        maxhp = "2000",
        model_id = 1100,
        mutate_color = {},
        mutate_texture = 0,
        name = "演示用怪物",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "1800",
        texture = 11,
        wpmodel = 2100,
    },

    [11028] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 30101, ["ratio"] = 1}, {["pfid"] = 30102, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "50",
        boss = 0,
        critical_damage = "100",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "敌人",
        double_attack_suspend = 1,
        id = 11028,
        level = "LV",
        maxhp = "100",
        model_id = 301,
        mutate_color = {},
        mutate_texture = 0,
        name = "任务怪物",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "2",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [11029] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 30201, ["ratio"] = 1}, {["pfid"] = 30202, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "50",
        boss = 0,
        critical_damage = "100",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "敌人帮手",
        double_attack_suspend = 1,
        id = 11029,
        level = "LV",
        maxhp = "100",
        model_id = 302,
        mutate_color = {},
        mutate_texture = 0,
        name = "任务怪物",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [11030] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50701, ["ratio"] = 1}, {["pfid"] = 50702, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "50",
        boss = 0,
        critical_damage = "100",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "敌人手下",
        double_attack_suspend = 1,
        id = 11030,
        level = "LV",
        maxhp = "100",
        model_id = 507,
        mutate_color = {},
        mutate_texture = 0,
        name = "任务怪物",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [11031] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 40101, ["ratio"] = 1}, {["pfid"] = 40102, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "50",
        boss = 0,
        critical_damage = "100",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "敌人打手",
        double_attack_suspend = 1,
        id = 11031,
        level = "LV",
        maxhp = "100",
        model_id = 401,
        mutate_color = {},
        mutate_texture = 0,
        name = "任务怪物",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [12001] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 160001, ["ratio"] = 1}, {["pfid"] = 160002, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "500",
        boss = 0,
        critical_damage = "100",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "敌人打手",
        double_attack_suspend = 1,
        id = 12001,
        level = "LV",
        maxhp = "10000",
        model_id = 401,
        mutate_color = {},
        mutate_texture = 0,
        name = "任务怪物",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "2",
        special_skill = {{["pfid"] = 160002, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [12002] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 175201, ["ratio"] = 1}, {["pfid"] = 175202, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "500",
        boss = 0,
        critical_damage = "100",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "敌人打手",
        double_attack_suspend = 1,
        id = 12002,
        level = "LV",
        maxhp = "10000",
        model_id = 401,
        mutate_color = {},
        mutate_texture = 0,
        name = "任务怪物",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 175202, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [12003] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 150101, ["ratio"] = 1}, {["pfid"] = 150102, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "500",
        boss = 0,
        critical_damage = "100",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "敌人打手",
        double_attack_suspend = 1,
        id = 12003,
        level = "LV",
        maxhp = "10000",
        model_id = 401,
        mutate_color = {},
        mutate_texture = 0,
        name = "任务怪物",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 150102, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [12004] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 175101, ["ratio"] = 1}, {["pfid"] = 175102, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "500",
        boss = 0,
        critical_damage = "100",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "敌人打手",
        double_attack_suspend = 1,
        id = 12004,
        level = "LV",
        maxhp = "10000",
        model_id = 401,
        mutate_color = {},
        mutate_texture = 0,
        name = "任务怪物",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 175102, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [12005] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 170001, ["ratio"] = 1}, {["pfid"] = 170002, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "500",
        boss = 0,
        critical_damage = "100",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "敌人打手",
        double_attack_suspend = 1,
        id = 12005,
        level = "LV",
        maxhp = "10000",
        model_id = 401,
        mutate_color = {},
        mutate_texture = 0,
        name = "任务怪物",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 170002, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [12006] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 100201, ["ratio"] = 1}, {["pfid"] = 100202, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "500",
        boss = 0,
        critical_damage = "100",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "敌人打手",
        double_attack_suspend = 1,
        id = 12006,
        level = "LV",
        maxhp = "10000",
        model_id = 401,
        mutate_color = {},
        mutate_texture = 0,
        name = "任务怪物",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 100202, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [12007] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 101801, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "500",
        boss = 0,
        critical_damage = "100",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "敌人打手",
        double_attack_suspend = 1,
        id = 12007,
        level = "LV",
        maxhp = "10000",
        model_id = 401,
        mutate_color = {},
        mutate_texture = 0,
        name = "任务怪物",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [12008] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 110201, ["ratio"] = 1}, {["pfid"] = 110202, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "500",
        boss = 0,
        critical_damage = "100",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "敌人打手",
        double_attack_suspend = 1,
        id = 12008,
        level = "LV",
        maxhp = "10000",
        model_id = 401,
        mutate_color = {},
        mutate_texture = 0,
        name = "任务怪物",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 110202, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [12009] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 120101, ["ratio"] = 1}, {["pfid"] = 120102, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "500",
        boss = 0,
        critical_damage = "100",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "敌人打手",
        double_attack_suspend = 1,
        id = 12009,
        level = "LV",
        maxhp = "10000",
        model_id = 401,
        mutate_color = {},
        mutate_texture = 0,
        name = "任务怪物",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 120102, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [12010] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 165001, ["ratio"] = 1}, {["pfid"] = 165002, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "500",
        boss = 0,
        critical_damage = "100",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "敌人打手",
        double_attack_suspend = 1,
        id = 12010,
        level = "LV",
        maxhp = "10000",
        model_id = 401,
        mutate_color = {},
        mutate_texture = 0,
        name = "任务怪物",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 165002, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [12011] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 110001, ["ratio"] = 1}, {["pfid"] = 110002, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "500",
        boss = 0,
        critical_damage = "100",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "敌人打手",
        double_attack_suspend = 1,
        id = 12011,
        level = "LV",
        maxhp = "10000",
        model_id = 401,
        mutate_color = {},
        mutate_texture = 0,
        name = "任务怪物",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 110002, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [12012] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 175001, ["ratio"] = 1}, {["pfid"] = 175002, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "500",
        boss = 0,
        critical_damage = "100",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "敌人打手",
        double_attack_suspend = 1,
        id = 12012,
        level = "LV",
        maxhp = "10000",
        model_id = 401,
        mutate_color = {},
        mutate_texture = 0,
        name = "任务怪物",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 175002, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [13000] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 101801, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "NPC1018",
        double_attack_suspend = 1,
        id = 13000,
        level = "LV",
        maxhp = "1000000",
        model_id = 1018,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1018（没怒气技）",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [13001] = {
        abnormal_attr_ratio = "1",
        activeSkills = {{["pfid"] = 110001, ["ratio"] = 1}, {["pfid"] = 110002, ["ratio"] = 2}},
        ai_arg = 0,
        attack = "101",
        boss = 0,
        critical_damage = "151",
        critical_ratio = "1",
        cure_critical_ratio = "6",
        defense = "101",
        desc = "NPC1100",
        double_attack_suspend = 1,
        id = 13001,
        level = "LV",
        maxhp = "1000001",
        model_id = 1100,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1100",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "1",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 110002, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "51",
        texture = 11,
        wpmodel = 2100,
    },

    [13002] = {
        abnormal_attr_ratio = "2",
        activeSkills = {{["pfid"] = 110201, ["ratio"] = 1}, {["pfid"] = 110202, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "102",
        boss = 0,
        critical_damage = "152",
        critical_ratio = "2",
        cure_critical_ratio = "7",
        defense = "102",
        desc = "NPC1102",
        double_attack_suspend = 1,
        id = 13002,
        level = "LV",
        maxhp = "1000002",
        model_id = 1102,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1102（没模型）",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "2",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 110202, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "52",
        texture = 11,
        wpmodel = 2100,
    },

    [13003] = {
        abnormal_attr_ratio = "3",
        activeSkills = {{["pfid"] = 120101, ["ratio"] = 1}, {["pfid"] = 120102, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "103",
        boss = 0,
        critical_damage = "153",
        critical_ratio = "3",
        cure_critical_ratio = "8",
        defense = "103",
        desc = "NPC1201",
        double_attack_suspend = 1,
        id = 13003,
        level = "LV",
        maxhp = "1000003",
        model_id = 1201,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1201",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "3",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 120102, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "53",
        texture = 11,
        wpmodel = 2100,
    },

    [13004] = {
        abnormal_attr_ratio = "4",
        activeSkills = {{["pfid"] = 150101, ["ratio"] = 1}, {["pfid"] = 150102, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "104",
        boss = 0,
        critical_damage = "154",
        critical_ratio = "4",
        cure_critical_ratio = "9",
        defense = "104",
        desc = "NPC1501",
        double_attack_suspend = 1,
        id = 13004,
        level = "LV",
        maxhp = "1000004",
        model_id = 1501,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1501",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "4",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 150102, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "54",
        texture = 11,
        wpmodel = 2100,
    },

    [13005] = {
        abnormal_attr_ratio = "5",
        activeSkills = {{["pfid"] = 160001, ["ratio"] = 1}, {["pfid"] = 160002, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "105",
        boss = 0,
        critical_damage = "155",
        critical_ratio = "5",
        cure_critical_ratio = "10",
        defense = "105",
        desc = "NPC1600",
        double_attack_suspend = 1,
        id = 13005,
        level = "LV",
        maxhp = "1000005",
        model_id = 1600,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1600",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "5",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 160002, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "55",
        texture = 11,
        wpmodel = 2100,
    },

    [13006] = {
        abnormal_attr_ratio = "6",
        activeSkills = {{["pfid"] = 165001, ["ratio"] = 1}, {["pfid"] = 165002, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "106",
        boss = 0,
        critical_damage = "156",
        critical_ratio = "6",
        cure_critical_ratio = "11",
        defense = "106",
        desc = "NPC1650",
        double_attack_suspend = 1,
        id = 13006,
        level = "LV",
        maxhp = "1000006",
        model_id = 1650,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1650",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "6",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 165002, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "56",
        texture = 11,
        wpmodel = 2100,
    },

    [13007] = {
        abnormal_attr_ratio = "7",
        activeSkills = {{["pfid"] = 170001, ["ratio"] = 1}, {["pfid"] = 170002, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "107",
        boss = 0,
        critical_damage = "157",
        critical_ratio = "7",
        cure_critical_ratio = "12",
        defense = "107",
        desc = "NPC1700",
        double_attack_suspend = 1,
        id = 13007,
        level = "LV",
        maxhp = "1000007",
        model_id = 1700,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1700",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "7",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 170002, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "57",
        texture = 11,
        wpmodel = 2100,
    },

    [13008] = {
        abnormal_attr_ratio = "7",
        activeSkills = {{["pfid"] = 175001, ["ratio"] = 1}, {["pfid"] = 175002, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "107",
        boss = 0,
        critical_damage = "157",
        critical_ratio = "7",
        cure_critical_ratio = "12",
        defense = "107",
        desc = "NPC1750",
        double_attack_suspend = 1,
        id = 13008,
        level = "LV",
        maxhp = "1000007",
        model_id = 1750,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1750（没模型）",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "7",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 175002, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "57",
        texture = 11,
        wpmodel = 2100,
    },

    [13009] = {
        abnormal_attr_ratio = "8",
        activeSkills = {{["pfid"] = 175101, ["ratio"] = 1}, {["pfid"] = 175102, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "108",
        boss = 0,
        critical_damage = "158",
        critical_ratio = "8",
        cure_critical_ratio = "13",
        defense = "108",
        desc = "NPC1751",
        double_attack_suspend = 1,
        id = 13009,
        level = "LV",
        maxhp = "1000008",
        model_id = 1751,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1751",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "8",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 175102, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "58",
        texture = 11,
        wpmodel = 2100,
    },

    [13010] = {
        abnormal_attr_ratio = "8",
        activeSkills = {{["pfid"] = 175201, ["ratio"] = 1}, {["pfid"] = 175202, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "108",
        boss = 0,
        critical_damage = "158",
        critical_ratio = "8",
        cure_critical_ratio = "13",
        defense = "108",
        desc = "NPC1752",
        double_attack_suspend = 1,
        id = 13010,
        level = "LV",
        maxhp = "1000008",
        model_id = 1752,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1752",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "8",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 175202, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "58",
        texture = 11,
        wpmodel = 2100,
    },

    [13011] = {
        abnormal_attr_ratio = "8",
        activeSkills = {{["pfid"] = 100201, ["ratio"] = 1}, {["pfid"] = 100202, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "108",
        boss = 0,
        critical_damage = "158",
        critical_ratio = "8",
        cure_critical_ratio = "13",
        defense = "108",
        desc = "NPC1002",
        double_attack_suspend = 1,
        id = 13011,
        level = "LV",
        maxhp = "1000008",
        model_id = 1002,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1002",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "8",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 100202, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "58",
        texture = 11,
        wpmodel = 2100,
    },

    [13012] = {
        abnormal_attr_ratio = "8",
        activeSkills = {{["pfid"] = 101501, ["ratio"] = 1}, {["pfid"] = 101502, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "108",
        boss = 0,
        critical_damage = "158",
        critical_ratio = "8",
        cure_critical_ratio = "13",
        defense = "108",
        desc = "NPC1015",
        double_attack_suspend = 1,
        id = 13012,
        level = "LV",
        maxhp = "1000008",
        model_id = 1015,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1015",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "8",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 101502, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "58",
        texture = 11,
        wpmodel = 2100,
    },

    [14001] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50101, ["ratio"] = 1}, {["pfid"] = 50102, ["ratio"] = 1}, {["pfid"] = 50103, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "吴凌锋-高血低攻",
        double_attack_suspend = 1,
        id = 14001,
        level = "LV",
        maxhp = "1000000",
        model_id = 501,
        mutate_color = {},
        mutate_texture = 0,
        name = "阿坊",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "2",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [14002] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50201, ["ratio"] = 1}, {["pfid"] = 50202, ["ratio"] = 1}, {["pfid"] = 50203, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "吴凌锋-高血低防",
        double_attack_suspend = 1,
        id = 14002,
        level = "LV",
        maxhp = "1000000",
        model_id = 502,
        mutate_color = {},
        mutate_texture = 0,
        name = "马面面",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [14003] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50301, ["ratio"] = 1}, {["pfid"] = 50302, ["ratio"] = 1}, {["pfid"] = 50303, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "吴凌锋-高血低攻",
        double_attack_suspend = 1,
        id = 14003,
        level = "LV",
        maxhp = "1000000",
        model_id = 800,
        mutate_color = {},
        mutate_texture = 0,
        name = "黑",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [14004] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50401, ["ratio"] = 1}, {["pfid"] = 50402, ["ratio"] = 1}, {["pfid"] = 50403, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "吴凌锋-高血低防",
        double_attack_suspend = 1,
        id = 14004,
        level = "LV",
        maxhp = "1000000",
        model_id = 801,
        mutate_color = {},
        mutate_texture = 0,
        name = "白",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [14005] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41801, ["ratio"] = 1}, {["pfid"] = 41802, ["ratio"] = 1}, {["pfid"] = 41803, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "1000",
        desc = "吴凌锋-高血防御一",
        double_attack_suspend = 1,
        id = 14005,
        level = "LV",
        maxhp = "1000000",
        model_id = 418,
        mutate_color = {},
        mutate_texture = 0,
        name = "嘟嘟噜",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [14006] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 41801, ["ratio"] = 1}, {["pfid"] = 41802, ["ratio"] = 1}, {["pfid"] = 41803, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "2000",
        desc = "吴凌锋-高血防御二",
        double_attack_suspend = 1,
        id = 14006,
        level = "LV",
        maxhp = "1000000",
        model_id = 702,
        mutate_color = {},
        mutate_texture = 0,
        name = "片羽临凤",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [14010] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 5018, ["ratio"] = 1, ["level"] = 1}},
        ai_arg = 0,
        attack = "80",
        boss = 1,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "世界BOSS技能测试",
        double_attack_suspend = 1,
        id = 14010,
        level = "LV",
        maxhp = "300000",
        model_id = 1018,
        mutate_color = {},
        mutate_texture = 0,
        name = "大吉大利",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "999",
        special_skill = {},
        speed = "500",
        texture = 11,
        wpmodel = 2100,
    },

    [14011] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "1",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "世界BOSS技能测试",
        double_attack_suspend = 1,
        id = 14011,
        level = "LV",
        maxhp = "1",
        model_id = 1018,
        mutate_color = {},
        mutate_texture = 0,
        name = "今晚吃鸡",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "250",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [14012] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "50",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "高血低防2",
        double_attack_suspend = 1,
        id = 14012,
        level = "LV",
        maxhp = "10000",
        model_id = 140,
        mutate_color = {},
        mutate_texture = 0,
        name = "测试3406",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [14013] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 100501, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "1005怪物",
        double_attack_suspend = 1,
        id = 14013,
        level = "LV",
        maxhp = "500000",
        model_id = 1005,
        mutate_color = {},
        mutate_texture = 0,
        name = "1005怪物",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [14014] = {
        abnormal_attr_ratio = "10000",
        activeSkills = {{["pfid"] = 3001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "1000",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "高血低防",
        double_attack_suspend = 1,
        id = 14014,
        level = "LV",
        maxhp = "1000000",
        model_id = 140,
        mutate_color = {},
        mutate_texture = 0,
        name = "测试",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [14015] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 115402, ["ratio"] = 1}},
        ai_arg = 40,
        attack = "7",
        boss = 1,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "世界BOSS技能测试",
        double_attack_suspend = 1,
        id = 14015,
        level = "LV",
        maxhp = "10000000",
        model_id = 1018,
        mutate_color = {},
        mutate_texture = 0,
        name = "冯.诺依曼",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "21",
        special_skill = {},
        speed = "1000",
        texture = 11,
        wpmodel = 2100,
    },

    [14016] = {
        abnormal_attr_ratio = "760",
        activeSkills = {{["pfid"] = 3501, ["ratio"] = 5}, {["pfid"] = 3502, ["ratio"] = 3}, {["pfid"] = 3503, ["ratio"] = 2}},
        ai_arg = 0,
        attack = "412",
        boss = 0,
        critical_damage = "15650",
        critical_ratio = "1520",
        cure_critical_ratio = "760",
        defense = "173",
        desc = "新手引导-比武场模拟战主角",
        double_attack_suspend = 1,
        id = 14016,
        level = "LV",
        maxhp = "3160",
        model_id = 150,
        mutate_color = {},
        mutate_texture = 0,
        name = "专用人形电脑",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "760",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "812.4",
        texture = 11,
        wpmodel = 2200,
    },

    [14017] = {
        abnormal_attr_ratio = "760",
        activeSkills = {{["pfid"] = 40101, ["ratio"] = 3}, {["pfid"] = 40102, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "412",
        boss = 0,
        critical_damage = "15650",
        critical_ratio = "1520",
        cure_critical_ratio = "760",
        defense = "173",
        desc = "新手引导-比武场新手模拟战伙伴1",
        double_attack_suspend = 1,
        id = 14017,
        level = "LV",
        maxhp = "3160",
        model_id = 401,
        mutate_color = {},
        mutate_texture = 0,
        name = "北溟",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "760",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "812.4",
        texture = 11,
        wpmodel = 2100,
    },

    [14018] = {
        abnormal_attr_ratio = "760",
        activeSkills = {{["pfid"] = 41001, ["ratio"] = 3}, {["pfid"] = 41002, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "412",
        boss = 0,
        critical_damage = "15650",
        critical_ratio = "1520",
        cure_critical_ratio = "760",
        defense = "173",
        desc = "新手引导-比武场新手模拟战伙伴2",
        double_attack_suspend = 1,
        id = 14018,
        level = "LV",
        maxhp = "3160",
        model_id = 410,
        mutate_color = {},
        mutate_texture = 0,
        name = "青竹",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "760",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "812.4",
        texture = 11,
        wpmodel = 2100,
    },

    [14019] = {
        abnormal_attr_ratio = "760",
        activeSkills = {{["pfid"] = 40401, ["ratio"] = 3}},
        ai_arg = 0,
        attack = "412",
        boss = 0,
        critical_damage = "15650",
        critical_ratio = "1520",
        cure_critical_ratio = "760",
        defense = "173",
        desc = "新手引导-比武场新手模拟战伙伴3",
        double_attack_suspend = 1,
        id = 14019,
        level = "LV",
        maxhp = "3160",
        model_id = 404,
        mutate_color = {},
        mutate_texture = 0,
        name = "绿狸",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "760",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "812.4",
        texture = 11,
        wpmodel = 2100,
    },

    [14020] = {
        abnormal_attr_ratio = "760",
        activeSkills = {{["pfid"] = 50401, ["ratio"] = 3}, {["pfid"] = 50402, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "412",
        boss = 0,
        critical_damage = "15650",
        critical_ratio = "1520",
        cure_critical_ratio = "760",
        defense = "173",
        desc = "新手引导-比武场新手模拟战伙伴4",
        double_attack_suspend = 1,
        id = 14020,
        level = "LV",
        maxhp = "3160",
        model_id = 504,
        mutate_color = {},
        mutate_texture = 0,
        name = "白无常",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "760",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "812.4",
        texture = 11,
        wpmodel = 2100,
    },

    [14021] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50301, ["ratio"] = 1}, {["pfid"] = 50302, ["ratio"] = 1}, {["pfid"] = 50303, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "高血低攻",
        double_attack_suspend = 1,
        id = 14021,
        level = "LV",
        maxhp = "1000000",
        model_id = 503,
        mutate_color = {},
        mutate_texture = 0,
        name = "黑",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [14022] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 50401, ["ratio"] = 1}, {["pfid"] = 50402, ["ratio"] = 1}, {["pfid"] = 50403, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "高血低防",
        double_attack_suspend = 1,
        id = 14022,
        level = "LV",
        maxhp = "1000000",
        model_id = 504,
        mutate_color = {},
        mutate_texture = 0,
        name = "白",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [14023] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 175401, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "10",
        desc = "吴凌锋-高血低防",
        double_attack_suspend = 1,
        id = 14023,
        level = "LV",
        maxhp = "1000000",
        model_id = 1754,
        mutate_color = {},
        mutate_texture = 0,
        name = "鲜肉包",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [15001] = {
        abnormal_attr_ratio = "1",
        activeSkills = {{["pfid"] = 100901, ["ratio"] = 1}, {["pfid"] = 100902, ["ratio"] = 2}},
        ai_arg = 100,
        attack = "101*SLV",
        boss = 0,
        critical_damage = "151",
        critical_ratio = "1",
        cure_critical_ratio = "6",
        defense = "101",
        desc = "NPC1009",
        double_attack_suspend = 1,
        id = 15001,
        level = "LV",
        maxhp = "1000001*SLV",
        model_id = 1009,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1009",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "1",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 100902, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "51",
        texture = 11,
        wpmodel = 2100,
    },

    [15002] = {
        abnormal_attr_ratio = "1",
        activeSkills = {{["pfid"] = 101001, ["ratio"] = 1}, {["pfid"] = 101002, ["ratio"] = 2}},
        ai_arg = 100,
        attack = "101",
        boss = 0,
        critical_damage = "151",
        critical_ratio = "1",
        cure_critical_ratio = "6",
        defense = "101",
        desc = "NPC1010",
        double_attack_suspend = 1,
        id = 15002,
        level = "LV",
        maxhp = "1000001",
        model_id = 1010,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1010",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "1",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 101002, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "51",
        texture = 11,
        wpmodel = 2100,
    },

    [15003] = {
        abnormal_attr_ratio = "1",
        activeSkills = {{["pfid"] = 101101, ["ratio"] = 1}, {["pfid"] = 101102, ["ratio"] = 2}},
        ai_arg = 0,
        attack = "101",
        boss = 0,
        critical_damage = "151",
        critical_ratio = "1",
        cure_critical_ratio = "6",
        defense = "101",
        desc = "NPC1011",
        double_attack_suspend = 1,
        id = 15003,
        level = "LV",
        maxhp = "1000001",
        model_id = 1011,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1011",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "1",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 101102, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "51",
        texture = 11,
        wpmodel = 2100,
    },

    [15004] = {
        abnormal_attr_ratio = "1",
        activeSkills = {{["pfid"] = 101401, ["ratio"] = 1}, {["pfid"] = 101402, ["ratio"] = 2}},
        ai_arg = 0,
        attack = "101",
        boss = 0,
        critical_damage = "151",
        critical_ratio = "1",
        cure_critical_ratio = "6",
        defense = "101",
        desc = "NPC1014",
        double_attack_suspend = 1,
        id = 15004,
        level = "LV",
        maxhp = "1000001",
        model_id = 1014,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1014",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "1",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 101402, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "51",
        texture = 11,
        wpmodel = 2100,
    },

    [15005] = {
        abnormal_attr_ratio = "1",
        activeSkills = {{["pfid"] = 101501, ["ratio"] = 1}, {["pfid"] = 101502, ["ratio"] = 2}},
        ai_arg = 0,
        attack = "101",
        boss = 0,
        critical_damage = "151",
        critical_ratio = "1",
        cure_critical_ratio = "6",
        defense = "101",
        desc = "NPC1015",
        double_attack_suspend = 1,
        id = 15005,
        level = "LV",
        maxhp = "1000001",
        model_id = 1015,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1015",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "1",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 101502, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "51",
        texture = 11,
        wpmodel = 2100,
    },

    [15006] = {
        abnormal_attr_ratio = "1",
        activeSkills = {{["pfid"] = 101601, ["ratio"] = 1}, {["pfid"] = 101602, ["ratio"] = 2}},
        ai_arg = 100,
        attack = "2000",
        boss = 0,
        critical_damage = "151",
        critical_ratio = "1",
        cure_critical_ratio = "6",
        defense = "101",
        desc = "NPC1016",
        double_attack_suspend = 1,
        id = 15006,
        level = "LV",
        maxhp = "1000001",
        model_id = 1016,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1016",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "1",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 101602, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "51",
        texture = 11,
        wpmodel = 2100,
    },

    [15007] = {
        abnormal_attr_ratio = "1",
        activeSkills = {{["pfid"] = 101801, ["ratio"] = 1}, {["pfid"] = 101802, ["ratio"] = 2}},
        ai_arg = 0,
        attack = "101",
        boss = 0,
        critical_damage = "151",
        critical_ratio = "1",
        cure_critical_ratio = "6",
        defense = "101",
        desc = "NPC1018",
        double_attack_suspend = 1,
        id = 15007,
        level = "LV",
        maxhp = "1000001",
        model_id = 1018,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1018",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "1",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 101802, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "51",
        texture = 11,
        wpmodel = 2100,
    },

    [15008] = {
        abnormal_attr_ratio = "1",
        activeSkills = {{["pfid"] = 120001, ["ratio"] = 1}, {["pfid"] = 120002, ["ratio"] = 2}},
        ai_arg = 100,
        attack = "2000",
        boss = 0,
        critical_damage = "151",
        critical_ratio = "1",
        cure_critical_ratio = "6",
        defense = "101",
        desc = "NPC1200",
        double_attack_suspend = 1,
        id = 15008,
        level = "LV",
        maxhp = "1000001",
        model_id = 1200,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1200",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "1",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 120002, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "51",
        texture = 11,
        wpmodel = 2100,
    },

    [15009] = {
        abnormal_attr_ratio = "1",
        activeSkills = {{["pfid"] = 150201, ["ratio"] = 1}, {["pfid"] = 150202, ["ratio"] = 2}},
        ai_arg = 100,
        attack = "2000",
        boss = 0,
        critical_damage = "151",
        critical_ratio = "1",
        cure_critical_ratio = "6",
        defense = "101",
        desc = "NPC1502",
        double_attack_suspend = 1,
        id = 15009,
        level = "LV",
        maxhp = "1000001",
        model_id = 1502,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1502",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "1",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 150202, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "51",
        texture = 11,
        wpmodel = 2100,
    },

    [15010] = {
        abnormal_attr_ratio = "1",
        activeSkills = {{["pfid"] = 102001, ["ratio"] = 1}, {["pfid"] = 102002, ["ratio"] = 2}},
        ai_arg = 100,
        attack = "101",
        boss = 0,
        critical_damage = "151",
        critical_ratio = "1",
        cure_critical_ratio = "6",
        defense = "101",
        desc = "NPC1020",
        double_attack_suspend = 1,
        id = 15010,
        level = "LV",
        maxhp = "1000001",
        model_id = 1020,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1020",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "1",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 102002, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "51",
        texture = 11,
        wpmodel = 2100,
    },

    [15011] = {
        abnormal_attr_ratio = "1",
        activeSkills = {{["pfid"] = 151101, ["ratio"] = 1}, {["pfid"] = 151102, ["ratio"] = 2}},
        ai_arg = 0,
        attack = "101",
        boss = 0,
        critical_damage = "151",
        critical_ratio = "1",
        cure_critical_ratio = "6",
        defense = "101",
        desc = "NPC1511",
        double_attack_suspend = 1,
        id = 15011,
        level = "LV",
        maxhp = "1000001",
        model_id = 1511,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1511",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "1",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 151102, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "51",
        texture = 11,
        wpmodel = 2100,
    },

    [15012] = {
        abnormal_attr_ratio = "1",
        activeSkills = {{["pfid"] = 151201, ["ratio"] = 1}, {["pfid"] = 151202, ["ratio"] = 2}},
        ai_arg = 0,
        attack = "101",
        boss = 0,
        critical_damage = "151",
        critical_ratio = "1",
        cure_critical_ratio = "6",
        defense = "101",
        desc = "NPC1512",
        double_attack_suspend = 1,
        id = 15012,
        level = "LV",
        maxhp = "1000001",
        model_id = 1512,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1512",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "1",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 151202, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "51",
        texture = 11,
        wpmodel = 2100,
    },

    [15013] = {
        abnormal_attr_ratio = "1",
        activeSkills = {{["pfid"] = 101201, ["ratio"] = 1}, {["pfid"] = 101202, ["ratio"] = 2}},
        ai_arg = 0,
        attack = "101",
        boss = 0,
        critical_damage = "151",
        critical_ratio = "1",
        cure_critical_ratio = "6",
        defense = "101",
        desc = "NPC1012",
        double_attack_suspend = 1,
        id = 15013,
        level = "LV",
        maxhp = "1000001",
        model_id = 1012,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1012",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "1",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 101202, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "51",
        texture = 11,
        wpmodel = 2100,
    },

    [15014] = {
        abnormal_attr_ratio = "1",
        activeSkills = {{["pfid"] = 115201, ["ratio"] = 1}, {["pfid"] = 115202, ["ratio"] = 2}},
        ai_arg = 0,
        attack = "101",
        boss = 0,
        critical_damage = "151",
        critical_ratio = "1",
        cure_critical_ratio = "6",
        defense = "101",
        desc = "NPC1152",
        double_attack_suspend = 1,
        id = 15014,
        level = "LV",
        maxhp = "1000001",
        model_id = 1152,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1152",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "1",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 115202, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "51",
        texture = 11,
        wpmodel = 2100,
    },

    [15015] = {
        abnormal_attr_ratio = "1",
        activeSkills = {{["pfid"] = 115401, ["ratio"] = 1}, {["pfid"] = 115402, ["ratio"] = 2}},
        ai_arg = 0,
        attack = "101",
        boss = 0,
        critical_damage = "151",
        critical_ratio = "1",
        cure_critical_ratio = "6",
        defense = "101",
        desc = "NPC1154",
        double_attack_suspend = 1,
        id = 15015,
        level = "LV",
        maxhp = "1000001",
        model_id = 1154,
        mutate_color = {},
        mutate_texture = 0,
        name = "NPC1154",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "1",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 115402, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "51",
        texture = 11,
        wpmodel = 2100,
    },

    [15016] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "一万血",
        double_attack_suspend = 1,
        id = 15016,
        level = "LV",
        maxhp = "10000",
        model_id = 301,
        mutate_color = {},
        mutate_texture = 0,
        name = "2104技能",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 1009}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [15017] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "三万血",
        double_attack_suspend = 1,
        id = 15017,
        level = "LV",
        maxhp = "30000",
        model_id = 409,
        mutate_color = {},
        mutate_texture = 0,
        name = "2104技能",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 1009}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [15018] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "100",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "十万血",
        double_attack_suspend = 1,
        id = 15018,
        level = "LV",
        maxhp = "100000",
        model_id = 305,
        mutate_color = {},
        mutate_texture = 0,
        name = "2104技能",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 1007}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [15019] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 3001, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "3000",
        boss = 0,
        critical_damage = "150",
        critical_ratio = "0",
        cure_critical_ratio = "5",
        defense = "100",
        desc = "有点攻击力",
        double_attack_suspend = 1,
        id = 15019,
        level = "LV",
        maxhp = "100000",
        model_id = 306,
        mutate_color = {},
        mutate_texture = 0,
        name = "2104技能",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 1009}},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {},
        speed = "50",
        texture = 11,
        wpmodel = 2100,
    },

    [15020] = {
        abnormal_attr_ratio = "0",
        activeSkills = {{["pfid"] = 40101, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "1",
        boss = 0,
        critical_damage = "1",
        critical_ratio = "1",
        cure_critical_ratio = "1",
        defense = "1",
        desc = "咸鱼王",
        double_attack_suspend = 1,
        id = 15020,
        level = "LV",
        maxhp = "10000",
        model_id = 401,
        mutate_color = {},
        mutate_texture = 0,
        name = "咸鱼王",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "0",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "",
        special_skill = {{["pfid"] = 40102, ["level"] = 8, ["sum_grid"] = 3, ["cur_grid"] = 3}},
        speed = "3000",
        texture = 11,
        wpmodel = 2100,
    },

    [15021] = {
        abnormal_attr_ratio = "17",
        activeSkills = {{["pfid"] = 151201, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "10",
        boss = 1,
        critical_damage = "14",
        critical_ratio = "13",
        cure_critical_ratio = "15",
        defense = "11",
        desc = "BOSS王",
        double_attack_suspend = 0,
        id = 15021,
        level = "LV",
        maxhp = "1000000",
        model_id = 1512,
        mutate_color = {},
        mutate_texture = 0,
        name = "BOSS王",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 1007}, {["pfid"] = 1010}},
        petId = 0,
        res_abnormal_ratio = "18",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "100",
        special_skill = {{["pfid"] = 151202, ["level"] = 1, ["sum_grid"] = 3, ["cur_grid"] = 1}},
        speed = "12",
        texture = 11,
        wpmodel = 2100,
    },

    [15022] = {
        abnormal_attr_ratio = "17",
        activeSkills = {{["pfid"] = 31401, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "10",
        boss = 0,
        critical_damage = "14",
        critical_ratio = "13",
        cure_critical_ratio = "15",
        defense = "11",
        desc = "猫王",
        double_attack_suspend = 0,
        id = 15022,
        level = "LV",
        maxhp = "1000000",
        model_id = 314,
        mutate_color = {},
        mutate_texture = 0,
        name = "猫王",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 31403}},
        petId = 0,
        res_abnormal_ratio = "18",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "100",
        special_skill = {{["pfid"] = 31402, ["level"] = 1, ["sum_grid"] = 2, ["cur_grid"] = 1}},
        speed = "12",
        texture = 11,
        wpmodel = 2100,
    },

    [15023] = {
        abnormal_attr_ratio = "17",
        activeSkills = {{["pfid"] = 31101, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "10",
        boss = 1,
        critical_damage = "14",
        critical_ratio = "13",
        cure_critical_ratio = "15",
        defense = "11",
        desc = "BOSS王",
        double_attack_suspend = 0,
        id = 15023,
        level = "LV",
        maxhp = "1000000",
        model_id = 311,
        mutate_color = {},
        mutate_texture = 0,
        name = "BOSS王",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {},
        petId = 0,
        res_abnormal_ratio = "18",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "100",
        special_skill = {{["pfid"] = 31102, ["sum_grid"] = 2, ["cur_grid"] = 2}},
        speed = "12",
        texture = 11,
        wpmodel = 2100,
    },

    [15024] = {
        abnormal_attr_ratio = "17",
        activeSkills = {{["pfid"] = 51101, ["ratio"] = 1}},
        ai_arg = 0,
        attack = "10",
        boss = 0,
        critical_damage = "14",
        critical_ratio = "13",
        cure_critical_ratio = "15",
        defense = "11",
        desc = "猫王",
        double_attack_suspend = 0,
        id = 15024,
        level = "LV",
        maxhp = "2000",
        model_id = 511,
        mutate_color = {},
        mutate_texture = 0,
        name = "猫王",
        nameType = 0,
        ornament_id = 0,
        passiveSkills = {{["pfid"] = 51103, ["level"] = 8}, {["pfid"] = 51104}},
        petId = 0,
        res_abnormal_ratio = "18",
        res_critical_ratio = "0",
        scale = 0,
        show_lv = "100",
        special_skill = {{["pfid"] = 51102, ["sum_grid"] = 3, ["cur_grid"] = 3}},
        speed = "12",
        texture = 11,
        wpmodel = 2100,
    },

}
