-- ./excel/task/house/tasknpc.xlsx
return {

    [100000] = {
        dialogId = 0,
        diglogface = 0,
        event = 0,
        grade = 1,
        id = 100000,
        lifeTime = 0,
        modelId = 302,
        mutateColor = {},
        mutateTexture = 0,
        name = "重华",
        nameType = 1,
        ornamentId = 0,
        refreshCycle = 0,
        reuse = 1,
        rotateY = 180.0,
        scale = 1.0,
        sceneId = 101000,
        shortName = "日常委托",
        title = "",
        tollgateId = 0,
        type = 3,
        wpmodel = 0,
        x = 12.5,
        y = 19.0,
        z = 0.0,
    },

    [101000] = {
        dialogId = 0,
        diglogface = 0,
        event = 0,
        grade = 1,
        id = 101000,
        lifeTime = 0,
        modelId = 312,
        mutateColor = {},
        mutateTexture = 0,
        name = "伊露",
        nameType = 1,
        ornamentId = 0,
        refreshCycle = 0,
        reuse = 1,
        rotateY = 117.0,
        scale = 1.0,
        sceneId = 101000,
        shortName = "日常委托",
        title = "",
        tollgateId = 0,
        type = 3,
        wpmodel = 0,
        x = 13.4,
        y = 18.4,
        z = 0.0,
    },

    [102000] = {
        dialogId = 0,
        diglogface = 0,
        event = 0,
        grade = 1,
        id = 102000,
        lifeTime = 0,
        modelId = 1752,
        mutateColor = {},
        mutateTexture = 0,
        name = "喵小萌",
        nameType = 1,
        ornamentId = 0,
        refreshCycle = 0,
        reuse = 1,
        rotateY = 136.0,
        scale = 1.0,
        sceneId = 206000,
        shortName = "日常委托",
        title = "",
        tollgateId = 0,
        type = 3,
        wpmodel = 0,
        x = 3.6,
        y = 8.0,
        z = 0.0,
    },

    [103000] = {
        dialogId = 0,
        diglogface = 0,
        event = 0,
        grade = 1,
        id = 103000,
        lifeTime = 0,
        modelId = 407,
        mutateColor = {},
        mutateTexture = 0,
        name = "莲",
        nameType = 1,
        ornamentId = 0,
        refreshCycle = 0,
        reuse = 1,
        rotateY = 180.0,
        scale = 1.0,
        sceneId = 204000,
        shortName = "日常委托",
        title = "",
        tollgateId = 0,
        type = 3,
        wpmodel = 0,
        x = 21.0,
        y = 10.0,
        z = 0.0,
    },

}
