-- ./excel/system/rank/rushrank.xlsx
return {

    [1] = {
        key = 1,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 105,
        reward = {{["amount"] = 5, ["sid"] = "13002"}, {["amount"] = 1, ["sid"] = "1011(value=2000)"}, {["amount"] = 1, ["sid"] = "1003(value=800)"}},
        subtype = 0,
        title = 1028,
    },

    [2] = {
        key = 2,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 2,
        rank_id = 105,
        reward = {{["amount"] = 2, ["sid"] = "13002"}, {["amount"] = 1, ["sid"] = "1011(value=1000)"}, {["amount"] = 1, ["sid"] = "1003(value=600)"}},
        subtype = 0,
        title = 1029,
    },

    [3] = {
        key = 3,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 3,
        rank_id = 105,
        reward = {{["amount"] = 1, ["sid"] = "13002"}, {["amount"] = 1, ["sid"] = "1011(value=500)"}, {["amount"] = 1, ["sid"] = "1003(value=400)"}},
        subtype = 0,
        title = 1030,
    },

    [4] = {
        key = 4,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 4,
        rank_id = 105,
        reward = {{["amount"] = 1, ["sid"] = "1011(value=200)"}, {["amount"] = 1, ["sid"] = "1003(value=100)"}},
        subtype = 0,
        title = 0,
    },

    [5] = {
        key = 5,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 5,
        rank_id = 105,
        reward = {{["amount"] = 1, ["sid"] = "1011(value=200)"}, {["amount"] = 1, ["sid"] = "1003(value=100)"}},
        subtype = 0,
        title = 0,
    },

    [6] = {
        key = 6,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 6,
        rank_id = 105,
        reward = {{["amount"] = 1, ["sid"] = "1011(value=200)"}, {["amount"] = 1, ["sid"] = "1003(value=100)"}},
        subtype = 0,
        title = 0,
    },

    [7] = {
        key = 7,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 7,
        rank_id = 105,
        reward = {{["amount"] = 1, ["sid"] = "1011(value=200)"}, {["amount"] = 1, ["sid"] = "1003(value=100)"}},
        subtype = 0,
        title = 0,
    },

    [8] = {
        key = 8,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 8,
        rank_id = 105,
        reward = {{["amount"] = 1, ["sid"] = "1011(value=200)"}, {["amount"] = 1, ["sid"] = "1003(value=100)"}},
        subtype = 0,
        title = 0,
    },

    [9] = {
        key = 9,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 9,
        rank_id = 105,
        reward = {{["amount"] = 1, ["sid"] = "1011(value=200)"}, {["amount"] = 1, ["sid"] = "1003(value=100)"}},
        subtype = 0,
        title = 0,
    },

    [10] = {
        key = 10,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 10,
        rank_id = 105,
        reward = {{["amount"] = 1, ["sid"] = "1011(value=200)"}, {["amount"] = 1, ["sid"] = "1003(value=100)"}},
        subtype = 0,
        title = 0,
    },

    [11] = {
        key = 11,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 106,
        reward = {{["amount"] = 1, ["sid"] = "1017(value=120)"}, {["amount"] = 1, ["sid"] = "1009(value=2000)"}, {["amount"] = 1, ["sid"] = "1003(value=800)"}},
        subtype = 0,
        title = 1025,
    },

    [12] = {
        key = 12,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 2,
        rank_id = 106,
        reward = {{["amount"] = 1, ["sid"] = "1017(value=60)"}, {["amount"] = 1, ["sid"] = "1009(value=1000)"}, {["amount"] = 1, ["sid"] = "1003(value=600)"}},
        subtype = 0,
        title = 1026,
    },

    [13] = {
        key = 13,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 3,
        rank_id = 106,
        reward = {{["amount"] = 1, ["sid"] = "1017(value=30)"}, {["amount"] = 1, ["sid"] = "1009(value=500)"}, {["amount"] = 1, ["sid"] = "1003(value=400)"}},
        subtype = 0,
        title = 1027,
    },

    [14] = {
        key = 14,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 4,
        rank_id = 106,
        reward = {{["amount"] = 1, ["sid"] = "1009(value=200)"}, {["amount"] = 1, ["sid"] = "1003(value=100)"}},
        subtype = 0,
        title = 0,
    },

    [15] = {
        key = 15,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 5,
        rank_id = 106,
        reward = {{["amount"] = 1, ["sid"] = "1009(value=200)"}, {["amount"] = 1, ["sid"] = "1003(value=100)"}},
        subtype = 0,
        title = 0,
    },

    [16] = {
        key = 16,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 6,
        rank_id = 106,
        reward = {{["amount"] = 1, ["sid"] = "1009(value=200)"}, {["amount"] = 1, ["sid"] = "1003(value=100)"}},
        subtype = 0,
        title = 0,
    },

    [17] = {
        key = 17,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 7,
        rank_id = 106,
        reward = {{["amount"] = 1, ["sid"] = "1009(value=200)"}, {["amount"] = 1, ["sid"] = "1003(value=100)"}},
        subtype = 0,
        title = 0,
    },

    [18] = {
        key = 18,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 8,
        rank_id = 106,
        reward = {{["amount"] = 1, ["sid"] = "1009(value=200)"}, {["amount"] = 1, ["sid"] = "1003(value=100)"}},
        subtype = 0,
        title = 0,
    },

    [19] = {
        key = 19,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 9,
        rank_id = 106,
        reward = {{["amount"] = 1, ["sid"] = "1009(value=200)"}, {["amount"] = 1, ["sid"] = "1003(value=100)"}},
        subtype = 0,
        title = 0,
    },

    [20] = {
        key = 20,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 10,
        rank_id = 106,
        reward = {{["amount"] = 1, ["sid"] = "1009(value=200)"}, {["amount"] = 1, ["sid"] = "1003(value=100)"}},
        subtype = 0,
        title = 0,
    },

    [21] = {
        key = 21,
        org_cash = 50000,
        org_leader_reward = {},
        org_leader_title = 1019,
        rank = 1,
        rank_id = 113,
        reward = {{["amount"] = 1, ["sid"] = "1014(value=1000)"}},
        subtype = 0,
        title = 1018,
    },

    [22] = {
        key = 22,
        org_cash = 25000,
        org_leader_reward = {},
        org_leader_title = 1021,
        rank = 2,
        rank_id = 113,
        reward = {{["amount"] = 1, ["sid"] = "1014(value=500)"}},
        subtype = 0,
        title = 1020,
    },

    [23] = {
        key = 23,
        org_cash = 10000,
        org_leader_reward = {},
        org_leader_title = 1023,
        rank = 3,
        rank_id = 113,
        reward = {{["amount"] = 1, ["sid"] = "1014(value=200)"}},
        subtype = 0,
        title = 1022,
    },

    [24] = {
        key = 24,
        org_cash = 3000,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 4,
        rank_id = 113,
        reward = {{["amount"] = 1, ["sid"] = "1014(value=50)"}},
        subtype = 0,
        title = 0,
    },

    [25] = {
        key = 25,
        org_cash = 3000,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 5,
        rank_id = 113,
        reward = {{["amount"] = 1, ["sid"] = "1014(value=50)"}},
        subtype = 0,
        title = 0,
    },

    [26] = {
        key = 26,
        org_cash = 3000,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 6,
        rank_id = 113,
        reward = {{["amount"] = 1, ["sid"] = "1014(value=50)"}},
        subtype = 0,
        title = 0,
    },

    [27] = {
        key = 27,
        org_cash = 3000,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 7,
        rank_id = 113,
        reward = {{["amount"] = 1, ["sid"] = "1014(value=50)"}},
        subtype = 0,
        title = 0,
    },

    [28] = {
        key = 28,
        org_cash = 3000,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 8,
        rank_id = 113,
        reward = {{["amount"] = 1, ["sid"] = "1014(value=50)"}},
        subtype = 0,
        title = 0,
    },

    [29] = {
        key = 29,
        org_cash = 3000,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 9,
        rank_id = 113,
        reward = {{["amount"] = 1, ["sid"] = "1014(value=50)"}},
        subtype = 0,
        title = 0,
    },

    [30] = {
        key = 30,
        org_cash = 3000,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 10,
        rank_id = 113,
        reward = {{["amount"] = 1, ["sid"] = "1014(value=50)"}},
        subtype = 0,
        title = 0,
    },

    [31] = {
        key = 31,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 30, ["sid"] = "20301"}, {["amount"] = 1, ["sid"] = "1003(value=400)"}},
        subtype = 301,
        title = 1031,
    },

    [32] = {
        key = 32,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 20, ["sid"] = "20302"}, {["amount"] = 1, ["sid"] = "1003(value=600)"}},
        subtype = 302,
        title = 1032,
    },

    [33] = {
        key = 33,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 20, ["sid"] = "20303"}, {["amount"] = 1, ["sid"] = "1003(value=600)"}},
        subtype = 303,
        title = 1033,
    },

    [34] = {
        key = 34,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 10, ["sid"] = "20305"}, {["amount"] = 1, ["sid"] = "1003(value=800)"}},
        subtype = 305,
        title = 1034,
    },

    [35] = {
        key = 35,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 10, ["sid"] = "20306"}, {["amount"] = 1, ["sid"] = "1003(value=800)"}},
        subtype = 306,
        title = 1035,
    },

    [36] = {
        key = 36,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 30, ["sid"] = "20308"}, {["amount"] = 1, ["sid"] = "1003(value=400)"}},
        subtype = 308,
        title = 1036,
    },

    [37] = {
        key = 37,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 20, ["sid"] = "20311"}, {["amount"] = 1, ["sid"] = "1003(value=600)"}},
        subtype = 311,
        title = 1037,
    },

    [38] = {
        key = 38,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 20, ["sid"] = "20312"}, {["amount"] = 1, ["sid"] = "1003(value=600)"}},
        subtype = 312,
        title = 1038,
    },

    [39] = {
        key = 39,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 20, ["sid"] = "20313"}, {["amount"] = 1, ["sid"] = "1003(value=600)"}},
        subtype = 313,
        title = 1039,
    },

    [40] = {
        key = 40,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 20, ["sid"] = "20314"}, {["amount"] = 1, ["sid"] = "1003(value=600)"}},
        subtype = 314,
        title = 1040,
    },

    [41] = {
        key = 41,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 10, ["sid"] = "20315"}, {["amount"] = 1, ["sid"] = "1003(value=800)"}},
        subtype = 315,
        title = 1041,
    },

    [42] = {
        key = 42,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 20, ["sid"] = "20316"}, {["amount"] = 1, ["sid"] = "1003(value=600)"}},
        subtype = 316,
        title = 1042,
    },

    [43] = {
        key = 43,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 30, ["sid"] = "20401"}, {["amount"] = 1, ["sid"] = "1003(value=400)"}},
        subtype = 401,
        title = 1043,
    },

    [44] = {
        key = 44,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 20, ["sid"] = "20402"}, {["amount"] = 1, ["sid"] = "1003(value=600)"}},
        subtype = 402,
        title = 1044,
    },

    [45] = {
        key = 45,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 30, ["sid"] = "20403"}, {["amount"] = 1, ["sid"] = "1003(value=400)"}},
        subtype = 403,
        title = 1045,
    },

    [46] = {
        key = 46,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 30, ["sid"] = "20404"}, {["amount"] = 1, ["sid"] = "1003(value=400)"}},
        subtype = 404,
        title = 1046,
    },

    [47] = {
        key = 47,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 10, ["sid"] = "20405"}, {["amount"] = 1, ["sid"] = "1003(value=800)"}},
        subtype = 405,
        title = 1047,
    },

    [48] = {
        key = 48,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 20, ["sid"] = "20407"}, {["amount"] = 1, ["sid"] = "1003(value=600)"}},
        subtype = 407,
        title = 1048,
    },

    [49] = {
        key = 49,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 20, ["sid"] = "20409"}, {["amount"] = 1, ["sid"] = "1003(value=600)"}},
        subtype = 409,
        title = 1049,
    },

    [50] = {
        key = 50,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 30, ["sid"] = "20410"}, {["amount"] = 1, ["sid"] = "1003(value=400)"}},
        subtype = 410,
        title = 1050,
    },

    [51] = {
        key = 51,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 30, ["sid"] = "20412"}, {["amount"] = 1, ["sid"] = "1003(value=400)"}},
        subtype = 412,
        title = 1051,
    },

    [52] = {
        key = 52,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 30, ["sid"] = "20413"}, {["amount"] = 1, ["sid"] = "1003(value=400)"}},
        subtype = 413,
        title = 1052,
    },

    [53] = {
        key = 53,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 30, ["sid"] = "20414"}, {["amount"] = 1, ["sid"] = "1003(value=400)"}},
        subtype = 414,
        title = 1053,
    },

    [54] = {
        key = 54,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 30, ["sid"] = "20415"}, {["amount"] = 1, ["sid"] = "1003(value=400)"}},
        subtype = 415,
        title = 1054,
    },

    [55] = {
        key = 55,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 30, ["sid"] = "20416"}, {["amount"] = 1, ["sid"] = "1003(value=400)"}},
        subtype = 416,
        title = 1055,
    },

    [56] = {
        key = 56,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 30, ["sid"] = "20417"}, {["amount"] = 1, ["sid"] = "1003(value=400)"}},
        subtype = 417,
        title = 1056,
    },

    [57] = {
        key = 57,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 10, ["sid"] = "20418"}, {["amount"] = 1, ["sid"] = "1003(value=800)"}},
        subtype = 418,
        title = 1057,
    },

    [58] = {
        key = 58,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 30, ["sid"] = "20501"}, {["amount"] = 1, ["sid"] = "1003(value=400)"}},
        subtype = 501,
        title = 1058,
    },

    [59] = {
        key = 59,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 30, ["sid"] = "20502"}, {["amount"] = 1, ["sid"] = "1003(value=400)"}},
        subtype = 502,
        title = 1059,
    },

    [60] = {
        key = 60,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 20, ["sid"] = "20503"}, {["amount"] = 1, ["sid"] = "1003(value=600)"}},
        subtype = 503,
        title = 1060,
    },

    [61] = {
        key = 61,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 20, ["sid"] = "20504"}, {["amount"] = 1, ["sid"] = "1003(value=600)"}},
        subtype = 504,
        title = 1061,
    },

    [62] = {
        key = 62,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 20, ["sid"] = "20505"}, {["amount"] = 1, ["sid"] = "1003(value=600)"}},
        subtype = 505,
        title = 1062,
    },

    [63] = {
        key = 63,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 20, ["sid"] = "20506"}, {["amount"] = 1, ["sid"] = "1003(value=600)"}},
        subtype = 506,
        title = 1063,
    },

    [64] = {
        key = 64,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 30, ["sid"] = "20507"}, {["amount"] = 1, ["sid"] = "1003(value=400)"}},
        subtype = 507,
        title = 1064,
    },

    [65] = {
        key = 65,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 20, ["sid"] = "20508"}, {["amount"] = 1, ["sid"] = "1003(value=600)"}},
        subtype = 508,
        title = 1065,
    },

    [66] = {
        key = 66,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 20, ["sid"] = "20509"}, {["amount"] = 1, ["sid"] = "1003(value=600)"}},
        subtype = 509,
        title = 1066,
    },

    [67] = {
        key = 67,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 10, ["sid"] = "20510"}, {["amount"] = 1, ["sid"] = "1003(value=800)"}},
        subtype = 510,
        title = 1067,
    },

    [68] = {
        key = 68,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 10, ["sid"] = "20511"}, {["amount"] = 1, ["sid"] = "1003(value=800)"}},
        subtype = 511,
        title = 1068,
    },

    [69] = {
        key = 69,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 10, ["sid"] = "20512"}, {["amount"] = 1, ["sid"] = "1003(value=800)"}},
        subtype = 512,
        title = 1069,
    },

    [70] = {
        key = 70,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 30, ["sid"] = "20513"}, {["amount"] = 1, ["sid"] = "1003(value=400)"}},
        subtype = 513,
        title = 1070,
    },

    [71] = {
        key = 71,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 115,
        reward = {{["amount"] = 20, ["sid"] = "20514"}, {["amount"] = 1, ["sid"] = "1003(value=600)"}},
        subtype = 514,
        title = 1071,
    },

    [72] = {
        key = 72,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 117,
        reward = {{["amount"] = 30, ["sid"] = "20301"}, {["amount"] = 1, ["sid"] = "1003(value=400)"}},
        subtype = 0,
        title = 0,
    },

    [73] = {
        key = 73,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 2,
        rank_id = 117,
        reward = {{["amount"] = 30, ["sid"] = "20301"}, {["amount"] = 1, ["sid"] = "1003(value=400)"}},
        subtype = 0,
        title = 0,
    },

    [74] = {
        key = 74,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 3,
        rank_id = 117,
        reward = {{["amount"] = 30, ["sid"] = "20301"}, {["amount"] = 1, ["sid"] = "1003(value=400)"}},
        subtype = 0,
        title = 0,
    },

    [75] = {
        key = 75,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 1,
        rank_id = 118,
        reward = {{["amount"] = 30, ["sid"] = "20301"}, {["amount"] = 1, ["sid"] = "1003(value=400)"}},
        subtype = 0,
        title = 0,
    },

    [76] = {
        key = 76,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 2,
        rank_id = 118,
        reward = {{["amount"] = 30, ["sid"] = "20301"}, {["amount"] = 1, ["sid"] = "1003(value=400)"}},
        subtype = 0,
        title = 0,
    },

    [77] = {
        key = 77,
        org_cash = 0,
        org_leader_reward = {},
        org_leader_title = 0,
        rank = 3,
        rank_id = 118,
        reward = {{["amount"] = 30, ["sid"] = "20301"}, {["amount"] = 1, ["sid"] = "1003(value=400)"}},
        subtype = 0,
        title = 0,
    },

}
